### ISSUE TITLE
React Native: Error: @firebase/firestore: ", "Firestore(4.10.1): Could not reach Firestore backend "

### ISSUE THREAD

**Issue by Luckygirlllll** [firebase/firebase-js-sdk#638] opened 2018-04-05 12:51 UTC
### [REQUIRED] Describe your environment

 Operating System version: IOS (React Native), Android (React Native)
Firebase SDK version: 4.12.0
Firebase Product: Firestore

> Error: @firebase/firestore: ", "Firestore(4.10.1): Could not reach Firestore backend " 

**Steps to reproduce:**

Add npm install firebase@4.12.0 --save to the react native project
Add the code below to the project
Nothing is happening (collections and documents were not created)

**Relevant Code:**

```
import * as firebase from 'firebase'
import firestore from 'firebase/firestore'

var config = {
  apiKey: "xxxxxxxxxxxxxxxxxx",
  authDomain: "xxxxxxxxxxxxxxxxxx",
  databaseURL: "xxxxxxxxxxxxxxxxxx",
  projectId: "xxxxxxxxxxxxxxxxxx",
  storageBucket: "xxxxxxxxxxxxxxxxxx",
  messagingSenderId: "xxxxxxxxxxxxxxxxxx"
};

firebase.initializeApp(config);

var db = firebase.firestore();

var docRef = db.collection('users').doc('alovelace');

var setAda = docRef.set({
    first: 'Ada',
    last: 'Lovelace',
    born: 1815
})

db.collection("users").get().then((querySnapshot) => {
      querySnapshot.forEach((doc) => {
          console.log(`${doc.id} => ${doc.data()}`)
      })
    })

```
<img width="421" alt="screen shot 2018-04-05 at 15 50 21" src="https://user-images.githubusercontent.com/10096433/38366636-1bed5338-38e9-11e8-8018-f4274cd01fe3.png">

**Comment by yishin** [comment] 2018-04-06 10:10
Operating System version: Android (React Native)
Firebase SDK version: 4.12.1
Firebase Product: Firestore

I have the same issue, too.
but, only error in android.

If this error occurs, the data can not be read.
See below error:

> Failed to get document because the client is offline.

**Comment by Luckygirlllll** [comment] 2018-04-06 10:25
@yishin I can't read and write data both in Android and IOS to Firestore.

**Comment by arielalvarez88** [comment] 2018-04-06 11:46
+1

**Comment by schmidt-sebastian** [comment] 2018-04-06 16:29
It would help us isolate this issue if you could provide debug logging. Please take a look here: https://firebase.google.com/docs/reference/js/firebase.firestore.Firestore#setLogLevel

Furthermore, can you tell us when you first saw this behavior? Additionally, can you check and see if you are currently able to access your project from the Firebase Console?

Thanks for your help!

**Comment by Luckygirlllll** [comment] 2018-04-06 16:38
@schmidt-sebastian I'm able to access project in Firebase Console. I get this error from the very beginning, so I was testing Firestore, and was not able to write or read data to Firestore. I also have firebase realtime db in the project, it works fine.

**Comment by Luckygirlllll** [comment] 2018-04-06 16:43
@schmidt-sebastian Where should I exactly set LogLevel to debug? Inside the react native project? or I should enable it somewhere in console?

**Comment by schmidt-sebastian** [comment] 2018-04-06 16:48
@Luckygirlllll You should be able to do so via https://github.com/invertase/react-native-firebase/blob/master/android/src/main/java/io/invertase/firebase/firestore/RNFirebaseFirestore.java#L68

**Comment by mjsmagalhaes** [comment] 2018-04-06 17:26
Also having error below from browser (Chrome 65)

> @firebase/firestore: Firestore (4.10.1): Could not reach Firestore backend.

The setLogLevel('debug') also gives an error:

> firestore(...).setLogLevel is not a function

**Comment by Salakar** [comment] 2018-04-07 00:09
@schmidt-sebastian appears @Luckygirlllll is using the web SDK inside here not our RNFirebase one - the import of ours would be `import * as firebase from 'react-native-firebase';`

**Comment by Luckygirlllll** [comment] 2018-04-07 00:12
@Salakar @schmidt-sebastian yes, I’m using web sdk, not react-native-firebase

**Comment by Luckygirlllll** [comment] 2018-04-07 18:34
@schmidt-sebastian I'm trying to setLogLevel to "debug", but I'm getting an error, that this function is not defined 
<img width="373" alt="screen shot 2018-04-07 at 21 32 25" src="https://user-images.githubusercontent.com/10096433/38458853-6439e9bc-3aab-11e8-975a-3bea9009eeed.png">

**Comment by mikelehen** [comment] 2018-04-08 13:39
To enable logging it's actually `firebase.firestore.setLogLevel('debug')` (no parens after `firestore`).

Also, you may be running into https://github.com/firebase/firebase-js-sdk/issues/283.  There was a fix made in react native but I don't think it's been released yet.  You can try the workaround in https://github.com/firebase/firebase-js-sdk/issues/283#issuecomment-345884425 and see if that solves the issue for you.

**Comment by Luckygirlllll** [comment] 2018-04-08 18:30
@mikelehen I have already tried that solution from the comments of  #283, and it didn't help, besides of that I don't have an expo project, I have pure react native,  and in my case it doesn't work both in Android and IOS. 

@schmidt-sebastian  Here are my logs: 

```
[2018-04-08T18:22:12.120Z]  @firebase/firestore: Firestore (4.10.1) [Connection]: WebChannel transport opened.
logger.js:67 [2018-04-08T18:22:12.132Z]  @firebase/firestore: Firestore (4.10.1) [Connection]: WebChannel transport opened.
[2018-04-08T18:22:20.642Z]  @firebase/firestore: Firestore (4.10.1) [OnlineStateTracker]: Watch stream didn't reach online or offline within 10000ms. Considering client offline.
[2018-04-08T18:22:20.643Z]  @firebase/firestore: Firestore (4.10.1): Could not reach Firestore backend.
[2018-04-08T18:22:20.658Z]  @firebase/firestore: Firestore (4.10.1) [MemoryPersistence]: Starting transaction: Release query
[2018-04-08T18:22:20.665Z]  @firebase/firestore: Firestore (4.10.1) [Connection]: WebChannel sending: {"database":"projects/xxx/databases/(default)","removeTarget":2}
logger.js:67 [2018-04-08T18:22:20.669Z]  @firebase/firestore: Firestore (4.10.1) [MemoryPersistence]: Starting transaction: Garbage collection 
[2018-04-08T18:23:20.676Z]  @firebase/firestore: Firestore (4.10.1) [Connection]: WebChannel transport closed  
```

**Comment by mjsmagalhaes** [comment] 2018-04-08 21:55
I am using firebase (4.12.1) on a Vue application running on Windows 10 version of Chrome.

```
18:36:51.257 logger.js?f9f0:65 [2018-04-08T21:36:51.257Z]  @firebase/firestore: Firestore (4.10.1) [MemoryPersistence]: Starting transaction: Start LocalStore
18:36:51.466 logger.js?f9f0:65 [2018-04-08T21:36:51.467Z]  @firebase/firestore: Firestore (4.10.1) [MemoryPersistence]: Starting transaction: Get last stream token
18:36:51.481 logger.js?f9f0:65 [2018-04-08T21:36:51.482Z]  @firebase/firestore: Firestore (4.10.1) [MemoryPersistence]: Starting transaction: Get next mutation batch
18:36:51.484 logger.js?f9f0:65 [2018-04-08T21:36:51.484Z]  @firebase/firestore: Firestore (4.10.1) [MemoryPersistence]: Starting transaction: Allocate query
18:36:51.486 logger.js?f9f0:65 [2018-04-08T21:36:51.487Z]  @firebase/firestore: Firestore (4.10.1) [MemoryPersistence]: Starting transaction: Execute query
18:36:51.488 logger.js?f9f0:65 [2018-04-08T21:36:51.488Z]  @firebase/firestore: Firestore (4.10.1) [MemoryPersistence]: Starting transaction: Remote document keys
18:36:51.494 logger.js?f9f0:65 [2018-04-08T21:36:51.495Z]  @firebase/firestore: Firestore (4.10.1) [Connection]: Creating WebChannel: https://firestore.googleapis.com/google.firestore.v1beta1.Firestore/Listen/channel [object Object]
18:36:51.543 logger.js?f9f0:65 [2018-04-08T21:36:51.544Z]  @firebase/firestore: Firestore (4.10.1) [Connection]: Opening WebChannel transport.
18:36:51.550 logger.js?f9f0:65 [2018-04-08T21:36:51.550Z]  @firebase/firestore: Firestore (4.10.1) [Connection]: WebChannel sending: {"database":"projects/teste-vue-d02f6/databases/(default)","addTarget":{"documents":{"documents":["***"]},"targetId":2}}
18:36:51.743 logger.js?f9f0:65 [2018-04-08T21:36:51.744Z]  @firebase/firestore: Firestore (4.10.1) [Connection]: WebChannel transport opened.
18:37:01.495 logger.js?f9f0:65 [2018-04-08T21:37:01.495Z]  @firebase/firestore: Firestore (4.10.1) [OnlineStateTracker]: Watch stream didn't reach online or offline within 10000ms. Considering client offline.
18:37:01.502 logger.js?f9f0:77 [2018-04-08T21:37:01.502Z]  @firebase/firestore: Firestore (4.10.1): Could not reach Firestore backend.

(...)

18:37:01.517 logger.js?f9f0:65 [2018-04-08T21:37:01.518Z]  @firebase/firestore: Firestore (4.10.1) [MemoryPersistence]: Starting transaction: Release query
18:37:01.522 logger.js?f9f0:65 [2018-04-08T21:37:01.523Z]  @firebase/firestore: Firestore (4.10.1) [Connection]: WebChannel sending: {"database":"projects/teste-vue-d02f6/databases/(default)","removeTarget":2}
18:37:01.527 logger.js?f9f0:65 [2018-04-08T21:37:01.528Z]  @firebase/firestore: Firestore (4.10.1) [MemoryPersistence]: Starting transaction: Garbage collection
18:37:01.534 error.js?6b3a:140 Uncaught (in promise) Error: Failed to get document because the client is offline.

(...)

18:37:01.728 logger.js?f9f0:65 [2018-04-08T21:37:01.729Z]  @firebase/firestore: Firestore (4.10.1) [Connection]: WebChannel received: {"targetChange":{"targetChangeType":"ADD","targetIds":[2]}}
18:37:01.737 logger.js?f9f0:65 [2018-04-08T21:37:01.737Z]  @firebase/firestore: Firestore (4.10.1) [Connection]: WebChannel received: {"documentChange":{"document":{"createTime":"2018-03-17T13:49:17.638986Z","fields":{"config":{"mapValue":{"fields":{"teste":{"stringValue":"1111"}}}}},"name":"***","updateTime":"2018-04-02T19:56:05.971661Z"},"targetIds":[2]}}
18:37:01.745 logger.js?f9f0:65 [2018-04-08T21:37:01.746Z]  @firebase/firestore: Firestore (4.10.1) [Connection]: WebChannel received: {"targetChange":{"readTime":"2018-04-08T21:36:50.262970Z","resumeToken":"CgkIuoehstGr2gI=","targetChangeType":"CURRENT","targetIds":[2]}}
18:37:01.753 logger.js?f9f0:65 [2018-04-08T21:37:01.753Z]  @firebase/firestore: Firestore (4.10.1) [Connection]: WebChannel received: {"targetChange":{"readTime":"2018-04-08T21:36:50.262970Z","resumeToken":"CgkIuoehstGr2gI="}}
18:37:01.758 logger.js?f9f0:65 [2018-04-08T21:37:01.759Z]  @firebase/firestore: Firestore (4.10.1) [Connection]: WebChannel received: {"targetChange":{"readTime":"2018-04-08T21:36:50.304946Z","resumeToken":"CgkIss+jstGr2gI="}}
18:37:01.763 logger.js?f9f0:65 [2018-04-08T21:37:01.763Z]  @firebase/firestore: Firestore (4.10.1) [Connection]: WebChannel received: {"targetChange":{"targetChangeType":"REMOVE","targetIds":[2]}}
18:37:01.773 logger.js?f9f0:65 [2018-04-08T21:37:01.774Z]  @firebase/firestore: Firestore (4.10.1) [MemoryPersistence]: Starting transaction: Apply remote event
18:37:01.779 logger.js?f9f0:65 [2018-04-08T21:37:01.780Z]  @firebase/firestore: Firestore (4.10.1) [MemoryPersistence]: Starting transaction: Notify local view changes
18:37:01.784 logger.js?f9f0:65 [2018-04-08T21:37:01.785Z]  @firebase/firestore: Firestore (4.10.1) [MemoryPersistence]: Starting transaction: Garbage collection
18:37:01.787 logger.js?f9f0:65 [2018-04-08T21:37:01.788Z]  @firebase/firestore: Firestore (4.10.1) [MemoryPersistence]: Starting transaction: Apply remote event
18:37:01.790 logger.js?f9f0:65 [2018-04-08T21:37:01.790Z]  @firebase/firestore: Firestore (4.10.1) [MemoryPersistence]: Starting transaction: Notify local view changes
18:37:01.792 logger.js?f9f0:65 [2018-04-08T21:37:01.792Z]  @firebase/firestore: Firestore (4.10.1) [MemoryPersistence]: Starting transaction: Garbage collection
18:38:01.531 logger.js?f9f0:65 [2018-04-08T21:38:01.532Z]  @firebase/firestore: Firestore (4.10.1) [Connection]: WebChannel transport closed
```

Looks like it is actually getting data but just after the 10s timer has expired .... Perhaps something in the timer is blocking??

**Comment by yishin** [comment] 2018-04-09 01:59
@Luckygirlllll I did not have the time, so I switch to react-native-firebase to fix the problem. 
Good luck.

**Comment by terenceponce** [comment] 2018-04-09 02:45
I came across the same problem as well, but I only get this on Android. It's working as expected on iOS. Is there a solution for this already? I've heard that this problem doesn't exist in react-native-firebase, but using that library would mean that I have to eject out of CRNA/Expo and I would prefer to do that only as a last resort.

**Comment by mikelehen** [comment] 2018-04-09 13:15
@Luckygirlllll Hrm. That does sound like a different issue if it's happening on iOS as well. Any chance you can grab the network tab of chrome dev tools when the problem occurs (export as a HAR or something)?

@mjsmagalhaes If you're not using react native, can you please open a separate issue with as much detail you can provide about how you're reproducing the issue?

@terenceponce You're probably hitting https://github.com/firebase/firebase-js-sdk/issues/283.  There was a bug in react-native which was fixed with https://github.com/facebook/react-native/commit/d52569c4a1b6bd19792e4bda23e3a8c3ac4ad8df but hasn't made it into a release yet.

In the meantime, you can try adding this before you call any firebase methods to work around the issue:

```
const originalSend = XMLHttpRequest.prototype.send;
XMLHttpRequest.prototype.send = function(body) {
  if (body === '') {
    originalSend.call(this);
  } else {
    originalSend.call(this, body);
  }
};
```

**Comment by terenceponce** [comment] 2018-04-09 13:38
@mikelehen Thanks for the temporary workaround. I can confirm that this has fixed my problem with Android. I was afraid I was going to have to eject and switch to RNF, but I'm glad that's not going to be the case.

**Comment by JancoBH** [comment] 2018-04-12 01:00
I have the same problem, I'm using Angular 5 with angularfire2, since yesterday everything was fine but now I have no idea why im getting the @firebase/firestore: Firestore (4.10.1): Could not reach Firestore backend error

**Comment by mikelehen** [comment] 2018-04-12 01:55
Just to be clear, the simplest explanation for that error would be that your device legitimately can't reach the backend for some reason.  A simple test for this would be to try to open the Firestore data viewer in the Firebase console from your device / emulator and see if that works.

**Comment by mikelehen** [comment] 2018-04-12 14:00
@Luckygirlllll Yes, exactly.  Thanks for confirming.  Was there any delay in it loading?  The logs you pasted suggest we're not getting a response from the backend within 10 seconds and so the client is reverting to offline behavior.  But it's possible things are just slow for some reason.

**Comment by 185driver** [comment] 2018-04-14 10:46
@mikelehen, you mentioned [here](https://github.com/firebase/firebase-js-sdk/issues/638#issuecomment-380815298) about 
> not getting a response from the backend within 10 seconds

I'm getting this same error in my app, but only on first load. An immediate browser refresh works fine, as does successive backend calls every few minutes.

I'm not using offline mode, and am wondering if there is a way to extend the timeout beyond 10 seconds.  I'm in a remote location with poor internet so more time would be helpful, unless I should handle the error by sending a successive call to the backend instead?

**Comment by mikelehen** [comment] 2018-04-14 16:07
@185driver Thanks for the feedback. We're intending to look into exposing configuring this timeout in the future. For now, your options are probably either:

1. Switch to using `onSnapshot()` instead of `get()` [this creates an ongoing listener which may end up raising an "empty" event from cache after 10 seconds but will continue listening and raise a new event if it eventually gets a response from the server].
2. Just re-try the get() call if it fails or returns results from cache and you're willing to wait longer.

Note that soon (https://github.com/firebase/firebase-js-sdk/commit/8b29658a074bd48225efe81731e151251b0ed659) you'll be able to do `.get({source: 'server'})`.  This will still be subject to the 10 second delay but you'll be able to use it to consistently get an error (rather than results from cache) in the case that we don't reach the backend.

**Comment by Fax3D** [comment] 2018-04-16 08:00
I'm also having this issue in a Cordova Android app using web sdk (4.12.1).
This error happens "randomly", while the app works perfectly for a certain time and then suddenly stop working gaving "Firestore (4.12.1): Could not reach Firestore backend".
Reading the log, i also find this interesting error next to backend error:

ERR_SPDY_PING_FAILED
firestore.googleapis.com/google.firestore.v1beta1.Firestore/Write/channel?database=XXXX....

From that point, only clearing the cache or reinstalling the app could solve the issue.
Workaround described in #283 not helped me.

Thanks.

**Comment by 185driver** [comment] 2018-04-16 23:13
@mikelehen, I've switched to using `onSnapshot()`. Thanks. I'm not seeing a way to capture the 'empty' event you mention above. I'd like to catch it and handle with a gentle note to the user that the data is coming in more slowly. As I'm not using offline mode, how might I do that?

**Comment by mikelehen** [comment] 2018-04-19 15:46
@185driver Sorry for the delay.  The behavior depends on whether you're listening to a query or a single document.  If you're listening to a query, then you should get an empty `QuerySnapshot` with `querySnapshot.empty == true` and `querySnapshot.metadata.fromCache == true` after the 10 second delay if we couldn't reach the backend.

If you're listening to a single document, then you won't get an event until we actually receive a response from the backend, since we don't want to raise an event saying the document doesn't exist until we know for sure.  So if you want to show a note to the user you should probably just implement your own timeout.  

Hope this helps!

**Comment by mikelehen** [comment] 2018-04-26 14:56
@camstuart To be clear, you're also hitting this issue in a React Native app and the device is online and should be able to connect to the Firestore backend?

**Comment by Frisbeetarian** [comment] 2018-04-26 18:41
Getting the same error. Code works fine locally, issue appears when I firebase deploy.

**Comment by mikelehen** [comment] 2018-04-26 18:45
@Frisbeetarian This issue is scoped to a React Native connectivity issue.  If you are experiencing that error outside of React Native (which you must be if you're using Firebase Hosting) and the device has a working network connection that should be able to reach the Firestore backend, can you open a new issue with as much detail as possible? (code snippet, details on the device(s) that are having the issue, etc.)

**Comment by mjsmagalhaes** [comment] 2018-04-30 18:45
Is this issue still happening?

https://status.firebase.google.com/incident/Console/18006 might have fixed any issues i had.

**Comment by Frisbeetarian** [comment] 2018-05-03 07:16
@mikelehen I had forgotten to whitelist the site from uMatrix. My bad :#

**Comment by exxmen** [comment] 2018-05-11 04:49
ran into this issue today. was working on my Vue project and for some reason, my project config details were changed when I turned on Firestore. the word "staging" became "stating" might be a good idea to also check your config details in case you encounter this issue for the first time

**Comment by aranzuglia** [comment] 2018-05-16 02:34
In case this helps someone. I had the same issue in the browser's console: `@firebase/firestore: Firestore (5.0.1): Could not reach Firestore backend.`

As you can see I upgraded to latest Firebase Web SDK version. I was using 4.8.1 before, but both failed.

After turning on debugging using `firebase.firestore.setLogLevel('debug')` I could see the following: `@firebase/firestore: Firestore (5.0.1) [Connection]: WebChannel received error: {"code":400,"message":"Request contains an invalid argument.","status":"INVALID_ARGUMENT"}`

We had a few queries already using `onSnapshot`, but they had a limit of 1,000,000 `.limit(1000000)`. After changing this value to a smaller one everything is working again!

There is no documentation I could find about it. The `limit()` method is documented but says nothing about a possible range. Something must have changed recently, as it was working perfectly until several days ago.

Just making sure you don't spend too many hours looking for this one ;)

**Comment by mikelehen** [comment] 2018-05-16 14:50
@aranzuglia Oh, that's very interesting. Thanks for flagging this. We should definitely handle that better (either surface an error in the client or fix the backend to allow it).  I'll see if I can figure out what changed and what the best path forward is.  Thanks!

**Comment by mikelehen** [comment] 2018-05-29 06:07
I'm closing this issue as I'm not sure there's anything actionable here.  I was not able to reproduce @Luckygirlllll's issue (React Native was working when I tested a few weeks ago).  We'll also be improving the "Could not reach Firestore backend" error message in the next release to provide more details.  If anybody has a reproducible issue they believe to be a bug, please open a new issue.  Thanks!

**Closed by mikelehen** 2018-05-29 06:07 UTC
Labels: Component-Firestore

**Comment by mikelehen** [comment] 2018-06-04 13:20
This issue has a confusing history with different symptoms and solutions.  If you're experiencing an issue, please open a new issue with the exact details you're seeing (versions of Firestore / React Native, the exact error or incorrect behavior you're experiencing, etc.).  This will avoid confusion and let us focus on the relevant details.

If you can also enable logging via `firebase.firestore.setLogLevel('debug')` and capture the log output, that'll help us diagnose the issue.  And it'd be best to use the latest version of the firebase SDK as some of the log output has been tweaked recently.  Thanks!

**Comment by Luckygirlllll** [comment] 2018-06-04 13:33
Briefly about current situation  ![this-is-fine-meme-625x350](https://user-images.githubusercontent.com/10096433/40920361-93c6eade-680c-11e8-99a3-25c2607e1ea4.jpg)

**Comment by mikelehen** [comment] 2018-06-04 13:44
Sorry if it seems like I'm not being as helpful as I could be. React Native has been a notoriously difficult environment for us to support. It is quirky and difficult to debug.  We have found / fixed (or worked around) a variety of issues in the past. Our most recent fix was about a month ago and I did some tests and everything was working for me, but it's entirely possible that folks are still hitting problems under certain environments / conditions. But we have limited bandwidth to chase these issues and need all the help we can get.  So for anybody hitting issues, please make sure you're using the very latest versions, and file a bug with all the details you can provide. If we can't reproduce the issue, there's a good chance we won't be able to diagnose and resolve it. :-/

**Comment by mikelehen** [comment] 2018-06-04 18:39
Bummer!  If you open a new issue including repro steps, I can try to reproduce this.  It'll be helpful if you start from a vanilla create-react-native-app created app. And be sure to specify whether this is iOS / Android / both.

**Comment by aranzuglia** [comment] 2018-06-04 18:39
Why are the config elements empty? Only to avoid displaying them here?

Can you the actual query?

**Comment by reedmarques** [comment] 2018-06-04 18:41
Im not using Expo so I did react-native init. And Ive only tried on iOS so far, which doesnt work.
@aranzuglia Yeah empty just to hide them, but theyre all copy and pasted from the firebase console so there are were typos

**Comment by reedmarques** [comment] 2018-06-04 19:14
Okay so I just react-native init a new project and only npm installed firebase and firestore works... 
This was my old dependencies so maybe the interaction of one of these packages with Firestore doesnt work? Going to look into it
"dependencies": {
    "firebase": "^5.0.4",
    "react": "16.3.1",
    "react-native": "0.55.4",
    "react-native-elements": "^0.19.1",
    "react-native-fbsdk": "^0.7.0",
    "react-native-fetch-blob": "^0.10.8",
    "react-native-image-picker": "^0.26.10",
    "react-native-permissions": "^1.1.1",
    "react-native-vector-icons": "^4.6.0",
    "react-navigation": "^2.0.4"
  },

**Comment by mikelehen** [comment] 2018-06-04 20:42
Very interesting!  Please let us know what you figure out.

**Comment by reedmarques** [comment] 2018-06-05 01:41
FINALLY FOUND IT!!!!!!!
I was using react-native-image-picker and had 
`const Blob = RNFetchBlob.polyfill.Blob
  const fs = RNFetchBlob.fs
  window.XMLHttpRequest = RNFetchBlob.polyfill.XMLHttpRequest
  window.Blob = Blob`
and that was screwing up the firestore call. So I removed this declaration into a method so it wasnt affecting the global xmlhttp calls!

**Comment by mikelehen** [comment] 2018-06-05 23:03
@reedmarques Woo! Nice work. Thanks for tracking this down. That's very interesting.  Googling around, I guess this is somewhat of a known issue (https://github.com/wkh237/react-native-fetch-blob/issues/634). :-/

@Luckygirlllll Could this be the cause of your failure as well?

**Comment by Luckygirlllll** [comment] 2018-06-06 08:42
@mikelehen I'm using react-native-image-picker in my project as well, so yeah, that can be the reason which is causing the problem.

**Comment by raviatr** [comment] 2018-06-24 22:01
I am also facing the same issue reported  by Luckygirl , but with flutter and firebase

**Comment by mikelehen** [comment] 2018-07-13 22:19
Just FYI- The issue reported by @aranzuglia in https://github.com/firebase/firebase-js-sdk/issues/638#issuecomment-389375927 regarding large limit() queries should be resolved now.  The backend will fail the individual query, but it shouldn't cause any disruption to the stream and so everything else should work and you won't get the "Could not reach Cloud Firestore backend" log message.

For anybody still seeing issues, please create a brand new github issue with as much detail as you can provide (platform / environment, repro steps, etc.). Commenting on this issue will not be very helpful as it does not track any specific root cause (the comments to date are for a wide variety of root causes, most of which have been resolved AFAIK).

**Comment by mydoal** [comment] 2018-07-30 08:41
I am experiencing a similar issue. @mikelehen  Per your request, I've opened a new issue for this:

https://github.com/firebase/firebase-js-sdk/issues/1060

**Comment by zerefdragneel3007** [comment] 2019-04-05 18:40
+1 still getting this back end error with react-native -_-

**Comment by LucianoTrujillo** [comment] 2019-08-06 03:26
Getting the same error on real device but not in emulator. It's not allowing me to use storage!

**Comment by schmidt-sebastian** [comment] 2019-08-06 17:27
@LucianoTrujillo If the issue persists, do you also mind opening a new issue? Please include log lines and the exact product configuration that you are using.
