### ISSUE TITLE
Project fails to start on 8.6.4

### ISSUE THREAD

**Issue by yeegor** [firebase/firebase-js-sdk#4981] opened 2021-06-04 12:28 UTC
### Describe your environment

  * Operating System version: macOS Big Sur 11.2.3
  * Browser version: unrelated
  * Firebase SDK version: 8.6.4
  * Firebase Product: firebase

#### Steps to reproduce:
1. Initialize the application with `create-react-app`
2. Install `yarn add firebase@8.6.4`
3. Have the sample code (from below) in any component
4. Start the application, receive the following error:
```bash
$ react-scripts build
Creating an optimized production build...
Failed to compile.

./node_modules/@firebase/firestore/dist/esm5/prebuilt-db9cc925-eb007c37.js
Attempted import error: 'FetchXmlHttpFactory' is not exported from '@firebase/webchannel-wrapper' (imported as 'v').
```
5. Roll one version back `yarn add firebase@8.6.3`
6. See that the project starts properly

#### Relevant Code:
```
import firebase from 'firebase';

class SignIn extends PureComponent {
    componentDidMount() {
        const provider = new firebase.auth.GoogleAuthProvider()
        firebase.auth().signInWithRedirect(provider)
    }
}
```

**Comment by Auxx** [comment] 2021-06-04 12:34
Same stuff here. Downgraded to 8.6.3 and everything works.

I started a brand new Angular project following @angular/fire quick start guide https://github.com/angular/angularfire/blob/master/docs/install-and-setup.md

**Comment by jdevalez** [comment] 2021-06-04 13:09
this is duplicate of https://github.com/firebase/firebase-js-sdk/issues/4977

**Comment by looptheloop88** [comment] 2021-06-04 15:06
Hi @yeegor, thanks for the report. I will mark this issue as duplicate of #4977.

**Closed by looptheloop88** 2021-06-04 15:06 UTC
Labels: api: core
