### ISSUE TITLE
[discuss}:import error: 'FetchXmlHttpFactory' is not exported from '@firebase/webchannel-wrapper'

### ISSUE THREAD

**Issue by KishaniKandasamy** [firebase/firebase-js-sdk#4984] opened 2021-06-04 19:11 UTC
I got this error while running my app.Can anyone help me to resolve this?

./node_modules/@firebase/firestore/dist/esm5/prebuilt-db9cc925-eb007c37.js
Attempted import error: 'FetchXmlHttpFactory' is not exported from '@firebase/webchannel-wrapper' (imported as 'v').

**Comment by rudenick0309** [comment] 2021-06-05 00:28
you find this #4977

**Comment by unclehooptie** [comment] 2021-06-05 02:55
Clear your package lock and import the newest firebase version. The webchannel wrapper has been updated to resolve this issue.

**Comment by KishaniKandasamy** [comment] 2021-06-05 06:12
Thanks I will import the updated version.

**Comment by KishaniKandasamy** [comment] 2021-06-05 06:58
It works fine now :) Thanks so much

**Comment by looptheloop88** [comment] 2021-06-07 10:03
Hi @KishaniKandasamy, thanks for the report. I will close this now, since the issue is already fixed.

**Closed by looptheloop88** 2021-06-07 10:03 UTC
Labels: api: core
