### ISSUE TITLE
code: "auth/network-request-failed" 

### ISSUE THREAD

**Issue by kishansbs** [firebase/firebase-js-sdk#2880] opened 2020-04-07 06:58 UTC
same issue in react native --

in android-
code: "auth/network-request-failed", message: "A network error (such as timeout, interrupted connection or unreachable host) has occurred."
in ios-
Type Error undefined is not an object (evaluating 'Wu.getRandomValues')

"firebase": "^7.13.2",
"react": "16.9.0",
"react-native": "0.61.5",

**Comment by dconeybe** [comment] 2020-04-07 14:18
Thank you for reporting this issue.  It is a duplicate of https://github.com/firebase/firebase-js-sdk/issues/2858 and it will be fixed in the next release.  Please accept my apologies for the inconvenience.

**Closed by dconeybe** 2020-04-07 14:18 UTC
Labels: needs-triage, type: duplicate
