### ISSUE TITLE
Firebase auth : "signInWithPopup" popup does not appear

### ISSUE THREAD

**Issue by RomainGranata** [firebase/firebase-js-sdk#5699] opened 2021-11-04 10:48 UTC
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10
  * Browser version: Chrome 95.0.4638.69 / Firefox 94.0 
  * Firebase SDK version: 9.2.0
  * Firebase Product: auth 

### [REQUIRED] Describe the problem

Hello ! I am having an issue with the "signInWithPopup" method from firebase/auth. It seems to be extremely inconsistent, as it sometimes works flawlessely (the popup appears on screen, and I am able to connect using Google to my firebase app), while most of the time the popup never appears on screen. No error is displayed in the console, until I try to click a second time on my "Login with Google" button, at which point a "Firebase : Error (auth/cancelled-popup-request)" error is thrown. 

For reference, here are some pictures of the website with devtools and the code : 

<img width="960" alt="issue1" src="https://user-images.githubusercontent.com/72044425/140299533-92529c9b-ffa0-4eab-8a92-191675886bce.png"> 

_The (very straight forward) sign in page. The isue only apperas with the Google button, as the other sign in method does not use any popup._

___

<img width="173" alt="issue2" src="https://user-images.githubusercontent.com/72044425/140299731-b974b442-ebc6-42ea-bd6b-6b741900196a.png">

_The "sources" section of devtools, prior to clicking the Google sign in button._

___

<img width="173" alt="issue3" src="https://user-images.githubusercontent.com/72044425/140299874-5dcd5ee2-a238-43d6-a37f-5fd83f029804.png">

_The same section, after having clicked on the button. A new source appears and apparently loads an iframe, but nothing is displayed on screen._

___

<img width="369" alt="issue4" src="https://user-images.githubusercontent.com/72044425/140300093-905d03c8-cafd-4aab-ad07-657f99c864ac.png">

_If I click the button a second time, the following error appears in the console._

___

<img width="265" alt="issue5" src="https://user-images.githubusercontent.com/72044425/140300215-56a9c053-7c85-4b88-84f7-0d901c7ee63a.png">

_This is the code behind authentication in the app. It is quite straight forward._
**EDIT :** _Here, I made the "googleSignIn" function async, and added an await before the call to "signInWithPopup". This was something that I tested to see if it would resolve the issue, and I forgot to remove it. Sorry for that !_

___

The frustrating thing is that, as I mentionned, it sometimes works flawlessly, and I litteraly don't touch a thing between two different results. 

I saw a very similar post on reddit, another user that had the exact same problem. I don't know if I can post the link here, but please let me know if it would help !

**Comment by facuparedes** [comment] 2021-11-04 15:57
Same issue here, "signInWithPopup" is undefined

**Comment by pruscius** [comment] 2021-11-04 16:17
Same thing here, both signInWithPopup and signInWithRedirect are undefined.

**Comment by sam-gc** [comment] 2021-11-04 17:31
@facuparedes and @pruscius, this is a separate issue; React Native does not export the `signInWIthPopup` and `signInWithReactNative` entrypoints since both of these functions directly modify the DOM. This issue here is unrelated to that. Please open a separate issue if you feel this is the wrong behavior.

@RomainGranata, I'm wondering if this is due to popup blockers within the browser. How often would you say the issue occurs? Does it get fixed on refresh?

**Comment by RomainGranata** [comment] 2021-11-04 17:37
@sam-gc , it is really hard to say. What I can tell you is that I have had issues to make it work on both Firefox and Edge (which were te only two browsers I had installed on my computer back then). When I downloaded Chrome and made a fresh install of it, the popup initially worked (which had me believe that the problem came from my own browser - which I tweaked for maximum security). But when I tested the login a few hours later in chrome and without having changed anything to the code, the issue was back.

**Comment by sam-gc** [comment] 2021-11-04 18:43
Very odd... Does it seem to happen on other machines as well? Is anything printed in the console when the popup doesn't open? Would you mind downgrading to v8 to see if the issue persists there? (This will inform which part of the code base the issue is occurring in)

**Comment by RomainGranata** [comment] 2021-11-06 11:04
Ok so here are my observations : 

- The popup does not seems to be working on other computers. The same proble happens.
- Nothing is written in the console when the popup does not appear.
- When downgrading to v8, I have a different issue. The popup does appear, but it is a blank one (about:blank).

![issue1](https://user-images.githubusercontent.com/72044425/140607276-34a1ac19-14aa-468d-8a62-0332b729bf71.png)

This happens on both Chrome and Edge. On my main browser (Firefox), the popup does open, lets me choose my account, but then nothing happens, and I am kept logged out of my app.

**Comment by Shashank-Prasanna** [comment] 2021-11-08 21:32
If it is on React Native, it does not work in the browser. I have no clue why but that's just how it is. A lot of modal/popup things don't seem to work. You might want to look into a library that makes a popup in which you can display firebase auth rather than using the firebase auth popup itself.

**Comment by sam-gc** [comment] 2021-11-09 20:45
@RomainGranata the fact that you're seeing issues in v8 as well (it's possible v8 and v9 have a different order of steps which is causing the issue to manifest differently) indicates to me this may be an issue with your project's specific configuration. Please reach out to Firebase Support; they'll be better equipped to investigate your specific configuration to determine what's going on: https://firebase.google.com/support.

@Shashank-Prasanna this issue is unrelated to React Native.

I'm going to close this issue out for now, but if you have new findings please feel free to comment/reopen.

**Closed** 2021-11-09 20:45 UTC
Labels: api: auth, v9
