### ISSUE TITLE
FCM getToken issue:  An error occurred while retrieving token for web push notification

### ISSUE THREAD

**Issue by ghanavel** [firebase/firebase-js-sdk#5096] opened 2021-07-01 16:17 UTC
Firebase SDK version: 8.6.8
Environment: localhost

After successful configuration web worker registered and allow of notification alert, getting following issue

 POST https://fcmregistrations.googleapis.com/v1/projects/app-name/registrations   401

firebase.js:35 An error occurred while retrieving token.  FirebaseError: Messaging: A problem occurred while subscribing the user to FCM: Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project. (messaging/token-subscribe-failed).
    at api.ts:67
    at step (tslib.es6.js:102)
    at Object.next (tslib.es6.js:83)
    at fulfilled (tslib.es6.js:73)

**Comment by CretanBull** [comment] 2021-07-01 16:22
Facing same issue. Any working solution for this? Everything was fine until I deleted the existing FCM token for testing purposes. Now it keeps showing this same error on all the getToken() calls.

**Comment by looptheloop88** [comment] 2021-07-01 16:26
Hi @ghanavel, thanks for the report. This is a duplicate of #5081.

**Closed by looptheloop88** 2021-07-01 16:26 UTC
Labels: needs-triage

**Comment by CretanBull** [comment] 2021-07-01 16:41
> Hi @ghanavel, thanks for the report. This is a duplicate of #5081.

is there any fix for this? Was it a bug introduced recently in firebase SDK?
