### ISSUE TITLE
Error in IE9 and IE10.  Cannot instantiate firebase-database.js - be sure to load firebase-app.js first

### ISSUE THREAD

**Issue by elitechance** [firebase/firebase-js-sdk#125] opened 2017-08-10 00:06 UTC
### Environment

  * Operating System version: Win 7
  * Firebase SDK version: firebasejs 4.2.0
  * Firebase Product: database

### The problem
I'm getting this error below when loading our angular application in IE9 and IE10.  It works fine on IE11.
`Cannot instantiate firebase-database.js - be sure to load firebase-app.js first.`
#### Steps to reproduce:

 1. $ ng new firebase-app
 2. $ cd firebase-app
 3. Modify src/polyfills.ts
 4. Uncomment all import under /** IE9, IE10 and IE11 requires all of the following polyfills **/
 5. Uncomment `import 'classlist.js';`
 6. $ npm install --save classlist.js
 7. Modify src/index.html and add firebase links.

```html

<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>FirebaseApp</title>
  <base href="/">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
  <script src="https://www.gstatic.com/firebasejs/4.2.0/firebase-app.js"></script>
  <script src="https://www.gstatic.com/firebasejs/4.2.0/firebase-auth.js"></script>
  <script src="https://www.gstatic.com/firebasejs/4.2.0/firebase-database.js"></script>

</head>
<body>
  <app-root></app-root>
</body>
</html>
```
 8. $ ng serve
 9. Open http://localhost:4200 in ie9 or ie10 browser and in the console tab you'll see this error:
`Cannot instantiate firebase-database.js - be sure to load firebase-app.js first.`

**Comment by github2021** [comment] 2017-08-15 14:21
Same here

SCRIPT5022: Cannot instantiate firebase-database.js - be sure to load firebase-app.js first. 
firebase.js, line 320 character 170977

**Comment by bangive** [comment] 2017-08-19 01:40
me the same
```SCRIPT5022: Cannot instantiate firebase-database.js - be sure to load firebase-app.js first. ```

**Comment by katowulf** [comment] 2017-08-30 16:11
Are all three of you using Angular? "Same here" is a fast reply, but not very useful for us. Including environment, version, and steps to repro (or a failing test unit) will help us isolate the cause and find a fix.

**Comment by lTyl** [comment] 2017-08-30 16:18
It isn't a Angular specific issue. Here is a very simple Fiddle which only includes Firebase 4.2.0:
https://jsfiddle.net/teq0nx3L/1/

On IE10 or IE9, this throws the error described in the op.

**Comment by LeonStankowski** [comment] 2017-09-08 05:40
Any news on a fix?

**Comment by katowulf** [comment] 2017-09-13 20:09
This is low priority given the affected browsers and small number of affected users. Given our current backlog, it seems realistic to expect that we will sunset IE 10 support before we get time to investigate a fix for this. Note that IE 9 is already unsupported.  Note that the limitation here is bandwidth, so if a low risk PR were submitted to resolve this, we may have time to review that and merge.

**Comment by raulrene** [comment] 2017-09-27 11:06
@lTyl thanks for your remark regarding `4.1.2`. I downgraded to that version and it's working now for IE10.

**Comment by jshcrowthe** [comment] 2017-10-04 17:51
I'm going to close this in favor of https://github.com/firebase/firebase-js-sdk/issues/157 which has more information on the issue.

**Closed by jshcrowthe** 2017-10-04 17:51 UTC
Labels: Component: Database
