### ISSUE TITLE
Unable to get token after initialization

### ISSUE THREAD

**Issue by marosivanco** [firebase/firebase-js-sdk#5093] opened 2021-07-01 15:04 UTC
### Describe your environment

  * Operating System version: Window 10
  * Browser version: 91.0.4472.114
  * Firebase SDK version: 9.0.0-beta.5
  * Firebase Product: messaging

### Describe the problem
After migration to v9 the getToken function initiates 2 requests:
DELETE https://fcmregistrations.googleapis.com/v1/projects/nikemobiledev/registrations/<strange_Id>
which fails with HTTP 404
and
POST https://fcmregistrations.googleapis.com/v1/projects/nikemobiledev/registrations
with request body:
```json
{"web": {
        "applicationPubKey": "<VAPID_KEY>",
        "auth": "<AUTH>",
        "endpoint": "https://fcm.googleapis.com/fcm/send/<STRANGE_SUFFIX>",
        "p256dh": "<P256DH>"
    }
}
```
which fails with HTTP 401 or 429 randomly.
The 401 response is
```json
{
  "error": {
    "code": 401,
    "message": "Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.",
    "status": "UNAUTHENTICATED"
  }
}
```
The credentials used are identical with ones that work in 8.x version.
#### Steps to reproduce:
Just try it.

#### Relevant Code:

```javascript
import { initializeApp } from 'firebase/app';
import { getMessaging, getToken, onMessage } from 'firebase/messaging';

const { apiKey, appId, messagingSenderId, projectId, vapidKey } = FIREBASE_CONFIG;
let messaging;

export function initFirebaseMessaging(serviceWorkerRegistration) {
    if (!messaging) {
        messaging = getMessaging(initializeApp({ apiKey, appId, messagingSenderId, projectId }) );
    }
    if (Notification.permission === 'granted') {
        onMessage(messaging, handleMessage);
        return getToken(messaging, { vapidKey, serviceWorkerRegistration })
            .then(storeToken)
            .then(checkUserChange)
            .catch(e => console.error('Cannot get messaging token', e));
    }
}
```

**Comment by looptheloop88** [comment] 2021-07-01 16:27
Hi @marosivanco, thanks for the report. This is a duplicate of #5081.

**Closed by looptheloop88** 2021-07-01 16:27 UTC
Labels: api: messaging
