### ISSUE TITLE
Permission-Denied

### ISSUE THREAD

**Issue by jachzen** [firebase/firebase-js-sdk#4990] opened 2021-06-07 09:51 UTC
* Operating System version: MacOS 11.2.3
  * Browser version: Chrome 91
  * Firebase SDK version: 8.6.2
  * Firebase Product:database (auth, database, storage, etc)

Remark : I am using angular fire 6.1.5.
Since version 8.6.2 (8.6.1 does not have this issue) after logging in via  auth.signInWithEmailAndPassword and getting the user by listening to the authstate change, it is not possible to get data from Firestore database although a valid authorized user is used. (code='permission-denied'). 

Seems that this rule does not match anymore:
    match /users/{userId} {
      allow read: if request.auth.uid == userId;
    }
Switching back to 8.6.1 fixes the problem.

**Comment by trakhimenok** [comment] 2021-06-07 20:14
Same regression with 8.6.5, reverting to 8.6.1 fixes it.

**Comment by lesharris** [comment] 2021-06-09 09:06
We also hit this and had to downgrade to 8.6.1 which has resolved it.

**Comment by looptheloop88** [comment] 2021-06-09 13:31
Hi @jachzen, thanks for the report. Could this be an issue with AngularFire? I tried using the SDK version 6.8.5, but I wasn't able to replicate the issue.

I'm using the security rules below and able to read/write to Firestore database successfully:

```
rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
     match /users/{userId} {
  		allow read, write: if request.auth.uid == userId;
  	 }
  }
}
```

Write to Firestore database:

```
const userID = firebase.auth().currentUser.uid;
firebase.firestore().collection("users").doc(userID).set({
   name: "looptheloop88"
})
.then(() => {
   console.log("Document successfully written!");
})
.catch((error) => {
   console.error("Error writing document: ", error);
});
```

Read from Firestore database:
```
const userID = firebase.auth().currentUser.uid;
const docRef = firebase.firestore().collection("users").doc(userID);
docRef.get().then((doc) => {
   if (doc.exists) {
      console.log("Document data:", doc.data());
   } else {
      console.log("No such document!");
   }
}).catch((error) => {
   console.log("Error getting document:", error);
});
```

Would you mind sharing a [minimal, but complete](https://stackoverflow.com/help/minimal-reproducible-example) sample of a project that I can run locally to replicate the issue?

**Comment by EazDine** [comment] 2021-06-09 20:27
Same   "firebase": "^8.6.5"  getting  FirebaseError: Missing or insufficient permissions.

rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    match /users/{userId} {
        allow read, write: if request.auth.uid == userId;
        }
     }
  }

Query I am trying with    :

const query = this.firestore.collection(FirebaseCollection.USERS);
                    query.ref.where('userId', '==', u.uid).get().then((res: any) => {
                      if (!res.empty) {
                        res.forEach(data => {
                          this.userDetails = data.data();
                   }
                });

**Comment by looptheloop88** [comment] 2021-06-10 10:14
Per checking, this issue is a duplicate of #4932.

**Closed by looptheloop88** 2021-06-10 10:14 UTC
Labels: api: firestore, needs-info
