### ISSUE TITLE
Severe performance regression in `onSnapshot` listeners in Cloud Firestore

### ISSUE THREAD

**Issue by djsweet** [firebase/firebase-js-sdk#2620] opened 2020-02-12 05:49 UTC
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10 Version 1909
  * Browser version: Google Chrome Version 80.0.3987.87 (Official Build) (64-bit)
  * Firebase SDK version: 7.8.1, since 7.3.0
  * Firebase Product: firestore (auth, database, storage, etc)

### [REQUIRED] Describe the problem

SDK 7.3.0 introduced a severe performance regression in the Firestore `onSnapshot` listener mechanism.

We listen to up to 3000 writes per second written in batches of 50 per transaction. As of SDK 7.2.3, each round of 3000 writes takes approximately 1 second, but often blocks the event loop for up to the entire second. Starting with SDK 7.3.0, this same amount of writes takes upwards of 30 seconds, also often blocking the event loop for the entirety of the duration. Our users were complaining that their browsers were recommending that they close their tabs due to unresponsiveness.

I have prepared [a sample project](https://github.com/djsweet/firestore-looplock-bug-report) to reproduce this problem. Here are some relevant screenshots with simple measurements. In the report columns, "RAF" is used as a placeholder for `requestAnimationFrame`. The sample project uses `window.requestAnimationFrame` to determine the severity of event loop blocking.

#### SDK 7.2.3

![Firebase 7 2 3 Update Times](https://user-images.githubusercontent.com/9657980/74306575-c1d88300-4d17-11ea-9bb6-8c66f4b14995.PNG)

#### SDK 7.3.0

![Firebase 7 3 0 Update Times](https://user-images.githubusercontent.com/9657980/74306579-c735cd80-4d17-11ea-959b-295a8d7be359.PNG)

#### SDK 7.8.0

![Firebase 7 8 0 Update Times](https://user-images.githubusercontent.com/9657980/74306583-cbfa8180-4d17-11ea-8268-0825c85471b3.PNG)

#### SDK 7.8.1

![Firebase 7 8 1 Update Times](https://user-images.githubusercontent.com/9657980/74306588-d157cc00-4d17-11ea-9fd2-f41915c8fdee.PNG)

It seems that there have been improvements since SDK 7.3.0, but stalling the event loop for 25 seconds as of SDK 7.8.1 is still unacceptable.

As is noted in the sample project, it is not easily possible to determine the duration of the first invocation of `onSnapshot` for an update session. Because of this, all reported times are optimistic: the actual duration of an update session is always worse than is written to the page.

#### Steps to reproduce:
See https://github.com/djsweet/firestore-looplock-bug-report for an environment which reproduces this problem.

**Comment by wu-hui** [comment] 2020-02-12 20:09
Thank you very much for reporting this and the very detailed reproduction! Really appreciate it!

It turns out from `7.2.3` to `7.3.0` we introduced a new feature that utilized an inefficient `Set` union operation, which led to the performance regression.

https://github.com/firebase/firebase-js-sdk/pull/2624 should fix this regression.

Again, thanks for reporting this!

**Comment by wu-hui** [comment] 2020-02-13 14:47
Fix is merged. This should be fixed in next release.

**Closed by wu-hui** 2020-02-13 14:47 UTC
Labels: api: firestore

**Comment by djsweet** [comment] 2020-02-26 23:36
I can confirm that Firebase 7.9.1 fixes this issue.
