### ISSUE TITLE
onAuthStateChanged Memory leak

### ISSUE THREAD

**Issue by GuilhermeBCC** [firebase/firebase-js-sdk#4130] opened 2020-11-28 18:56 UTC
### [REQUIRED] Describe your environment

  * Operating System version: Win10
  * Browser version: Chrome 87
  * Firebase SDK version: 8.1.1
  * Firebase Product: auth

### [REQUIRED] Describe the problem

Hello guys, I was correcting performance problems in my application when I came across an infinite growing list of listeners on the Chrome Dev Tools performance panel.

![print](https://user-images.githubusercontent.com/28517010/100523749-93864000-3191-11eb-961f-5b5e740ddaba.png)

After investigation, it was discovered that it was a firebase auth method (onAuthStateChanged).

I created a project on stackblitz for demonstration.
[project](https://stackblitz.com/edit/firebase-auth-memory-leak)

Edit: 
I thought it was the call to the onAuthStateChanged method, however just calling **firebase.auth()** already generates the leak

**Comment by Feiyang1** [comment] 2020-11-30 18:10
Duplicate of https://github.com/firebase/firebase-js-sdk/issues/1420

**Comment by GuilhermeBCC** [comment] 2020-11-30 18:21
Yes, but this issue is closed. And the problem has not been solved, nor has any satisfactory explanation been given for that problem.

**Comment by GuilhermeBCC** [comment] 2020-11-30 18:47
Correct me if I'm mistaken, this leak was created as a "CAT" to be able to use the auth in several tabs. Functionality that does not exist, but they managed to meet the requirements. However, this is hurting people.

I can propose that there is a way to disable this, with the appropriate consequences registered.

**Comment by sam-gc** [comment] 2023-06-21 17:25
Please see https://github.com/firebase/firebase-js-sdk/issues/1420#issuecomment-1601277470 for a full explanation about why this is expected, and a way to avoid the listener growth. I'm closing this issue as it is a duplicate.

**Closed by sam-gc** 2023-06-21 17:25 UTC
Labels: api: auth, question, needs-attention
