### ISSUE TITLE
Undefined credential and email from error in Firebase social auth

### ISSUE THREAD

**Issue by GermaVinsmoke** [firebase/firebase-js-sdk#6203] opened 2022-05-01 08:37 UTC
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10
  * Browser version: Google Chrome Version 101.0.4951.41 (Official Build) (64-bit)
  * Firebase SDK version: 9.7.0
  * Firebase Product: auth

### [REQUIRED] Describe the problem

In the case of social login when we log in with an email which is already present in Firebase auth, we get this error.
```
error.code === 'auth/account-exists-with-different-credential'
```

So, as per the documentation, we need to add this code to get the email and credential from the error.

```
    // Step 2.
    // User's email already exists.
    // The pending Facebook credential.
    var pendingCred = error.credential;
    // The provider account's email address.
    var email = error.email;
```

But, I'm getting **`undefined`** for both email and credential.

Someone else is also getting the same problem - [undefined email in auth error](https://www.techtalk7.com/firebase-auth-with-facebook-fails-if-the-account-already-exists-and-is-associated-with-a-google-auth/)

**Comment by DragomirMM** [comment] 2022-05-03 13:49
I had a logging problem ("FirebaseError: Firebase: Error (auth/argument-error)") in with @angular/fire 7.3.0, but when I switched to 7.1.0, everything is fine.

**Comment by jbalidiong** [comment] 2022-05-04 12:14
Hi @GermaVinsmoke, thanks for reaching out. This seems to be a duplicate of https://github.com/firebase/firebase-js-sdk/issues/5057. You can find the email under the [customData](firebase.google.com/docs/reference/js/auth.autherror.md#autherrorcustomdata) and for the credential, follow the workaround in the thread:

> To make this work in v9, you call the [credentialFromError method](https://firebase.google.com/docs/reference/js/v9/auth.oauthprovider.md#oauthprovidercredentialfromerror)
> 
> So, altering your example:
> 
> ```
> try {
>   const result = await getRedirectResult(firebaseAuth);
> } catch (error) {
>   if (error.code === 'auth/account-exists-with-different-credential') {
>     const credential = OAuthProvider.credentialFromError(error);
>   }
> }
> ```

**Closed by jbalidiong** 2022-05-04 12:14 UTC
Labels: api: auth, v9
