### ISSUE TITLE
No auth in firebase/app ?

### ISSUE THREAD

**Issue by webplease** [firebase/firebase-js-sdk#4022] opened 2020-10-31 23:21 UTC
Hi to all,

I upgrade my firebase package in my angular app to@angular/fire 6.0.4 and firebase 8.0.0.

Now I have an error here: 

import { auth } from 'firebase/app'
Module '"../../../node_modules/firebase"' has no exported member 'auth'

Why?

**Comment by Feiyang1** [comment] 2020-11-02 17:20
Duplicate of https://github.com/firebase/firebase-js-sdk/issues/4023.

**Closed by Feiyang1** 2020-11-02 17:20 UTC
Labels: needs-triage
