### ISSUE TITLE
Firestore add() shows up in database for a second despite missing permissions

### ISSUE THREAD

**Issue by janswist** [firebase/firebase-js-sdk#792] opened 2018-05-09 10:19 UTC
### Describe your environment

  * Operating System version: MacOS HighSierra
  * Firebase SDK version: 4.13.1
  * Firebase Product: firestore

#### Steps to reproduce:

I have my data connected to firestore with `onSnapshot()` and when I use `add()` while not having permissions to do so my list renders that item as though I have them and second later it removes that item and then error says "Missing permissions" which is good. Problem is why it shows that item? Shouldn't that data never reach database and show up on the list even for a second?
#### Relevant Code:

call:
```
firebase.firestore()
      .collection('todo-lists')
      .add({
        name: this.newListTitle[key],
        userId: this.userId,
        groupId: key,
        createdAt: firebase.firestore.FieldValue.serverTimestamp()
      })
```

realtime updates:
```
   db
          .collection('todo-lists')
          .where('groupId', '==', doc.id)
          .orderBy('createdAt', 'asc')
          .onSnapshot(querySnapshot => {
            let obj = {}
            querySnapshot.forEach(doc2 => {
                obj[doc2.id] = doc2.data()
            })
            this.$set(this.lists, doc.id, obj)
          })
```
https://stackblitz.com/fork/firebase-issue-sandbox

```javascript
// TODO(you): code here to reproduce the problem
```
I suppose there is something I don't know about Firestore inner workings, but if it would not be the case then I will try to reproduce it.

**Comment by mohshraim** [comment] 2018-05-09 11:12
Your data will be saved locally then synced with server.. and server return the invalid permission..

you can filter the displayed data with  `change.doc.metadata.hasPendingWrites`   if return false then its committed on server if true it's not

**Comment by janswist** [comment] 2018-05-09 11:32
That makes sense. I normally make loading icon show before the method and hide with `finally()` and now I know why it shows for the split second instead throughout the whole operation. Any ideas/solutions to overcome that so it would behave as normal AJAX call?

**Comment by mohshraim** [comment] 2018-05-09 13:58
querySnapshot also have property hasPendingWrites; `querySnapshot.hasPendingWrites`
so its a little tricky;
first note on JS.v.5.0.0 `querySnapshot.docChanges()` is function now..
i hope the following will help you..

         db.collection('todo-lists')
         .onSnapshot({
            includeMetadataChanges: true,
            // includeQueryMetadataChanges: true,   //this on old version before js.v.5.0
         }, function (snapshot) {
            console.log(' loaded from ' + (snapshot.metadata.fromCache ? "local cache" : "server"));

            if (snapshot.metadata.hasPendingWrites == false) {
                //--> this consider a confirmation that data successfully committed on server
                // and you can get the data from tempArray
            }

            // snapshot.docChanges.forEach(function (change) {   //this on old version before js.v.5.0
            snapshot.docChanges().forEach(function (change) {

                var data = change.doc.data();
                if (change.doc.metadata.hasPendingWrites == true) {
                    // -- > here you should add it to tempArray
                }
            });
        },
        function (error) {
            //--> check the error and clear the tempArray accordingly
        });

**Comment by wilhuff** [comment] 2018-05-09 15:43
This is working as intended. Firestore is designed to work disconnected from the server and to help you build highly responsive applications even when the connection to the server is slow. To work around poor or nonexistent connectivity the Firestore client raises events immediately and synchronizes the changes in the background.

You can either do as @mohshraim suggests to wait to display items until the server has validated them or arrange your UI such that in normal operation users can't create todos that would lead to a permission error. This makes the rules on the backend more of a failsafe.

In this example, if you're denying the creation of a todo based on whether or not the user is in the group, present the list of groups to which they have access at the point where you're creating it. In normal operation a user won't be able to choose a group they don't belong to and you'll never see a permission error.

**Closed by wilhuff** 2018-05-09 15:43 UTC
Labels: Component-Firestore

**Comment by janswist** [comment] 2018-05-10 19:52
Thanks guys! That was really helpful - I will try to approach this problem without using `hasPendingWrites` but it's good to know that there is such a thing.
