### ISSUE TITLE
Simple where clause is timing out after moving to eas development build (expo)

### ISSUE THREAD

**Issue by tomgiam** [firebase/firebase-js-sdk#6718] opened 2022-10-22 20:58 UTC
### [REQUIRED] Describe your environment
Windows 10
"firebase": "8.2.3",
    "expo": "^46.0.15",
    "react-native": "0.69.6",

### [REQUIRED] Describe the problem
I have an expo app that works correctly with firebase, but when I convert the build to an eas development client, some firebase code is timing out, but other code is still working. The code that is timing out is below. I tried upgrading to version 9, but ran into some other issues, so I'm back to debugging with version 8 for now. Error is "Could not reach Cloud Firestore backend. Backend didn't respond within 10 seconds"

Log from firebase debug:

```
[2022-10-22T20:35:25.027Z]  @firebase/firestore: Firestore (8.2.2): FirestoreClient Received user= E2Fqqu9FWDgTdpOzdKQOKEdo6wA3
loginCallback uid E2Fqqu9FWDgTdpOzdKQOKEdo6wA3 null
findUserByUID E2Fqqu9FWDgTdpOzdKQOKEdo6wA3
[2022-10-22T20:35:25.114Z]  @firebase/firestore: Firestore (8.2.2): RemoteStore RemoteStore received new credentials
[2022-10-22T20:35:25.115Z]  @firebase/firestore: Firestore (8.2.2): Connection WebChannel transport closed
[2022-10-22T20:35:25.118Z]  @firebase/firestore: Firestore (8.2.2): MemoryPersistence Starting transaction: Allocate target
[2022-10-22T20:35:25.118Z]  @firebase/firestore: Firestore (8.2.2): MemoryPersistence Starting transaction: Execute query
[2022-10-22T20:35:25.119Z]  @firebase/firestore: Firestore (8.2.2): QueryEngine Using full collection scan to execute query: Query(target=Target(users, filters: [uid == E2Fqqu9FWDgTdpOzdKQOKEdo6wA3], orderBy: [__name__ (asc)]); limitType=F)
[2022-10-22T20:35:25.120Z]  @firebase/firestore: Firestore (8.2.2): FirestoreClient Received user= E2Fqqu9FWDgTdpOzdKQOKEdo6wA3
[2022-10-22T20:35:25.122Z]  @firebase/firestore: Firestore (8.2.2): FirebaseCredentialsProvider getToken aborted due to token change.
[2022-10-22T20:35:25.123Z]  @firebase/firestore: Firestore (8.2.2): Connection Creating WebChannel: https://firestore.googleapis.com/google.firestore.v1.Firestore/Listen/channel {"httpSessionIdParam":"gsessionid","initMessageHeaders":{"X-Goog-Api-Client":"gl-js/ fire/8.2.2","Content-Type":"text/plain","Authorization":"Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjNmNjcyNDYxOTk4YjJiMzMyYWQ4MTY0ZTFiM2JlN2VkYTY4NDZiMzciLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vbGlxdWlkZ3VpZGVzLTJjZTYwIiwiYXVkIjoibGlxdWlkZ3VpZGVzLTJjZTYwIiwiYXV0aF90aW1lIjoxNjY2NDcwOTI0LCJ1c2VyX2lkIjoiRTJGcXF1OUZXRGdUZHBPemRLUU9LRWRvNndBMyIsInN1YiI6IkUyRnFxdTlGV0RnVGRwT3pkS1FPS0VkbzZ3QTMiLCJpYXQiOjE2NjY0NzA5MjQsImV4cCI6MTY2NjQ3NDUyNCwiZW1haWwiOiJ0b21AZ2lhbW1hcnJlc2kuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsidG9tQGdpYW1tYXJyZXNpLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.YEe0v_zaLko1OXTPhSBQVvRLADMJzBEDqrXnGcCTEZVd8_UjfWv1uH6lFNxbX29HpTkSdKhVUKNLrYGti8Vun5vb-fROIqgm-vYKcbJCuxRCHwMIpz16VR4-zfPQ6aZ_y_4XKZeBW8L-1V-1JQOjiGCrmgExchywvles4uXt-9lcQBdJdO_fQdZzVEayuJCNxebA3NQG0kDTuB0W7hBj4qj3uMinBXObfFUG3esAFCrf7VrWN8XQ6dJy9E2kjE9sBtwEjt0fAMMWWFfn6PaVzodkw6ZAaWTae4RviSUf43-HqyZJgWpOi1pX3Dis0YYdZzMGwPz53qDfnL3xCSIBSA"},"messageUrlParams":{"database":"projects/liquidguides-2ce60/databases/(default)"},"sendRawJson":true,"supportsCrossDomainXhr":true,"internalChannelParams":{"forwardChannelRequestTimeoutMs":600000},"forceLongPolling":false,"detectBufferingProxy":false} 
[2022-10-22T20:35:25.123Z]  @firebase/firestore: Firestore (8.2.2): PersistentStream stream callback skipped by getCloseGuardedDispatcher.
[2022-10-22T20:35:25.123Z]  @firebase/firestore: Firestore (8.2.2): RemoteStore RemoteStore received new credentials
[2022-10-22T20:35:25.124Z]  @firebase/firestore: Firestore (8.2.2): Connection Creating WebChannel: https://firestore.googleapis.com/google.firestore.v1.Firestore/Listen/channel {"httpSessionIdParam":"gsessionid","initMessageHeaders":{"X-Goog-Api-Client":"gl-js/ fire/8.2.2","Content-Type":"text/plain","Authorization":"Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjNmNjcyNDYxOTk4YjJiMzMyYWQ4MTY0ZTFiM2JlN2VkYTY4NDZiMzciLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vbGlxdWlkZ3VpZGVzLTJjZTYwIiwiYXVkIjoibGlxdWlkZ3VpZGVzLTJjZTYwIiwiYXV0aF90aW1lIjoxNjY2NDcwOTI0LCJ1c2VyX2lkIjoiRTJGcXF1OUZXRGdUZHBPemRLUU9LRWRvNndBMyIsInN1YiI6IkUyRnFxdTlGV0RnVGRwT3pkS1FPS0VkbzZ3QTMiLCJpYXQiOjE2NjY0NzA5MjQsImV4cCI6MTY2NjQ3NDUyNCwiZW1haWwiOiJ0b21AZ2lhbW1hcnJlc2kuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsidG9tQGdpYW1tYXJyZXNpLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.YEe0v_zaLko1OXTPhSBQVvRLADMJzBEDqrXnGcCTEZVd8_UjfWv1uH6lFNxbX29HpTkSdKhVUKNLrYGti8Vun5vb-fROIqgm-vYKcbJCuxRCHwMIpz16VR4-zfPQ6aZ_y_4XKZeBW8L-1V-1JQOjiGCrmgExchywvles4uXt-9lcQBdJdO_fQdZzVEayuJCNxebA3NQG0kDTuB0W7hBj4qj3uMinBXObfFUG3esAFCrf7VrWN8XQ6dJy9E2kjE9sBtwEjt0fAMMWWFfn6PaVzodkw6ZAaWTae4RviSUf43-HqyZJgWpOi1pX3Dis0YYdZzMGwPz53qDfnL3xCSIBSA"},"messageUrlParams":{"database":"projects/liquidguides-2ce60/databases/(default)"},"sendRawJson":true,"supportsCrossDomainXhr":true,"internalChannelParams":{"forwardChannelRequestTimeoutMs":600000},"forceLongPolling":false,"detectBufferingProxy":false} 
[2022-10-22T20:35:25.128Z]  @firebase/firestore: Firestore (8.2.2): PersistentStream stream callback skipped by getCloseGuardedDispatcher.
[2022-10-22T20:35:25.130Z]  @firebase/firestore: Firestore (8.2.2): Connection Opening WebChannel transport.
[2022-10-22T20:35:25.130Z]  @firebase/firestore: Firestore (8.2.2): Connection WebChannel sending: {"database":"projects/liquidguides-2ce60/databases/(default)","addTarget":{"query":{"structuredQuery":{"from":[{"collectionId":"users"}],"where":{"fieldFilter":{"field":{"fieldPath":"uid"},"op":"EQUAL","value":{"stringValue":"E2Fqqu9FWDgTdpOzdKQOKEdo6wA3"}}},"orderBy":[{"field":{"fieldPath":"__name__"},"direction":"ASCENDING"}]},"parent":"projects/liquidguides-2ce60/databases/(default)/documents"},"targetId":6}}
[2022-10-22T20:35:25.520Z]  @firebase/firestore: Firestore (8.2.2): Connection WebChannel transport opened.
[2022-10-22T20:35:35.137Z]  @firebase/firestore: Firestore (8.2.2): OnlineStateTracker Could not reach Cloud Firestore backend. Backend didn't respond within 10 seconds.
This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.
[2022-10-22T20:35:35.151Z]  @firebase/firestore: Firestore (8.2.2): MemoryPersistence Starting transaction: Release target
readUserCallback Object {
  "doc_id": null,
  "pass": false,
  "res": "No user found",
}
[2022-10-22T20:35:35.180Z]  @firebase/firestore: Firestore (8.2.2): Connection WebChannel sending: {"database":"projects/liquidguides-2ce60/databases/(default)","removeTarget":6}
```

#### Relevant Code:

```javascript

import firebase from "firebase/app";
import "firebase/auth";
import "firebase/database";
import "firebase/firestore";
import "firebase/functions";
import "firebase/storage";
if (!firebase.apps.length) {
  firebase.initializeApp(firebaseConfig);
}

  static findUserByUID = (uid, callback) => {
    console.log("findUserByUID", uid);
    const db = firebase.firestore();
    db.collection("users")
      .where("uid", "==", uid)
      .get()
      .then((querySnapshot) => {
        if (querySnapshot.empty) {
          callback({ pass: false, res: "No user found", doc_id: null });
          // return;
        } else {
          var doc = querySnapshot.docs[0];
          console.log("findUserByUID doc", doc);
          callback({ pass: true, res: doc.data(), doc_id: doc.id });
          // return;
        }
      })
      .catch(function (error) {
        console.log("Error finding User By UID:", error.message);
        callback({ pass: false, res: error, doc_id: null });
      });
  };
```

**Comment by dconeybe** [comment] 2022-10-24 18:35
Thank you for reporting this bug.

First of all, I'm not very familiar with Expo, and I'm not sure what an "eas development client" is. Could you explain briefly what that means, and if you can think of how that may contribute to this bug?

You also mentioned that you're stuck on v8. Note that even if we find the root cause in v8, we are not implementing fixes in v8 and would only fix it in v9. Is it something on our end that is blocking you from upgrading to v9?

I don't see anything obvious at first glance that may be causing this issue for you. Unfortunately, that error message is very generic. I'll take a deeper look and get back to you in the coming days. Is it possible to publish a minimal app that reproduces the issue on GitHub? Then I could clone it and try to reproduce for myself. Thank you.

**Comment by tomgiam** [comment] 2022-10-24 22:01
@dconeybe Thanks for responding. I will work on providing you more information. 

What I can tell you as background is that for over a year, I have been successfully releasing my app using expo and firebase for both Android and iOS. Expo is a great framework for creating and distributing react native apps. A key part of the framework, is the "expo go" client app which runs on android and iOS and provides the environment for running and debugging the target app. The final production app is in fact the fusion of the user code and the expo go code. 

Like any framework, there comes a time (for non trivial apps) when you need to add a feature that is not supported by the framework (e.g. some npm packages support expo, but others do not), so you need to work around the framework. Up until recently the only option was to "eject" from expo and use bare bones react native. Late last year they introduced a way to extend the expo framework by building a custom expo client also known as an "eas development client" by adding the npm packages that are not expo compatible. 

The feature that I need, is to read exif data from images. Expo does offer 2 ways of doing that, however, one way only works on one file at a time (i.e. multi file selection is not supported), the other way does work and does support multi file selection, but only in my debug environment and not on a real device (I have an issue open with the expo team on that). 

So I started going down the road of creating a custom expo client because it could not only solve this problem but also open the door for other future features. The problem is, that the same app that works with the generic expo client, does not work with the custom expo client. The only difference with the custom expo client is that I added a package to allow me to read the filesystem and another to read exif data. The package should not have anything to do with the bug because it doesn't even get that far. I believe that the build process may have triggered a bug (perhaps because of npm dependencies), but it only effects firebase (that I know of) and not all aspects of firebase. Some firebase reads are working.

To reproduce the problem I launch the app and try to login with email and password. The  code calls signInWithEmailAndPassword which returns correctly, then the app uses the ID returned from signInWithEmailAndPassword to find the user in the "users" collection, but it times out, even though the user record is there.

Would an apk be ok to send you?
What else would you like the code to do?

If v8 is a dead end, is it better to switch to v9 (in compatibility mode first) and tackle the issues that came up? I stayed with v8 hoping that the fewer changes the better.

Thanks
Tom

**Comment by tomgiam** [comment] 2022-10-25 11:16
@dconeybe UPDATE. I upgraded my non custom expo client to v9 (9.6.11). Now I will try to create the custom expo client with this version so that we can at least eliminate the v8 supportability issues.

**Comment by tomgiam** [comment] 2022-10-25 17:31
@dconeybe  Thanks for the quick response.
I tried #1 and it didn't have any effect.
Just to be sure, I'm doing it correctly what I did was:

const firebaseConfig = {
  apiKey: "XXXXXX",
  authDomain: "liquidguides-2ce60.firebaseapp.com",
  databaseURL: "https://liquidguides-2ce60.firebaseio.com",
  projectId: "liquidguides-2ce60",
  storageBucket: "liquidguides-2ce60.appspot.com",
  messagingSenderId: "146934822866",
  appId: "1:146934822866:web:242e8852b05ea7bbb6fa0b",
  measurementId: "G-93YRF595B3",
  experimentalForceLongPolling: true, 
  useFetchStreams: false,
};

if (!firebase.apps.length) {
  firebase.initializeApp(firebaseConfig);
}

BTW, I also added useFetchStreams: false, because I saw that in a post, although it may be a dated fix/workaround.

For # 2, I'm not quite sure how to do that and if it's compatible with expo or even react native. What I do now is:

import firebase from "firebase/compat/app";
import "firebase/compat/auth";
import "firebase/database";
import "firebase/compat/firestore";
import "firebase/compat/functions";
import "firebase/compat/storage";

and then in my methods I use code like this:

    const db = firebase.firestore();
    var docRef = db.collection("users").doc(user_id);

Thanks
Tom

**Comment by dconeybe** [comment] 2022-10-25 20:29
For # 1 you did not set `experimentalForceLongPolling` correctly. You have to configure it in the Firestore settings.

In the compat library, you do it like this:
```ts
const db = firebase.firestore();
db.settings({ experimentalForceLongPolling: true });
```

In the full v9 sdk, you do it like this:
```ts
const db = getFirestore(app);
db = initializeFirestore(app, { experimentalForceLongPolling: true });
```

For # 2, there is no way to use the Lite SDK from the compat library. You'd have to migrate to the native v9 APIs. In v9, you import the full SDK using
```ts
import { getFirestore } from '@firebase/firestore';
```

and import the Lite SDK using
```ts
import { getFirestore } from '@firebase/firestore/lite';
```

**Comment by tomgiam** [comment] 2022-10-26 06:52
@dconeybe I quickly tried #1 and #2 and they didn't seem to fix the issue (although I need to double check my work before giving up on them). However, something you said triggered an idea for a third option. You said that "Transactions do not use WebChannel to communicate with the server", and transactions worked, so I changed the first 2 failing document requests (for settings and users) to transactions, and they work! So now I can launch the app and login correctly! Before I change every document request to a transaction, I wanted to ask you if there are any downsides or potential pitfalls with doing that. One downside that I'm seeing is that previously when I restarted my app (without first logging out), it remembered that I was already logged in, now I need to login every time I launch the app. Is that a consequence of loosing the local caching support? I suppose I could implement my own caching for the login, if that's the way I end up going.

I will investigate #1 and #2 a little more today. What I have noticed so far is that #1 gets rid of the 10 second timeout, but the call never returns. #2 seemed to behave the same as before, but I will run it again and send you the logs, to make sure.

BTW, what I did for #2710 

```
import { Database, getFirestore, getDoc, updateDoc, doc } from "@firebase/firestore/lite";
const db = new Database({ projectId: "liquidguides-2ce60" });
```

Then the rest of the code is the same as before.

Thanks
Tom

**Comment by tomgiam** [comment] 2022-10-26 07:47
@dconeybe UPDATE 

# 1 does work!!!

I had to make sure that this code:

db.settings({ experimentalForceLongPolling: true });

is only executed once at the very beginning, which is before the settings are read.

It still forgets that I was logged in when I restart the app, but maybe there is another reason for that.

I will go with this approach because it's the simplest, unless I run into other problems.

Thanks so much for your help!!

Tom

**Comment by dconeybe** [comment] 2022-10-26 12:14
I'm glad to hear that `experimentalForceLongPolling` worked for you! You can see https://github.com/firebase/firebase-js-sdk/issues/1674 for more details about this option. I'll close this issue since it appears that it's been resolved. Feel free to comment if you're issue is not resolved, or open a new issue for other issues you may encounter.

Regarding transactions, there are indeed drawbacks to performing all document reads through transactions:
1. They only work when you are online and are able to connect to the server.
2. They do not cache the documents they fetch, nor do they use the cache if the document is cached.
3. You cannot run queries, only single-document fetches.
4. They are clumsy to use for just retrieving one document.

**Closed by dconeybe** 2022-10-26 12:14 UTC
Labels: api: firestore, v9
