### ISSUE TITLE
Code hangs on `await updateDoc` and `await deleteDoc` operations after calling `disableNetwork`

### ISSUE THREAD

**Issue by Daquisu** [firebase/firebase-js-sdk#8657] opened 2024-11-29 17:15 UTC
### Operating System

Windows 11

### Environment (if applicable)

Chrome 131.0.6778.86 (Official Build) (64-bit)

### Firebase SDK Version

11.0.2

### Firebase SDK Product(s)

Firestore

### Project Tooling

Svelte with vite

### Detailed Problem Description

**Trying to achieve**: I was trying to use `await` on write operations such as `updateDoc` and `deleteDoc` with the network disabled.

**What actually happened**: the code hung on the write operation, never finishing it.

**Any error messages or unexpected behavior you observed**: no error messages no warnings, it just hung there.

**Relevant log snippets or console output (if available).**: no relevant log message.

### Steps and code to reproduce issue

Minimal steps to reproduce it:

```javascript
async function demonstrateBug() {
  try {
    await disableNetwork(db);
    console.log('##### Network disabled');

    // This will hang indefinitely
    console.log('##### Attempting update...');
    await updateDoc(doc(db, 'collection', 'document'), {
      field: 'value'
    });

    // This line will never be reached
    console.log('##### Update complete');
  } catch (error) {
    console.error('##### Error:', error);
  }
}
```

Using only `updateDoc` instead of `await updateDoc` makes the code log `##### Update complete` and the operation is properly completed on the local cache.

`getDoc` works fine even with the `await`.

**Comment by wu-hui** [comment] 2024-12-03 15:41
This is expected behavior. Promises from updates are resolved when the backend applied the changes, when the network is turned off, the backend never sees these updates. The updates are still applied in SDK's cache, and will be sent to backend when the SDK is online again.

If your intend is to use the SDK as a mostly offline tool, you are not supposed to await for these promises.

get() is different, as there is a mechanism where results from sdk cache are returned if backend cannot be reached.

**Comment by jbalidiong** [comment] 2024-12-10 13:45
It looks like the initial issue was already answered. I'll be closing this issue now. If you encounter another issue, feel free to create a new one.

**Closed by jbalidiong** 2024-12-10 13:45 UTC
Labels: question, api: firestore, needs-attention
