### ISSUE TITLE
![issue] firebase.messaging().deleteToken(Token) Failed on Firebase WEB SDK 7.6.1

### ISSUE THREAD

**Issue by fhajarf** [firebase/firebase-js-sdk#3324] opened 2020-06-30 09:22 UTC
![issue](https://user-images.githubusercontent.com/44539744/85369496-a479b800-b546-11ea-8db0-6e7a060a6f65.PNG)

_Originally posted by @Mwaseemzakir in https://github.com/firebase/firebase-js-sdk/issues/2364#issuecomment-647942849_

same here 

<img width="493" alt="error" src="https://user-images.githubusercontent.com/59512761/86109452-14e78280-bacd-11ea-8e45-dc4452b071c7.PNG">

[REQUIRED] Describe your environment
Operating System version: windows 10
Browser version: Version 83.0.4103.116 (Official Build) (64-bit)
Firebase SDK version: 7.6.1
Firebase Product: Firebase Cloud Messaging
[REQUIRED] Describe the problem
The issue I have identified was introduced in version 7.0.0 of the firebase-js-sdk. I do not run into this issue in versions previous to 7.0.0. The issue occurs when a use grants notification permissions, gets a FCM token, then updates the notification permissions in the browser back to Ask (default), reloads the page, grants notification permissions again in Chrome, and get an error when trying to getToken at this point. Note: subsequent calls to getToken don't face this issue.

my code :
if(messaging){
      messaging.requestPermission()
      .then(async () => {
          const token = await messaging.getToken();
          const user= JSON.parse(localStorage.getItem('userObj'));
          var isMyObjectEmpty = !Object.keys(user).length;
          const doc = await db.collection('tokens').doc('webTokens').get();
          if(user && !isMyObjectEmpty){
              db.collection('tokens').doc(user.uid).set({webPushToken: token}, {merge: true}).then(() => {
              }).catch((error) => {
                  console.log(error.message,'here we are');
              })
          } 
          if(doc.exists){
              db.collection('tokens').doc('webTokens').update({tokens: firebase.firestore.FieldValue.arrayUnion(token)}).then(() => {
              }).catch((error) => { console.log(error.message,'hahaha'); })
          }
          else {
            console.log("Doc dosen't exist ");
          }
      })
      .catch((err) => {
          console.log("Unable to get permission to notify.", err.code);
          

      });
      navigator.serviceWorker.addEventListener("message", (message) => console.log(message));

**Comment by fhajarf** [comment] 2020-06-30 09:27
<img width="493" alt="error" src="https://user-images.githubusercontent.com/59512761/86109452-14e78280-bacd-11ea-8e45-dc4452b071c7.PNG">

**Comment by Feiyang1** [comment] 2020-06-30 17:07
Duplicate of https://github.com/firebase/firebase-js-sdk/issues/3325. Closing

**Closed by Feiyang1** 2020-06-30 17:07 UTC
Labels: needs-triage
