### ISSUE TITLE
@firebase/database-types@0.2.1 Unexpected end of JSON input while parsing near

### ISSUE THREAD

**Issue by talamaska** [firebase/firebase-js-sdk#831] opened 2018-05-16 10:50 UTC
#### Setup
  * Operating System version: Window 10
  * Firebase SDK version: latest
  * Firebase Product: admin, functions(auth, database, storage, etc)
  * Node v8.9.2
  * npm v5.5.1
#### Description
I'm trying to install the latest firebase dependencies for my functions. 
I have these errors reported from npm
```
58 silly fetchPackageMetaData error for @firebase/database-types@0.2.1 Unexpected end of JSON input while parsing near '...CDig==","shasum":"67f'
59 http fetch GET 304 https://registry.npmjs.org/@firebase%2flogger 1179ms (from cache)
60 silly pacote version manifest for @firebase/logger@0.1.1 fetched in 1185ms
61 silly resolveWithNewModule @firebase/logger@0.1.1 checking installable status
62 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...CDig==","shasum":"67f'
```
#### Steps to reproduce:
try to run update. it failed
removed all node_modules. tried npm install firebase-functions@latest firebase-admin@latest --save
still same errror

**Comment by AmazingDesign** [comment] 2018-05-16 10:52
Same thing.

```
Unexpected end of JSON input while parsing near '...,"unpackedSize":67228'
```

**Comment by mmermerkaya** [comment] 2018-05-16 11:34
Duplicate of #768. Please try the suggested fix from that issue.

**Closed by mmermerkaya** 2018-05-16 11:34 UTC
Labels: needs-triage

**Comment by talamaska** [comment] 2018-05-16 11:48
@mmermerkaya ok thanks, seems worked.

**Comment by mmermerkaya** [comment] 2018-05-16 11:52
No problem :)

**Comment by TeamInnovations** [comment] 2018-10-12 09:47
Try clearing the npm cache and update it back again before re-install firebase tools.
1. npm cache clean --force
2. npm install -g @angular/cli@latest
3. npm install -g firebase-tools

follow the steps.
