### ISSUE TITLE
The inability to load a firebase service twice breaks co-existance of firebase and firebase-admin in a project

### ISSUE THREAD

**Issue by remie** [firebase/firebase-js-sdk#974] opened 2018-06-30 17:04 UTC
### Describe your environment

  * Operating System version: OSX High Sierra
  * Browser version: N/A
  * Firebase SDK version: 5.0.x
  * Firebase Product: firebase-js-sdk & firebase-admin

### Describe the problem

You cannot combine firebase 5.x loading mechanism with firebase-admin.

#### Steps to reproduce:

Starting with firebase 5, the new way of importing firebase and the firebase services is 

```javascript
import * as firebase from 'firebase/app';
import 'firebase/auth';
import 'firebase/storage';
import 'firebase/database';
```

Which of course is totally cool if someone would have also told the 'firebase-admin' team. Because if you add one single line to your import statement:

```javascript
import * as admin from 'firebase-admin';
import * as firebase from 'firebase/app';
import 'firebase/auth';
import 'firebase/storage';
import 'firebase/database';
```

the application will totally freak out and throw an error saying `'Firebase: Firebase service named \'database\' already registered (app/duplicate-service).'`

I haven't really looked into the code but I'm guessing that the import 'firebase/database' is pro-actively registering the database service for the default firebase instance. The firebase-admin probably also has an import of 'firebase/database' somewhere which will cause the database service to try and register twice.

A possible solution would be to remove the [code block](https://github.com/firebase/firebase-js-sdk/blob/6754b7fb8e6cf41bd420c6c93a6c2248c0a888de/packages/app/src/firebaseApp.ts#L363) which tells us that we cannot register a service twice and simply return the existing instance if the service already exists.

#### Relevant Code:

A workaround seems to be to make the imports dynamic:

```javascript
const fb = firebase.initializeApp(config, name);
if (!(<any>fb).services_['auth'] || !(<any>fb).services_['auth'][fb.name]) require('firebase/auth');
if (!(<any>fb).services_['storage'] || !(<any>fb).services_['storage'][fb.name]) require('firebase/storage');
if (!(<any>fb).services_['database'] || !(<any>fb).services_['database'][fb.name]) require('firebase/database');
```

**Comment by jshcrowthe** [comment] 2018-07-02 18:00
Duplicate of #752

**Closed by jshcrowthe** 2018-07-02 18:00 UTC
Labels: needs-triage
