### ISSUE TITLE
Auth uses soon to be deprecated apis.google.com/js/api.js

### ISSUE THREAD

**Issue by nahuelmap** [firebase/firebase-js-sdk#7012] opened 2023-02-06 19:14 UTC
* Operating System version: PopOS 22.04
  * Browser version: Chrome 109.0.5414.74 
  * Firebase SDK version:  9.17.1 
  * Firebase Product: Auth

Google will be deprecating his "Google Sign-In Javascript Platform library" to his new "Identity Services for the Web" on **March 31, 2023**, as stated in:

https://developers.google.com/identity/gsi/web/guides/migration
https://developers.google.com/identity/oauth2/web/guides/migration-to-gis

The first link says `apis.google.com/js/api.js` is going to be deprecated. This library seems to be used by `firebase-sdk-js`, see:

https://github.com/firebase/firebase-js-sdk/blob/b6c231a282313aeda59c447c24f71fdad35240bc/packages/auth/src/platform_browser/iframe/gapi.ts#L107

So it seems `firebase-sdk-js` uses the old version and is not ready for the incoming deprecation (correct me if I'm wrong) . There are upgrade plans / an schedule for them in the horizon?

**Comment by nahuelmap** [comment] 2023-02-13 23:52
@prameshj Thanks for your reply. Notice that `gapi.auth` is also used, not only `gapi.iframes` as you stated:

https://github.com/firebase/firebase-js-sdk/blob/79df09b11f44f8340f45e8c38fdd8c0f7b3742c4/packages/firestore/src/api/credentials.ts#L425

but it seems is a fallback option. Is `gapi.auth` really used or is a legacy code path never executed because an `authTokenFactory` is always present? If used, it will be upgraded? Note this is not `gapi.auth2` but an even older `gapi.auth` api also implemented in `api.js`

**Comment by nahuelmap** [comment] 2023-02-14 13:21
The google migration documentation only mentions `gapi.auth2` as a deprecated module, but I think is not safe to assume `gapi.auth` will not be also deprecated although it is not mentioned, because `gapi.auth` is a very old module already deprecated (but still present in `api.js`) by `gapi.auth2`.

**Comment by nahuelmap** [comment] 2023-02-28 14:49
Hi @milaGGL any thoughts / news on this? You need help?

**Comment by keeth** [comment] 2023-03-01 16:47
I got a notice emailed to me the other day:

> One or more of your web applications uses the legacy Google Sign-In JavaScript library. Please migrate your project(s) to the new Google Identity Services SDK before March 31, 2023.

Does anyone know if this refers to the Firebase JS SDK? I don't think we use Google Sign-in directly anywhere, we only use it via Firebase Auth.

**Comment by milaGGL** [comment] 2023-03-01 17:14
> Hi @milaGGL any thoughts / news on this? You need help?

Hi @nahuelmap, thank you so much for offering help. It turns out one of our other firebase product will be effected by this deprecation, and we have alerted them on time, thanks to your ticket. 

As for our web SDK, we are working on the safe removal of the gapi.auth. I will keep the thread updated.

**Comment by keeth** [comment] 2023-03-03 20:43
@milaGGL I don't see a reference to gapi in the release notes you mentioned, but I'll take your word for it!

**Comment by milaGGL** [comment] 2023-03-06 18:42
@keeth, sorry for the confusion. I meant since there are no firebase release note on any products, stating that changes are made due to the gapi.auth deprecation, there is no upgrading required regarding this matter.

**Comment by nahuelmap** [comment] 2023-03-17 17:57
Thanks for your work @milaGGL ! When we will get a release with this fix applied?

**Comment by milaGGL** [comment] 2023-03-17 22:42
@nahuelmap, with pleasure. 😊 
The PR is newly merged in and there is no exact date scheduled yet. I will update the thread once the release date is confirmed. 
However, since the `FirstPartyAuthCredentialsProvider` is meant to be used for Google's  internal authentication, this fix should not affect your app, unless you have intentionally used the first party credentials in your code with modifications.

**Comment by milaGGL** [comment] 2023-04-04 22:33
The removal of `FirstPartyAuthCredentialsProvider` is released https://github.com/firebase/firebase-js-sdk/pull/7166. Please feel free to reopen this ticket if there is any issue related to this matter. 

@nahuelmap, once again, thank you for bringing this to our attention.

**Closed by milaGGL** 2023-04-04 22:33 UTC
Labels: api: firestore
