### ISSUE TITLE
FR: Phone Auth Support in React Native

### ISSUE THREAD

**Issue by kirilavdeew** [firebase/firebase-js-sdk#180] opened 2017-10-04 07:24 UTC

**Comment by bojeil-google** [comment] 2017-10-04 07:27
You can use an approach similar to the one described for Cordova/Ionic apps:
https://stackoverflow.com/questions/44081040/ionic2-authentication-firebase

**Comment by jshcrowthe** [comment] 2017-10-04 16:47
I'm going to convert this to a feature request. Seems like something that is unsupported, for good reason, but would be nice to at least investigate in the future.

**Comment by jshcrowthe** [comment] 2017-10-04 17:25
Sorry for the churn here, closing this as a dupe of https://github.com/firebase/firebase-js-sdk/issues/102

**Closed by jshcrowthe** 2017-10-04 17:25 UTC
Labels: Component: Auth, feature-request
