### ISSUE TITLE
Remote Config Parameters with Conditions are Inconsistent and Often Incorrect

### ISSUE THREAD

**Issue by ewebfinity** [firebase/firebase-js-sdk#3230] opened 2020-06-17 21:58 UTC
### Describe your environment

  * Operating System version: macOS 10.14.6 (18G5033) (Mojave)
  * Browser version: Google Chrome (83.0.4103.106 (Official Build) (64-bit))
  * Firebase SDK version: 7.15.1
  * Firebase Product: remote-config, analytics

### Describe the problem

When remote config parameters values are determined by a condition on a user property, the parameter values returned are incorrect or inconsistent. Sometimes they are correct and other times they are wrong. Once they are wrong they appear to get "stuck" in that incorrect state. No amount of refreshing or fetching will get them unstuck.

#### Steps to reproduce:

Note: jsbin contains fully working sample with playground firebase project

1. Create a user property called "testing_group"
2. Create a remote config parameter called "showDebugInfo" and make it's default to false
3. Create a condition on that parameter with the following condition:
 "testing_group" "contains regex" ".+"
OR if you like:
"testing_group" "contains" "dev"
4. In javascript, send up user properties of "testing_group = dev" and retrieve the parameter and it will sometimes be incorrect. It's flaky.

Often times the name of the user property won't even matter. It will return the wrong value.

#### Relevant Code:

Run this sample.........

Notice: If you get true on your first run and then comment out the code the sends up the user properties and firebase will still return true for that value even though it's conditioned on it being set.

https://jsbin.com/xijolazaka/1/edit?html,console,output

**Comment by Feiyang1** [comment] 2020-06-18 18:09
I notice that you didn't send any event after setting the user property. On Web, you need to first send user properties to the analytics backend in order to use it in remote config conditions. This is how it's supposed to work with your example:

1. set user property `testing_group` on client and send any event to analytics.
2. An unique instance id and `testing_group` are sent to analytics backend and are recorded.
3. Retrieve parameters from remote config
4. The unique instance id is sent to remote config backend which talks to the analytics backend to check if the condition satisfies for this instance id. (We do some preprocessing so there is no real communication between remote config and analytics, so the lookup is fast)

To remove a user property for an instance id, you will set it to `null`, then send any event.

If you have used FirebaseAnalytics on Android or iOS, you might notice they work differently where user properties are sent along the remote config request. We are not able to do that on Web because we use gtag.js which doesn't expose an API for reading user properties set on client.

Hope it helps! Let me know if it doesn't explain your issue.

**Comment by ewebfinity** [comment] 2020-06-18 20:15
@Feiyang1 
That does clarify why it's working on our mobile app, thanks. I had wondered if you had to send up 
an event to get the user properties to go up. Thanks for that clarification. Maybe add that to the docs?

So now, I've updated the sample here with a logEvent() and I'm still seeing false: 

[https://jsbin.com/diruxazigi/1/edit?html,console,output](url)

Here's what I'm doing:

1. In a Chrome incognito window, open the url above
2. Open the developer console and observe the network tab and wait until it sends the user properties to Google analytics (seems to take 2-3 seconds to fire)
3. After the user properties are sent up, click the "Get Remote Config" button
4. Right now it's returning false for me which is incorrect.

**Another scenario that's confusing**: 
Once you magically get it returning true, you can rename the user property to a junk value and it's still stuck in the "true" state.

Sometimes I will get a "true" value returned. In that case I'll change the code and rename the user property to a garbage name so it should always be false and repeat the steps above and it will still return a "true" value even though I'm sending up the wrong user property name. The network call itself will return as true which is wrong. It's as if it's cached somehow server-side even though I'm sending up a garbage user property name now.

**Comment by Feiyang1** [comment] 2020-06-18 22:15
I got `true` now. I opened the link and waited for a couple of minutes before clicking the button. Note that though we process user properties in real time, there is still some delay before they become available for targeting. Can you try now? I believe you will get "true" now.

> Another scenario that's confusing:
Once you magically get it returning true, you can rename the user property to a junk value and it's still stuck in the "true" state.

I believe it is working as designed (though I admit it can be confusing). When you rename the user property and send it again, you are appending the renamed property to the list of all user properties you have set previously. If you want to remove a user property, you need to set it to `null` and send it again.

I do think our documentation can be improved on explaining how things work, especially when it works differently on Web vs Android and iOS. I will keep the issue open til we update the documentation.

**Comment by ewebfinity** [comment] 2020-06-19 19:54
@Feiyang1 

Okay, the user property behavior makes more sense. So, what I'm gathering is when we send up the user properties it takes an indeterminate amount of time before they become "active" and so remote-config will return false until that time. Is that correct?

It still doesn't seem consistent to me. I've been trying to duplicate this behavior in a new jsbin sample: 

https://jsbin.com/desurunaji/1/edit?html,console,output

I've changed the sample to have two buttons to set and nullify the user properties and I'm not able to get the parameters to flip between true and false after minutes of waiting between setting them. Maybe I'm just not patient enough but how long does this typically take?

**Comment by Feiyang1** [comment] 2020-06-20 00:42
Correct. I also saw inconsistent behavior. I suspect when we change the value of user property somewhat rapidly, the backend pipeline is delayed and updates are buffered. Until all updates are applied, we are going to see inconsistent behavior. Can you try updating the value, wait for 30mins ( the longer the better), fetch RC parameter and see if you get consistent behavior?

I have talked to our backend team about it and I will try to debug with them next week.

**Comment by shtengel** [comment] 2020-06-21 08:41
im having the "same" problem (https://github.com/firebase/firebase-js-sdk/issues/2990)
can't get the right values from the remote config based on user-properties..

why the Remote Config API can't accept a condition as a paramenter in the inital fetch or when getting values ?

**Comment by ewebfinity** [comment] 2020-06-22 22:03
@Feiyang1 
Okay, I can confirm that if you do wait along enough it does seem to return the correct value eventually. In my testing, I've seen it flip instantly, after 30 minutes, and after 1 hour. It does seem to eventually get the right value. Interestingly, once it has the right value I've been able to open multiple incognito browsers and have it return the correct value for me. 

At this point my worry is this: We want to use this as a feature flag mechanism to turn on/off certain features for different user types (e.g. like when user is a "beta user" or not). If the user properties take up to 1 hour to sync how long will those values "stick"? Will our beta users open our app every morning and have to wait up to 2 hours for the beta features to show up? There's our dilemma.

**Comment by Feiyang1** [comment] 2020-06-23 17:12
@ewebfinity how often do you change the user property? Your users only need to wait the first morning after you change the value of the user property. They don't need to wait in subsequent uses util you change the user property again.

> If the user properties take up to 1 hour to sync how long will those values "stick"?
Do you mean when they will be changed again? They will not change until you set new values to them.

**Comment by ewebfinity** [comment] 2020-06-23 20:03
@Feiyang1 
Since our intent is to use remote-config as feature flags we likely won't change the values very often for production users. However, for internal testing purposes we'd change them frequently as you can imagine so remote config conditions wouldn't work for that. We'd have find another mechanism because our QA can't wait an hour for it to flip for testing.

I'm glad the values stick long term. That's what I'm seeing in my testing. This morning I tried it and it still held the "true" value I had from yesterday. Though my question is how exactly does that mechanism work? I assume there's a user id or session id stored in a cookie or one of the browser caching systems (local storage, indexedDB, etc). So if a user ever clears their cache they would lose access to features behind a feature flag until the remote-config values sync to their correct values. You can see that if you open the jsbin sample in a new incognito window the values will be "false" again.

Could something like adding a priority flag on the user properties be added so that they would become active faster?

**Comment by Feiyang1** [comment] 2020-06-26 17:36
> Though my question is how exactly does that mechanism work? I assume there's a user id or session id stored in a cookie or one of the browser caching systems (local storage, indexedDB, etc). So if a user ever clears their cache they would lose access to features behind a feature flag until the remote-config values sync to their correct values. 

Correct and Correct. We store a unique id in the indexedDB. If a user clears the cache, they will get a new id where user property need to be set and associated with it again.

> Could something like a priority flag on the user properties be added so that they would become active faster?

It might be just a performance issue that will be fixed, rather than working as designed. I opened an issue with our backend team b/159815508. Will let you know once I hear back.

**Comment by ewebfinity** [comment] 2020-07-08 20:33
@Feiyang1 Any news from the backend team? Have they got a chance to look into this?

**Comment by Feiyang1** [comment] 2020-11-21 01:06
@ewebfinity According to the backend team, the latency should be a few seconds in general. They think even a few minutes are too high. Also the ordering of updates is not guaranteed. So if you try to update user properties a few times within a short period, the end value may not be the last value you tried to set. Maybe it can explain some of the things you are seeing?

Sorry I don't have a better answer, but hope it helps!

**Comment by lmakarov** [comment] 2020-11-23 18:24
> At this point my worry is this: We want to use this as a feature flag mechanism to turn on/off certain features for different user types (e.g. like when user is a "beta user" or not). If the user properties take up to 1 hour to sync how long will those values "stick"? Will our beta users open our app every morning and have to wait up to 2 hours for the beta features to show up? There's our dilemma.

We have a similar use case where we want certain features in a web application available to users based on their company property value. We were hoping to use remote config for this. Unfortunately, we are seeing delays of about 10 minutes for new users (or existing users using a fresh browser window) between the time they log in and the time we get their applicable configuration from remote config.

The delay (especially for existing users logging in in a fresh browser window) causes an inconsistent user experience and is very confusing to the end users. It makes remote config unusable for feature flagging in web apps whenever you need to rely on config fetching based on user properties.

**Comment by ewebfinity** [comment] 2020-12-23 18:25
@Feiyang1 Thanks for the followup. That is insightful about the user properties order and frequency of updates. We'll look into that. Our team has implemented a hack for now where based on the user properties we flip boolean values we get from firebase remoteConfig manually on the client side to ensure they have the right values. In the future, we'll likely move away from RemoteConfig because of these delays we keep experiencing.

**Comment by clemens-unterkofler** [comment] 2021-07-22 10:26
I have this problem and I am not using user properties. Also even when the the conditions don't even change anything. i.e: a value set to true in either condition (which hasn't changed according to the history of the value) and also in the defaults on the device, but returning false occasionally for some users.

**Comment by lmakarov** [comment] 2021-07-23 17:02
> It makes remote config unusable for feature flagging in web apps whenever you need to rely on config fetching based on user properties.

We eventually went with Unleash (https://www.getunleash.io/) for feature flagging and are very happy with it.

/unsubscribe

**Comment by agupta1411** [comment] 2023-02-03 15:26
Any updates on this? @Feiyang1 

The inconsistency is making remote config unusable for feature flagging.

**Comment by DellaBitta** [comment] 2023-08-08 14:27
Hi @agupta1411 and all,

There doesn't seem to be anything within the SDK that would explain a behavior in the delay that's being reported. Instead this seems like to caused by behavior in the backend which is beyond the scope of the support that we can provide here in this repo.

I recommend that your [reach out to Firebase Support](https://firebase.google.com/support/troubleshooter/contact). They can do work in the backend to track issues based on project configuration, service logs, etc. My hope is that they can find something useful!

I'm going to close this issue for now since I don't think that there's anything for us to do in the JS SDK for this. If you encounter any information that points to the SDK causing a problem then please do open a new issue with the relevant information and please link to this issue to provide more context. Thanks!

**Closed by DellaBitta** 2023-08-08 14:27 UTC
Labels: question, documentation, needs-attention, api: analytics, api: remoteconfig
