### ISSUE TITLE
FR: Disable also console message: WARNING: You are using the Auth Emulator, which is intended for local testing only.  Do not use with production credentials.

### ISSUE THREAD

**Issue by gpfister** [firebase/firebase-js-sdk#5463] opened 2021-09-09 10:52 UTC
### Describe your environment

  * Operating System version: Ubuntu 20.04.3 LTS
  * Browser version: Not run in browser
  * Firebase SDK version: 9.0.1
  * Firebase Product: auth

### Describe the problem

Would it be possible to also disable the console warning when the {disableWarning: true} option is set ? This is polluting the logs in some cases (for example when using the emulator to unit test).

#### Steps to reproduce:

```javascript
const auth = getAuth(app);
connectAuthEmulator(auth, `http://localhost:9099`, { disableWarnings: true });
```

#### Relevant Code:

in `package/auth/src/core/auth/emulator.ts`:

```javascript
function emitEmulatorWarning(disableBanner: boolean): void {
  function attachBanner(): void {
    const el = document.createElement('p');
    const sty = el.style;
    el.innerText =
      'Running in emulator mode. Do not use with production credentials.';
    sty.position = 'fixed';
    sty.width = '100%';
    sty.backgroundColor = '#ffffff';
    sty.border = '.1em solid #000000';
    sty.color = '#b50000';
    sty.bottom = '0px';
    sty.left = '0px';
    sty.margin = '0px';
    sty.zIndex = '10000';
    sty.textAlign = 'center';
    el.classList.add('firebase-emulator-warning');
    document.body.appendChild(el);
  }

  if (typeof console !== 'undefined' && typeof console.info === 'function') {
    console.info(
      'WARNING: You are using the Auth Emulator,' +
        ' which is intended for local testing only.  Do not use with' +
        ' production credentials.'
    );
  }
  if (
    typeof window !== 'undefined' &&
    typeof document !== 'undefined' &&
    !disableBanner
  ) {
    if (document.readyState === 'loading') {
      window.addEventListener('DOMContentLoaded', attachBanner);
    } else {
      attachBanner();
    }
  }
}
```

**Comment by sam-gc** [comment] 2021-09-09 16:52
This is a duplicate of https://github.com/firebase/firebase-js-sdk/issues/5297. For the time being we will not remove the `console.info` message for security reasons. See my response in the other issue: https://github.com/firebase/firebase-js-sdk/issues/5297#issuecomment-900436252.

One possible solution would be to stub out `console.info()` in your unit tests.

**Closed by sam-gc** 2021-09-09 16:52 UTC
Labels: type: feature request, v9

**Comment by gpfister** [comment] 2021-09-09 18:16
Thanks for the feedback. It is quite critical that users realize there are using a non production version of the app, however this doesn't really achieve it: only people looking at the console would see it, and if someone really want to get by, he/she could patch your code to get rid of the warning.

In the end, this is poluting the console with messages that are not concerns in certain context, been able to control it would help.
