### ISSUE TITLE
Firebase has unmet peer dependency "@firebase/app-types@^0.1.0"

### ISSUE THREAD

**Issue by mcfarljw** [firebase/firebase-js-sdk#387] opened 2017-12-19 02:47 UTC
### [REQUIRED] Describe your environment

  * Operating System version: macOS High Sierra 10.13.2
  * Firebase SDK version: 4.8.1
  * Firebase Product: all

#### Steps to reproduce:

1. Install yarn 1.3.2
1. Add firebase 4.8.1 as dependency `yarn add firebase`

I know it's just a warning a it could just be a yarn this, but I'm wondering why they need to be peer dependencies?

<img width="918" alt="screen shot 2017-12-19 at 10 38 54 am" src="https://user-images.githubusercontent.com/4167341/34138159-2519b508-e4a9-11e7-949c-27c36ed19db7.png">

**Comment by bjornharvold** [comment] 2017-12-19 04:03
Works great in 4.8.0. 4.8.1 gives me:

```
ERROR in node_modules/@firebase/database/dist/esm/src/api/Database.d.ts(4,33): error TS2307: Cannot find module '@firebase/app-types/private'.
node_modules/@firebase/database/dist/esm/src/core/AuthTokenProvider.d.ts(17,39): error TS2307: Cannot find module '@firebase/app-types/private'.
node_modules/angularfire2/auth/auth.d.ts(10,20): error TS2503: Cannot find namespace 'firebase'.
node_modules/angularfire2/auth/auth.d.ts(11,36): error TS2503: Cannot find namespace 'firebase'.
node_modules/angularfire2/firebase.app.module.d.ts(5,45): error TS2503: Cannot find namespace 'firebase'.
node_modules/angularfire2/firebase.app.module.d.ts(8,17): error TS2503: Cannot find namespace 'firebase'.
node_modules/angularfire2/firebase.app.module.d.ts(9,21): error TS2503: Cannot find namespace 'firebase'.
node_modules/angularfire2/firebase.app.module.d.ts(10,22): error TS2503: Cannot find namespace 'firebase'.
node_modules/angularfire2/firebase.app.module.d.ts(11,20): error TS2503: Cannot find namespace 'firebase'.
node_modules/angularfire2/firebase.app.module.d.ts(13,22): error TS2503: Cannot find namespace 'firebase'.
node_modules/angularfire2/firestore/collection/changes.d.ts(8,43): error TS2503: Cannot find namespace 'firebase'.
node_modules/angularfire2/firestore/collection/changes.d.ts(9,46): error TS2503: Cannot find namespace 'firebase'.
node_modules/angularfire2/firestore/collection/changes.d.ts(9,80): error TS2503: Cannot find namespace 'firebase'.
node_modules/angularfire2/firestore/collection/changes.d.ts(10,49): error TS2503: Cannot find namespace 'firebase'.
node_modules/angularfire2/firestore/collection/changes.d.ts(10,95): error TS2503: Cannot find namespace 'firebase'.
node_modules/angularfire2/firestore/collection/changes.d.ts(10,140): error TS2503: Cannot find namespace 'firebase'.
node_modules/angularfire2/firestore/collection/changes.d.ts(10,182): error TS2503: Cannot find namespace 'firebase'.
node_modules/angularfire2/firestore/collection/changes.d.ts(11,49): error TS2503: Cannot find namespace 'firebase'.
node_modules/angularfire2/firestore/collection/changes.d.ts(11,94): error TS2503: Cannot find namespace 'firebase'.
node_modules/angularfire2/firestore/collection/changes.d.ts(11,130): error TS2503: Cannot find namespace 'firebase'.
node_modules/angularfire2/firestore/collection/collection.d.ts(8,54): error TS2503: Cannot find namespace 'firebase'.
node_modules/angularfire2/firestore/collection/collection.d.ts(8,96): error TS2503: Cannot find namespace 'firebase'.
node_modules/angularfire2/firestore/collection/collection.d.ts(10,19): error TS2503: Cannot find namespace 'firebase'.
node_modules/angularfire2/firestore/collection/collection.d.ts(12,22): error TS2503: Cannot find namespace 'firebase'.
node_modules/angularfire2/firestore/collection/collection.d.ts(12,69): error TS2503: Cannot find namespace 'firebase'.
node_modules/angularfire2/firestore/collection/collection.d.ts(13,27): error TS2503: Cannot find namespace 'firebase'.
node_modules/angularfire2/firestore/collection/collection.d.ts(14,25): error TS2503: Cannot find namespace 'firebase'.
node_modules/angularfire2/firestore/collection/collection.d.ts(15,30): error TS2503: Cannot find namespace 'firebase'.
node_modules/angularfire2/firestore/collection/collection.d.ts(16,27): error TS2503: Cannot find namespace 'firebase'.
node_modules/angularfire2/firestore/collection/collection.d.ts(17,27): error TS2503: Cannot find namespace 'firebase'.
node_modules/angularfire2/firestore/document/document.d.ts(8,10): error TS2503: Cannot find namespace 'firebase'.
node_modules/angularfire2/firestore/document/document.d.ts(9,22): error TS2503: Cannot find namespace 'firebase'.
node_modules/angularfire2/firestore/document/document.d.ts(10,28): error TS2503: Cannot find namespace 'firebase'.
node_modules/angularfire2/firestore/document/document.d.ts(14,42): error TS2503: Cannot find namespace 'firebase'.
node_modules/angularfire2/firestore/firestore.d.ts(9,55): error TS2503: Cannot find namespace 'firebase'.
node_modules/angularfire2/firestore/firestore.d.ts(12,25): error TS2503: Cannot find namespace 'firebase'.
node_modules/angularfire2/firestore/interfaces.d.ts(4,11): error TS2503: Cannot find namespace 'firebase'.
node_modules/angularfire2/firestore/interfaces.d.ts(5,14): error TS2503: Cannot find namespace 'firebase'.
node_modules/angularfire2/firestore/interfaces.d.ts(14,37): error TS2503: Cannot find namespace 'firebase'.
node_modules/angularfire2/firestore/interfaces.d.ts(14,80): error TS2503: Cannot find namespace 'firebase'.
node_modules/angularfire2/firestore/interfaces.d.ts(16,10): error TS2503: Cannot find namespace 'firebase'.
node_modules/angularfire2/firestore/interfaces.d.ts(17,12): error TS2503: Cannot find namespace 'firebase'.
node_modules/angularfire2/firestore/observable/fromRef.d.ts(6,41): error TS2503: Cannot find namespace 'firebase'.
node_modules/angularfire2/firestore/observable/fromRef.d.ts(6,80): error TS2503: Cannot find namespace 'firebase'.
node_modules/angularfire2/firestore/observable/fromRef.d.ts(7,41): error TS2503: Cannot find namespace 'firebase'.
node_modules/angularfire2/firestore/observable/fromRef.d.ts(7,98): error TS2503: Cannot find namespace 'firebase'.
node_modules/angularfire2/firestore/observable/fromRef.d.ts(8,48): error TS2503: Cannot find namespace 'firebase'.
node_modules/angularfire2/firestore/observable/fromRef.d.ts(8,93): error TS2503: Cannot find namespace 'firebase'.
```

**Comment by yassbaat** [comment] 2017-12-19 08:23
getting the same problem during the build with the angular CLI which throws this error:
![image](https://user-images.githubusercontent.com/30470601/34147517-05150d74-e4af-11e7-81b2-9f1bc036e309.png)

**Comment by devpeerapong** [comment] 2017-12-19 08:34
4.8.1 change the types file path, you either change all the types to match the new path or downgrade to 4.8.0.

**Comment by polo13999** [comment] 2017-12-19 09:50
it's miss https://github.com/firebase/firebase-js-sdk/blob/master/packages/app-types/private.d.ts
this file . the same problem here

**Comment by tonyshaji** [comment] 2017-12-19 10:28
having the same problem

**Comment by ZouYouShun** [comment] 2017-12-19 12:17
same problem with [bjornharvold](https://github.com/bjornharvold), how can solve it, 
add `import * as firebase from 'firebase';` can solve it once, but when change file the error message is also show QQ

**Comment by jshcrowthe** [comment] 2017-12-19 19:00
@mcfarljw thanks for the issue! I was looking at this and it seems that the issue is `yarn` specific (I was able to repro on my end but `NPM` didn't have the same behavior).

Let me see what I can do about this.

**Comment by jshcrowthe** [comment] 2017-12-19 19:02
@bjornharvold the issue you are seeing is related to the issue described in #388. Follow the suggested update there and you'll be good to go!

**Comment by jshcrowthe** [comment] 2017-12-19 19:18
@mcfarljw a little searching reveals that this has already been acknowledged by the yarn team (see https://github.com/yarnpkg/yarn/issues/4850). I'm going to close this in favor of an upstream fix.

**Closed by jshcrowthe** 2017-12-19 19:18 UTC
Labels: Component: Core

**Comment by xjuanc** [comment] 2017-12-21 09:37
Same is happening to me on NPM, had to go back to 4.8.0

**Comment by sajeetharan** [comment] 2017-12-25 03:45
Here is the similar question asked on SO 

Angular Cannot find module '@firebase/app-types/private' - Firebase throws error

https://stackoverflow.com/questions/47949311/angular-cannot-find-module-firebase-app-types-private-firebase-throws-error/47949323#47949323

**Comment by vincentwoo** [comment] 2018-05-15 12:32
It seems that Yarn does not consider this to be an error on their end: https://github.com/yarnpkg/yarn/issues/4850#issuecomment-384376115.

Any chance for a fix on the Firebase end?

**Comment by mesqueeb** [comment] 2018-10-04 05:32
I have the same issue!

**Comment by blurymind** [comment] 2019-03-25 20:34
me too
