### ISSUE TITLE
onSnapshot inconsistency with includeMetadataChanges when adding a document

### ISSUE THREAD

**Issue by grundmanise** [firebase/firebase-js-sdk#1930] opened 2019-06-29 19:22 UTC
* Operating System version: MacOS 10.14.5
  * Browser version: Chrome 75.0.3770.90
  * Firebase SDK version: 6.2.4
  * Firebase Product: firestore

#### Description:

I'll quote @reneeOlson:

> I'm in iOS, but I'm seeing a related strange behavior. When I add a document to a collection and then check for pendingWrites to server - if it's local, then under documentChanges it calls ".added." But once pendingWrites comes back as false, then under documentChanges it comes in under .modified. This seems to be a bug, as I'm only adding new documents and they cannot be modified.

_Originally posted by @reneeOlson in https://github.com/firebase/firebase-js-sdk/issues/471#issuecomment-362132892_

I'm getting the same odd behavior with the JS SDK. For me, that's a bug.

#### Steps to reproduce:
1. Have a snapshot listener for a query:
```
query.onSnapshot(
   { includeMetadataChanges: true },
   (querySnapshot) => {
       querySnapshot
           .docChanges({ includeMetadataChanges: true })
           .forEach(function docChanged(change) {
               console.log(change.doc.metadata.hasPendingWrites, change.type);
           });
   }
);
```
2. Add a document to the collection which the snapshot is listening to
```
collection.add(foo)
```
3. Observe
   1. `hasPendingWrites === true` -> `change.type === "added"`
   2. `hasPendingWrites === false` -> `change.type === "modified"`

**Comment by schmidt-sebastian** [comment] 2019-06-29 19:34
@grundmanise Thanks for filing this issue! 

What you describe matches the expected behavior. If you opt into metadata changes and issue a write to a collection that you are listening to, you will receive at least two events:

- The first event will raise a QuerySnapshot with `hasPendingWrites:true` which contains an added DocumentSnapshot with [hasPendingWrites:true](https://firebase.google.com/docs/reference/js/firebase.firestore.DocumentSnapshot.html#metadata)
- When the write has been committed, you will receive a QuerySnapshot with `hasPendingWrites:false`. To let you know which document's metadata has changed, we will include the affected document in the `modified` list. The DocumentSnapshot will now have  `hasPendingWrites:false`.

Even if the document's data did not change, a metadata change causes a document to be added to the `modified` list. 

This is as intended and I will close this issue for now. If this behavior doesn't work for you, feel free to respond and we can re-open your issue.

**Closed by schmidt-sebastian** 2019-06-29 19:34 UTC
Labels: api: firestore
