### ISSUE TITLE
firebase SDK v9 update current user fail

### ISSUE THREAD

**Issue by freefony** [firebase/firebase-js-sdk#5753] opened 2021-11-23 09:35 UTC
### Describe your environment
* Operating System version: MacOS 11.2.3
* Browser version: Chrome, Version 95.0.4638.69 (Official Build) (x86_64)
* Firebase SDK version: 9.4.1
* Firebase Product: auth

I am using SDK v9 and having issues with updating user profiles fails with 

```
TypeError: user._clone is not a function
    at AuthImpl.updateCurrentUser (auth_impl.ts:309)
    at updateUser (firebase.service.ts:41)
    at Object.signUp (firebase.service.ts:31)
    at async handlesubmit (index.tsx:32)
```
here in the firebase SDK

```
async updateCurrentUser(userExtern: User | null): Promise<void> {
    // The public updateCurrentUser method needs to make a copy of the user,
    // and also check that the project matches
    const user = userExtern
      ? (getModularInstance(userExtern) as UserInternal)
      : null;
    if (user) {
      _assert(
        user.auth.config.apiKey === this.config.apiKey,
        this,
        AuthErrorCode.INVALID_AUTH
      );
    }
    return this._updateCurrentUser(user && user._clone(this));
  }
```

Firebase `User` does not have any `_clone` property and if it is supposed be on UserInternal, doesn't seem to be working.

**Comment by sam-gc** [comment] 2021-11-24 15:17
The `_clone` property exists on instances of `UserInternal`, which is what the SDK expects:
https://github.com/firebase/firebase-js-sdk/blob/086df7c7e0299cedd9f3cff9080f46ca25cab7cd/packages/auth/src/core/user/user_impl.ts#L141-L147

What are you passing in to `updateCurrentUser`? If you're just passing in a plain object that meets the interface of `User`, it won't work

**Comment by freefony** [comment] 2021-11-24 18:04
Thanks @jbalidiong and @sam-gc for your responses. I think you are both right but i still can't find a fix from the documentation. 
Your are right I am using user object of type `User` that is returned on `auth.getCurrentUser`.
the doc did say to use it though `(method) Auth.updateCurrentUser(user: User | null): Promise<void>`
infact, `UserInternal` is not a public interface.
![Screen Shot 2021-11-24 at 7 03 55 PM](https://user-images.githubusercontent.com/1643919/143291658-af80117a-5371-4fce-b5b4-d45a5f02520b.png)

**Comment by freefony** [comment] 2021-11-24 20:20
@jbalidiong all i was trying to do is update users with `displayName` after signup.
Below is the full function
```
const signUp = async (email:string, password:string, name:string) => {
  try {
    const cred = await createUserWithEmailAndPassword(auth, email, password)
    if (cred.user) {
      
      await updateUser({...cred.user, displayName: name})
      return auth.currentUser
    }
  } catch (e) {
    console.error(e)
    return null
  }
}
```

**Comment by sam-gc** [comment] 2021-11-24 22:19
@freefony this line is the issue: `await updateUser({...cred.user, displayName: name})`

This line is destructuring the user object and creating a **new** object with a displayName field. The SDK expects an instance of a user that was created within the SDK; you won't be able to pass in an arbitrary JavaScript dictionary like this. To accomplish what you're trying to do here, please use the [`updateProfile`](https://firebase.google.com/docs/reference/js/auth.md#updateprofile) method, i.e.:

```js
await updateProfile(cred.user, {displayName: name});
```

I'm going to close this issue out as working as intended. Please feel free to follow up if you have more questions.

**Closed by sam-gc** 2021-11-24 22:19 UTC
Labels: api: auth, needs-attention, v9

**Comment by freefony** [comment] 2021-11-25 09:35
Thanks @sam-gc . that worked

**Comment by helloheesu** [comment] 2021-12-05 10:45
@sam-gc Thank you, I had a similar issue and your answer explains my issue as well! 

Could you tell me where I can find about this 'expectation' in reference? I want to improve my understanding about SDK and docs.

> The SDK expects an instance of a user that was created within the SDK; you won't be able to pass in an arbitrary JavaScript dictionary like this.
