### ISSUE TITLE
Seeing async issues with Firebase Auth 4.13.0

### ISSUE THREAD

**Issue by jamesdaniels** [firebase/firebase-js-sdk#745] opened 2018-04-30 19:23 UTC
### [REQUIRED] Describe your environment

  * Operating System version: rodete 201804RD3-2
  * Firebase SDK version: 4.13.0
  * Firebase Product: auth

Chrome Version 65.0.3325.181 (Official Build) (64-bit)

### [REQUIRED] Describe the problem

`signInWithPopup` is not working, unless a breakpoint is placed on my workstation; suggested some async issue. Cannot reproduce on other machines.

#### Steps to reproduce:

Clicking sign in only engages the app spinner until timeout on https://appship.io/

#### Relevant Code:

```javascript
      this.signInButton.click(() => {
        this.signInButton.prop('disabled', true);
        this.auth.signInWithPopup(new firebase.auth.GoogleAuthProvider()).catch(e => {
          this.signInButton.prop('disabled', false);
          console.error(e);
          if (e.code === 'auth/operation-not-supported-in-this-environment') {
            window.alert('Firebase auth does not work in this environment. Are you using private browsing or incognito? If yes try again in non-incognito mode.');
          } else {
            window.alert('There was an error signing-in Firebase: \n\n' + e.toString());
          }
        }).then(() => {
          this.signInButton.prop('disabled', false);
        });
      });
```

**Comment by wti806** [comment] 2018-05-01 00:10
I tested with the app you provided. It works fine for me. Did you test it in browser environment?

**Comment by jamesdaniels** [comment] 2018-05-01 19:28
Yes, this is in the web browser; seems just to be that machine. Are there any suggested diagnostic methods for auth? If there is a bug would be happy to help find it.

**Comment by bojeil-google** [comment] 2018-05-01 22:06
So are you saying the Promise hangs without resolving? Can you check the browser console for any errors? That would be the first place to start. 
Also, is the popup actually opening? Do you get redirected to sign in with Google?

**Comment by jamesdaniels** [comment] 2018-05-01 22:51
Correct, hangs without resolving, no popup, no errors until timeout. If I
put a breakpoint in, hit it, and then continue it does trigger the popup.

**Comment by hiepxanh** [comment] 2018-05-11 04:11
I guest the problem is chrome version or popup not allow (blocking by something). I experienced that error sometime

**Comment by jamesdaniels** [comment] 2018-05-12 04:17
@hiepxanh I'd have guessed popup getting blocked too, but simply adding a breakpoint and immediately hitting continue allows it to work. We've seen bugs in a past with the realtime database resolving sync rather than async and that caused a similar problem. Which is why I'm thinking it has something to do with timing. 

Chrome 65.0.3325.181

**Comment by malcolmdeck** [comment] 2020-05-05 23:53
Given that we haven't been able to consistently reproduce this nor has this been touched in the intervening 2 years, I'm closing this. If you see this issue again, please re-open.

**Closed by malcolmdeck** 2020-05-05 23:53 UTC
Labels: api: auth
