### ISSUE TITLE
Can't specify specific services to initalize when calling initializeApp()

### ISSUE THREAD

**Issue by JosephReece** [firebase/firebase-js-sdk#8460] opened 2024-08-25 11:47 UTC
### Operating System

macOS Monterey 12.7.3

### Environment (if applicable)

Chrome 127.0.6533.120

### Firebase SDK Version

10.13.0

### Firebase SDK Product(s)

Firestore

### Project Tooling

React using Ionic Capacitor's default toolset

### Detailed Problem Description

Creating an instance of a firebaseApp also creates instances of other services (such as analytics, firestore etc) - this means that you cannot specify config options for each service that has already been initalised.

### Steps and code to reproduce issue

I create an instance of my app.

```
const firebaseConfig = {
  apiKey: import.meta.env.VITE_FIREBASE_API_KEY,
  authDomain: import.meta.env.VITE_FIREBASE_AUTH_DOMAIN,
  databaseURL: import.meta.env.VITE_FIREBASE_DATABASE_URL,
  projectId: import.meta.env.VITE_FIREBASE_PROJECT_ID,
  storageBucket: import.meta.env.VITE_FIREBASE_STORAGE_BUCKET,
  messagingSenderId: import.meta.env.VITE_FIREBASE_MESSAGING_SENDER_ID,
  appId: import.meta.env.VITE_FIREBASE_APP_ID,
  measurementId: import.meta.env.VITE_FIREBASE_MEASUREMENT_ID,
};

// Initialize Firebase
const app = initializeApp(firebaseConfig);

// Get Firestore
const firestore = getFirestore(app);
```

This works fine but then if I want to specify certain settings for firestore, I have to add configuration details for this service.

```
// Specify firestore settings

const firestore = initializeFirestore(app, {localCache: memoryLocalCache()});
```

I can't do this because `initializeFirestore()` has already been called by `initializeApp()`, it just throws an error and I can't specify any settings.

<img width="531" alt="Screenshot 2024-08-25 at 12 41 56" src="https://github.com/user-attachments/assets/8867c06b-5215-4f46-9263-325218ed6086">

I also can't specify individual instances for each service without creating an app instance (as they all take in the app instance as a parameter). I can't specify whether to create certain services or not because this option is not available when calling `initializeApp()`.

Because of this there seems to be no way to specify any sort of configuration for firestore (or any other service created by `initializeApp()`.

**Comment by jbalidiong** [comment] 2024-08-26 14:53
Hi @JosephReece, thanks for reaching out. I tried replicating the issue but I was only able to see the error on initial refresh done by the app. However, I tried refreshing the page and it works as intended. Does the issue persist after refreshing the page or just the initial reload after the code change?

**Comment by rromanchuk** [comment] 2024-08-27 00:01
Something certainly regressed for me when using 10.13, that works again when swapping 10.12.2.  It's probably user error, but just posting in case the signal gives any hints. Not exactly related, but suspiciously similar around initialization and next service setup.  I'll come back and update once i get a chance to poke around some more. 

```html
<script type="module">
  const firebaseConfig = {}; // [..clipped]

  import { initializeApp } from "https://www.gstatic.com/firebasejs/10.13/firebase-app.js";
  import { getAuth,
    connectAuthEmulator,
    GoogleAuthProvider,
    signInWithCredential } from "https://www.gstatic.com/firebasejs/10.13/firebase-auth.js";

  const app = initializeApp(firebaseConfig);
  const auth = getAuth(app); // explodes 
  connectAuthEmulator(auth, "http://localhost:9099");

  // other services
</script>
```

**Comment by JosephReece** [comment] 2024-08-27 08:51
@jbalidiong I kept getting the error repeatedly, even restarting the server. Tried replicating this with a minimal repro with no success. Made some changes to the project I originally was working on where I found the bug and it seems to be working now - I’ll do some more digging and keep you guys posted if I find anything.

**Comment by MarkDuckworth** [comment] 2024-08-28 19:34
I also attempted to reproduce, but was not able to reproduce.

I'll leave this open with the `needs-info` label. oss-bot will close it in 10 days if you are unable to find a reproduction and update this issue. Thanks!

**Closed** 2024-09-10 01:04 UTC
Labels: question, api: firestore, needs-info, no-recent-activity
