### ISSUE TITLE
Can not sign-in using Multiple Auth Providers with Chrome extension Manifest v3

### ISSUE THREAD

**Issue by deepblue-will** [firebase/firebase-js-sdk#6699] opened 2022-10-17 00:54 UTC
### [REQUIRED] Describe your environment

- Operating System version: Mac Os
- Browser version: Chrome latest
- Firebase SDK version: 9.9.3
- Firebase Product: auth

### [REQUIRED] Describe the problem
The following examples cannot be achieved with Chrome extension Manifest v3.
https://firebase.google.com/docs/auth/web/account-linking

Because the functions(`linkWithPopup ` and `linkWithRedirect`) do not working in the Chrome extension Manifest v3.

Is there any way to achieve this with a chrome extension manifest v3?

**Comment by jbalidiong** [comment] 2022-10-17 15:01
Hi @deepblue-will, thanks for filling this. Most auth flow that works on manifest v2 is not working on manifest v3. We're aware of the issue but can't provide any timeline for updates/changes. I'm marking this as duplicate of #6567.

**Closed by jbalidiong** 2022-10-17 15:01 UTC
Labels: api: auth
