### ISSUE TITLE
SyntaxError: The requested module '@firebase/rules-unit-testing' does not provide an export named 'RulesTestEnvironment'.

### ISSUE THREAD

**Issue by asaadjaber** [firebase/firebase-js-sdk#7987] opened 2024-01-29 11:04 UTC
### Operating System

MacOS 14.3.

### Browser Version

Firefox/122.0.

### Firebase SDK Version

13.0.3

### Firebase SDK Product:

Firestore

### Describe your project's tooling

iOS app with Mocha v10.2.0 and node v20.9.0.

### Describe the problem

I was trying to run a unit test locally to test writes to my database which is in Cloud Firestore. I wrote a test which I called 'test.js' that imports RulesTestEnvironment from the @firebase/rules-unit-testing module. The test uses an import from @firebase/rules-unit testing and another from "firebase/firestore". 

```
import {
  assertFails,
  assertSucceeds,
  initializeTestEnvironment,
  RulesTestEnvironment,
} from "@firebase/rules-unit-testing"
```

When I tried to run the unit test from the command line, I ran into an error that said 'SyntaxError: The requested module '@firebase/rules-unit-testing' does not provide an export named 'RulesTestEnvironment'.

The error that appeared:
<img width="846" alt="Screenshot 2024-01-29 at 12 20 02" src="https://github.com/firebase/firebase-js-sdk/assets/13552884/f3a51c2a-b1d7-4355-b3a7-d626bf666d64">

### Steps and code to reproduce issue

After I started the emulator, I ran the test in this file [https://github.com/asaadjaber/special-parakeet-fork/blob/cloud-firestore-unit-tests-using-mocha/Special%20Parakeet/test/test.js](url) from the command line using `npm test` and I encountered the error saying 'SyntaxError: The requested module '@firebase/rules-unit-testing' does not provide an export named 'RulesTestEnvironment'.

**Comment by ehsannas** [comment] 2024-01-29 21:40
Thanks for reporting @asaadjaber. Have you installed the [@firebase/rules-unit testing](https://www.npmjs.com/package/@firebase/rules-unit-testing) package in addition to the firebase package? I see the RulesTestEnvironment [exported](https://github.com/firebase/firebase-js-sdk/blob/3f8cbcd18f47fcae8c0d8060fd8c245c025784c0/packages/rules-unit-testing/src/public_types/index.ts#L159).

**Comment by asaadjaber** [comment] 2024-01-30 08:24
Hi, no I have added the import to import RulesTestEnvironment using the sample code that was provided in the guide [https://firebase.google.com/docs/firestore/security/test-rules-emulator](url) which is here.

**Comment by asaadjaber** [comment] 2024-01-30 10:48
Hi @ehsannas upon installing the firebase rules unit testing package and the firebase package I reran the test and I ran into the same error:
<img width="851" alt="Screenshot 2024-01-30 at 12 45 41" src="https://github.com/firebase/firebase-js-sdk/assets/13552884/761d7821-6181-4df6-a0d8-fc211cf20c34">

**Comment by hsubox76** [comment] 2024-01-31 19:11
`RulesTestEnvironment` is a TypeScript type, and it's not in the actual JS file (index.cjs.js) but in the typescript definitions file (index.d.ts), which would only be read by a TypeScript compiler. Since you have a minimal JS setup (using Node directly) and are not using TypeScript, you can just ignore that and not import it.

It happens to be the type returned by `initializeTestEnvironment` (assigned to `testEnv` in the docs and in your file), which doesn't matter at all if you're not using TypeScript.

**Comment by asaadjaber** [comment] 2024-02-01 12:00
Hi, I have tried commenting out the import and running the test using the `initializeTestEnvironment`,



```
let testEnv = await initializeTestEnvironment({
  projectId: "special-parakeet",
  firestore: {
    rules: fs.readFileSync("special-parakeet-firestore.rules", "utf8"),
  },
});
```
That resulted in this error:
<img width="411" alt="Screenshot 2024-02-01 at 13 52 59" src="https://github.com/firebase/firebase-js-sdk/assets/13552884/5cefc598-a862-46b0-b61d-dd6180eaefbe">

**Comment by asaadjaber** [comment] 2024-02-06 13:41
Hi @DellaBitta , I used the code below to initialize the test environment. I can try out your suggestion though. 
```
let testEnv = await initializeTestEnvironment({
  projectId: "special-parakeet",
  firestore: {
    rules: fs.readFileSync("special-parakeet-firestore.rules", "utf8"),
  },
});
```

**Comment by asaadjaber** [comment] 2024-02-06 13:43
I checked the wrong file. I used this to import `RulesTestEnvironment`
```
import {
  assertFails,
  assertSucceeds,
  initializeTestEnvironment,
  RulesTestEnvironment,
} from "@firebase/rules-unit-testing"
```

**Comment by DellaBitta** [comment] 2024-02-12 14:27
Can you update the import so that it reads:

```
import {
  assertFails,
  assertSucceeds,
  initializeTestEnvironment
} from "@firebase/rules-unit-testing"
```

and see if that does the trick? If not, then can you provide the source to a minmal reproducible test case? Thank you!

**Comment by asaadjaber** [comment] 2024-02-14 11:16
Hi @DellaBitta , I removed the import statement for RulesTestEnvironment and then I reran the test and I got the following error: 
<img width="264" alt="Screenshot 2024-02-14 at 12 59 59" src="https://github.com/firebase/firebase-js-sdk/assets/13552884/f0e06685-76fe-42e6-b648-0de64ae99ff8">. 

This is the minimum reproducible test case: 

```
import {
  assertFails,
  assertSucceeds,
  initializeTestEnvironment,
} from "@firebase/rules-unit-testing"

let testEnv = await initializeTestEnvironment({
  projectId: "special-parakeet",
  firestore: {
    rules: fs.readFileSync("special-parakeet-firestore.rules", "utf8"),
  },
});

import { setDoc } from "firebase/firestore";

const context = testEnv.unauthenticatedContext();

test("Test simulated write by an unauthenticated user", async () => {
	await assertSucceeds(setDoc(context.firestore().collection("isFavorited"), "Sparrow"), { "name": "Sparrow", "isFavorited": true });
    // await assertSucceeds(setDoc(context.firestore(), '/isFavorited/Sparrow'), { "name": "Sparrow", "isFavorited": true });
});
```

**Comment by DellaBitta** [comment] 2024-02-14 13:32
Hi @asaadjaber,

You need to also import the `fs` module:

```
import * as fs from 'fs';
```

That should clear up that error.

**Comment by asaadjaber** [comment] 2024-02-21 09:10
I reran the test and my test case now looks like this

```
import * as fs from 'fs';

import {
  assertFails,
  assertSucceeds,
  initializeTestEnvironment,
} from ***@***.***/rules-unit-testing"

let testEnv = await initializeTestEnvironment({
  projectId: "special-parakeet",
  firestore: {
    rules: fs.readFileSync("special-parakeet-firestore.rules", "utf8"),
    host: "127.0.0.1",
    port: 8080,
  },
});

import { setDoc } from "firebase/firestore";

const context = testEnv.unauthenticatedContext();

test("Test simulated write by an unauthenticated user", async () => {
await assertSucceeds(setDoc(context.firestore().collection("isFavorited"),
"Sparrow"), { "name": "Sparrow", "isFavorited": true });
    // await assertSucceeds(setDoc(context.firestore(),
'/isFavorited/Sparrow'), { "name": "Sparrow", "isFavorited": true });
});|
```

The error I am getting now is:
[image: Screenshot 2024-02-14 at 16.38.48.png]

**Comment by dconeybe** [comment] 2024-02-23 19:12
@asaadjaber The error is due to passing a `CollectionReference` as an argument to `setDoc()`, which expects a `DocumentReference` as an argument.

Try replacing

```js
await assertSucceeds(setDoc(context.firestore().collection("isFavorited"),
  "Sparrow"), { "name": "Sparrow", "isFavorited": true });
```

with

```js
await assertSucceeds(setDoc(context.firestore().doc("isFavorited/Sparrow"),
  { "name": "Sparrow", "isFavorited": true }));
```

Since it appears that you have solved the originally-reported problem, I'm going to close this issue. Feel free to open a new issue if you run into bugs in Firestore. Thanks!

**Closed by dconeybe** 2024-02-23 19:12 UTC
Labels: question, needs-attention, testing-sdk
