### ISSUE TITLE
Upgrading firebase and firebase-admin in the same project causes problems again

### ISSUE THREAD

**Issue by richtera** [firebase/firebase-js-sdk#5709] opened 2021-11-07 22:58 UTC
### [REQUIRED] Describe your environment
nv.dev environment with 
    "firebase": "^9.0.1",
    "firebase-admin": "^9.11.1",
Upgrading to latest breaks the project.

  * Operating System version: MacOS 12.0.1 (21A559)
  * Browser version: Version 95.0.4638.69 (Official Build) (x86_64)
  * Firebase SDK version: 9.0.1
  * Firebase Product: auth,database,storage,functions,firestore

### [REQUIRED] Describe the problem
Upgrading to latest npm packages on firebase and firebase-admin mismatch again.
This is identical to what happened in this defect https://github.com/firebase/firebase-js-sdk/issues/752

**Comment by richtera** [comment] 2021-11-08 14:10
The upgrade was versions involved are from and to
firebase                         9.1.3   9.3.0  9.3.0  dependencies    https://firebase.google.com/                                            
firebase-admin                   9.12.0  9.12.0 10.0.0 dependencies    https://firebase.google.com/                                            
i.e. 9.1.3 to 9.3.0
and 9.12.0 to 10.0.0
So 9.3.0 and 10.0.0 don't seem to be able to live together in the same project agin.

**Comment by jbalidiong** [comment] 2021-11-09 11:27
Hi @richtera, thanks for reaching out. I tried to replicate it but I wasn't able to experience the same behavior. If I can replicate the issue, I can have a better look into it. Please share a minimal, but complete sample of a project that I can run locally.

**Comment by richtera** [comment] 2021-11-09 11:31
I can retry it again toward the end of the week, my upgrade took a nose dive after upgrading the firebase and firebase-admin modules due to a dependency that is somehow shared between them but now mismatching. It used to be the @firebase modules, but after seeing the problem I didn't have the bandwidth to find out exactly which ones.

**Comment by richtera** [comment] 2021-11-16 17:54
Ok, so the main problem is that now firebase/firestore at al are no longer loadable in nodejs making all jest test scripts fail.
![image](https://user-images.githubusercontent.com/708186/142039239-4e779393-89fd-4340-8dd6-dd5ee03c57bc.png)
I am trying to see if there is a special workaround for loading the web libraries in node to use under jsdom.

**Comment by Feiyang1** [comment] 2021-11-16 17:59
duplicate of https://github.com/firebase/firebase-js-sdk/issues/5687

**Closed** 2022-07-07 23:19 UTC
Labels: api: core, v9
