### ISSUE TITLE
How do we get the AccessToken in `onAuthStateChanged` callback?

### ISSUE THREAD

**Issue by jerrythomas** [firebase/firebase-js-sdk#5208] opened 2021-07-28 12:21 UTC
### [REQUIRED] Describe your environment

  * Operating System version: macOS
  * Browser version: Chrome 92.0
  * Firebase SDK version: 9.0.0.beta.5
  * Firebase Product: auth

### [REQUIRED] Describe the problem
How do I get the Access token in the `onAuthStateChanged` callback.

On sign-in we can get the credentials using the sample code below
```js
const result = await signInWithPopup(auth, provider);

const user = result.user;
// This gives you a OAuth Access Token for the provider.
const credential = OAuthProvider.credentialFromResult(result);
const token = credential.accessToken;
```

However in the `onAuthStateChanged` callback only the user is available and in this case `OAuthProvider.credentialFromResult()` returns null

The idToken can be obtained from the user, but not the AccessToken.

#### Relevant Code:

```javascript
onAuthStateChanged(auth, async (user) => {
      console.log(
        'cred from result',
        OAuthProvider.credentialFromResult(user)
      )
      console.log(
        'Idtoken',
        await user.getIdToken()
      )
    })
```

**Comment by looptheloop88** [comment] 2021-07-29 17:15
Hi @jerrythomas, thanks for the report. It seems that Firebase Auth for JS SDK v9 still doesn't support Google access token monitoring. You might need to use the [GApi library](https://developers.google.com/identity/sign-in/web/sign-in) to get the access token continuously. Per checking, there's already an internal bug _(b/187072938)_ filed for this feature, however we can't provide definite timelines or details for when it will be implemented. See issue for your #4850 reference.

Here's a sample [implementation](https://github.com/firebase/quickstart-js/blob/master/auth/google-credentials.html#L68-L69) from the JS SDK v8 quickstart project. Just convert it using JS SDK v9 modules.

**Comment by looptheloop88** [comment] 2021-07-29 17:16
I will close and mark this issue as duplicate of #4850.

**Closed by looptheloop88** 2021-07-29 17:16 UTC
Labels: api: auth, type: feature request, type: question, v9

**Comment by jerrythomas** [comment] 2021-07-30 04:18
Thanks, @looptheloop88. Is this applicable for only the Google API? 
What about third party AccessToken like when we use Microsoft OAuth provider?
