### ISSUE TITLE
FR: Firebase to integrate One-tap google login

### ISSUE THREAD

**Issue by mesqueeb** [firebase/firebase-js-sdk#521] opened 2018-02-18 11:18 UTC
Google has a great way to [login with just one tap](https://developers.google.com/identity/one-tap/web/overview)!

I'd love if firebase could integrate this. Any possibilities?

**Comment by bojeil-google** [comment] 2018-02-18 20:17
Duplicate of https://github.com/firebase/firebase-js-sdk/issues/455

**Closed** 2018-02-18 20:17 UTC
Labels: Type: Duplicate, feature-request
