### ISSUE TITLE
Firebase Auth is no longer working in incognito mode

### ISSUE THREAD

**Issue by opolo** [firebase/firebase-js-sdk#3004] opened 2020-05-01 18:34 UTC
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10 
  * Browser version: Version 81.0.4044.129 (Official Build) (64-bit)
  * Firebase SDK version: 7.13.1
  * Firebase Product: auth

### [REQUIRED] Describe the problem
Multiple of our users has reported, they are no longer able to login and use our product... After some investigation, it seems to happen for all the users, which accesses our platform in incognito mode. 

It seems to no longer be possible to use the firebase auth SDK in Google Incognito mode. The exact same users can log in with the exact same credentials or SSO integrations through firebase in non-incognito.

#### Steps to reproduce:
If users try to use firebase authentication on our platform in incognito mode, the error:
`{code: "auth/web-storage-unsupported", message: "This browser is not supported or 3rd party cookies and data may be disabled.", a: null}`
is thrown from the SDK. 

I believe it potentially can be an issue in a newer Chrome update, as I know Google has been experimenting with having Chrome block 3rd Party Cookies (I believe they experimented with it in version 83 of Chrome, which I am not using though).

**Comment by avolkovi** [comment] 2020-05-18 21:34
@opolo which sign in method and provider are you using? We are aware that popup-based signs in particular require localStorage and will not work when it is disabled.  As a potential workaround you can try signing directly with the provider (Google, Facebook, etc) using their SDK and then signing into Firebase using signInWithCredential().

**Comment by brianmhunt** [comment] 2020-05-25 15:32
I just started getting this error with Google Chrome 83 today, trying to sign in via a Google account while in Incognito mode.

![image](https://user-images.githubusercontent.com/135528/82826549-5c9a3f00-9e7b-11ea-9c23-ba4ad621cb5f.png)

**Comment by tmcf** [comment] 2020-05-28 06:38
Just updated to Chrome Version 83.0.4103.61 (Official Build) (64-bit)
Our firebase auth integration no longer appears to work..investigating.
This is not in incognito mode.

Still works with Chrome Canary Version 85.0.4157.4 (Official Build) canary (64-bit), Firebox, and Safari.

Sorry not to have more information at this time.

**Comment by opolo** [comment] 2020-05-30 09:00
@avolkovi it was one of our users that faced this issue; I do not believe I can get the information again. Perhaps the comments by @brianmhunt or @tmcf helps.

**Comment by raineorshine** [comment] 2020-06-04 23:32
Also getting this error after upgrading to Chrome 83.0.4103.61 (OSX). 

- Firebase v4.12.0
- GoogleAuthProvider
- signInWithRedirect
- incognito mode

**Comment by mparizeau-pdftron** [comment] 2020-06-05 16:24
Also getting this issue after updating to Chrome 83. It had been working consistently in incognito mode before that. Same error message as @brianmhunt 
```
{
  "code": "auth/web-storage-unsupported",
  "message": "This browser is not supported or 3rd party cookies and data may be disabled."
}
```

**Comment by ManiDoraisamy** [comment] 2020-06-14 19:06
> Also getting this issue after updating to Chrome 83. It had been working consistently in incognito mode before that. Same error message as @brianmhunt
> 
> ```
> {
>   "code": "auth/web-storage-unsupported",
>   "message": "This browser is not supported or 3rd party cookies and data may be disabled."
> }
> ```

Same problem with my app. It happens in incognito mode randomly and for some users it is consistent.

**Comment by MrCoder** [comment] 2020-06-18 07:57
This is happening to my app - https://app.zenuml.com . For myself, it is consistent on Chrome - Version 83.0.4103.106 (Official Build) (64-bit). Haven't heard anything from our users.

**Comment by schmidt-sebastian** [comment] 2020-06-18 19:20
Sorry, I think this may have been closed by mistake. Re-opening.

**Comment by jesselve** [comment] 2020-06-20 15:09
If you change the Chrome browser cookie settings from the default value of "Block third-party cookies in Incognito" to "Allow all cookies", Google authentication then succeeds in Chrome incognito:
![image](https://user-images.githubusercontent.com/3021609/85204918-d2ac8d00-b2e5-11ea-8066-b822491a2fd6.png)

(Not that this should be a work-around, of course -- just as additional information for the issue.)

Note also that once all cookies have been allowed, authentication then triggers console warnings regarding a missing 'SameSite' attribute:
![image](https://user-images.githubusercontent.com/3021609/85204971-2d45e900-b2e6-11ea-8963-c8b6d3dd2958.png)

**Comment by TheOtherJFK** [comment] 2020-06-27 20:28
I'm also having this issue only in Chrome in Incognito:
- Version 83.0.4103.116 (Official Build) (64-bit)
- MacOS 10.15.5 (19F101)

Happy to provide more info to debug if needed.

**Comment by vggarg96** [comment] 2020-06-29 14:21
Any solutions?? I am facing the same issues

**Comment by ManiDoraisamy** [comment] 2020-06-29 14:28
> Any solutions?? I am facing the same issues

I am facing the same issue intermittently. But, if I login using this sample app - https://fir-ui-demo-84a6c.firebaseapp.com/ and try logging in my app, it seems to work.

**Comment by vggarg96** [comment] 2020-06-29 16:39
> > Any solutions?? I am facing the same issues
> 
> I am facing the same issue intermittently. But, if I login using this sample app - https://fir-ui-demo-84a6c.firebaseapp.com/ and try logging in my app, it seems to work. You can use this as a workaround, if it is happens occasionally.

I am able to login normally but not in incognito mode

**Comment by scottcrossen** [comment] 2020-06-29 20:59
It looks like this issue is related to persistent storage in incognito. The team is currently working on rewriting the full auth SDK. This issue should be addressed when it launches. We currently have no plans to retroactively make this change in the main branch.

**Comment by scottcrossen** [comment] 2020-06-29 22:38
I deleted my previous comment. I will be looking more into this issue.

**Comment by curiouscod3** [comment] 2020-07-07 02:54
chrome://settings/cookies?search=allow+all

Allow All Cookies !

**Comment by jesselve** [comment] 2020-07-08 21:22
(Repeating my previous comment that changing the client browser settings to "allow all" -- or per the comment of @curiouscod3 -- is NOT an acceptable work-around.  We cannot expect our users to make this kind of change in their browsers.)

**Comment by vggarg96** [comment] 2020-07-09 13:22
I have 10K users of my application. @curiouscod3 are you suggesting that I should ask all my users to do that changes in there browser seriously????

**Comment by MeghaB** [comment] 2020-07-13 19:38
tracking internally via b/161150773

**Comment by etutlyaeva** [comment] 2020-07-14 14:59
I have the same issue.
"@angular/fire": "^6.0.2"
GoogleAuthProvider
signInWithRedirect
incognito mode

**Comment by rajorpratyush** [comment] 2020-07-15 10:27
This issue is recent, any updates ?

**Comment by avolkovi** [comment] 2020-07-15 16:38
Folks-

To provide a small update, we are looking at ways internally to mitigate this, some notes for now:

1) This issue is due to chrome blocking our use of local persistence within an iframe *in incognito*, though we understand that this behavior will become default even in non-incognito [within 2 years](https://www.theverge.com/2020/1/14/21064698/google-third-party-cookies-chrome-two-years-privacy-safari-firefox).

2) Unfortunately this breaks our implementation of the popup & redirect flows, fixing this issue will require a major rethink of how we perform these flows, including updating server side logic.  We're also going to look to see if there are short term fixes we can implement.

Workarounds for now:
1) As mentioned above (https://github.com/firebase/firebase-js-sdk/issues/3004#issuecomment-647007598), on the client side your customers can opt-out of this new behavior, this is obviously not ideal (https://github.com/firebase/firebase-js-sdk/issues/3004#issuecomment-655764893)

2) Until we have a long term fix, you can update your app to perform a "manual" OAuth Flow (example for [Google sign-in](https://firebase.google.com/docs/auth/web/google-signin#expandable-2)) by using signInWithCredential if you need to support Chrome Incognito.

**Comment by curiouscod3** [comment] 2020-07-19 07:34
@jesselve  Of Course, I mentioned it for the test/dev purpose because I was developing apps in that mode couldn't proceed anymore without the setting option.. I am also annoying with it.. I agree It should work without allow ******* all :)

**Comment by earok** [comment] 2020-07-22 04:40
Attempted work around #2 (use Google sign-in), but does not appear to work in Firebase Incognito mode.

- GAPI gives an error on page load:
details: "Cookies are not enabled in current environment."
error: "idpiframe_initialization_failed"

- Opening google sign in pop up window works, but doesn't trigger the data-onsuccess callback when sign in is complete. It works fine outside of incognito mode (and also when third party cookies are enabled).

**Comment by johnmark442** [comment] 2020-07-22 14:07
@avolkovi Same issue here. The second workaround of using a "manual" OAuth Flow also does not work, as it seems GAPI also needs cookie access, returning:

details: "Cookies are not enabled in current environment."
error: "idpiframe_initialization_failed"

Hoping the team will find a solution soon.

**Comment by mitar** [comment] 2020-07-23 05:58
Isn't this also something which should be breaking with newest Safari? https://webkit.org/blog/10218/full-third-party-cookie-blocking-and-more/ Is it breaking there as well? If not, why not and what are Chrome and Safari doing differently?

**Comment by vicdup** [comment] 2020-07-23 13:10
For those landing on this page from Google, you might want to check 
https://github.com/firebase/firebase-js-sdk/issues/865#issuecomment-394324472

Although it seems unrelated at first, I realized the issue was happening because of a "cross domain" cookie. Incognito mode in Chrome by default block cross domain cookies, not all of them.

This was happening because I was using the default firebase callback url https://auth-xxxx.firebaseapp.com/__/auth/handler

When registering my own url on the same domain as my website, it worked well even in incognito mode!

**Comment by patrickxchong** [comment] 2020-07-23 13:32
@vicdup For your method to work, the site has to be hosted with Firebase hosting right? I don't think one can do the same trick if the site is hosted somewhere else.

**Comment by HellBlazer616** [comment] 2020-07-31 18:00
As mentioned here https://github.com/firebase/firebase-js-sdk/issues/2241#issuecomment-658924408 firebase auth is being rewritten from the ground up. So, could we expect a fix in the new version?

**Comment by avolkovi** [comment] 2020-08-04 19:27
@HellBlazer616 We are working on providing fixes both in the new version and also back-porting the changes to the current version.  

Update on longer term fixes:
We should have a fix for the popup flow soon, the redirect flow will take longer as it requires a more complicated solution.

**Comment by patrickxchong** [comment] 2020-08-05 01:41
Thanks for the update @avolkovi ! Looking forward to the changes 😄 Do update us here when it's up!

**Comment by seki2020** [comment] 2020-10-16 09:50
Hi folks, Hope this can help. It is an alternative solution that was being used in my company's project.

To make the app working again, you have to create a new custom AUTH URL with the DOMAIN which you are using. 
In other words, The Domain of the new auth URL must equivalent to the Domain of your current web app. 
That can solve all the problems including the `sameSite` issue.

So how to change the auto-provision auth URL of firebase?
All steps were listed in the document.
See [Customizing the redirect domain for Google sign-in](https://firebase.google.com/docs/auth/web/google-signin?authuser=0#expandable-4)

I was inspired by this post [This browser is not supported or 3rd party cookies and data may be disabled. ](https://github.com/firebase/firebase-js-sdk/issues/865#issuecomment-394324472)
Thanks @bpetetot

**Comment by bojeil-google** [comment] 2020-11-06 19:00
You may have already noticed this but we had already fixed the popup flow for browsers with 3P cookies disabled. You should be able to use it without updating the SDK. As for the redirect flow, it is still a work in progress. For now, you may have to fallback on the popup flow for browsers with 3P cookies disabled.

**Comment by veeralpatel** [comment] 2021-04-14 19:17
@bojeil-google We have implemented workaround 2 mentioned [here](https://github.com/firebase/firebase-js-sdk/issues/3004#issuecomment-658871220) and still experiencing issues with the `idpiframe_initialization_failed` error being thrown on load. 

Is there another workaround you recommend before biting the bullet and implementing server-side Auth 2.0 flow?

**Comment by GorvGoyl** [comment] 2021-09-15 20:26
@avolkovi could you confirm if we updating the custom domain of cookie will fix the auth flow with 3rd party cookie disabled? even if project is not using firebase hosting? Just want to make sure before investing time in custom domain implementation.

**Comment by avolkovi** [comment] 2021-09-15 20:36
@sam-gc can you provide our latest guidance?

**Comment by sam-gc** [comment] 2021-09-15 21:07
@GorvGoyl we don't actually use cookies, it's just that the machinery that blocks third-party cookies in incognito also prevents certain features that we do make use of. What fix are you specifically looking at? Incognito mode should now work for `signInWithPopup`.

**Comment by GorvGoyl** [comment] 2021-09-15 21:35
@sam-gc thanks for the clarification on cookies part. I was actually using `signInWithRedirect` (Firebase: ^8.9.1) which was causing issue auth issue. `signInWithPopup` is working fine in incognito mode.

**Comment by danicholls** [comment] 2021-09-25 00:17
I seem to have experience this problem with Anonymous auth, and I believe it was on one of the provided (.app) domains.

**Comment by andrewhamili** [comment] 2021-09-25 00:23
Hi, for everyone that experienced this problem, just switch on the third pqrty cookies fornthe incognito sesssion and this will be resolved. :D

**Comment by igorsilveriocosta** [comment] 2022-01-26 22:06
I think that a workaround for this problem is to use `signInWithPopup` only when in incognito mode on Chrome, and `signInWithRedirect` when not in incognito mode. There is a way to us make the same test that firebase SDK makes to throws `auth/web-storage-unsupported`, for select the way of our users will do google login ? I don't found a easy solution looking in the firebase source code

**Comment by andrewhamili** [comment] 2022-01-27 00:12
On the blank incognito page, there is a slider for 3rd party cookies. You should enable third party cookies in irder for the firebase auth to work.

**Comment by joel-moonlight** [comment] 2022-01-27 08:46
> I think that a workaround for this problem is to use `signInWithPopup` only when in incognito mode on Chrome, and `signInWithRedirect` when not in incognito mode. There is a way to us make the same test that firebase SDK makes to throws `auth/web-storage-unsupported`, for select the way of our users will do google login ? I don't found a easy solution looking in the firebase source code

Yeah that would be great. I've tried detecting incognito mode for this exact reason, but this is not as easy as it looks: turns out incognito is made with the aim of not being easily detectable itself. Being able to directly test the firebase functionality that throws an error on incognito sure would be an ideal solution. Let us know if you find something @igorsilveriocosta !


@andrewhamili We can not ask our users to do that

**Comment by andrewhamili** [comment] 2022-01-27 08:53
@joel-moonlight this is not a restriction 9f the firebase but a restriction of the browser. I think it is on google chrome only. I do not know on other browsers if they are also disabling 3rd party cookies on browser mode similar to incognito of google chrome.

I think there is no fix or workaround that the firebase team can offer.

PS:  I haven't tried if using signInWithPopup might do some trick as advised by @igorsilveriocosta

**Comment by joel-moonlight** [comment] 2022-01-27 09:01
> I haven't tried if using signInWithPopup might do some trick as advised by @igorsilveriocosta

It does, hence our messages.

**Comment by andrewhamili** [comment] 2022-01-27 10:19
@joel-moonlight well thats good. But i think signInwithPopup won't work with webviews. It odes not work on in-app browser of Messenger App.

**Comment by joel-moonlight** [comment] 2022-01-27 12:43
That's why we want to use it only when `signInWithRedirect` won't work, hence our messages.

**Comment by veniplex** [comment] 2023-01-03 15:57
As I can verify in my own environment this issue still exists... Is there any idea on how to solve this and is there a timeline for it? It might be good to include a note about this behaviour in the firebase documentation becuase this issue now exists nearly 3 years...

**Comment by prameshj** [comment] 2023-01-03 17:52
> As I can verify in my own environment this issue still exists... Is there any idea on how to solve this and is there a timeline for it? It might be good to include a note about this behaviour in the firebase documentation becuase this issue now exists nearly 3 years...

The options listed in https://firebase.google.com/docs/auth/web/redirect-best-practices apply to this issue as well.

**Comment by prameshj** [comment] 2023-01-03 17:53
Closing since it is a duplicate of https://github.com/firebase/firebase-js-sdk/issues/6716

**Closed by prameshj** 2023-01-03 17:53 UTC
Labels: type: bug, api: auth, needs-attention, internal-bug-filed
