### ISSUE TITLE
Firebase npm package 8.2.0 -> 8.6.5: .add() works but .update() no longer works in firestore emulator

### ISSUE THREAD

**Issue by n8sb** [firebase/firebase-js-sdk#4999] opened 2021-06-09 08:16 UTC
### [REQUIRED] Describe your environment

  * Operating System version: MacOS 11.3
  * Browser version: 91.0.4472.77
  * Firebase SDK version: 9.12.1
  * Firebase Product: firestore emulator

After updating firebase from 8.2.0 to 8.6.5 the update function no longer works.  Add function works fine.  Reverting to 8.2.0 npm package fixed the issue.

#### Steps to reproduce:

Within my react app form, a button calls onClick  calling the function below:

#### Relevant Code:

```
const updateOrAddToDatabase = (e) => {
    if (e) {
      e.preventDefault();
    }

    let newData = { ...selectedCategory };
    delete newData.id;
    delete newData.dropdownName;

    const id = selectedCategory.id;
    if (id === "" || id === null) {
      newData.createdAt = new Date();

      db.collection("categories")
        .add(newData)
        .then(function (docRef) {
          newData.id = docRef.id;
          newData.dropdownName = newData.name;
          setSelectedCategory(newData);

          setAllCategories((previousCategories) => [
            ...previousCategories,
            newData,
          ]);

          setMessage({
            description: "Successfully added new category.",
            isError: false,
          });
        })
        .catch(function (error) {
          setMessage({
            description: `Error adding new category: ${error}`,
            isError: true,
          });
        });
    } else {
      console.log("updating");
      //update exisiting category
      db.collection("categories")
        .doc(id)
        .update(newData)
        .then(function () {
          console.log("In then");
          newData.id = id;
          setSelectedCategory(newData);

          let theCategories = [...allCategories];
          let index = theCategories.findIndex((category) => category.id === id);
          theCategories[index] = newData;
          setAllCategories(theCategories);

          setMessage({
            description: "Successfully updated existing category.",
            isError: false,
          });
        })
        .catch(function (error) {
          console.log("In error");
          setMessage({
            description: `Error updating existing category: ${error}`,
            isError: true,
          });
        });
    }
  };

```

**Possible Related log error:**
```
WARNING: invalid message: {"streamToken":"MA==","writes":[{"update":{"name":"projects/demo-94fog/databases/(default)/documents/categories/bDQvgnPhNNbpHgIRAaja","fields":{"order":{"integerValue":"5"},"image":{"stringValue":""},"name":{"stringValue":"Nate"},"createdAt":{"timestampValue":{"seconds":1623224058,"nanos":172000000}}}},"updateMask":{"fieldPaths":["createdAt","image","name","order"]},"currentDocument":{"exists":true}}]}
Jun 09, 2021 12:37:56 AM com.google.net.webchannel.server.common.ChannelProcessor run
WARNING: Failed to consume the event.
```

**Comment by n8sb** [comment] 2021-06-09 08:37
Update: 8.6.2 works as expected. Later releases do not.

**Comment by looptheloop88** [comment] 2021-06-09 17:14
Hi @n8sb, I wasn't able to replicate this issue. I've used the SDK version 8.6.5, however both [`add()`](https://firebase.google.com/docs/firestore/manage-data/add-data#add_a_document) and [`update()`](https://firebase.google.com/docs/firestore/manage-data/add-data#update-data) methods of Firestore are working fine.

If you're using an emulator, make sure to use the correct port and double check the security rules. You may also want to update the version of your Firebase Tools, if you haven't already.

If I can replicate the issue, I can have a better look into it. It would help if you could share a sample project that I can run locally.

**Comment by n8sb** [comment] 2021-06-09 17:45
Hi @looptheloop88.  Thanks for looking into this.  Im running 9.12.1.  Odd that add would work and not update.  Im not getting any permissions errors that would point to the security rules.  I'll continue running 8.6.2 since it is working as expected. Let me see if I can get you a project to test.

**Comment by looptheloop88** [comment] 2021-06-10 13:11
Thanks for the confirmation, @n8sb. I am using the same version of Firebase Tool. I will close this issue for now, since this can't be reproduced consistently. Please reopen the issue when the test project you will share with us is ready.

**Closed by looptheloop88** 2021-06-10 13:11 UTC
Labels: api: firestore, needs-attention, testing-sdk
