### ISSUE TITLE
HTTPS hosts for emulators not working

### ISSUE THREAD

**Issue by jasonford** [firebase/firebase-js-sdk#5115] opened 2021-07-03 00:49 UTC
It seems like this code section illustrates the major choke point for https hosts working for the emulators.

https://github.com/firebase/firebase-js-sdk/blob/129888c6e28e848127169a797ba703ab15e1f119/packages/firestore/src/lite/database.ts#L245

I see that the front end emulator gets all the way to making a request with 'http://' prepended to my host, but then I get an inevitable "Blocked loading mixed active content" error since I'm developing over an https connection.

I was instructed in issue #3104 (Edit: issue opened in other repo. https://github.com/firebase/firebase-tools/issues/3104#issuecomment-772928581) that the new version would handle this correctly so I tried but sadly the wild code chase led here :( though the suggestion did fix 1/2 of the issue, the https host complication seems like it was overlooked.

Is there a workaround or is this just not possible now?
Is there a plan/timeline for HTTPS host support for the emulators?

I'll probably at least try another monkey patch and report back here if there is any good news...

Thanks for your attention!

**Comment by looptheloop88** [comment] 2021-07-05 17:38
Hi @jasonford, I would like to confirm if you're reporting that Firebase emulators can't be started in HTTPS or the SDK can't accept other domains?

**Comment by jasonford** [comment] 2021-07-06 18:05
Hey, thanks for the reply! The back end of the emulators have been working fine for me using them with http but behind an https proxy. The issue here is the browser sdk forces an "http://" prefix to all my requests and there doesn't seem to be an option (short of modifying npm module code) to use https.

**Comment by looptheloop88** [comment] 2021-07-07 16:38
Thanks for the confirmation, @jasonford. This feature isn't currently supported, but we'll take it as a feature request. We can't provide definite timelines or details, so you may need to check this thread or our release notes to get the latest updates about Firebase and its services.

**Comment by hsubox76** [comment] 2021-12-20 17:07
Duplicate of https://github.com/firebase/firebase-js-sdk/issues/4124 (see that issue for more information).

**Closed by hsubox76** 2021-12-20 17:07 UTC
Labels: testing-sdk, type: feature request
