### ISSUE TITLE
Warning: This is a browser-targeted Firebase

### ISSUE THREAD

**Issue by vuvgaG** [firebase/firebase-js-sdk#5174] opened 2021-07-19 06:08 UTC
How can I get rid of this warning.

  @firebase/app: 
      Warning: This is a browser-targeted Firebase bundle but it appears it is being
      run in a Node environment.  If running in a Node environment, make sure you
      are using the bundle specified by the "main" field in package.json.
      
      If you are using Webpack, you can specify "main" as the first item in
      "resolve.mainFields":
      https://webpack.js.org/configuration/resolve/#resolvemainfields
      
      If using Rollup, use the @rollup/plugin-node-resolve plugin and specify "main"
      as the first item in "mainFields", e.g. ['main', 'module'].
      https://github.com/rollup/@rollup/plugin-node-resolve
      
#### Relevant Code:

The most basic setup.

**Comment by daveteu** [comment] 2021-07-19 13:43
What is your most basic set up? Did you attempt to use it in node? 

Which version you are using? 

I'm asking because it has been a long time since we have been importing from "firebase/app" instead of "@firebase/app"

**Comment by vuvgaG** [comment] 2021-07-20 08:23
It was using the vue-cli using node 12. Using the typescript options

I had copied the inputs from vuefirex package

**Comment by hsubox76** [comment] 2021-07-20 17:23
Can you please share a minimal reproduction of your setup? You mention a lot of variables that could affect what's going on - vue-cli, vuefirex, some kind of testing framework, etc.  The warning appears when Firebase is being loaded in a Node environment, but whatever tool you have that is bundling it for your tests is grabbing the Firebase bundle from the "browser" or "module" fields and not from "main" which is the correct field for Node.

If we could get a look at your project setup maybe we could figure it out, or maybe some Vue experts could help you figure out how to point your bundler at the "main" field instead of "browser".

**Comment by vuvgaG** [comment] 2021-07-23 02:39
> Can you please share a minimal reproduction of your setup? You mention a lot of variables that could affect what's going on - vue-cli, vuefirex, some kind of testing framework, etc. The warning appears when Firebase is being loaded in a Node environment, but whatever tool you have that is bundling it for your tests is grabbing the Firebase bundle from the "browser" or "module" fields and not from "main" which is the correct field for Node.
> 
> If we could get a look at your project setup maybe we could figure it out, or maybe some Vue experts could help you figure out how to point your bundler at the "main" field instead of "browser".

Thanks for your response, knowing that its possible, I'll the another look at it. I might be a be a able to point it correctly. I'll let you know the result.

**Comment by looptheloop88** [comment] 2021-07-29 17:19
Hi @vuvgaG, I will close this issue now. Please reopen if you have any other questions or clarifications.

**Closed by looptheloop88** 2021-07-29 17:19 UTC
Labels: api: core, type: question
