### ISSUE TITLE
Google Sign-in not working/warning in Instagram in-app browser

### ISSUE THREAD

**Issue by y-yeah** [firebase/firebase-js-sdk#4421] opened 2021-02-05 11:51 UTC
### [REQUIRED] Environment info

**firebase-tools:8.2.0

**Platform: developed on macOS Catalina 10.15.7, bug found on mobile browsers (iPhone/Android)

### [REQUIRED] Test case

Google needs to redirect to complete authentication but Instagram browser does not allow it to happen. Therefore unless a user opens an external browser, google sign-up/in fails and the user is not even warned with the error.

### [REQUIRED] Steps to reproduce

1. Deploy any website using Google sign-up provided by firebase.
2. Send the link of the website to an Instagram user and have him/her open it using the mobile device.
3. Have a user proceed with signing up or signing in using Google account.

### [REQUIRED] Expected behavior

The user should be successfully able to sign up/sign in, or at least be warned that they cannot use Google sign-in inside the app (e.g. inside Facebook messenger it does that).

### [REQUIRED] Actual behavior

The whole screen turns completely white.

**Comment by hsubox76** [comment] 2021-02-05 17:01
Seems related to https://github.com/firebase/firebase-js-sdk/issues/4256

**Comment by vamsi-manyam** [comment] 2021-02-05 19:33
> ### [REQUIRED] Environment info
> **firebase-tools:8.2.0
> 
> **Platform: developed on macOS Catalina 10.15.7, bug found on mobile browsers (iPhone/Android)
> 
> ### [REQUIRED] Test case
> Google needs to redirect to complete authentication but Instagram browser does not allow it to happen. Therefore unless a user opens an external browser, google sign-up/in fails and the user is not even warned with the error.
> 
> ### [REQUIRED] Steps to reproduce
> 1. Deploy any website using Google sign-up provided by firebase.
> 2. Send the link of the website to an Instagram user and have him/her open it using the mobile device.
> 3. Have a user proceed with signing up or signing in using Google account.
> 
> ### [REQUIRED] Expected behavior
> The user should be successfully able to sign up/sign in, or at least be warned that they cannot use Google sign-in inside the app (e.g. inside Facebook messenger it does that).
> 
> ### [REQUIRED] Actual behavior
> The whole screen turns completely white.

Hey did you find any solution for this? Im stuck at this

**Comment by subhendukundu** [comment] 2021-02-14 18:44
I had been meaning to open this issue for a while now. Finally, someone actually raised it. Thank you.
To reproduce the issue an example https://fir-ui-demo-84a6c.firebaseapp.com

**Comment by MohammadArik** [comment] 2021-03-06 13:30
Messenger browser supports no more than 1 tab at a time. So if you use signInWithPopup it removes the main page and takes you to the auth provider page which later on can't figure how to go back to the previous page. Consider using signInWithRedirect instead. It worked for me. Thanks you....
This will work in single tab browsers..
`firebase.auth().signInWithRedirect(provider)`;
And this one won't..
`firebase.auth().signInWithPopup(provider);`

**Comment by samhorlbeck** [comment] 2021-03-08 17:15
Hi everyone, @MohammadArik is correct: the in-app browser falls back to a redirect when the SDK tries to open a popup. The redirect and popup flows have fundamentally different handling and so there's not a good way to fail gracefully and allow the sign in to continue to work (nor would we want to support this case: redirect and popup are two different things---it would be confusing if we sometimes switched one out for the other based on platform).

I believe there are ways to detect whether your app is running in one of these webviews: a possible mitigation here is to use `signInWithRedirect()` if you detect you're in a Facebook webview.

I have filed a bug internally (b/182168083) to make `signInWithPopup()` fail fast with a relevant error message if it's called within the context of a Facebook webview

**Comment by MohammadArik** [comment] 2021-03-10 14:55
@y-yeah you can close this issue now as it solved. People don't usally like read through an open issue.

**Comment by sam-gc** [comment] 2021-06-23 14:17
@tsaopei - As I understand it there are ways of detecting that you're in an in-app browser, but it's going to depend on the app. Unfortunately I can't give specific guidance in that area

**Comment by hoangbn** [comment] 2022-09-28 01:42
I'm using `signInWithRedirect`, but still running into issues when signing in from in-app browsers in apps like Instagram and Messenger (works on Gmail though).

I'm getting 403 disallowed_useragent

**Comment by prameshj** [comment] 2022-09-29 04:43
> 403 disallowed_useragent

Are you using Google sign in? Looks like the error might be because Google does not allow that specific user agent to sent Oauth2 requests - similar to https://stackoverflow.com/questions/40591090/403-error-thats-an-error-error-disallowed-useragent

**Comment by hoangbn** [comment] 2022-09-29 04:49
Yes, I'm using Google sign-in. 

I see, so there's nothing I can do about it right?

**Comment by prameshj** [comment] 2022-09-29 05:11
> Yes, I'm using Google sign-in.
> 
> I see, so there's nothing I can do about it right?

This is outside of the firebase auth SDKs, since the error comes from Google Oauth. The recommendation there is to use the device browser for login - I see some workarounds in the stackoverflow link to set a custom useragent string.

**Closed** 2022-10-03 17:37 UTC
Labels: api: auth, internal-bug-filed
