### ISSUE TITLE
Firestore not working not working in Safari 9 on iOS

### ISSUE THREAD

**Issue by andre-gois** [firebase/firebase-js-sdk#431] opened 2018-01-12 10:31 UTC
* Operating System version: iOS 9.3
  * Firebase SDK version: 4.8.0
  * Firebase Product: firestore 

Firestore not working not working in Safari 9 on iOS.

I'm using firebase (+Angularfire 5.0) on an Angular 5 app. O Safari 9 I get this error:
![image](https://user-images.githubusercontent.com/8902376/34870963-ae7fd470-f783-11e7-8610-79327d2bb262.png)

Example: https://colorwise.io

**Comment by nikhilag** [comment] 2018-01-17 13:46
I am seeing the same issue too and it's a BIG problem for me. Here's the issue as per the template:-


Are you in the right place?Yes



### [REQUIRED] Describe your environment

  * Operating System version: iOS 9.3.2
  * Firebase SDK version: 4.8.2
  * Firebase Product: Firestore



### [REQUIRED] Describe the problem

#### Steps to reproduce:
On iOS 9.3.2 in Safari or Chrome, load a website which uses firestore and it won't load at all.
On debugging via my macbook, I saw the following error in the console:-

> NotFoundError: DOM IDBDatabase Exception 8: An operation failed because the requested database object could not be found.

#### Relevant Code:
The error shows up in the following code in the line with `this.transaction = db.transaction(...)`

`
/**
 * Wraps an IDBTransaction and exposes a store() method to get a handle to a
 * specific object store.
 */
var SimpleDbTransaction = /** @class */ (function () {
    function SimpleDbTransaction(db, mode, objectStoresNames) {
        var _this = this;
        this.aborted = false;
        this.transaction = db.transaction(objectStoresNames, mode);
        this.completionPromise = new Promise(function (resolve, reject) {
            // We consider aborting to be "normal" and just resolve the promise.
            // May need to revisit if/when we actually need to abort transactions.
            _this.transaction.onabort = _this.transaction.oncomplete = function (event) {
                resolve();
            };
            _this.transaction.onerror = function (event) {
                reject(event.target.error);
            };
        });
    }
`

**Comment by wilhuff** [comment] 2018-03-06 05:42
This is a duplicate of https://github.com/firebase/firebase-js-sdk/issues/443. Please follow that for updates.

**Closed by wilhuff** 2018-03-06 05:42 UTC
Labels: Component-Firestore
