### ISSUE TITLE
Firestore's GRPC client does not terminate its open connection with Jest 27.0.1

### ISSUE THREAD

**Issue by inf3rnus** [firebase/firebase-js-sdk#4947] opened 2021-05-27 17:38 UTC
### [REQUIRED] Describe your environment

  * Operating System version: Ubuntu 18.04 LTS
  * Browser version: NA (Related to Jest tests, so jsdom)
  * Firebase SDK version: 8.6.2
  * Firebase Product: firestore

### [REQUIRED] Describe the problem

This may not be a firebase problem (although it very well could be), but it is tied to firebase, so I thought I'd leave this for your team's awareness/investigation.

Jest 27.0.1 does not exit tests cleanly in that it complains of pending asynchronous operations. The pending asynchronous operation when running --detectOpenHandles comes from the grpc client used by Firestore, it does not seem to close its socket, either in time, or it hangs. This may be due to its interaction with jsdom.

One thing to note is that Jest 25.5.4 *does* exit tests cleanly.

I've alerted the Jest team to this issue here: https://github.com/facebook/jest/issues/11464

#### Steps to reproduce:
1. Clone this repro repo I've made: https://github.com/inf3rnus/firebase-jest-pending-grpc-connection
2. Run the following: npm i
3. Run: npx jest (You'll see the tests do not exit cleanly.)
4. Run: npx jest --detectOpenHandles (This will show the specific source of the hanging resource.)

#### Relevant Code:

https://github.com/inf3rnus/firebase-jest-pending-grpc-connection

Here's are some pictures showing what's happening:

Normal jest run:

![image](https://user-images.githubusercontent.com/5959983/119872011-3f5ddd80-bee0-11eb-9c60-4938bac685b2.png)

Jest with --detectOpenHandles:

![image](https://user-images.githubusercontent.com/5959983/119872171-69170480-bee0-11eb-8a4c-fef1edb07e7a.png)

**Comment by looptheloop88** [comment] 2021-05-27 18:32
Hi @inf3rnus, thanks for the report. This is a duplicate of  #4884. The logs when running jest with `--detectOpenHandles` option will help in the investigation. Thanks for the report, we appreciate it.

**Closed by looptheloop88** 2021-05-27 18:32 UTC
Labels: api: firestore, testing-sdk
