### ISSUE TITLE
Firebase Auth is creating 2 new listeners every ~1s 

### ISSUE THREAD

**Issue by jrbasso** [firebase/firebase-js-sdk#3093] opened 2020-05-20 18:33 UTC
### [REQUIRED] Describe your environment

  * Operating System version: Web
  * Browser version: Chrome 81.0.4044.138
  * Firebase SDK version: 7.14.4
  * Firebase Product: auth

#### Steps to reproduce:

Just load Firebase Auth in a page (`firebase.auth()`). No errors in console, but if you start to profile the page, you are going to notice that the number of listeners goes up by 2 every ~1s.

You can see for example on the Firebase UI demo page: https://fir-ui-demo-84a6c.firebaseapp.com/

![image](https://user-images.githubusercontent.com/26548/82483539-8aac0780-9aa6-11ea-9e43-a44896c248b8.png)

I tested not using the Firebase UI and it gives the same issue. I'm just point to their demo since it's easier to demonstrate the issue.

#### Relevant Code:

```javascript
firebase.initializeApp(firebaseConfig);
firebase.auth();
```

**Comment by Feiyang1** [comment] 2020-05-20 19:29
Duplicate of https://github.com/firebase/firebase-js-sdk/issues/1420

**Closed by Feiyang1** 2020-05-20 19:29 UTC
Labels: api: auth
