### ISSUE TITLE
loadFirestoreRules leads to http handle leak

### ISSUE THREAD

**Issue by IchordeDionysos** [firebase/firebase-js-sdk#4898] opened 2021-05-12 20:49 UTC
### [REQUIRED] Describe your environment

  * Operating System version: macOS Big Sur 11.2.3
  * Browser version: n/a
  * Firebase SDK version: 1.2.11
  * Firebase Product: @firebase/rules-unit-test

#### Steps to reproduce:

Create a test with Jest ***and load the security rules using***:

```ts
require('leaked-handles');
import * as firebase from '@firebase/rules-unit-testing';
await firebase.loadFirestoreRules()
```

Run the test with:

```
firebase emulators:exec --project not-a-project --only firestore './node_modules/.bin/jest --runInBand'
```

You will get an error like this from the `leaked-handles` package:

```
http handle leaked at one of: 
    at Request.start (/Users/user/develop/backend/config/firestore/node_modules/request/request.js:751:32)
http stream {
  fd: 27,
  readable: true,
  writable: true,
  address: { address: '127.0.0.1', family: 'IPv4', port: 57786 },
  method: 'PUT',
  path: '/emulator/v1/projects/not-a-project:securityRules',
  host: 'localhost:8081'
}
```

#### Relevant Code:

```ts
firebase.loadFirestoreRules()
```

**Comment by looptheloop88** [comment] 2021-05-14 14:33
Hi @IchordeDionysos, I wasn't able to reproduce the error. Please share a [minimal, but complete](https://stackoverflow.com/help/minimal-reproducible-example) sample project that I can run locally to replicate the issue.

<img width="1038" alt="Screen Shot 2021-05-14 at 10 24 10 PM" src="https://user-images.githubusercontent.com/80330521/118285539-22023a00-b504-11eb-8164-030d2ce7ffab.png">

**Comment by IchordeDionysos** [comment] 2021-05-14 14:38
@looptheloop88 do you see the Jest did not exit after one second warning?

That's exactly the reason why I did open this issue!
I imported `leaked-handles` to debug what asynchronous operation may still be running 🤔 

So in general the issue is about jest complaning that there are "open handles"/still running async operations.

I can create an MVCE if that helps, but it seems like you also got the initial warning, why I opened the issue initially.

Sorry if that wasn't clear enough

**Comment by looptheloop88** [comment] 2021-05-14 16:10
Thanks for the confirmation @IchordeDionysos. This is a duplicate of #4884.

**Closed** 2021-05-14 16:11 UTC
Labels: needs-attention, testing-sdk
