### ISSUE TITLE
cannot install firebase

### ISSUE THREAD

**Issue by unoegohh** [firebase/firebase-js-sdk#852] opened 2018-05-21 19:06 UTC
if i try to install firebase via
`npm install firebase --save`
it shows me
```

`C:\Projects\reactnative\auth>npm install firebase --save

grpc@1.11.3 install C:\Projects\reactnative\auth\node_modules\grpc
node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp ERR! Completion callback never invoked!
node-pre-gyp ERR! System Windows_NT 10.0.17134
node-pre-gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Projects\reactnative\auth\node_modules\grpc\node_modules\node-pre-gyp\bin\node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd C:\Projects\reactnative\auth\node_modules\grpc
node-pre-gyp ERR! node -v v9.10.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.0
node-pre-gyp ERR! This is a bug in node-pre-gy.
node-pre-gyp ERR! Try to update node-pre-gyp and file an issue if it does not help:
node-pre-gyp ERR! https://github.com/mapbox/node-pre-gyp/issues
npm ERR! code ELIFECYCLE
npm ERR! errno 6
npm ERR! grpc@1.11.3 install: `node-pre-gyp install --fallback-to-build --library=static_library
npm ERR! Exit status 6
npm ERR!
npm ERR! Failed at the grpc@1.11.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\unoeg\AppData\Roaming\npm-cache_logs\2018-05-21T18_44_21_908Z-debug.log`
```

and if i try to
`node-pre-gyp install --fallback-to-build --library=static_library`
it gives me
```
C:\Projects\reactnative\auth>node-pre-gyp install --fallback-to-build --library=static_library
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.10.0
node-pre-gyp info using node@9.10.0 | win32 | x64
node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: auth package.json is not node-pre-gyp ready:
node-pre-gyp ERR! stack package.json must declare these properties:
node-pre-gyp ERR! stack binary.module_name
node-pre-gyp ERR! stack binary.module_path
node-pre-gyp ERR! stack binary.host
node-pre-gyp ERR! stack at validate_config (C:\Users\unoeg\AppData\Roaming\npm\node_modules\node-pre-gyp\lib\util\versioning.js:220:15)
node-pre-gyp ERR! stack at Object.module.exports.evaluate (C:\Users\unoeg\AppData\Roaming\npm\node_modules\node-pre-gyp\lib\util\versioning.js:279:5)
node-pre-gyp ERR! stack at install (C:\Users\unoeg\AppData\Roaming\npm\node_modules\node-pre-gyp\lib\install.js:182:31)
node-pre-gyp ERR! stack at Object.self.commands.(anonymous function) [as install] (C:\Users\unoeg\AppData\Roaming\npm\node_modules\node-pre-gyp\lib\node-pre-gyp.js:52:37)
node-pre-gyp ERR! stack at run (C:\Users\unoeg\AppData\Roaming\npm\node_modules\node-pre-gyp\bin\node-pre-gyp:82:30)
node-pre-gyp ERR! stack at Object. (C:\Users\unoeg\AppData\Roaming\npm\node_modules\node-pre-gyp\bin\node-pre-gyp:134:1)
node-pre-gyp ERR! stack at Module._compile (module.js:649:30)
node-pre-gyp ERR! stack at Object.Module._extensions..js (module.js:660:10)
node-pre-gyp ERR! stack at Module.load (module.js:561:32)
node-pre-gyp ERR! stack at tryModuleLoad (module.js:501:12)
node-pre-gyp ERR! System Windows_NT 10.0.17134
node-pre-gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Users\unoeg\AppData\Roaming\npm\node_modules\node-pre-gyp\bin\node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd C:\Projects\reactnative\auth
node-pre-gyp ERR! node -v v9.10.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.0
node-pre-gyp ERR! not ok
auth package.json is not node-pre-gyp ready:
package.json must declare these properties:
binary.module_name
binary.module_path
binary.host
```
[2018-05-21T18_44_21_908Z-debug.log](https://github.com/firebase/firebase-js-sdk/files/2023768/2018-05-21T18_44_21_908Z-debug.log)

maybe i dont get something?

**Comment by jshcrowthe** [comment] 2018-05-21 19:09
Closing as a duplicate of #843

**Closed by jshcrowthe** 2018-05-21 19:09 UTC
Labels: needs-triage
