### ISSUE TITLE
ES6 import incompatible with "resolved Hosting URLs"

### ISSUE THREAD

**Issue by Ewall198** [firebase/firebase-js-sdk#3060] opened 2020-05-13 23:17 UTC
OS: Ubuntu 18.04.4 LTS
Browser version: Version 81.0.4044.138 (Official Build) (64-bit)
Firebase SDK version: 7.14.3
Firebase Product: hosting (locally)

ES6 import: `import * as firebase from 'firebase';`
resolved hosting urls: `<script defer src="/__/firebase/init.js"></script> `

When using ES6 imports and resolved hosting urls, each system uses its own reference to firebase. This means that initializing the app with one firebase reference won't initialize the app for the other reference.

**Comment by Feiyang1** [comment] 2020-05-13 23:40
`<script defer src="/__/firebase/init.js"></script>` is not meant to work with your own bundle. It assumes a global `firebase` object and works on top of it. 
You can probably make it work by creating a global firebase object in your bundle manually and load your bundle file before the resolved hosting url.

Closing because it is working as intended.

**Closed by Feiyang1** 2020-05-13 23:40 UTC
Labels: needs-triage
