### ISSUE TITLE
Firefox in Private Mode error in database

### ISSUE THREAD

**Issue by ArcherEmiya05** [firebase/firebase-js-sdk#4127] opened 2020-11-27 13:59 UTC
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10
  * Browser version: Firefox 82.0.3 (64-bit)
  * Firebase SDK version: 8.1.1
  * Firebase Product: auth, database, storage

### [REQUIRED] Describe the problem
Having some error when loading a page that uses Firebase products

#### Steps to reproduce:
Use Firefox private mode then open your website that uses Firebase product
#### Relevant Code:
![image](https://user-images.githubusercontent.com/38008900/100456733-d4cc1080-30fb-11eb-9398-3a6526a30094.png)

**Comment by hsubox76** [comment] 2020-11-30 17:25
This is usually an IndexedDB error that happens when Firebase tries to call IndexedDB.open() in a context that doesn't allow it (such as Firefox private). We have checks in some packages but not others. Can you identify which Firebase product is causing the error (auth, database, storage, etc.) by removing them one by one?

**Comment by aliokan** [comment] 2020-12-08 10:43
duplicate: https://github.com/firebase/firebase-js-sdk/issues/4069

**Comment by ArcherEmiya05** [comment] 2020-12-08 11:59
> 
> 
> This is usually an IndexedDB error that happens when Firebase tries to call IndexedDB.open() in a context that doesn't allow it (such as Firefox private). We have checks in some packages but not others. Can you identify which Firebase product is causing the error (auth, database, storage, etc.) by removing them one by one?

Definitely Firebase Auth as I checked the line where error start
![image](https://user-images.githubusercontent.com/38008900/101481229-cbf6fc80-398f-11eb-8d54-94ebec01ee7d.png)
![image](https://user-images.githubusercontent.com/38008900/101481233-ce595680-398f-11eb-88ba-90df28a3470a.png)

**Comment by samhorlbeck** [comment] 2020-12-08 16:10
Duplicate of #4069

**Closed by samhorlbeck** 2020-12-08 16:10 UTC
Labels: api: auth
