### ISSUE TITLE
FR: Allow override the default *.googleapis.com hostname when calling API

### ISSUE THREAD

**Issue by sunset1234321** [firebase/firebase-js-sdk#6065] opened 2022-03-12 19:00 UTC
Similar to https://github.com/firebase/firebase-android-sdk/issues/905

Request is:
Hope the sdk could allow a proxy server domain to be set.

Reason:
since the  default *.googleapis.com hostname is blocked in china,       which my proxy server could be deployed in an environment that has access to *.googleapis.com

**Comment by zymotik** [comment] 2023-01-10 12:42
Duplicate of #1641

**Closed** 2023-06-16 17:47 UTC
