### ISSUE TITLE
ES6 import

### ISSUE THREAD

**Issue by codeselfceo** [firebase/firebase-js-sdk#834] opened 2018-05-16 18:45 UTC
### Environment

  * Operating System version: any
  * Firebase SDK version: 5.0.2
  * Firebase Product: firebase itself

### The problem

When importing firebase as in the documentation `import * as firebase from 'firebase'` I'm getting console errors like this one:

`(index):1 Uncaught SyntaxError: The requested module '../../webchannel-wrapper/dist/index.js' does not provide an export named 'ErrorCode'`

#### Steps to reproduce

* Install firebase using `npm i --save firebase`
* use the code in the doc to initialize the app.
* See the console.

#### Relevant Code:

This is the code I'm using.
Then in the Polymer 3 element, I import like this: `import './firebase-app.js' which is the file that contains the following code:

Obviously, I changed the code to use my firebase app.

```javascript

import * as firebase from "firebase";

export default app = firebase.initializeApp({
    apiKey: "<API_KEY>",
    authDomain: "<PROJECT_ID>.firebaseapp.com",
    databaseURL: "https://<DATABASE_NAME>.firebaseio.com",
    projectId: "<PROJECT_ID>",
    storageBucket: "<BUCKET>.appspot.com",
    messagingSenderId: "<SENDER_ID>"
});
```

**Comment by mironal** [comment] 2018-05-17 03:13
I have same issue.

**Comment by codeselfceo** [comment] 2018-05-17 15:48
@mironal did you find a solution?

**Comment by a-xin** [comment] 2018-05-17 16:05
@codeselfceo I'm having the same issue and currently using the global import as a workaround: https://github.com/firebase/firebase-js-sdk/issues/815#issuecomment-389413719 :-/

**Comment by Bastardly** [comment] 2018-05-23 15:26
I had the same problem. Did a little workaround from my polymer3 index.html - But it's basically a just prettier global import. I haven't fully tested it out, but it seems to work.

In index.html I added
```
<script src="/node_modules/firebase/firebase.js"></script>
<script src="/src/my-app/_fb.js"></script>
```
in _fb.js I simply initialised the code.

**Comment by jshcrowthe** [comment] 2018-05-23 16:05
Closing as a duplicate of #815.

**Closed by jshcrowthe** 2018-05-23 16:05 UTC
Labels: needs-triage
