### ISSUE TITLE
Auth not persisted when used inside of an `<iframe>`

### ISSUE THREAD

**Issue by nandorojo** [firebase/firebase-js-sdk#7870] opened 2023-12-13 17:09 UTC
### Operating System

macOS 14.1

### Browser Version

Chrome 119.0.6045.199

### Firebase SDK Version

9.6.1

### Firebase SDK Product:

Auth

### Describe your project's tooling

Next.js

### Describe the problem

Our website, [beatgig.com](https://beatgig.com) uses firebase auth.

When we do `<iframe src="https://beatgig.com" />`, I expect the auth to persist inside of the `iframe` window. All other `localStorage` does indeed persist, **other than firebase auth.**

This used to work properly, though I'm not sure which version it worked on.

### Steps and code to reproduce issue

Initialize Firebase Auth using `browserLocalPersistence`, sign in, and then open the same URL in a new tab. It will not persist the auth properly.

I think the issue is due to these lines: https://github.com/firebase/firebase-js-sdk/blob/15addde0b9d56dd3490e9c3c1e2f015e10e156cb/packages/auth/src/platform_browser/persistence/local_storage.ts#L36-L39

I'm going to see if a patch removing that fixes it.

**Comment by nandorojo** [comment] 2023-12-13 18:45
I think this may be caused by newer browsers. I used lambdatest.com to test on Chrome 115 and it worked fine there...

**Comment by DellaBitta** [comment] 2023-12-15 19:59
If the iframe domain differs from the main domain, then yes, I believe this is expected behavior. It's a browser feature to prevent other websites from reading your users persisted states.

> I wonder if any non-local-storage approaches to auth could fix it? If so, I can use a different persistence method.

We have [a guide to our persistence options here](https://firebase.google.com/docs/auth/web/auth-state-persistence), but no, cookies persistence isn't one of the options.

**Comment by nandorojo** [comment] 2023-12-15 21:33
I’d expect the content inside of the iframe to load as if it were in a new tab. This is the case on Chrome <= 115 it looks like. Now it comes with storage partitioning set as true by default, which unfortunately makes having the same experience in an iframe very difficult.

**Comment by DellaBitta** [comment] 2023-12-20 23:38
Hi @nandorojo,

If the domains are different then I believe this is in the realm of browser behaviors that we can't affect, unfortunately. If there's something else we can do then please let us know. Thanks!

**Comment by nandorojo** [comment] 2023-12-21 00:21
Yeah fair enough.

If anyone knows of an API like cookies that would work across iframe and tab let me know...

**Comment by spa5k** [comment] 2024-01-11 15:33
@nandorojo were you able to find any solution to this problem?

**Comment by nandorojo** [comment] 2024-01-11 15:35
Unfortunately not yet. I haven't tried cookies yet as an alternative. I'm not sure if there is a way around this with new browser versions. A bit frustrating on Chrome's part imo.

**Comment by DellaBitta** [comment] 2024-01-13 19:59
Ok, I'm going to close this issue for now since I don't think we can do anything about the browser behavior.

**Closed** 2024-01-13 19:59 UTC
Labels: api: auth, question
