### ISSUE TITLE
Proactive refresh not started if auth after database repo start

### ISSUE THREAD

**Issue by mhofman** [firebase/firebase-js-sdk#5498] opened 2021-09-15 21:30 UTC
### Describe your environment

  * Operating System version: Linux 62afaeb9d86d 5.10.16.3-microsoft-standard-WSL2
  * Browser version: Node 14.16.1
  * Firebase SDK version: 9.0.2
  * Firebase Product: auth + database

#### Steps to reproduce:
When authenticating an app for the first time after the db repo was started, the proactive refresh of the auth token is not started correctly.
#### Relevant Code:

Extracted from larger authentication and connection logic:
```javascript
const app = initializeApp(firebaseConfig);
const auth = getAuth(app);
const db = getDatabase(app);

// Comment out to restore expected behavior
goOffline(db);

const connectUser = async (user) => {
  const connectedRef = ref(db, '.info/connected');

  goOnline(db);

  onValue(connectedRef, (snap) => {
    if (snap.val() === true) {
      console.log('Firebase connected', user);
    } else {
      console.log('Firebase disconnected');
    }
  });
};

let lastSeenUser = null;
onIdTokenChanged(auth, (user) => {
  if (lastSeenUser === user) {
    return;
  }
  console.log('Firebase updating authentication status');

  if (!lastSeenUser) {
    lastSeenUser = user;
    connectUser(user);
  } else {
    console.warn('Updating user not supported');
  }
});

signInWithCustomToken(auth, authToken);
```

I believe the problem stems from the check in [`AuthImpl#directlySetCurrentUser`](https://github.com/firebase/firebase-js-sdk/blob/firebase%409.0.2/packages/auth/src/core/auth/auth_impl.ts#L529-L534)

```javascript
    if (this.currentUser && this.currentUser !== user) {
      this._currentUser._stopProactiveRefresh();
      if (user && this.isProactiveRefreshEnabled) {
        user._startProactiveRefresh();
      }
    }
``` 

The proactive refresh is only (re)started if a previous user existed, but not if it's the first user to be authenticated.

**Comment by mhofman** [comment] 2021-09-15 22:47
My current workaround is to call the private `user._startProactiveRefresh()` manually when the user first connects.

**Comment by sam-gc** [comment] 2021-09-16 20:58
Out of curiosity, it always works as expected if you don't call `goOffline()` first?

**Comment by mhofman** [comment] 2021-09-16 23:25
In the small reproduction I made above, yes. I believe that's because in that case the repo connection is not started until after the user is authenticated, which exercises `user._startProactiveRefresh()` directly:

https://github.com/firebase/firebase-js-sdk/blob/dabda55f0163ead5c65013840a1108c339455a83/packages/auth/src/core/auth/auth_impl.ts#L458-L463

Unfortunately not doing `goOffline()` is not really an option for me. I'd argue the current user logic in `directlySetCurrentUser` is not quite right and should be more along the lines of:

```js
    if (this.currentUser !== user) {
      if (this.currentUser) {
        this._currentUser._stopProactiveRefresh();
      }
      if (user && this.isProactiveRefreshEnabled) {
        user._startProactiveRefresh();
      }
    }
```

**Comment by sam-gc** [comment] 2021-09-29 21:54
I'm wondering if the issue is that the database doesn't start the proactive refresh after it goes back online. @schmidt-sebastian what do you think?

**Comment by mhofman** [comment] 2021-09-29 22:14
The database does enable the proactive refresh, but before any user exists in auth, so the proactive refresh is not actually started. When the user gets authenticated, the following auth function's checks don't line up, and the proactive refresh is never started, even through it actually is enabled: 

https://github.com/firebase/firebase-js-sdk/blob/dabda55f0163ead5c65013840a1108c339455a83/packages/auth/src/core/auth/auth_impl.ts#L526-L534

**Comment by maneesht** [comment] 2022-08-26 22:46
@mhofman  - thanks for reporting this and for your patience. We just merged this in recently. It should be in the next release.

**Closed by maneesht** 2022-08-26 22:46 UTC
Labels: api: auth, api: database, needs-attention
