### ISSUE TITLE
Chrome extension Service worker "ReferenceError : XMLHttpRequest is not defined" Using firebase storage 

### ISSUE THREAD

**Issue by CarrizalViaro** [firebase/firebase-js-sdk#8149] opened 2024-04-10 20:51 UTC
### Operating System

Windows 11

### Browser Version

Chrome/123.0.0.0

### Firebase SDK Version

10.10.0

### Firebase SDK Product:

Storage

### Describe your project's tooling

It is an extension supervises exams and monitors the camera and desktop. It then uploads images to Firebase storage.

The extension is useful for:
- Proctors who need to monitor students during exams
- Teachers who want to prevent cheating
- Anyone who wants to keep an eye on their computer activity

The extension has the following features:
- It can take screenshots of the user's desktop
- It can record video of the user's webcam

### Describe the problem

When I try to use the uploadString method, I get an error with this message:
"Uncaught ReferenceError: XMLHttpRequest is not defined URL: https://www.gstatic.com/firebasejs/10.10.0/firebase-storage.js"

### Steps and code to reproduce issue

This is my relevant code inside of service worker:

```
import {initializeApp, getApp, getApps, deleteApp} from 'https://www.gstatic.com/firebasejs/10.10.0/firebase-app.js';
import { getStorage, ref, uploadString } from 'https://www.gstatic.com/firebasejs/10.10.0/firebase-storage.js';

const fileRef = ref(storage_fb, "imagenes/" + _current_session_id + "/" + media_data.name + ".jpg");

uploadString(fileRef, media_data.img_data, 'data_url')
  .then((snapshot) => {
      // do something
  })
  .catch((error) => {
      console.log(error);...
```

**Comment by DellaBitta** [comment] 2024-04-11 17:26
Hi @CarrizalViaro,

We've used XMLHttpRequest in Storage because it allows the implementation to track upload progress. Unfortunately XMLHttpRequest isn't supported within service workers.

There's already an open Feature Request to find an alternative, however. Please upvote #6595 to help us prioritize it.

Duplicate of #6595.

**Closed by DellaBitta** 2024-04-11 17:26 UTC
Labels: api: storage, question, needs-attention
