### ISSUE TITLE
WebSockets timeout and long wait time before fallback to long polling

### ISSUE THREAD

**Issue by benjarwar** [firebase/firebase-js-sdk#540] opened 2018-03-01 15:23 UTC
### Describe your environment

  * Operating System version: Mac OS X Sierra
  * Firebase SDK version: 4.10.1
  * Firebase Product: database

### Describe the problem

When instantiating my Firebase app and making the first database call, I'm seeing occasional (but consistent) WebSocket connection failures. It occurs about one out of every 10-20 page loads, and looks like this:

> WebSocket connection to 'wss://s-usc1c-nss-214.firebaseio.com/.ws?v=5&ns=foo' failed: WebSocket opening handshake timed out
> WebSocketConnection.js:122

I have already contacted support, and, after a lengthy correspondence, have been told that this is likely due to internet traffic. But I've been reproducing the issue consistently for many weeks. And, because my app requires a Firebase connection before the user sees any content, constitutes a really bad user experience when it occurs.

My only option at this point is [to force Firebase to use long polling](https://stackoverflow.com/questions/20805467/firebase-is-there-a-flag-to-force-long-polling-when-websockets-are-blocked-by/28334167#28334167) before instantiating the app. But in the words of my Firebase support contact, "that would degrade service in all cases over the percentage that have connectivity issues".

I'd like to suggest two possible solutions:

1. Decrease the maximum wait time before Firebase gives up on WebSockets and falls back to long polling (perhaps 5-10s instead of 20-30s), or...
2. Provide a method for switching to long polling *after* the Firebase app has been instantiated. Then, developers can run their own timers and make the switch manually at their discretion.

#### Steps to reproduce:

I can reproduce this issue consistently approximately one out of every 10-20 page loads on any Firebase application, including the [test connection page](https://www.firebase.com/test.html ). Here's a screenshot of one such failure:

<img width="649" alt="screen shot 2018-03-01 at 10 21 09 am" src="https://user-images.githubusercontent.com/2565278/36852721-78ae8260-1d3a-11e8-8c06-3f6159e8d4c7.png">

See also [this StackOverflow issue](https://stackoverflow.com/questions/12421993/firebase-websocket-is-closed-before-the-connection-is-established?answertab=active#tab-top) where other users are reporting and concerned about similar behavior.

**Comment by mikelehen** [comment] 2018-03-02 17:05
Thanks for the detailed feedback.

I'm unfortunately not able to reproduce this against https://www.firebase.com/test.html (I refreshed 50 times and each time it completed in <1 sec, usually < 0.5 sec). So I'd be curious to know if you've been able to reproduce using different network connections (perhaps there's a buggy router / proxy / whatever in your route to Firebase) or verify that users of your app are experiencing this as well. I'm also curious if you've confirmed that forcing long-polling 100% resolves the issue.

As for the timeouts, I'd be hesitant to change them since on a low-signal mobile network, 5-10 seconds may not be long enough (and in general tweaking these timeouts is somewhat risky).

Out of curiosity, have you tried calling `firebase.database().goOffline()` followed by `firebase.database().goOnline()` when your timer detects it's taking too long to establish the connection?  I'm not certain, but that may be enough to get it to fall back to long-polling (the SDK will prefer long-polling if the most recent WebSocket attempt did not succeed).

Sorry for the pain. Hope this maybe provides some help.

**Comment by benjarwar** [comment] 2018-03-02 22:29
Thanks for the advice and testing, @mikehaney24. I did have one of our other devs test our application, and he reported a >30s timeout during one of his refreshes (although he didn't see the same error I did). As mentioned, there seems to be [other users experiencing similar behavior  in this StackOverflow question](https://stackoverflow.com/questions/12421993/firebase-websocket-is-closed-before-the-connection-is-established). In my testing, switching to forced long polling definitely fixes the issue in my app.

I get your point about the riskiness of reducing the timeouts, but still think it'd be nice to expose this option to developers. If we can already force long polling entirely, why not give us control over when Firebase makes the switch? Seems like it's less of a hammer drop, as we wouldn't be penalizing all users for the minority with connection issues.

I haven't tested `goOffline` and `goOnline`. It sounds like a possible solution, but have concerns about potential race conditions between the client and Firebase. Would in-flight requests be returned safely if Firebase access is toggled? I also have event listeners bound to authentication, and would need to ensure that they don't fire additional times, and/or that the callback methods are properly idempotent.

**Comment by mikehaney24** [comment] 2018-03-02 23:02
I think you might've meant @mikelehen?

**Comment by benjarwar** [comment] 2018-03-02 23:12
Sorry for the bother, @mikehaney24. Finger slipped on the autocomplete!

**Comment by mikelehen** [comment] 2018-03-09 23:36
Unfortunately these timeouts probably aren't good candidates for exposing via public APIs since they are internal implementation details and we may change their behavior (or remove them entirely) over time. Changing the timeouts could also potentially have undesirable effects on our backend servers if tuned improperly. It would also be extremely hard to document how developers are expected to use them.

That said, there's a reason we made the clients open source.  If you feel that tuning these timeouts is going to lead to a better user experience for your app, feel free to give that a try. And I'd be interested to hear the results (if it increases or decreases connection latency across your user base, etc.).

**Comment by skopanev** [comment] 2018-09-13 07:40
HI all! Did you solve this issue? We still have this problem.

**Comment by mwood23** [comment] 2019-02-21 04:08
Any updates on this one? I'm running into this using [Expo](https://forums.expo.io/t/expo-standalone-with-cloud-firestore-web-sdk-responses-take-a-really-long-time/18357/2) and it's really wrecking my app. Happy to help make a fix if anyone can point me in the right direction.

**Comment by imanbee** [comment] 2019-02-21 10:00
we tried this:
`for (var key in localStorage) {
    if (key.includes('firebaseio.com')) {
      localStorage.removeItem(key);
    }
}`
and it resolved the problem

**Comment by Saccarab** [comment] 2019-03-14 00:13
Running into same problem and none of the solutions listed here seems to do it

**Comment by glauberramos** [comment] 2019-03-14 19:43
@imanbee do you run this code always for all users?

**Comment by imanbee** [comment] 2019-03-15 10:12
> @imanbee do you run this code always for all users?

yes, exactly

**Comment by maneesht** [comment] 2022-08-24 05:49
Closing as this may have been solved in Chrome itself. Please reopen if you're still having issues.

**Closed by maneesht** 2022-08-24 05:49 UTC
Labels: api: database
