### ISSUE TITLE
Firebase Database (4.3.1) INTERNET ASSERT FAILED: Reference.ts has not been loaded.

### ISSUE THREAD

**Issue by thruthesky** [firebase/firebase-js-sdk#157] opened 2017-09-08 09:30 UTC
### [REQUIRED] Describe your environment

  * Operating System version: Windows7/Windows10
  * Firebase SDK version: 4.3.1
  * Firebase Product: database (auth, database, storage, etc)

### [REQUIRED] Describe the problem

When I load my Angular app with IE10, I see an error message:
Firebase Database (4.3.1) INTERNET ASSERT FAILED: Reference.ts has not been loaded.

#### Steps to reproduce:

It's very easy to reproduce. Just install fresh Angular project with firebase module.

$ ng new projectName
$ cd projectName
$ npm install firebase
... setup firebase ...
... setup polyfills for IE ...
$ ng serve
... browser with IE11 and Emulate IE10 and you will see error.

When I use IE11 in Windows 10 emulating IE10, I see this error.
When I use IE10 in Windows 7 (on Virtual Box), I see this error.

![image](https://user-images.githubusercontent.com/5080329/30205451-6012ed2a-94bb-11e7-88b0-dc226826c243.png)

**Comment by schmitzt3** [comment] 2017-09-11 19:16
I was hoping the latest release (4.3.1) would fix this, but it still exists. I have them same setup and steps to reproduce.

**Comment by schmitzt3** [comment] 2017-09-12 12:23
After digging through the source, I found that commenting out this line works, but I am unsure of what the consequences are, but it may help you get to other errors that you can begin fixing. https://github.com/firebase/firebase-js-sdk/blob/bc1f67c448804a28fa64e91611ea60398890bcaa/src/database/api/Query.ts#L66

**Comment by JounQin** [comment] 2017-09-21 13:35
Confirm this issue started from version 4.1.4 after trying several times.

**Comment by mralbobo** [comment] 2017-10-04 20:13
Since #125 was closed in favor of this, is this issue inheriting the "won't fix" opinion kato posted?

**Comment by jshcrowthe** [comment] 2017-10-04 21:24
As Kato mentioned the limitation here is bandwidth. I'd love for someone to take a look at this and submit a fix but given that the impact is only for IE 10, this is low priority for now.

**Comment by jtemerson** [comment] 2017-10-13 22:23
I can confirm this issue when using an android emulator with nativescript. I am building an app and when using firebase to register a new user it throws this error.

**Comment by aaronksaunders** [comment] 2017-11-11 01:18
just ran into this using IOS Simulator?

**Comment by jtemerson** [comment] 2017-11-11 03:37
@aaronksaunders, I have the issue with Android Simulator as stated above. It looks as though google is putting this issue on the back burner due to the narrowness of the scope (since it only effects I.E. and simulators). 

I have just decided to move on, leaving FireBase behind, and use MongoDB instead.

**Comment by antoinerousseau** [comment] 2017-11-23 18:40
issue still present in Firebase 4.6.2 under IE9 and IE10.

**Comment by antoinerousseau** [comment] 2017-11-23 18:42
```
Firebase Database (${JSCORE_VERSION}) INTERNAL ASSERT FAILED: Reference.ts has not been loaded
File "../node_modules/@firebase/util/dist/cjs/src/assert.js" line 26 col 1 in [anonymous]
throw exports.assertionError(message);
```

**Comment by tangjingyuan** [comment] 2018-01-24 09:40
The issue still exists in Firebase 4.9.0 under IE 10.
I have to downgrade the version to 4.1.3 according to [this](https://github.com/vuejs/vue-hackernews-2.0/pull/254)

**Comment by ruucm-working** [comment] 2018-04-28 17:59
@schmitzt3 's way also works.

**Comment by ivanm376** [comment] 2019-01-04 12:06
same error under IE 11 (11.0.9600.)
````
Firebase Database (${JSCORE_VERSION}) INTERNAL ASSERT FAILED: Reference.ts has not been loaded

**Comment by agnieszkabugla** [comment] 2019-05-20 10:00
still the same error in firebase 6.0.2  on IE10 and IE9...

**Comment by maneesht** [comment] 2022-08-24 05:43
Closing this as we don't support IE10 and it's likely this has been solved. Please reopen if otherwise.

**Closed by maneesht** 2022-08-24 05:43 UTC
Labels: api: database
