### ISSUE TITLE
Receiving undefined for an existing document after the connection has existed for a long time.

### ISSUE THREAD

**Issue by Joao-Preto** [firebase/firebase-js-sdk#7246] opened 2023-04-21 13:24 UTC
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10 22H2
  * Browser version: Chrome 112.0.5615.138
  * Firebase SDK version: 9.17.1
  * Firebase Product: firestore database

### [REQUIRED] Describe the problem
We are experiencing an intermittent issue where we receive undefined from the database in certain conditions. We aren’t sure why it happens, but we are sure the problem is not in the application since it happens in multiple different places. If the screen is open for hours we sometimes receive an undefined from the database.
We use angularFire to access the database.
Very infrequently we see in our logging that a user experiences a crash because they receive an updated document from the database that is undefined. However we know that that document actually still exists.
This happens when the user hasn’t done anything for hours and then starts using the application again.

![9fbffcb5-61c6-4006-ada9-333ca15f62cf](https://user-images.githubusercontent.com/34801261/233646207-1a70427a-5d49-4fd9-9a5f-5f6e68bd3066.png)

#### Relevant Code:

```javascript
import { docData } from '@angular/fire/firestore';

connectToDoc$<T>(path: string, patcherList?: PatcherList<T>): Observable<T> {
    const docReference = this.docRef(path);

    return docData(docReference).pipe(
      map((localDoc: T) => this.patcherVersionControlService.applyPatches<T>(localDoc, patcherList)),
}

applyPatches<T extends VersionControlledModel>(model: T, patchersList: PatcherList<T>): T {
    if (!model) return null;
    if (!patchersList) return model;
    return patchersList.patchers.reduce<T>((previousModel, currentPatcher) => this._applyPatch(previousModel, currentPatcher), model);
}

```

**Comment by LanderBeeuwsaert** [comment] 2023-04-22 11:48
Hi @wu-hui , I'm from the same team as @Joao-Preto .
No recent upgrade, but it doesn't really matter, it was even already happening before we switched to modular firestore (so before version 9).
Indeed, we cannot reproduce it ourselves.

And we cannot enable debug logs as that would mean we would need to enable them for all our users.

Rate of occurance:
We have +-30.000 users in a weekend (depends on the weekend, the platform is used for competitions, so if we have a big competition, that means a lot of users that weekend)
+- 3.000.000 document reads on the database
=> it will happen 15 to 50 times.
There is no clear pattern except then that it seems to occur when a user "wakes up" the application after an hour or longer.
Seems to happen on mobile, desktop, webkit, chromium, …

**Comment by wu-hui** [comment] 2023-04-25 14:19
OK, I'd like to ask a few more questions:

* Do you turn on firestore's persistent cache or using the default memory cache? If you use a persistent cache, do you set a custom cache size?

* Do you use some other firebase products? Specifically, do you use AppCheck and/or Auth?

**Comment by LanderBeeuwsaert** [comment] 2023-04-25 17:35
Sure,

_Do you turn on firestore's persistent cache or using the default memory cache? If you use a persistent cache, do you set a custom cache size?_
No, we haven't enabled peristency, this is our angular app.module line:
![image](https://user-images.githubusercontent.com/1098243/234356728-78c7f95c-a039-484c-a063-3904fb548551.png)

_Do you use some other firebase products? Specifically, do you use AppCheck and/or Auth?_
Auth: yes, appCheck: No
we also use functions, analytics, storage, RTDB, hosting

**Comment by wu-hui** [comment] 2023-04-25 18:11
With memory cache, there is a strategy to delete document from memory as soon as they are not used in any active queries. When this happens, and the same query is issued again, it won't be able to find it from the cache, and rely on backend to tell the SDK the document content. If there happen to be some network difficulty around the time, this could happen. Can this be the cause?

For now, you can switch to enable persistence, this way the documents won't be deleted immediately. A least-recently-used GC is used instead to keep the cache size sane.

We do have a feature to bring LRU GC to memory cache, I'll update the issue when it is available to use.

**Comment by LanderBeeuwsaert** [comment] 2023-04-25 18:22
@wu-hui ahhhhh that could very well be it! Yes sports halls are notoriously bad with network stability.
we already tried moving to persistency some years (+- 4 years) ago, at that time it gave us a lot of issues and we quickly reverted back. We'll try to find time to experiment again.
It would be great if there would be an option for the LRU GC in the memory cache! thank you for the quick follow-up

**Comment by wu-hui** [comment] 2023-05-03 20:26
Update: LRU GC for memory is released.

See https://firebase.google.com/docs/reference/js/firestore_#memorylocalcache as a starting point.

**Closed** 2023-06-08 01:04 UTC
Labels: type: question, api: firestore, needs-info, no-recent-activity
