### ISSUE TITLE
Firebase Auth inside Excel task pane add-in

### ISSUE THREAD

**Issue by AlexFlok1** [firebase/firebase-js-sdk#7724] opened 2023-10-25 22:11 UTC
### Operating System

macOs 14

### Browser Version

Latest Chrome

### Firebase SDK Version

10.5.0

### Firebase SDK Product:

Auth

### Describe your project's tooling

Firebase auth inside a custom Excel task pane add-in

### Describe the problem

I am trying to be able Sign In via google using firebase auth. It's working when I am doing it though online excel but It's not working when I am using desktop version. When I am trying to sign in on the desktop version it's returning ```{credential: null, user: null}```

### Steps and code to reproduce issue

**This page called by Office Dialog Box:** 
```
Office.context.ui.displayDialogAsync(
      "page-url",
      {height: 100, width: 60}
    )
```
    
**Page code:** 
```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Firebase Login</title>
  <!-- Include Firebase JavaScript SDK -->
  <script src="https://www.gstatic.com/firebasejs/10.5.0/firebase-app-compat.js"></script>
  <script src="https://www.gstatic.com/firebasejs/10.5.0/firebase-firestore-compat.js"></script>
  <script src="https://www.gstatic.com/firebasejs/10.5.0/firebase-auth-compat.js"></script>
  <script src="https://www.gstatic.com/firebasejs/ui/6.0.1/firebase-ui-auth.js"></script>
  <link type="text/css" rel="stylesheet" href="https://www.gstatic.com/firebasejs/ui/6.0.1/firebase-ui-auth.css" />

</head>
<body>
<button id="google-signin-button">Sign in with Google</button>
<div id="google-firebase-ui"></div>
<script>
  // Firebase configuration
  var firebaseConfig = {
    apiKey: "your-key",
    authDomain: "your-domain",
    projectId: "your-project-id",
    storageBucket: "your-storage-bucket",
    messagingSenderId: "your-messaging-Sender-Id",
    appId: "your-app-id",
    measurementId: "your-measurement-id",
    name: "your-app-name"
  };
  // Initialize Firebase
  const app = firebase.initializeApp(firebaseConfig);
  const googleSignInButton = document.getElementById('google-signin-button');
  const container = document.getElementById("google-firebase-ui")
  const auth = firebase.auth(); // Get the Firebase Auth instance

  auth.getRedirectResult().then(res => {console.log(res)}).catch(err => {console.log(err)})
  googleSignInButton.addEventListener('click', () => {
    const provider = new firebase.auth.GoogleAuthProvider();
    provider.setCustomParameters({
      prompt: "select_account"
    });
    // Start the Google Sign-In process with redirect
    auth.signInWithRedirect(provider)


  });
</script>

</body>
</html>
```

**Comment by pragatimodi** [comment] 2023-10-30 22:12
Hi, thanks for reporting this issue. 
Can you fetch an OAuth token from google sign in and use that to login with firebase via signInWithCredential? The signInWithRedirect flow requires session storage access and redirects to an oauth handler web page. Do those launch within a browser, when you attempt sign in with a desktop version? This flow might not be supported in a desktop version.

**Comment by AlexFlok1** [comment] 2023-11-09 02:06
> Hi, thanks for reporting this issue. Can you fetch an OAuth token from google sign in and use that to login with firebase via signInWithCredential? The signInWithRedirect flow requires session storage access and redirects to an oauth handler web page. Do those launch within a browser, when you attempt sign in with a desktop version? This flow might not be supported in a desktop version.

Are you talking about "google sign" using "google-auth-library" package? I am launching it via desktop version of Excel. I did also try SignInWithPoup and it's saying that browser is blocking poup but I checked all my browsers and they all allow to have popup. The same method is working when I am using web version of excel.

**Comment by DellaBitta** [comment] 2023-11-13 19:34
Hi @AlexFlok1,

The signInWithPopup flow was designed for use in a browser and so it's required for the operation to complete successfully. I'm going to close this issue for now since the Excel desktop app isn't one of our supported environments, but if you run into other problems them please open a new issue, and link this one if it's related. Thanks!

**Closed** 2023-11-13 19:34 UTC
Labels: api: auth, question
