### ISSUE TITLE
Error "auth/invalid-email" kills NodeJS process even though it is handled with try-catch

### ISSUE THREAD

**Issue by sweethuman** [firebase/firebase-js-sdk#2101] opened 2019-08-21 17:42 UTC
### [REQUIRED] Describe your environment

  * Operating System version: Manjaro 18
  * Browser version: none
  * NodeJS version: 12.9.0 and 12.8.1 and 10.16.0(in repl.it example)
  * Firebase SDK version: 6.4.0
  * Firebase Product: auth 

### [REQUIRED] Describe the problem
Error "auth/invalid-email" when is thrown kills the nodejs process even though it is handled. Only happens when `signInWithEmailAndPassword` and `createUserWithEmailAndPassword` are awaited and surrounded in a `try-catch`. If I use a `.then().catch()` it works alright.

#### Steps to reproduce:

As you can see in the example below the process is killed before the code in `setTimeout` can run. Thus proving it kills the process. The errors are handled as you can see. If the `try-catch` block and code is removed the code in setTimeout runs without a problem.
This Happens only when the sign in and create methods are surrounded in a try catch. If they are handled via `.then().catch()` the error is handled as it should. You can test and edit the example to see for yourself.
#### Relevant Code:

https://repl.it/repls/UnripeLuckyMapping

**Comment by wti806** [comment] 2019-08-29 17:59
Duplicate of https://github.com/firebase/firebase-js-sdk/issues/1881

**Closed** 2019-08-29 17:59 UTC
Labels: api: auth
