### ISSUE TITLE
FR: Better errors for firestore batch writes

### ISSUE THREAD

**Issue by ribrdb** [firebase/firebase-js-sdk#1416] opened 2018-12-05 21:00 UTC
### [REQUIRED] Describe your environment

  * Operating System version: macOS 10.13.6
  * Browser version: 70.0.3538.110
  * Firebase SDK version: 5.3.0
  * Firebase Product: firestore (auth, database, storage, etc)

If one write in a batch commit fails, the whole commit fails with an error like: `FirebaseError: [code=permission-denied]: Missing or insufficient permissions.`
It would be much easier to debug if I could tell which write the error is from.
I can't catch an error on an individual write, since the WriteBatch.set method returns the batch, not a promise. A way to get promises would be nice. Or if the batch fails with more info, telling me which reference caused the error. Or maybe return something like https://godoc.org/cloud.google.com/go/datastore#MultiError

**Comment by mikelehen** [comment] 2019-01-19 03:30
Unfortunately the backend doesn't expose this information, and exposing it would be difficult, based on how the protocol is set up.  So there's nothing we can do in the SDK.  I'll forward your request to the backend team, but I'm not sure if it'll be feasible in any kind of reasonable timeframe, so I'm going to go ahead and close this.  Sorry.

**Closed by mikelehen** 2019-01-19 03:30 UTC
Labels: Component-Firestore, feature-request

**Comment by rockwotj** [comment] 2019-01-19 03:48
This is working as intended - we don't want to leak security information if permissions are denied.

If you're debugging - I suggest trying out our [local emulator][1] instead of testing against a live database.

[1]: https://firebase.google.com/docs/firestore/security/test-rules-emulator
