### ISSUE TITLE
withConverter doesn't work when used with CollectionReference

### ISSUE THREAD

**Issue by maletor** [firebase/firebase-js-sdk#2601] opened 2020-02-06 18:23 UTC
@thebrianchen, it seems types don't work correctly with CollectionReference.

```ts
 const posts = await store
  .collection("posts")
  .withConverter({ toFirestore, fromFirestore })
  .get();

posts.forEach(doSomething);
```

The forEach callback takes a `QueryDocumentSnapshot` (not a DocumentSnapshot) and there's no way to get the T on that object. It's only on `DocumentSnapshot`.

Is this by design, can we fix this

**Comment by thebrianchen** [comment] 2020-02-06 18:59
@maletor Thanks for writing in!

The `forEach` callback takes a `QueryDocumentSnapshot` because the documents are guaranteed to exist since they are coming from a `QuerySnapshot`. `QueryDocumentSnapshot` has [support](https://github.com/firebase/firebase-js-sdk/blob/01da30b0cea916f58caf47d8b48e7b4bbcd7188e/packages/firebase/index.d.ts#L8150) for generics, and you should be able to access `T`.

For example, the following code snippet using the `Post` class from the documentation should be valid:
```typescript
 const posts = db
  .collection('posts')
  .withConverter(PostConverter)
  .get();

posts.forEach((snapshot: QueryDocumentSnapshot<Post>) => {
  const post: Post = snapshot.data();
  ...
});
```

**Comment by maletor** [comment] 2020-02-06 19:35
I would think so as well. But...

<img width="725" alt="Screen Shot 2020-02-06 at 11 34 50 AM" src="https://user-images.githubusercontent.com/138785/73971984-cb578a80-48d4-11ea-8c4a-b910e22fd0b1.png">

**Comment by thebrianchen** [comment] 2020-02-06 19:39
Can you provide a minimal repro so I can see what's going on? It seems to work fine for me in a local test I wrote with that snippet I posted above.

**Comment by maletor** [comment] 2020-02-06 19:44
@thebrianchen something like this:

https://gist.github.com/maletor/cdbe979b10c87a892f6cb9bb3db8f0f0

**Comment by thebrianchen** [comment] 2020-02-06 20:02
@maletor Thanks for the repro! You are using the admin SDK, which is located at https://github.com/googleapis/nodejs-firestore/. I was able to reproduce this on the admin Node SDK and I'll make a bug fix for it soon.

**Comment by maletor** [comment] 2020-02-06 20:04
@thebrianchen, doesn't the admin SDK simply use the firestore SDK? It's not doing anything different. It's the same type. Correct me if I'm wrong.

**Comment by thebrianchen** [comment] 2020-02-06 23:38
Marking as closed. The fix for the admin SDK should go out with the next release.

**Closed** 2020-02-06 23:38 UTC
Labels: api: firestore
