### ISSUE TITLE
PWA using Polymer 2.0 when installed on Android device requires double login attempt

### ISSUE THREAD

**Issue by vinvantest** [firebase/firebase-js-sdk#814] opened 2018-05-12 19:44 UTC
Operating System version: Mac High Sierra 10.13.4
Firebase SDK - firebase@4.13.0
Firebase Tools version: 3.18.4
Firebase Product: auth
Chrome (android 8.1.0 Pixel XL Build) : 66.0.3359.158 version 

bower polymerfire#^2.2.1 cached https://github.com/firebase/polymerfire.git#2.2.1
bower polymerfire#^2.2.1 validate 2.2.1 against https://github.com/firebase/polymerfire.git#^2.2.1
bower firebase#* cached https://github.com/firebase/firebase-bower.git#4.6.1
bower firebase#* validate 4.6.1 against https://github.com/firebase/firebase-bower.git#*
bower firebase#* new version for https://github.com/firebase/firebase-bower.git#*
bower firebase#* resolve https://github.com/firebase/firebase-bower.git#*
bower firebase#* download https://github.com/firebase/firebase-bower/archive/v4.13.0.tar.gz
bower firebase#* extract archive.tar.gz
bower firebase#* resolved https://github.com/firebase/firebase-bower.git#4.13.0
bower firebase#^4.13.0 install firebase#4.13.0
bower polymerfire#^2.2.1 install polymerfire#2.2.1

Hi, 

I have a PWA app using Polymer 2.0 and firebase.
Issue - user has to attempt twice to login to the PWA on Android Chrome devices.

The issue I am facing is for Twitter and Facebook login using signinwithredirect option the user has to attempt twice. 1st time user initiates Auth. It gets redirected to respective provider login page and then on success redirects to my PWA landing page. But on the landing page that is configured as redirect url nothing happens. Then 2nd time user again clicks login attempt and now the user is not asked for Provider Login page login but simply redirects to my landing page and user is successfully logged in.

Here's the code snippet. Not sure what is wrong and I have been scratching my head a lot to fix it.
Index.html is the page where all my-app.html parent element is with app-routing. my-app.html has all other child pages.

Source code and screenshots to reproduce -> https://github.com/vinvantest/git_issue_firebase_login

**Comment by bojeil-google** [comment] 2018-05-13 19:56
This looks like a duplicate of https://github.com/firebase/firebaseui-web/issues/221 and unrelated to firebase library. It is an issue with chrome.

**Comment by vinvantest** [comment] 2018-05-13 20:17
Thanks for linking the issue. Hope it gets resolved. Also added Chrome version on Android if anyone wish to test/validate.

**Comment by jshcrowthe** [comment] 2018-06-20 17:40
Closing per @bojeil-google's comments let us know if this changes!

**Closed by jshcrowthe** 2018-06-20 17:40 UTC
Labels: Component-Auth
