### ISSUE TITLE
"Create index" link doesn't support multiple accounts

### ISSUE THREAD

**Issue by charles-allen** [firebase/firebase-js-sdk#5227] opened 2021-08-01 07:20 UTC
## Describe your environment

  * Operating System version: **N/A**
  * Browser version: **N/A**
  * Firebase SDK version: **firebase-admin 9.11.0** (probably N/A)
  * Firebase Product: **firestore**

## Describe the problem

- Firebase Console **supports multiple logged-in users**
- Firebase CLI **supports multiple logged-in users**
- "Create index" **links only work for the default logged-in user**  
_...they do not detect access for a secondary user & there is no opportunity to select a user manually_

### Suggested solution

1. Enumerate all logged in users until finding one with access
2. If none have access, redirect to login

### Steps to reproduce

1. Create a Node project under a secondary user (not default in your browser)
2. Write a query that requires an index
3. Click the "create index" link in the error message

**Expected:** Opens _Firebase Console_ as the correct user and suggest the index

![Screen Shot 2021-08-01 at 14 02 55](https://user-images.githubusercontent.com/31621095/127762760-b3ddbb45-9b44-4746-a20b-c20328588a8c.png)

**Actual:** Opens _Google Cloud Console_ as the default user and state that you don't have access

![Screen Shot 2021-08-01 at 14 03 19](https://user-images.githubusercontent.com/31621095/127762768-12b612fb-d4ec-4808-ba94-60e1c6108942.png)

**Additional:** When I changed user in Google Cloud Console, I was redirected to a GCP Console Firestore page, but for a completely different project (which I consider highly confusing and potentially dangerous)

![Screen Shot 2021-08-01 at 14 03 36](https://user-images.githubusercontent.com/31621095/127762774-5042ab38-4482-49be-a461-9575548e066f.png)

### Temporary Workaround

Usually I resolve such issues be adding `/u/2` at the start of the URL. In this instance, I also needed to remove `/v1/r` (which I assume is a redirect to support future-proofing). Note: I was only able to find the correct URL *after* adding my primary account to the project.

- Link from error message:  
`https://console.firebase.google.com/v1/r/project/<MY_PROJECT_ID>/firestore/indexes?create_composite=<SOME_INDEX_ID>`

- Link for user `#2`:  
`https://console.firebase.google.com/u/2/project/<MY_PROJECT_ID>/firestore/indexes?create_composite=<SOME_INDEX_ID>`

**Comment by looptheloop88** [comment] 2021-08-02 16:26
Hi @charles-allen, thanks for the report. I am trying to replicate the behavior that you've reported. I'm not sure what you really mean by the "secondary user (not default in your browser)" part. Do I need to log multiple accounts in the Firebase console? Open the link to create a Firestore index, then switch to a different user? Also, should the secondary user need to be a member of the Firebase project?

**Comment by charles-allen** [comment] 2021-08-02 16:57
> Hi @charles-allen, thanks for the report. I am trying to replicate the behavior that you've reported. I'm not sure what you really mean by the "secondary user (not default in your browser)" part. Do I need to log multiple accounts in the Firebase console? Open the link to create a Firestore index, then switch to a different user? Also, should the secondary user need to be a member of the Firebase project?

1. In your browser, login to Firebase Console with multiple users (Google account switcher that you get when you click your profile icon). The first account you logged in with is labelled your "default account".
2. Create a Firebase project under a non-default account
3. Try to create an index for that project 

Result: the link opens a page that is logged in with your default account (which does not have access to the Firebase project).

**Comment by charles-allen** [comment] 2021-08-02 17:02
Look at the top-right of my screenshots. Notice that the profile icon is different.

My Firebase project is under "suit/tie" account. But the link opens a page that's logged in with my default "hat" account.

**Comment by charles-allen** [comment] 2021-08-03 05:52
Once logged in with multiple users, all URLs are updated to include the user index, ex:
- https://console.firebase.google.com/u/0/ << default account
- https://console.firebase.google.com/u/1/ << another account
- https://console.firebase.google.com/u/2/ << another account

The "create index" URL does not include this.

**Comment by looptheloop88** [comment] 2021-08-03 16:36
Hi @charles-allen, thanks for the detailed explanation. I was able to reproduce the behavior now. Let me check what we can do for this issue or bring someone here that can provide more context about it. I’ll update this thread if I have any information to share.

**Comment by wu-hui** [comment] 2021-08-03 16:59
Hey @charles-allen 

Thanks for the report..our console team is able to reproduce this, and will try to address this by allowing you to pick which user profile to use. We are tracking this feature internally..and unfortunately there is no ETA at this point.

Will keep you updated when I hear more!

**Comment by looptheloop88** [comment] 2021-08-03 17:12
Here's the internal bug for reference: b/195421452

**Comment by charles-allen** [comment] 2021-08-17 04:53
I noticed the same effect this morning when clicking a link in a Firebase email (ie. this might be a much broader architectural issue). Again, the redirect assumes my default Google user (which seems ironic since I viewed the email in Gmail, while logged in as the secondary account).

![Screen Shot 2021-08-17 at 11 51 15](https://user-images.githubusercontent.com/31621095/129665602-84fad840-8bc1-40f9-93b9-77efa82d3085.png)

**Comment by TobiasHeidingsfeld** [comment] 2024-05-22 12:39
Issue still existing and not changes after 3 years?

**Comment by MarkDuckworth** [comment] 2024-05-22 16:05
It looks like this issue with the create index link was fixed in the console in March of 2022. I just verified that it is still behaving correctly. This GitHub ticket should have been closed.

@TobiasHeidingsfeld, can you tell us more about what you are experiencing?

**Comment by TobiasHeidingsfeld** [comment] 2024-05-22 16:14
The same as the other reports above. Links to create a compound index are not including the the user e.g. /u/1 in the url so they fail even if my flutter CLI uses the correct user.

**Comment by MarkDuckworth** [comment] 2024-05-22 16:31
I'm testing with the latest firebase-js-sdk, and when I'm logged into multiple Google accounts and then open the link to create an index (the link logged by the firebase-js-sdk), then I am prompted to choose the account. See the screenshot.

![image](https://github.com/firebase/firebase-js-sdk/assets/1124037/3aef5d65-de57-40f9-a39d-48758de7619b)

If I'm only logged into a single Google account, then I'm not prompted to choose the user when opening the link.

Can you provide more information about the SDK platform and version you are using? If you have detailed steps to reproduce, that would be helpful.

**Comment by MarkDuckworth** [comment] 2024-05-28 16:04
I'm closing this because it looks like the issue was addressed in the Firebase console in March of 2022. I verified that when the user is logged into multiple Google accounts, then the console will prompt the user to select an account when opening a create index link. 

If any customers are still experiencing this or related issues, please let us know. Googlers follow b/195421452.

**Closed by MarkDuckworth** 2024-05-28 16:04 UTC
Labels: bug, api: firestore, internal-bug-filed
