### ISSUE TITLE
RecaptchaVerifier error when used together with AppCheck

### ISSUE THREAD

**Issue by faizanabidnaqvi** [firebase/firebase-js-sdk#6133] opened 2022-04-10 17:12 UTC
### [REQUIRED] Describe your environment

  * Operating System version: MacOS Monterey 12.3
  * Browser version: Chrome version 100.0.4896.75
  * Firebase SDK version: 9.6.10
  * Firebase Product: auth

### [REQUIRED] Describe the problem
When I use the RecaptchaVerifier on my site with AppCheck enabled, I get an error when I call the verify method on the RecaptchaVerifier. The error is as follows:
`
TypeError: this.getAssertedRecaptcha(...).render is not a function
`
This only happens when AppCheck is enabled; without AppCheck it behaves normally, that is, the verification goes through. Also, it doesn't happen in development or production when running at localhost with the emulator. Only occurs in the deployed code in firebase hosting.

<img width="587" alt="Screenshot 2022-04-10 at 6 29 34 PM" src="https://user-images.githubusercontent.com/5749036/162631164-7ab44038-3b32-43c8-bd99-8fd4dd6e380c.png">

#### Steps to reproduce:
1. Create a react app with firebase app check enabled
2. Create a simple page with an invisible RecaptchaVerifier and a button that when clicked calls 'RecaptchaVerifier.verify()'
3. Build the app and deploy to hosting
4. Notice the error occurs when you press the button that calls the verify function
#### Relevant Code:

In my root App.tsx file, appcheck is initialized this way
```typescript
if(!getApps().length){
  const app = initializeApp(firebaseConfig)
  // console.log(`Initializing app check with ${import.meta.env.VITE_RECAPTCHA_KEY}`)
  //if localhost set debug app check token
  //https://firebase.google.com/docs/app-check/web/debug-provider?authuser=0&hl=en
  if (window.location.hostname === "localhost"){
    //this must be set to true to generate a new token and once generated and registered, we need to set the token value in env
    //(self as any).FIREBASE_APPCHECK_DEBUG_TOKEN = true
    (window.self as any).FIREBASE_APPCHECK_DEBUG_TOKEN = import.meta.env.VITE_APP_CHECK_DEBUG_TOKEN
  }

  initializeAppCheck(app, {
    provider: new ReCaptchaEnterpriseProvider(import.meta.env.VITE_RECAPTCHA_KEY),
    isTokenAutoRefreshEnabled: true
  })
}
```

The RecaptchaVerifier component is as follows
```typescript
export const FirebaseRecaptcha = ({instructionMessage, onVerificationComplete}: FirebaseRecaptchaProps)=>{

    const [isCaptchaLoading, setCaptchaLoading] = useState(false)
    const [verificationErrored, setVerificationErrored]= useState(false)
  
    let verifier: any = null
    useEffect(()=>{
      console.log("Initializing captcha");
  
      verifier = new RecaptchaVerifier("recaptcha-container", {
        'size': 'invisible',
        'callback': function(response: any) {
          console.log("verification success")
          setCaptchaLoading(false)
          onVerificationComplete(CaptchaVerificationStatus.SUCCESS)
        }
      }, getAuth())
    },[])
  
    const onStartClick = async ()=> {
      if(verifier){
        try {
          setCaptchaLoading(true)
          console.log("About to verify")
          const res = await verifier.verify()
        }catch(e){
          setCaptchaLoading(false)
          console.error(e)
          onVerificationComplete(CaptchaVerificationStatus.FAIL)
        }
      }
    }
  
    // <Button variant="contained" color="primary" id={recaptchaButtonId} onClick={()=>onStartClick()} className={`${classes.actionButton} ${classes.bottomMargin}`}>
    //   Start
    // </Button>

    return (
        <>
          <div id="recaptcha-container"></div>
          <Typography variant="h6" gutterBottom sx={{mb: 2}}>
            {instructionMessage ? instructionMessage : getStrings().message_start_page}
          </Typography>
          {isCaptchaLoading ?
            <CircularProgress sx={{mb: 2}} /> :
            <Button variant="contained" color="primary" onClick={()=>onStartClick()} sx={{mb: 2, width: '50%'}}>
              {getStrings().button_start}
            </Button>
          }
        </>
      )
  }
```

**Comment by jbalidiong** [comment] 2022-04-14 08:02
Hi @faizanabidnaqvi, thanks for the report. I was able to reproduce the behavior now. Let me check what we can do for this issue or bring someone here that can provide more context about it. I’ll update this thread if I have any information to share.

**Comment by votenex** [comment] 2022-05-17 05:15
I am currently experiencing this. Phone signin worked before app check. After app check, getting error "this.getAssertedRecaptcha(...).render is not a function".

**Comment by votenex** [comment] 2022-05-26 04:07
Is there an update on this?

**Comment by VFertak** [comment] 2022-06-15 05:38
any update on this issue?

**Comment by stjoe4** [comment] 2022-06-21 05:43
any update?

**Comment by stjoe4** [comment] 2022-06-21 11:19
It works with ReCaptchaV3Provider

**Comment by votenex** [comment] 2022-06-22 02:40
> It works with ReCaptchaV3Provider

I used app check ReCaptchaV3Provider with phone signin. I had the same issue. So it worked for you?

**Comment by stjoe4** [comment] 2022-06-23 20:21
> 

Yes it works with ReCaptchaV3Provider, but have the same error with ReCaptchaEnterpriseProvider.

**Comment by weixifan** [comment] 2022-06-27 17:35
Thank you for reporting this issue. We're looking into it. Internal bug filed: b/237289338.

**Comment by hsubox76** [comment] 2022-07-06 21:43
I actually haven't been able to reproduce this by using the code in the first post and trying to fill in the blanks. I've tried localhost dev server, localhost prod build, and deployed Firebase hosting, and they all work. Does anyone have a minimal repro I can use? (preferably one that errors in localhost, but if not, just let me know what environment)

**Comment by votenex** [comment] 2022-07-07 05:33
> 

When I had this error, I tried both v3 and enterprise. It doesn't even get to the verify code part. 

app check:
`const appCheck = initializeAppCheck(firebaseApp, {
    provider: new ReCaptchaV3Provider('***********************'),
    isTokenAutoRefreshEnabled: true
});`

phone auth:
`setPersistence(auth, browserLocalPersistence)
        .then(() => {
            // Sign in
            signInWithPhoneNumber(auth, usermobile, recaptchaVerifier)
            .then((confirmationResult) => {
                $('#otpcode').show();
                $('#phone-signin-sendcode').hide();
                $('#phone-signin-verifycode').show();

                $('#phone-signin-verifycode').click(async function() {
                    const code = document.getElementById('otpcode').value;
                    window.confirmationResult = confirmationResult;

                    let x = {
                        mobile: usermobile,
                        userid: z,
                        code: code
                    }
                    verifyCode(x)
                })

            }).catch((error) => {
                alert('An error occurred! ' + error.code + " " + error.message);
                window.recaptchaVerifier.render().then(function(widgetId) {
                    grecaptcha.reset(widgetId);
                });
            });
        })
        .catch((error) => {
            alert('An error occurred! ' + error.code + " " + error.message);
        });`

even if I used self.FIREBASE_APPCHECK_DEBUG_TOKEN = true; It still didn't work. 

a few weeks ago, v3 started working for me. But enterprise still doesn't work.

**Comment by hsubox76** [comment] 2022-07-07 18:20
I'm able to reproduce with App Check's `ReCaptchaEnterpriseProvider` only, and I think I can get a quick fix done for that. If you're experiencing this error with `ReCaptchaV3Provider`, it would be great if you can provide a reliable minimal repro of it with all the extraneous parts stripped out. Will post a PR for the Enterprise fix soon.

**Comment by hsubox76** [comment] 2022-07-07 21:01
Let me keep this open because there's still some uncertainty about if there is a bug with RecaptchaV3.

**Comment by ehedaya** [comment] 2022-08-01 18:40
I have this error and it started when I switched from using regular recaptcha to enterprise recaptcha on my firebase project. Seems like there's a difference between the object that gets returned by enterprise vs normal recaptcha, this is the object with the missing method in debug mode
<img width="424" alt="Screen Shot 2022-08-01 at 2 39 12 PM" src="https://user-images.githubusercontent.com/152859/182220534-28afead8-07ff-45f8-ba36-bc21c7f5f762.png">

**Comment by hsubox76** [comment] 2022-08-01 19:20
This should be fixed in 9.9.1, if it's not the case, can you try a fresh reinstall to make sure nothing was left behind? (remove node_modules and yarn.lock and reinstall). If that doesn't work, can you provide a minimal repro? See https://github.com/firebase/firebase-js-sdk/issues/6485#issuecomment-1201612743 for similar comment.

**Comment by ehedaya** [comment] 2022-08-04 14:39
Thanks! That did fix it!

**Comment by hsubox76** [comment] 2022-08-15 17:06
I haven't heard back from the other person who reported it in https://github.com/firebase/firebase-js-sdk/issues/6485 so I'll close this again, can reopen if someone reports the problem again.

**Closed by hsubox76** 2022-08-15 17:06 UTC
Labels: api: auth, v9, api: appcheck
