### ISSUE TITLE
Unable to install firebase using npm install firebase

### ISSUE THREAD

**Issue by ankush2394** [firebase/firebase-js-sdk#403] opened 2017-12-27 20:09 UTC
Steps to produce - 1. npm install firebase 
Only one step process.
Node version tried- 8.9.3 and 6.3 versions 
Npm version tried - 5.4 and 3.2 
Also tried deleting node_packages and then npm install.
Also tried including firebase in package.json and then npm install.
Also tried same process with yarn and bower.
Error is its unable to download grpc module@1.8 .
Also tried downloading grpc independently with both firewall open and close.
Any other expected solution before i need to eject at last.

ScreenShots-
![image](https://user-images.githubusercontent.com/11161508/34377640-ed53e3f8-eb17-11e7-8cac-50749ae1df4d.png)
![image](https://user-images.githubusercontent.com/11161508/34377662-fcc72a52-eb17-11e7-930e-4817e008a5cc.png)

**Comment by jshcrowthe** [comment] 2017-12-27 21:45
Hey @ankush2394 I'm going to close this as it seems to be a `grpc` issue. I was succesfully able to install firebase@4.8.1

<img width="1148" alt="screen shot 2017-12-27 at 1 44 43 pm" src="https://user-images.githubusercontent.com/5588878/34394139-2775e4de-eb0c-11e7-8856-24c80211891d.png">

Possibly consider trying to pin clear your NPM cache as well.

**Closed by jshcrowthe** 2017-12-27 21:45 UTC
Labels: needs-triage

**Comment by kidequinox** [comment] 2018-01-11 05:38
@ankush2394 I manually installed [node-pre-gyp](https://github.com/mapbox/node-pre-gyp), this worked.

**Comment by ankush2394** [comment] 2018-01-11 06:49
@kidequinox I am now working on os sierra because i have tried every possible solution including yours on my windows.
Thanks for the concern.

**Comment by pablougas** [comment] 2018-10-29 00:09
Found an article stating to clear npm cache with the following `npm cache clean --force`, then I was able to install it without issue. Spent a day on this, hope it helps the next person!

**Comment by danny-faith** [comment] 2018-11-14 11:20
I downgraded node from 11.0.0 to 10.13.0 and I was then able to successfully install firebase. See this guy for how to do it: https://www.abeautifulsite.net/how-to-upgrade-or-downgrade-nodejs-using-npm

**Comment by ad34** [comment] 2019-02-06 16:44
I have the same issue with node v10.15.1 and npm  6.7.0 , under windows 10. I get the error by typing npm install on a fresh empty node project with this package.json :

{
  "name": "firebasetest",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}


npm install firebase@latest --save

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.18.0 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grpc@1.18.0 install script.

the issue is erratic and not reproduced on an another windows 10 machine , but I am not able to find why it s failing on this machine
