### ISSUE TITLE
Error: NotYetImplemented at Document2.exports2.nyi 

### ISSUE THREAD

**Issue by Santoshah** [firebase/firebase-js-sdk#6677] opened 2022-10-11 08:18 UTC
The warning shouldn't affect any code functionality but you can downgrade to 9.10.0 if you want to avoid having a warning (or if I'm wrong and it is affecting your code). I have a fix (https://github.com/firebase/firebase-js-sdk/pull/6665) which should be released next week.

_Originally posted by @hsubox76 in https://github.com/firebase/firebase-js-sdk/issues/6660#issuecomment-1272100219_

**Comment by Santoshah** [comment] 2022-10-11 08:20
This does affect build of SSR version.

![image](https://user-images.githubusercontent.com/3863771/195037127-c23d0288-417e-42c5-a8d9-f8a8f70ed295.png)

**Comment by hsubox76** [comment] 2022-10-11 18:14
Thanks for the info, we'll be releasing a fix today or if not today, tomorrow.

**Comment by hsubox76** [comment] 2022-10-11 19:29
The fix has been released in 9.12.0.

**Comment by hsubox76** [comment] 2022-10-12 15:58
I don't think it's possible that you could get the same error in 9.8.1 because this method wasn't introduced until 9.11.0, possibly there was something left over in the node_modules or package-lock.json or yarn.lock.

Anyway it seems the problem is in https://github.com/firebase/firebase-js-sdk/blob/3e082cfa009b323b37f95efd4370eb501a562030/packages/util/src/defaults.ts#L73

Your SSR environment has a `document` object but it doesn't have a `document.cookie` or errors when you try to call it. Based on the error it looks like you're using Angular Universal, let me know if that's not the case. I'll do some research into the behavior of the `document` object in Angular Universal and see if I can figure it out. Also if this is a catchable error I'll look into wrapping the entire `getDefaults` function in a try/catch so that whatever odd environment errors happen, it won't block the rest of the app.

**Comment by Santoshah** [comment] 2022-10-12 16:16
Yes, its an Angular Universal project. 

I first notice this on Oct 10. while the code was uploding via aws codepipeline. This happens very sudden because before that my code was running fine. My firebase version was 9.8.1. (dam sure.) My deployment was success but the site throws 502 error. I login to server and checked that no command was running. Then I manually run the command `npm run serve:ssr` but it throws the same error `Error NotYetImplemented`. Then I checked the logs where I could see the same error after build was made.
<img width="551" alt="image" src="https://user-images.githubusercontent.com/3863771/195392928-3da47f02-cb5d-40c4-98e6-8faa5c3060a9.png">

I tried to search that in internet thats how I came to [this post](https://github.com/firebase/firebase-js-sdk/issues/6660).

This error appears on 9.8.1 only when fresh `npm install` is made.  Like codepipeline does with `codebuild`. My local project build worked fine. I tried to clone my project and checked with fresh `npm install` and I received the error.

I saw comments where user says that its working fine with `firebase 9.10.0` That's how I upgrade the firebase and checked and it was working fine. But when I update to 9.11.0 it throws same error. And again with 9.12.0 still not fixed..


My server.ts code.
```
import { enableProdMode } from "@angular/core";
(global as any).WebSocket = require('ws');
(global as any).XMLHttpRequest = require('xhr2');
import 'zone.js/dist/zone-node';
const domino = require('domino');
const fs = require('fs');
const path = require('path');

import { ngExpressEngine } from '@nguniversal/express-engine';
import * as express from 'express';
import { join } from 'path';
import { existsSync } from 'fs';
const dotenv = require('dotenv');
dotenv.config();
const distFolder = join(process.cwd(), 'dist/projectname/browser');
const template = fs.readFileSync(path.join(distFolder, 'index.html')).toString();
const win = domino.createWindow(template.toString());
global['window'] = win;
global['document'] = win.document;
global['DOMTokenList'] = win.DOMTokenList;
global['Node'] = win.Node;
global['Text'] = win.Text;
global['HTMLElement'] = win.HTMLElement;
global['navigator'] = win.navigator;
global['getComputedStyle'] = win.getComputedStyle;

(global as any).self = {fetch: require('node-fetch')};

// Faster server renders w/ Prod mode (dev mode never needed)
enableProdMode();

import { AppServerModule } from './src/main.server';
import { APP_BASE_HREF } from '@angular/common';


// The Express app is exported so that it can be used by serverless Functions.
export function app(): express.Express {
  const server = express();
  const distFolder = join(process.cwd(), 'dist/projectname/browser');
  const indexHtml = existsSync(join(distFolder, 'index.original.html')) ? 'index.original.html' : 'index';

  server.engine('html',  (_, options : any, callback) => {
    let engine = ngExpressEngine({
      bootstrap: AppServerModule,
      providers: [ { provide: 'host', useFactory: () => options.req.get('host') } ]
    });
  
    engine(_, options, callback)
  })
  server.set('view engine', 'html');
  server.set('views', distFolder);


  server.get('*.*', express.static(distFolder, {
    maxAge: '1y'
  }));
  let routesPath = ['/invite', '/invite/**','/lm', '/dashboard', '/dashboard/**', '/public/**', '/public', '/pre'];
  server.get(routesPath, (req, res) => {
    res.sendFile(distFolder + '/index.html');
  });

  // All regular routes use the Universal engine
  server.get('*', (req, res) => {    
      res.render(indexHtml, { req, providers: [
        { provide: APP_BASE_HREF, useValue: req.baseUrl }, 
        { provide: 'customConfig', useValue: req.get('host') }
      ] 
  });




  });

  return server;
}

function run(): void {
  const port = process.env.PORT || 8000;
  // Start up the Node server
  const server = app();
  server.get('/env', (req, res) => {
    res.json(process.env);
  })
  server.listen(port, () => {
    console.log(`Node Express server listening on https://localhost:${port}`);
  });
}

declare const __non_webpack_require__: NodeRequire;
const mainModule = __non_webpack_require__.main;
const moduleFilename = mainModule && mainModule.filename || '';
if (moduleFilename === __filename || moduleFilename.includes('iisnode')) {
  run();
}

export * from './src/main.server';

```

**Comment by hsubox76** [comment] 2022-10-12 17:00
In your package.json you don't have it pinned to 9.8.1, you have a `^` which is asking it to grab the latest version above 9.8.1, as long as it isn't a major bump (as long as it's not 10.x.x or above). So when you do a fresh npm install, it won't grab 9.8.1, it will grab the latest version. If it's important to install the exact version I would suggest you remove the `^`.  https://nodesource.com/blog/semver-tilde-and-caret/

In any case I'm working on a fix to be released in the next version, likely 9.12.1.

**Comment by Santoshah** [comment] 2022-10-12 17:17
Thanks for the comments. I want to keep my code up to date. Thank for the ^ tips.

**Closed** 2022-10-12 19:43 UTC
Labels: api: core, v9

**Comment by Santoshah** [comment] 2022-10-13 03:16
With `9.12.1` build working fine.  Thanks for the quick realease.

**Comment by shreyasPL** [comment] 2022-10-13 15:49
Hey,
This issue of @firebase/util __FIREBASE_DEFAULTS__ , is expected still persists,
I did the following before running the app, 
Our app is ionic capacitor app.
```💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.3.0
  @capacitor/core: 4.3.0
  @capacitor/android: 4.3.0
  @capacitor/ios: 4.3.0

Installed Dependencies:

  @capacitor/cli: 4.3.0
  @capacitor/core: 4.3.0
  @capacitor/android: 4.3.0
  @capacitor/ios: 4.3.0

[success] iOS looking great! 👌
[success] Android looking great! 👌 
```
1. deleted node_modules
2. deleted package_lock.json
3. Updated firebase: 9.12.1 in package.json
4. Installed packages again.


Please share some insight.
We are facing issue in the following as we are trying to refreshToken forcefully after an hour, by storing the txp in localStorage.
getIdToken(true) also returns -> jsonexception with 
```auth/network-request-failed ``` as error.
getIdToken() without the forceRefreshToken as param is working fine, until the token becomes expired, that's when, there is no response, but the error.
Thank you.

**Comment by hsubox76** [comment] 2022-10-13 16:01
I'm not sure if I'm reading your comment correctly but it sounds like you have two separate issues:

(1) Something about FIREBASE_DEFAULTS. Is it the exact error above ("NotYetImplemented at Document2.exports2.nyi") or something else? If it's something else, can you create a new issue and add more details about what the exact error is?

(2) Something to do with auth and refreshToken. Can you create a separate issue for this and provide the code you are using to call these auth methods?

**Comment by shreyasPL** [comment] 2022-10-13 16:12
yes I do have two separate issues, Will create two separate tickets. 
Thank you.
