### ISSUE TITLE
Uncaught Error: Component analytics has not been registered yet

### ISSUE THREAD

**Issue by b0ot** [firebase/firebase-js-sdk#6703] opened 2022-10-18 12:00 UTC
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10 Pro
  * Browser version: Chrome is up to date Version 106.0.5249.119 (Official Build) (64-bit)
  * Firebase SDK version: _____
  * Firebase Product: _____ (auth, database, storage, etc)
├── firebase-admin@11.2.0 ├── firebase-functions@3.24.1 ├── firebase@9.12.1

### [REQUIRED] Describe the problem
After doing an npm update, I get the following errors on my app.
```
app.js:264 Uncaught Error: Component analytics has not been registered yet
    at Provider.initialize (index.esm2017.js?1aea:232:1)
    at initializeAnalytics (index.esm2017.js?86f9:1024:1)
    at getAnalytics (index.esm2017.js?86f9:1003:1)
    at eval (firebase.js?fc1b:32:1)
    at ./src/boot/firebase.js (app.js:85:1)
    at __webpack_require__ (app.js:261:33)
    at fn (app.js:527:21)
    at eval (user.js:8:71)
    at ./src/stores/user.js (app.js:173:1)
    at __webpack_require__ (app.js:261:33)
```

    
#### Steps to reproduce:

Things Tried:
1. Uninstalling / Reinstalling Firebase
2. Commenting out the analytics section, still get an error. Always related to Firebase
If I keep going through commenting out firebase code, it will just find an error somewhere else. Errors include:
`Uncaught (in promise) Error: Service storage is not available`
or
`Uncaught Error: Service firestore is not available`

These errors appear to be related directly on the import. If I comment out all the code actually using Firebase but leave the import statements, it will still cause errors.

3. Adding initializeAnalytics(app);
(didn't seem to help, docs made it seem unnecessary, removed)
4. Deleting node_modules folder / package-lock.json file both in main directory and functions folder
5. Reverting Firebase to 9.9.2 (no change, went back to 9.12.1)
6. Reverting to @quasar/app-webpack@3.5.9 (plus deleting node_modules again) 

The firebase config file was not changed during the upgrade, and has been used for weeks successfully prior to the issue today after the npm update.

#### Relevant Code:

```javascript
// Import the functions you need from the SDKs you need
import { initializeApp, getApp } from "firebase/app";
import { getAnalytics } from "firebase/analytics";
import { getFirestore, connectFirestoreEmulator } from "firebase/firestore";
import {
  getAuth,
  connectAuthEmulator,
  onAuthStateChanged,
} from "firebase/auth";
import { getStorage, connectStorageEmulator } from "firebase/storage";
import { getFunctions, connectFunctionsEmulator } from "firebase/functions";

// Your web app's Firebase configuration
// For Firebase JS SDK v7.20.0 and later, measurementId is optional
const firebaseConfig = {
...
};

// Initialize Firebase
const app = initializeApp(firebaseConfig);
const analytics = getAnalytics(app);

// Initialize Cloud Firestore and get a reference to the service
const db = getFirestore(app);
const auth = getAuth(app);
const storage = getStorage(app);
const functions = getFunctions(app, "europe-central2");


...
...

export {
  db,
  auth,
  storage,
  functions,
  APP_INFO,
  getCurrentUser,
  STRIPE_PRICES,
};
```

**Comment by dwyfrequency** [comment] 2022-10-18 15:11
Can you also try clearing the npm cache as well? I'm having difficulty reproducing your issue but previous resolutions involved the deletion of lock files and node modules which you already did so I am thinking the cache could be an issue https://github.com/firebase/firebase-js-sdk/issues/6019#issuecomment-1122783339. Can you also try using an incognito tab?

**Comment by b0ot** [comment] 2022-10-18 17:38
> Can you also try clearing the npm cache as well? I'm having difficulty reproducing your issue but previous resolutions involved the deletion of lock files and node modules which you already did so I am thinking the cache could be an issue [#6019 (comment)](https://github.com/firebase/firebase-js-sdk/issues/6019#issuecomment-1122783339). Can you also try using an incognito tab?

I tried to delete the node_modules again then cleaned the npm cache, then reinstalled.
`npm cache clean --force`

Still showing the same error

Tried in incognito as well, did not seem to help.

**Comment by b0ot** [comment] 2022-10-19 04:42
Apparently I'm not the only one having this issue. From the Firebase discord, another user has just reported having a similar issue where they updated unrelated npm packages. I'm using Qusar Vue3 Firebase v9 Webpack, their app is React Firebase v9 Vite.

Their message:
-------------------------------
Has anyone gotten  `Service firestore is not available ` with js v9 sdk when calling getFirestore(app) before?

I am in a React app (built with Vite) and after bumping version of some other unrelated npm dependencies I suddenly get this.
Its being thrown from here [github code](https://github.com/firebase/firebase-js-sdk/blob/bb6b5abff6f89ce9ec1bd66ff4e795a059a98eec/packages/component/src/provider.ts#L130) , with a comment of `// In case a component is not initialized....`
I am not sure how I can ensure that the firestore component gets initialized or if there is some underlying problem. Maybe someone has seen this before?

-------------------------------

**Comment by b0ot** [comment] 2022-10-19 07:28
So, I reverted all of my npm packages using the npm before directive and then started to upgrade packages one at a time. It turns out the firebase package appears to be the problem.

I incrementally upgraded until I found:
LAST WORKING CONFIG: firebase 9.10.X
```
├── @babel/eslint-parser@7.18.9
├── @quasar/app-webpack@3.5.9
├── @quasar/extras@1.15.1
├── @stripe/firestore-stripe-payments@0.0.6
├── @vueuse/core@9.1.0
├── axios@0.21.4
├── core-js@3.25.5
├── cors@2.8.5
├── eslint-config-prettier@8.5.0
├── eslint-plugin-vue@9.3.0
├── eslint-webpack-plugin@3.2.0
├── eslint@8.21.0
├── firebase-admin@11.2.0
├── firebase-functions@3.24.1
├── firebase@9.10.0
├── lodash@4.17.21
├── luxon@3.0.1
├── nanoid@3.3.4
├── p5@1.5.0
├── pinia@2.0.23
├── prettier@2.7.1
├── quasar@2.10.0
├── vue-i18n@9.2.2
├── vue-router@4.1.3
└── vue@3.2.37
```
FIRST NOT WORKING: (Firebase 9.11.X)
```
├── @babel/eslint-parser@7.18.9
├── @quasar/app-webpack@3.5.9
├── @quasar/extras@1.15.1
├── @stripe/firestore-stripe-payments@0.0.6
├── @vueuse/core@9.1.0
├── axios@0.21.4
├── core-js@3.25.5
├── cors@2.8.5
├── eslint-config-prettier@8.5.0
├── eslint-plugin-vue@9.3.0
├── eslint-webpack-plugin@3.2.0
├── eslint@8.21.0
├── firebase-admin@11.2.0
├── firebase-functions@3.24.1
├── firebase@9.11.0
├── lodash@4.17.21
├── luxon@3.0.1
├── nanoid@3.3.4
├── p5@1.5.0
├── pinia@2.0.23
├── prettier@2.7.1
├── quasar@2.10.0
├── vue-i18n@9.2.2
├── vue-router@4.1.3
└── vue@3.2.37
```
Upgrading to the latest version 9.12.1 has the same issue.

Note I do get an error on the 9.11.X Webpack that states:
```
 App •  WARNING  •  UI  in ./node_modules/@firebase/analytics/node_modules/@firebase/util/dist/index.esm2017.js

Critical dependency: the request of a dependency is an expression


 App •  WARNING  • Compilation succeeded but there are warning(s). Please check the log above.
```

**Comment by b0ot** [comment] 2022-10-19 08:33
> 

How would I check this?

As a side note: I often delete the package-lock.json file when testing different packages.

**Comment by b0ot** [comment] 2022-10-19 08:57
I confirmed that I can update all of the other npm packages. The app works with firebase 9.10 but not 9.11.X / 9.12.X
```
├── @babel/eslint-parser@7.19.1
├── @quasar/app-webpack@3.6.2
├── @quasar/extras@1.15.5
├── @stripe/firestore-stripe-payments@0.0.6
├── @vueuse/core@9.3.1
├── axios@0.21.4
├── core-js@3.25.5
├── cors@2.8.5
├── eslint-config-prettier@8.5.0
├── eslint-plugin-vue@9.6.0
├── eslint-webpack-plugin@3.2.0
├── eslint@8.25.0
├── firebase-admin@11.2.0
├── firebase-functions@3.24.1
├── firebase@9.10.0
├── lodash@4.17.21
├── luxon@3.0.4
├── nanoid@3.3.4
├── p5@1.5.0
├── pinia@2.0.23
├── prettier@2.7.1
├── quasar@2.10.0
├── vue-i18n@9.2.2
├── vue-router@4.1.5
└── vue@3.2.41
```

**Comment by hsubox76** [comment] 2022-10-19 16:01
> Note I do get an error on the 9.11.X Webpack that states:
> 
> ```
>  App •  WARNING  •  UI  in ./node_modules/@firebase/analytics/node_modules/@firebase/util/dist/index.esm2017.js
> 
> Critical dependency: the request of a dependency is an expression
> 
> 
>  App •  WARNING  • Compilation succeeded but there are warning(s). Please check the log above.
> ```

(1) This is a separate issue that should be fixed in 9.12+

(2) Can you do a `npm ls firebase`, `npm ls @firebase/app` and `npm ls @firebase/analytics` inside your project dir while it is broken? The second one is the key usually (`npm ls @firebase/app`). Expect to see a number of entries, but they should all be the same version. If one of the results is a different version from the others, this will cause the problem.

(3) If that doesn't help we may need a minimal repro of your project.

**Comment by mesqueeb** [comment] 2022-10-29 03:59
It's definitely not stale.
I have this issue when upgrading to `"firebase": "9.13.0"`

My app only works up until `"firebase": "9.10.0"`, anything beyond that point breaks my app with this error:
> provider.ts:239 Uncaught Error: Component firestore has not been registered yet

sometimes the library shown here is different if I switch around some lines where i initialise my firebase services.

> (1) This is a separate issue that should be fixed in 9.12+

Nope, still happens on 9.13.0

> (2) Can you do a npm ls firebase, npm ls @firebase/app and npm ls @firebase/analytics inside your project dir while it is broken? The second one is the key usually (npm ls @firebase/app). Expect to see a number of entries, but they should all be the same version. If one of the results is a different version from the others, this will cause the problem.

`firebase` is all the same for me

<img width="400" src="https://user-images.githubusercontent.com/3253920/198812705-0d20e684-4758-4e72-b54e-6c4f756e6654.jpeg" />

`@firebase/app` is different with the culprits being `@firebase/auth@0.20.11` and `@firebase/app-compat@0.1.38` and `firebase@9.13.0` itself all having a higher version compared to all its other sub-packages.

<img width="400" src="https://user-images.githubusercontent.com/3253920/198812753-2644edd1-f07e-4481-a053-8d4d9aaddf76.jpeg" />

`@firebase/firestore` is the same version everywhere

<img width="400" src="https://user-images.githubusercontent.com/3253920/198812828-e0055d98-79bc-4b92-976b-cd0c823672f2.jpeg" />

**Comment by mesqueeb** [comment] 2022-10-29 04:06
@jbalidiong can you remove the `api:analytics` label you added? Since this is not an `analytics` issue, but more a version conflict related to the over-reaching firebase package. It will throw a similar issue for any package you try to initialise after firebase app.

@dwyfrequency can you remove the `needs-info` again which you added?

@looptheloop88 can you add back the `needs-attention` label which you removed?

**Comment by ishowta** [comment] 2022-10-29 04:40
@b0ot  @mesqueeb 
`@stripe/firestore-stripe-payments` has some old firebase dependency.
https://github.com/stripe/stripe-firebase-extensions/blob/ad40aa0a6bd08bf3a6b310d408126d5ed37a5561/firestore-stripe-web-sdk/package.json#L63

**Comment by hsubox76** [comment] 2022-10-31 16:23
I'm sorry to ask but you didn't mention, did you delete your node_modules and lockfile and reinstall? `@firebase/app` version 0.7.33 is incorrect and is several versions behind. The package.json for firebase@9.13.0 definitely points to `@firebase/app` version 0.8.3 so my guess is a problem with your lockfile, or something else that can cause an incomplete npm update.

If you do a fresh install into a new empty project and see this, let me know, but otherwise I think this is just an issue with the npm update process.

You can just let us know your status and what problems you're experiencing, you don't have to request specific labels, which won't necessarily do what you want. `needs-info`, for example, marks the issue to be closed in a week if no one replies, which I don't think is what you are asking for.

**Closed** 2022-11-14 02:02 UTC
Labels: needs-info, no-recent-activity, api: analytics, v9
