### ISSUE TITLE
React-Native Expo - firebase analytics web - document is undefined

### ISSUE THREAD

**Issue by bulby97** [firebase/firebase-js-sdk#2238] opened 2019-10-04 02:09 UTC
### [REQUIRED] Describe your environment

* Operating System version: OSX
* Browser version: React-native
* Firebase SDK version: 7.1.0
* Firebase Product: analytics

### [REQUIRED] Describe the problem

Native firebase analytics cannot be used with Expo for React-native at the moment, see [here](https://gist.github.com/brentvatne/9038b16b4f42a21cea40ad5c35fdb74c). So I tried to use firebase-analytics for web in Expo, but it fails with `document is not defined`

#### Steps to reproduce:

Add firebase js sdk to an expo project, import `firebase/analytics`

**Comment by edd0408** [comment] 2019-10-04 05:45
Duplicate of # 3

**Comment by Feiyang1** [comment] 2019-10-04 16:54
`firebase/analytics` doesn't work for React Native because it relies on gtag.js which only works in browser. Please see our [environment support](https://firebase.google.com/support/guides/environments_js-sdk?authuser=0) page.

**Closed by Feiyang1** 2019-10-04 16:54 UTC
Labels: needs-triage

**Comment by marcoancona** [comment] 2019-10-06 22:31
What about Electron? I would expect this to work, as it is essentially a Chrome browser.

**Comment by Feiyang1** [comment] 2019-10-07 16:57
It should work in Electron if you run your code in the renderer process. `firebase/analytics` added a script tag to the DOM. As long as `firebase/analytics` can do that, it should work.
