### ISSUE TITLE
iOS 15.2 Could not reach Cloud Firestore backend

### ISSUE THREAD

**Issue by elongberg** [firebase/firebase-js-sdk#7858] opened 2023-12-11 23:30 UTC
### Operating System

iOS 15.2

### Browser Version

Safari/604.1

### Firebase SDK Version

10.7.1

### Firebase SDK Product:

Auth, Firestore

### Describe your project's tooling

Angular 17

### Describe the problem

Unable to use recent versions of firebase on iOS 15.2. With firebase versions 10.7.0 and 10.7.1, we get the below error.

`Could not reach Cloud Firestore backend. Connection failed 1 times. Most recent error: FirebaseError: [code=unavailable]: The operation could not be completed
This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.`

This is followed (and preceded) by a trickle of warnings like so:
`WebChannelConnection RPC 'Listen' stream 0x8c3e05c0 transport errored`

We're having an unrelated error with firebase that also makes it unusable on any older versions since 10.0.0 (if we decide it's not just an oddity in our setup, we may post a separate issue for that, but that issue did go away in 10.7.0). Last known-working firebase was 9.17.2 (haven't been able to test yet on newer version 9's).

Enabling `experimentalForceLongPolling` has no effect. No issue when running in iOS 15.5 or later (unsure about 15.3/15.4). We don't have physical devices with these older iOS versions, but this happens consistently in iOS simulators/not just a network issue, and their are reports of this in the field as well.

### Steps and code to reproduce issue

See above

**Comment by thomasdao** [comment] 2023-12-12 10:28
@elongberg I also see the similar error `WebChannelConnection RPC 'Listen' stream 0x8c3e05c0 transport errored` in my project and also reported in https://github.com/firebase/firebase-js-sdk/issues/7860. Reverting to older version 10.6.0 works for me, maybe you can try on your side? I suspect that two issues may share the same root cause.

**Comment by ehsannas** [comment] 2023-12-12 21:09
@elongberg Would you be able to try version 10.6.0 and let us know if that resolves the issue for you?

**Comment by elongberg** [comment] 2023-12-14 16:33
@ehsannas On any version 10.x.x prior to 10.7.0, we have separate issues. We have code along the lines of this:
```ts
const app = initializeApp(config);
initializeAuth(app);
getFirestore(app);
```

This works on every other platform/firebase version. But with iOS 15.2 and e.g. firebase 10.6.0, `initializeAuth` throws this error
`Component auth has not been registered yet`
and (if we temporarily comment out the auth portion) `getFirestore` throws this error
`Service firestore is not available`

**Comment by elongberg** [comment] 2023-12-29 22:02
We've decided it's easiest to stop supporting the older iOS versions (updates are readily available). Hopefully the basic setup I described above would be enough to replicate it, but I won't be able to make a minimal version to confirm it.

**Comment by ehsannas** [comment] 2024-01-02 20:22
Closing since I'm not able to reproduce this issue.

**Closed by ehsannas** 2024-01-02 20:22 UTC
Labels: question, api: firestore, needs-attention
