### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by usb248** [firebase/firebase-js-sdk#1221] opened 2018-09-11 13:06 UTC
### Version info

"firebase": "^5.4.2",

### Platform Information

Windows 10 (tested browser : chrome with latest version)

### Steps to reproduce

Enter point of my app execute this in first : 
```javascript
firebase.initializeApp({
	apiKey: 'xxx',
	authDomain: 'xxx',
	databaseURL: 'xxx',
	projectId: 'xxx',
	storageBucket: 'xxx'
})
firebase.auth().onAuthStateChanged( (user) => {
	if (user) {
	    commit('setUser', {id: user.uid, email: user.email})
	}
})
```

### Expected behavior

No crash of browser

### Actual behavior

Crash of browser owing to memory leak. All browsers crash after about 20 hours.
All works fine without code above

----------------------------------------
with dev tools in chrome : 
t0
![t0](https://user-images.githubusercontent.com/7659927/45361737-44b15780-b5d3-11e8-8315-d315737cb761.png)
t+1
![t1](https://user-images.githubusercontent.com/7659927/45361845-880bc600-b5d3-11e8-9ab0-72d686534ccb.png)
t+2
![t3](https://user-images.githubusercontent.com/7659927/45361875-a5409480-b5d3-11e8-885a-7a0f8a26eb07.png)

The snapshot of allocation on timeline :
![snap](https://user-images.githubusercontent.com/7659927/45362072-239d3680-b5d4-11e8-8458-df71db8f0b2c.png) 

etc .... until memory is too high and browser crash.

**Comment by jakejdavis** [comment] 2018-09-17 22:31
I am experiencing this too, using the same command of firebase.auth().onAuthStateChanged with React Native

**Comment by usb248** [comment] 2018-09-26 12:01
So .... okay. I will fix this issue myself. This section seems to be useless :( 👎

**Comment by FallenRiteMonk** [comment] 2019-03-21 14:19
@usb248 where you able to fix this issue? if yes, could you please be so kind and share your fix?

**Comment by usb248** [comment] 2019-03-21 14:30
My application is running in a browser on raspberry, so i run a cron which execute a shellscript which restart browser every days .... 👎

**Comment by FallenRiteMonk** [comment] 2019-03-21 15:30
@usb248 that's not a solution for me. Could you please reopen this issue? if not, i'll create a new one!

**Comment by usb248** [comment] 2019-03-21 15:50
for me neither

**Comment by FallenRiteMonk** [comment] 2019-03-21 18:35
@usb248 Thanks.

I have done some further analysis and added the infos to #1420

**Comment by Feiyang1** [comment] 2019-05-31 17:55
duplicate of https://github.com/firebase/firebase-js-sdk/issues/1420

**Closed by Feiyang1** 2019-05-31 17:55 UTC
Labels: needs-triage
