### ISSUE TITLE
V9 Modular Authentication  - browserSessionPersistence log out when refresh

### ISSUE THREAD

**Issue by daveteu** [firebase/firebase-js-sdk#5171] opened 2021-07-17 16:23 UTC
### [REQUIRED] Describe your environment

  * Operating System version: macos / ubuntu / window
  * Browser version: chrome / safari
  * Firebase SDK version: 9 beta 6
  * Firebase Product: auth

### [REQUIRED] Describe the problem
I believe browserSessionPersistence is supposed to persist during the time window/tab is open. However, the moment I refresh my webpage, I get logged out. This behavior did not exist in SDK v8.

With the same codes, browserLocalPersistence works like how it should in Version 8, so I believe browserSessionPersistence is not behaving the way it should.

#### Steps to reproduce:

```
const auth = getAuth()

await setPersistence(auth, browserSessionPersistence)

//.... login codes to different providers
```

**Comment by looptheloop88** [comment] 2021-07-20 12:27
Hi @daveteu, thanks for the report. I tried replicating the behavior you've reported, but I wasn't able to. I used the following code snippets and the user auth state persists even when the page is refreshed.

Import Auth modules:
```
import { signOut, onAuthStateChanged, signInWithPopup, GoogleAuthProvider, initializeAuth, 
browserSessionPersistence, browserPopupRedirectResolver } from "firebase/auth";
```

Initialize Auth and listen to Auth state:
```
firebaseAuth = initializeAuth(firebaseApp, {
    persistence: browserSessionPersistence,
    popupRedirectResolver: browserPopupRedirectResolver,
});

onAuthStateChanged(firebaseAuth, (user) => {
    if (user) {
        console.log("User is signed in.");
    } else {
        console.log("User is signed out.");
    }
});
```

Sign in the user:
```
const gogleAuthProvider = new GoogleAuthProvider();
signInWithPopup(firebaseAuth, gogleAuthProvider)
    .then((result) => {
        console.log(result);
    })
    .catch((error) => {
        console.log(error);
    });
```

Sign out the user:

```
signOut(firebaseAuth).then(() => {
    console.log("User successfully signed out.");
}).catch((error) => {
    console.log("Signed out error.");
});
```

If I can replicate the issue, I can have a better look into it. Please share a minimal, but complete sample of a project that I can run locally to replicate the issue.

**Comment by porfirioribeiro** [comment] 2021-07-23 15:08
I'm having the same problem. 
It's hard to debug, 
when you are out of the page and get back, and it refreshes the auth on background, looks like `onAuthStateChanged` is called twice with null and then with the user object

**Comment by Crysp** [comment] 2021-07-26 14:38
Hi @looptheloop88 

I have the same issue.

This code snippet does't work
```js
import {
    getAuth,
    setPersistence,
    browserSessionPersistence,
    signInWithEmailAndPassword,
} from 'firebase/auth';

const auth = getAuth();

await setPersistence(auth, browserSessionPersistence);
await signInWithEmailAndPassword(auth, 'test@test.ru', 'password');
```

If i remove `setPersistence`, session persists after page reloads.

```js
import {
    getAuth,
    setPersistence,
    browserSessionPersistence,
    signInWithEmailAndPassword,
} from 'firebase/auth';

const auth = getAuth();

// await setPersistence(auth, browserSessionPersistence);
await signInWithEmailAndPassword(auth, 'test@test.ru', 'password');
```

**Comment by anttikuuskoski** [comment] 2021-08-01 10:41
@looptheloop88, @daveteu

Still an issue in 9.0.0-beta.7.

The issue seems to be related to the (likely incorrect) way `setPersistence` works. If `browserSessionPersistence` is set using `initializeAuth` (as in @looptheloop88's example), the persistence gets set and works as it should. If `getAuth` is used instead of `initializeAuth` and persistence is set using `setPersistence`, the session does not survive page reload as in @daveteu's issue description. I have not tested the effect of sign in methods other than email/password.

Also, it seems that if persistence is set using `initializeAuth`, subsequent `setPersistence` calls fail override the setting:

 * If persistence is set to `browserLocalPersistence` via `initializeAuth`, setting persistence to `browserSessionPersistence` i in `setPersistence` results in broken behaviour (as described by this issue)

 * If persistence is set to `browserSesssionPersistence` via `initializeAuth`, setting persistence to `browserLocalPersistence` results in incorrect behaviour (no change in behaviour).

As a personal note, although I'm not sure how inMemoryPersistence should work, I'd venture the broken behaviour works equally to it.

Here's a minimal example of code producing the error.

```typescript
import { initializeApp } from "@firebase/app"

import {
  getAuth,
  onAuthStateChanged,
  signInWithEmailAndPassword,
  setPersistence,
  browserSessionPersistence
  //,initializeAuth
} from "@firebase/auth";

import { firebaseConfig, email, password } from './constants';

const firebaseApp = initializeApp(firebaseConfig);

const firebaseAuth = getAuth(firebaseApp);

// works
//const firebaseAuth = initializeAuth(firebaseApp, {
//  persistence: browserSessionPersistence
//});

firebaseAuth.onAuthStateChanged((user) => {
  if (user) {
    console.log("User is signed in.");
  } else {
    console.log("User is signed out.");
  }
});

// To illustrate the issue, call this once and reload page.
function persistentLogin() {
  setPersistence(firebaseAuth, browserSessionPersistence)
    .then(
      () => signInWithEmailAndPassword(firebaseAuth, email, password)
    );
}
```

**Comment by sam-gc** [comment] 2021-08-06 16:24
Sorry about the bot, folks. We're working on a fix

**Comment by daveteu** [comment] 2021-08-09 18:11
@looptheloop88  sorry for the late reply. I'm not using `signInWithPopup` + I am setting persistence with ` setPersistence(auth, browserSessionPersistence)`. 

I believe a couple of us are facing the same issue above, may I know do you still need me to create a sandbox to reproduce this?

**Comment by sam-gc** [comment] 2021-08-09 18:14
@daveteu no need for a sandbox reproduction. Thanks though! The PR I linked above should fix this issue once it's merged/released.

**Comment by amitsingh-007** [comment] 2021-08-09 19:27
I am also somewhat facing same issue using `firebase@v9.0.0-beta.8`. I am using the following piece of code:
```js
export const googleSignIn = async (token: string) => {
  const auth = initializeAuth(firebaseApp, {
    persistence: indexedDBLocalPersistence, //also tried using `browserLocalPersistence`
  });
  return signInWithCredential(
    auth,
    GoogleAuthProvider.credential(null, token)
  );
};
```
As soon as the chrome extension popup is closed(I think kind of browser refresh), the authentication state is not persisted. I can see the values stored in the local storage and IndexedDB but firebase db and storage gives permission errors.

**Comment by sam-gc** [comment] 2021-08-09 20:53
@amitsingh-007 I think you're experiencing an unrelated issue. Would you mind creating a new GitHub Issue with more details about your setup / circumstances leading to the problem?

**Closed** 2021-08-09 20:54 UTC
Labels: api: auth, v9
