### ISSUE TITLE
FR: core-js@<3.23.3 is no longer maintained could cause a slowdown up to 100x

### ISSUE THREAD

**Issue by dodomui** [firebase/firebase-js-sdk#6549] opened 2022-08-22 04:28 UTC
### [REQUIRED] Describe your environment

  * Operating System version: _____
  * Browser version: _____
  * Firebase SDK version: _____
  * Firebase Product: _____ (auth, database, storage, etc)

### [REQUIRED] Describe the problem
core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.

Possible to upgrade the core-js for firebase/polyfill depency?

#### Relevant Code:

```javascript
// TODO(you): code here to reproduce the problem
```

**Comment by jbalidiong** [comment] 2022-08-22 13:13
Duplicate of https://github.com/firebase/firebase-js-sdk/issues/6503

**Closed by jbalidiong** 2022-08-22 13:13 UTC
Labels: type: feature request
