### ISSUE TITLE
A boolean is being passed as a fourth parameter to window.open. This is not used and may cause an exception in a future release.

### ISSUE THREAD

**Issue by lpellegr** [firebase/firebase-js-sdk#4988] opened 2021-06-06 22:21 UTC
### [REQUIRED] Describe your environment

  * Operating System version: Fedora 34
  * Browser version: Chrome 91.0.4472.77
  * Firebase SDK version: 8.6.5
  * Firebase Product: auth

Calling `auth.signInWithPopup(new firebase.auth.GoogleAuthProvider())` displays the following error in the console. However, the popup opens and authentication works.

> safe.js:753 A boolean is being passed as a fourth parameter to window.open. This is not used and may cause an exception in a future release.

#### Steps to reproduce:

1. Set a click listener on a button.
2. As the listener behavior call `auth.signInWithPopup(new firebase.auth.GoogleAuthProvider())`.
3. Click on the button.
4. Look at the console.

#### Relevant Code:

```javascript
auth.signInWithPopup(new firebase.auth.GoogleAuthProvider())
```

**Comment by looptheloop88** [comment] 2021-06-08 17:24
Hi @lpellegr, thanks for the report. I was able to reproduce the error. I also verified that the user is getting registered and authenticated successfully.

**Comment by Nabarajrai** [comment] 2021-06-09 15:32
I have same problem.How to solve it?

**Comment by danhpham1** [comment] 2021-06-09 15:50
I have same problem, when i use sign-in method apple and i get some error.

> A boolean is being passed as a fourth parameter to window.open. This is not used and may cause an exception in a future release.

> Uncaught S {code: "auth/operation-not-allowed", message: "Code flow is not enabled for Apple.", a: null}
Few day ago, it still work but i get this error today. How to solve it? please help me
Thanks.

**Comment by malinhanak** [comment] 2021-06-10 06:37
I am also getting this error, at least when running the emulator suit

**Comment by approached** [comment] 2021-06-17 20:57
Same error on version `8.6.7` for ios and facebook.

**Comment by saqib0401** [comment] 2021-06-19 08:09
Same error but the authentication is working fine

**Comment by robstarkdev** [comment] 2021-06-19 14:34
Same error but auth is otherwise working as expected/desired.

**Comment by jalal246** [comment] 2021-06-20 05:34
Same here. But it works fine despite throwing an error in the console.

**Comment by moxgeek** [comment] 2021-06-22 09:30
i have the same issue on an ionic project.

`auth.esm.js:76 A boolean is being passed as a fourth parameter to window.open. This is not used and may cause an exception in a future release.`

**Comment by roubee** [comment] 2021-06-23 10:04
I have the same error on version 8.5.0 for Google and Facebook sign in.

**Comment by sam-gc** [comment] 2021-06-23 19:27
It looks like this all boils down to this line in the Closure library: https://github.com/google/closure-library/blob/9d24a6c1809a671c2e54c328897ebeae15a6d172/closure/goog/dom/safe.js#L811

Unfortunately we're a couple levels downstream from that library, so I can't provide any timeline for a fix. This issue does not impact [v9](https://github.com/firebase/firebase-js-sdk/discussions/4791) (still in Beta) as that codebase uses `window.open` directly

**Comment by juandgarin** [comment] 2021-06-24 17:03
Same error here... it's working but i can see this error on my console in my browser

**Comment by harvester-klirk** [comment] 2021-06-25 00:56
same error (V8)

**Comment by Cherylxue** [comment] 2021-06-27 21:18
same error here

**Comment by atifghaffar83** [comment] 2021-07-09 22:32
Same error here also can someone please update us is it going to be fixed soon or not. Please

**Comment by Rudrava** [comment] 2021-07-18 16:41
any solution to the bug please !! auth works fine but the error is anoying

**Comment by Anithaselva07** [comment] 2021-07-23 10:01
Any solution on fixing the above error.

**Comment by KgosiTshepo** [comment] 2021-07-25 14:32
Got the same error. Any updates ?

**Comment by tyagihas** [comment] 2021-07-27 01:54
Is this going to be fixed or any workaround?

**Comment by moxgeek** [comment] 2021-07-27 15:18
i solved the issue by using v9 beta.

**Comment by jbalidiong** [comment] 2021-11-04 09:06
The issue seems to be not replicable in the latest SDK version. I've tried the 9.2.0 and I'm not experiencing the behavior, please try upgrading your SDK version. I'll be closing this issue now.

**Closed by jbalidiong** 2021-11-04 09:06 UTC
Labels: type: bug, api: auth
