### ISSUE TITLE
Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'https://www.gstatic.com/firebasejs/10.13.0/firebase-app.js' failed to load

### ISSUE THREAD

**Issue by hpeppers2020** [firebase/firebase-js-sdk#8439] opened 2024-08-19 15:57 UTC
### Operating System

Windows 11

### Browser Version

Chrome/v127

### Firebase SDK Version

10.13.0

### Firebase SDK Product:

Messaging

### Describe your project's tooling

Vue 2 PWA app with webpack

### Describe the problem

I have installed the new Firebase SDK in our app. We are migrating from a legacy version (v7).

We have firebase@10.13.0 installed via our package.json and in our local firebase-messaging-sw.js file we are importing the firebase-app.js and firebase-messaging.js files. But we continually get the following error in the chrome browser console:
`firebase-messaging-sw.js:6 Uncaught DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'https://www.gstatic.com/firebasejs/10.13.0/firebase-app.js' failed to load.
    at https://qa.law.com/firebase-messaging-sw.js:6:1`

I can load the https://www.gstatic.com/firebasejs/10.13.0/firebase-app.js file when I click on the link in the console error.

### Steps and code to reproduce issue

- use npm to install the latest firebase package.
- update our importScripts in our local firebase-messaging-sw.js to the following:
`importScripts('https://www.gstatic.com/firebasejs/10.13.0/firebase-app.js')`
`importScripts(
  'https://www.gstatic.com/firebasejs/10.13.0/firebase-messaging.js')`
- Load the app in Chrome and check the browser's console to see the error.

**Comment by dlarocque** [comment] 2024-08-19 16:16
Hi @hpeppers2020, thanks for reporting this issue. I actually ran into this myself, and it turned out the issue was caused by the firebase messaging service workers not being configured to use ES modules (docs: [ES modules in Chrome SW](https://docs.google.com/document/d/1SeQ085YdBTtW3D_ygSpO0Wz2DAe8QiS1gj37IG5lstg/edit#heading=h.xgjl2srtytjt)). If you pull the files in locally and try to do a local import (instead of `importScripts('https://www.gstatic.com/firebasejs/10.13.0/firebase-app.js')`, do `import('/firebase-app.js')`, you might notice that the error is something related to `export` not being allowed.

To fix this, could you try importing the compat package? See this example: https://github.com/firebase/snippets-web/blob/2117c619ce49b08d582f282e7d2ec798f5105c3d/messaging/service-worker.js#L10-L32

**Comment by dlarocque** [comment] 2024-08-19 16:19
Looks like this is a duplicate of https://github.com/firebase/firebase-js-sdk/issues/5403, so I'll close this issue. If you believe this isn't a duplicate, please add more info explaining why that's the case, and I'll reopen the issue

**Closed by dlarocque** 2024-08-19 16:19 UTC
Labels: api: messaging, question, needs-attention, new

**Comment by hpeppers2020** [comment] 2024-08-19 16:33
Using the compat packages did the trick. Thanks for the quick response!
