### ISSUE TITLE
Unable to install from NPM

### ISSUE THREAD

**Issue by boardmain** [firebase/firebase-js-sdk#829] opened 2018-05-16 10:20 UTC
hi im unable to install the firebase sdk from npm

  * Operating System version: Ubuntu 18.04 LTS 
  * Firebase SDK version: latest from npm
  * Firebase Product: all firebase

***
node@nodehosting:~/sanlorenzo/appweb$ npm install firebase --save
npm ERR! Unexpected end of JSON input while parsing near '...7nsTC1w8xBsYznSTpS/G6'
***

i tried with the latest lts node ( 8.11.2 ) and with the latest node 10.1.0 same result

**Comment by mnshkv** [comment] 2018-05-16 10:27
i try with yarn and have some problem.

```
error Couldn't find package "@firebase/functions" on the "npm" registry.
```

**Comment by mmermerkaya** [comment] 2018-05-16 10:34
Duplicate of #768. Please try the suggested fix from that issue.

@mnshkv Please don't hijack other issues. That package [is on NPM](https://www.npmjs.com/package/@firebase/functions), so it's likely that the issue is on your end. Try checking your registry settings in your `.npmrc` or `.yarnrc`.

**Closed by mmermerkaya** 2018-05-16 10:34 UTC
Labels: needs-triage
