### ISSUE TITLE
Remote config throws error in Firefox private browsing mode

### ISSUE THREAD

**Issue by kenkus-futurice** [firebase/firebase-js-sdk#2373] opened 2019-11-20 14:01 UTC
### Describe your environment

  * Operating System version: Windows 10
  * Browser version: Firefox 70.0.1 private mode
  * Firebase SDK version: 7.4.0
  * Firebase Product: remote config

### Describe the problem

Remote config throws error in Firefox (possibly also related problem in IE 11 and Edge) private browsing mode.

```
Error: Remote Config: Error thrown when opening storage. Original error: A mutation operation was attempted on a database that did not allow mutations.. (remoteconfig/storage-open).
```

#### Steps to reproduce:

Load a web app that uses remote config in Firefox private browsing mode.

#### Relevant Code:

```javascript
import * as firebase from 'firebase/app';
import 'firebase/remote-config';

const remoteConfig = firebase.remoteConfig();

remoteConfig.settings = {
  minimumFetchIntervalMillis: 3600000,
};

remoteConfig.fetchAndActivate()
  .then(() => {
    doSomething();
  })
  .catch((err) => {
    console.error(err);
  });
```

**Comment by rommelpe** [comment] 2019-11-20 16:47
Thanks for your report. I was able to replicate this. I'll confirm internally to see if this is an intended behavior or bug (b/144839642), and I'll let you know once I have an update.

**Comment by kenkus-futurice** [comment] 2019-11-21 07:13
I forgot to mention that it works fine in Chrome private mode.

**Comment by Feiyang1** [comment] 2019-11-21 22:04
According to https://bugzilla.mozilla.org/show_bug.cgi?id=781982, indexeddb doesn't work in Firefox private mode and Remote config needs it to work.

The good news is that Firefox is working on enabling indexeddb in the private mode - https://bugzilla.mozilla.org/show_bug.cgi?id=1562669.

I will close the issue for now.

**Closed by Feiyang1** 2019-11-21 22:04 UTC
Labels: api: remoteconfig

**Comment by kenkus-futurice** [comment] 2019-11-25 06:54
Alright, probably then similar reason with IE11/Edge private mode.

Another problem is that this promise doesn't return anything when the error occurs:
``` javascript
firebase.remoteConfig().fetchAndActivate()
    .then((res) => {
      // This is not printed
      console.log(res)
    })
    .catch((err) => {
      // This is not printed
      console.error(err)
    })
    .finally(() => {
      // This is not printed
      console.log('finally')
    })
```
Is there some other way of "handling" this error?

**Comment by Feiyang1** [comment] 2019-11-26 00:38
Ah, good catch! Once https://github.com/firebase/firebase-js-sdk/pull/2381 is merged and released, you will be able to catch the error. 

For now, are you able to detect private mode and not initiate RC at all?

**Comment by kenkus-futurice** [comment] 2019-11-26 06:51
Thank you. Great news that you have already fixed this.
Probably I can do something (in IE11/Edge `window.indexedDB` seems to be `null`, in Firefox there are some hacks e.g. based on IndexedDB, but if I understood correctly the general direction is to make the browser APIs work also in private mode and make it harder to detect private mode in web apps) but perhaps I can wait until this fix is released.
