### ISSUE TITLE
getIdToken(true) doesnt always trigger onIdTokenChanged

### ISSUE THREAD

**Issue by Mattinton** [firebase/firebase-js-sdk#4955] opened 2021-05-29 17:37 UTC
### Describe your environment

  * Operating System version: macOS
  * Browser version: Latest Firefox
  * Firebase SDK version: 8.6.3
  * Firebase Product: auth

### Describe the problem

Hi, when updating an email I am using reload() in conjunction with getIdToken(true) to force an update to the current user by triggering onIdTokenChanged and display the new email throughout my app. The problem is that occassionally onIdTokenChanged is not getting triggered by getIdToken(true) and therefore my user is not being updated.

#### Steps to reproduce:

Using the below test case I am expecting to see
```
onIdTokenChanged current@email.com // initial startup
reload new@email.com
getIdToken new@email.com
onIdTokenChanged current@email.com // triggered from getIdToken
```

But occassionally but often enough to be noticeable I'm getting
```
onIdTokenChanged current@email.com // initial startup
reload new@email.com
getIdToken new@email.com
```

If I use a 500ms delay or more then that solves my problem but that adds an unnecessary delay which I would like to avoid.

#### Relevant Code:

This is the test case I'm using

```javascript
// update email triggered on form submit
const credential = EmailAuthProvider.credential(auth.currentUser.email, data.password);
await auth.currentUser.reauthenticateWithCredential(credential);
await auth.currentUser.updateEmail(data.email);
console.log('reload', auth.currentUser.email);
await auth.currentUser.reload();
console.log('getIdToken', auth.currentUser.email);
await auth.currentUser.getIdToken(true);

// global user listener
auth.onIdTokenChanged((user) => console.log('onIdTokenChanged', user?.email))
```

As a side note, is there a better/recommended way of triggering an onIdTokenChanged for things like updating the displayName and email

**Comment by looptheloop88** [comment] 2021-06-01 16:28
Hi @Mattinton, thanks for patiently waiting. I used the same code flow that you've provided and the SDK version, but I wasn't able to reproduce the behavior. The email was successfully updated and the `onIdTokenChanged` listener is getting called as expected.

If I can replicate the issue, I can have a better look into it. Please share a [minimal, but complete](https://stackoverflow.com/help/minimal-reproducible-example) sample of a project that I can run locally.

**Comment by Mattinton** [comment] 2021-06-01 18:23
Hi @looptheloop88 thanks for looking into this. I've spent a couple of hours setting up a basic react project that I think illustrates the problem. Here it is: https://github.com/Mattinton/on-id-token-changed-problem. If you use the button to update the email you will see that the 'User email' doesn't stay consistent, you may need to update the email a few times to see this happening.

Let me know if I'm using onIdTokenChanged wrong or if this is a genuine problem :)

**Comment by looptheloop88** [comment] 2021-06-02 15:50
Hi @Mattinton, thanks for sharing a sample project. However, I still wasn't able to reproduce the issue using it. I tried updating the email more than 20 times and the same values are displayed. It seems that the `onIdTokenChanged` is being triggered correctly.

**Comment by Mattinton** [comment] 2021-06-02 15:54
@looptheloop88 this is what I get after on changing the email once

<img width="365" alt="image" src="https://user-images.githubusercontent.com/23560873/120512273-1d25fd00-c3c3-11eb-81f7-3f37acfcb084.png">

As you can see there is a discrepency between the top email value and the other two.

**Comment by looptheloop88** [comment] 2021-06-02 18:45
Hi @Mattinton, here's the result from my testing:

<img width="211" alt="Screen Shot 2021-06-03 at 1 30 22 AM" src="https://user-images.githubusercontent.com/80330521/120535410-859dca00-c415-11eb-9ae7-65f7e999c8fb.png">
Have you tried using other browser like Google Chrome?

**Comment by Mattinton** [comment] 2021-06-02 18:51
Here is a gif of me testing it on chrome too. Could this be to do with the project? (not that theres anything odd about it)

![on-id-token-changed-issue](https://user-images.githubusercontent.com/23560873/120536214-c7118380-c3db-11eb-83c3-fbd0cbe770ab.gif)

**Comment by looptheloop88** [comment] 2021-06-03 15:29
Hi @Mattinton, here's a screen recording showing that all emails displayed were similar. I tried both Firefox and Chrome.



https://user-images.githubusercontent.com/80330521/120669626-35c90c80-c4c2-11eb-9550-574515d17c34.mov


You may want to try different projects or use other frameworks to isolate the possible cause.

**Comment by looptheloop88** [comment] 2021-06-08 13:50
Hi @Mattinton, I will be closing this issue now since it can't be reproduced consistently.

**Closed by looptheloop88** 2021-06-08 13:50 UTC
Labels: api: auth
