### ISSUE TITLE
https.OnCall CORS error

### ISSUE THREAD

**Issue by emagaram** [firebase/firebase-js-sdk#6182] opened 2022-04-27 10:23 UTC
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10 Home, 64-bit
  * Browser version: Occured in both Chrome (100.0.4896.127) and Firefox (99.0)
  * Firebase SDK version:  firebase-admin: "^10.0.2", "firebase-functions": "^3.11.0",
  * Firebase Product: Cloud Functions (auth, database, storage, etc)

One of my onCall cloud functions named auth-sendLinkToken was throwing a CORS error which was strange because earlier it wasn't and I hadn't modified the code **at all.** I redeployed it several times with a few modifications but with no luck. Then, after I copied the code into a brad new onCall function (just with a different name:sendLinkToken1 ), the CORS error disappeared. Then I decided to delete my original function from firebase (auth-sendLinkToken) and redeploy it and voila, the CORS error then disappeared even though there was no code change at all. Others have had this issue here: https://stackoverflow.com/questions/50278537/firebase-callable-function-cors

One user: "after spending several hours trying all the different solutions here, I deleted every function and redeployed them again and suddenly, they started working without any CORS issues."

#### Steps to reproduce:
Unsure how to reproduce
#### Relevant Code:

```javascript
// TODO(you): code here to reproduce the problem
```

**Comment by hsubox76** [comment] 2022-04-27 16:51
Thanks for reporting. It will be difficult to dig any deeper without knowing how to reproduce it and being able to figure out what conditions cause it.

The only useful information I can add is that often the functions SDK reports a CORS error when it's actually an error in the cloud function itself. I know it's not ideal error reporting but in this case the data received on the client side looks exactly the same whether there is a CORS error or whether the cloud function had an error when running, and we can only report what we received. The stackoverflow page also has a number of other cases where the root problem isn't CORS but the end result is a CORS error.

One thing that might help debug in the case that there was some error on the backend is looking at the functions logs in the Firebase console or Google Cloud Console, to see if the called function actually ran, errored, or maybe was never called (the backend thinks it never received a legit request). That might help narrow down at what step the problem happened.

**Comment by emagaram** [comment] 2022-04-27 19:05
The function was never reported to be called in the logs since I believe the browser was preventing the request from being sent. Sorry for leaving that important detail out. But since both Chrome and Firefox were giving CORS errors I don't think it's a bug in the browser, so likely with the frontend SDK.

**Comment by hsubox76** [comment] 2022-05-06 22:39
Sorry, now that I'm looking more carefully I see you specified `onCall()` so you believe it's a problem with the Functions SDK itself (the SDK that allows you to actually write functions in Node). So if that's the case, this is the repo for that: https://github.com/firebase/firebase-functions

The Firebase JS client SDK (this repo) only contains the code for the client side functions SDK which is basically just `httpsCallable()`.

**Comment by dereekb** [comment] 2022-05-21 04:04
I ran into this issue and was confused at first because I have another Firebase project without any CORS related issues.

Turns out the firebase functions were deployed private in my case. This bug report helped me find the following overflow question:

https://stackoverflow.com/questions/47511677/firebase-cloud-function-your-client-does-not-have-permission-to-get-url-200-fr

What you need to do is add "allUsers" as a principle with the Cloud Functions Invoker role.

<img width="1498" alt="Screen Shot 2022-05-20 at 11 01 27 PM" src="https://user-images.githubusercontent.com/3586580/169634628-d0d51f70-1358-41f5-802a-8d017e7dc9bc.png">

Once added, you can see the "Allow unauthenticated" component.

<img width="1374" alt="Screen Shot 2022-05-20 at 10 57 06 PM" src="https://user-images.githubusercontent.com/3586580/169634600-6fa1f6f7-1233-49dd-a5ae-24e3bf22a959.png">

This is ok since your Firebase function is going to check authentication anyways using Firebase.

Being unfamiliar with what pre-flight cors meant, I thought at first meant that no request was going out (thinking chrome had blocked the request), but actually with CORS requests it sends out request to check CORS status (which is where it is failing, because the server was returning a 403) and that initial request is the pre-flight request. 

That's why there are two requests stacked in the developer tools.

![Screen Shot 2022-05-20 at 10 59 30 PM](https://user-images.githubusercontent.com/3586580/169634571-7caeb8dc-893a-4ac5-89af-79015d7a0955.png)

And after making the change:

![Screen Shot 2022-05-20 at 11 02 41 PM](https://user-images.githubusercontent.com/3586580/169634654-4b10ca43-fa98-4274-9f6a-e54ea28e112e.png)

(The 500 error is something else happening, but the server executed it!)

**Comment by hsubox76** [comment] 2022-05-23 21:02
Closing now as this issue doesn't seem to involve any code in the client side SDK.

**Closed by hsubox76** 2022-05-23 21:02 UTC
Labels: api: functions
