### ISSUE TITLE
firestore.enablePersistence().catch is not catching exceptions

### ISSUE THREAD

**Issue by jamesdaniels** [firebase/firebase-js-sdk#608] opened 2018-03-30 21:53 UTC
### [REQUIRED] Describe your environment

  * Operating System version: any
  * Firebase SDK version: <= 4.12.1
  * Firebase Product: firestore

Any exceptions with enable persistence raise an uncaught exception, even if you attempt to catch on the Promise. 

#### Steps to reproduce:

Call in two tabs:

`firestore.enablePersistence().then(() => {}, () => {})`
or `firestore.enablePersistence().catch(() => {})`

You'll get an uncaught exception RE Firestore persistence already having been initialized. 

The exception should have be caught with the Promise's reject argument / catch method and not bubble up further, which raises an uncaught exception. Developers currently need to wrap in a try/catch which isn't great ergo. 

This hits us here: https://github.com/angular/angularfire2/blob/e343f137bd0ca9a1d958253b58104c64acbe3944/src/firestore/firestore.ts#L123

**Comment by mikelehen** [comment] 2018-05-29 06:03
I believe this is a dupe of https://github.com/firebase/firebase-js-sdk/issues/256 which we'll try to address soon-ish. :-)

**Closed by mikelehen** 2018-05-29 06:03 UTC
Labels: Component-Firestore
