### ISSUE TITLE
firestore js get() never fall back to catch when offline

### ISSUE THREAD

**Issue by mohshraim** [firebase/firebase-js-sdk#525] opened 2018-02-21 01:03 UTC
@mikelehen 

this a new ticket according to your request.

### [REQUIRED] Describe your environment

  * Operating System version: macOS High Sierra v.10.12.2
  * Firebase SDK version: v.4.9.1
  * Firebase Product: firestore
  * chrome Version 63.0.3239.132 (Official Build) (64-bit)

### [REQUIRED] Describe the problem
firestore js get() never fall back to catch when offline
console will show the following errors but never reach catch -i wait forever-

![screen shot 2018-02-21 at 2 54 25 am](https://user-images.githubusercontent.com/16401732/36457483-de3cdc14-16b2-11e8-9eed-48b7b15af36e.png)

#### Steps to reproduce:
html page with a getItems button.
disable wifi
click on getItems button
   
#### Relevant Code:

```javascript

 db = firebase.firestore();
function getItems() {
      console.log('getItems Started', new Date().toString());
     db.collection("item")
     .get()
     .then(function (querySnapshot) {
         querySnapshot.forEach(function (doc) {
             console.log(" data: ", doc.data());
             // console.log(doc.id, " => ", doc.data());
         });
     })
     .catch(function (error) {
         console.log("Error getting documents: ", error);
     });
 }
```
the same behaviour if i use firebase.firestore().enablePersistence() 

another strange behaviour...
-----------
-> reconnect the wifi
-> click on getItems button 
-> time will be printed --> no errors on console -> no data from server!!!
-> click on getItems button  second time
-> time will be printed --> no errors on console -> data back from server successfully!!

--> iam facing the same behaviour every time.. and on reconnect always the first get() ignored without any result..
this spanshot after reconnecting 

![screen shot 2018-02-21 at 2 55 52 am](https://user-images.githubusercontent.com/16401732/36457595-7c99f5a4-16b3-11e8-868b-052ddceb3f5e.png)

Thanks

**Comment by samtstern** [comment] 2018-02-21 01:44
@mohshraim just curious are you accessing Firestore within a service worker?

**Comment by larssn** [comment] 2018-02-21 14:33
> console will show the following errors but never reach catch -i wait forever-

I'm pretty sure that is expected behavior. The errors are handled internally in the JS framework, so they will never reach your `.catch`. What you are seeing is just the output (console.error()). The intention is that your client will not start throwing errors on bad internet connections. The user experience should be transparent, and the app should not be able to tell if there is no connection to the backend.

Hopefully someone will correct me if I'm wrong about that.

The "cannot connect to backend", might be an actual problem. I've seen it myself a few times.

**Comment by mohshraim** [comment] 2018-02-21 20:39
@samedson , no i didn't use service worker.
just direct use of firestore js library as mentioned above on code.

**Comment by samedson** [comment] 2018-02-21 20:41
@mohshraim did you mean @samtstern?

**Comment by mohshraim** [comment] 2018-02-21 20:42
yes... sorry

**Comment by mikelehen** [comment] 2018-02-21 21:58
Sorry for the confusion, but I think this is expected.

Can you add this inside your .then() ?

```
console.log('size:', querySnapshot.size, 'fromCache:', querySnapshot.metadata.fromCache);
```

You should be getting an empty snapshot, served from cache.

Note that if instead you call .get() for a single document (e.g. `firestore.doc('item/foo').get()`) while offline then your catch handler _would_ be called since we can't provide a DocumentSnapshot if we don't know if the document exists. This is why I thought this was a bug originally. I didn't realize you were calling .get() on a query (my bad).

FYI- We're working on adding a new feature so you can do `db.collection('item').get({source: 'server'})...` which will cause us to fail (and call your catch handler) if you are offline.

I'm closing this issue as expected, but let me know if I missed anything or anything is unclear. Thanks, and sorry again for the confusion.

**Closed by mikelehen** 2018-02-21 21:58 UTC
Labels: Component-Firestore

**Comment by mohshraim** [comment] 2018-02-21 22:24
Thanks @mikelehen 

no need to sorry...
that was very confusing..

now its clear to use the  `querySnapshot.metadata.fromCache`  as indicator for offline state when we use Get() on collection... and the catch when use Get() for document..

adding the new option will be great and give us more control to handle offline state through catch only..

Thanks

**Comment by Graig123git** [comment] 2019-02-07 04:36
is there any code example of using querySnapshot.metadata.fromCache with the get() function?

**Comment by mohshraim** [comment] 2019-02-07 19:08
https://firebase.google.com/docs/firestore/query-data/get-data


```
        var docRef = db.collection("cities").doc("SF");

// Valid options for source are 'server', 'cache', or
// 'default'. See https://firebase.google.com/docs/reference/js/firebase.firestore.GetOptions
// for more information.
var getOptions = {
    source: 'cache'
};
```

```
// Get a document, forcing the SDK to fetch from the offline cache.
docRef.get(getOptions).then(function(doc) {
    // Document was found in the cache. If no cached document exists,
    // an error will be returned to the 'catch' block below.
    console.log("Cached document data:", doc.data());
}).catch(function(error) {
    console.log("Error getting cached document:", error);
});
```

**Comment by Graig123git** [comment] 2019-02-07 20:01
Hi Mohammad,


Thanks for your reply. however specifying the source will just cause
firestore to pull from the cache immediately.

Maybe i did not explain my issue properly. So firestore by default is
design to retry read/write operation

if the first executed operation was not successful. In some case the use is
offline for extended period of time

and firestore keeps on retying the the same operation over and over again.
My final question is how

can i get firestore to stop retyring after a couple attempts (1 or 2 maybe)
and throw and exception that will

iniate my catch block. Please see my code below.



export const loadUserNotifications = () => async (dispatch) => {

let user = firebase.auth().currentUser;
let notificationsval = [];
if (user != null) {
let docRef = firebase.firestore().collection(`notification/${user.uid}
/notificationsdata`).where("seen", "==", "no")
docRef.onSnapshot({ includeMetadataChanges: true}, function (querySnapshot)
{
if (querySnapshot.metadata.fromCache === true) {
alert('offline check connectivity')
dispatch({ type: NOTIFICATION_COUNT, payload: { error: true, message: 'no
internet' } })
}
if (querySnapshot.metadata.fromCache === false) {

querySnapshot.forEach(function (doc) {
notificationsval.push(doc.data());
dispatch({ type: NOTIFICATION_COUNT, payload: { count: notificationsval.
length } })
})
notificationsval = []

}

}, err => {
console.log('failed: ', err);
dispatch({ type: NOTIFICATION_COUNT, payload: { error: true, message: err.
message } })
return
});
}


}

**Comment by Graig123git** [comment] 2019-02-07 22:31
How would I rewrite that code in a transaction I am pretty new to fire
store.

**Comment by Graig123git** [comment] 2019-02-07 22:38
And also firestore transaction requires you to do an update if your using
transaction. This is just a read operation which doesn’t involve any write
operation so why would I use a transaction. Is there a Bettet approach to
solve this problem?

**Comment by Graig123git** [comment] 2019-02-08 11:43
In reference to the same transaction
Document firestore transaction
Only return failure in the 3 cases below


   - The transaction contains read operations after write operations. Read
   operations must always come before any write operations.
   - The transaction read a document that was modified outside of the
   transaction. In this case, the transaction automatically runs again. The
   transaction is retried a finite number of times.
   -

   The transaction exceeded the maximum request size of 10 MiB.

   Transaction size depends on the sizes of documents and index entries
   modified by the transaction. For a delete operation, this includes the size
   of the target document and the sizes of the index entries deleted in
   response to the operation.

A failed transaction returns an error and does not write anything to the
database. You do not need to roll back the transaction; Cloud Firestore
does this automatically.
This didn’t explicitly state anything about offline. Can you guys provide
anymore clarification such as code examples or guidance towards a proper
solution?

**Comment by mikelehen** [comment] 2019-02-08 18:53
I'm not clear on what issue you are trying to solve.  If you're just trying to do a get() and have it fail when you're offline, then you can do `docRef.get({source: 'server'})` ?

**Comment by Graig123git** [comment] 2019-02-09 22:23
@mikelehen  i am using a onSnapshot not a get(). The issue  that i am trying to solve is that i need
firestore to initiate a catch block on a onSnapshot  listener  if a user is not connected to the internet.
in the following code above in my first comment my catch block is never reach if the user if offline. and i get the erorr with a red screen. Firestore (5.8.1): Could not reach Cloud Firestore backend. Backend didn't respond within 10 seconds.
This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.

Is this because firestore does not throw an error when there is no internet connection? how could
i get firestore to throw an error if there is no internet connection and intiate a catch block.
