### ISSUE TITLE
Module not found: Can't resolve 'encoding'

### ISSUE THREAD

**Issue by AlexBrasileiro** [firebase/firebase-js-sdk#7369] opened 2023-06-16 13:41 UTC
### Operating System

macOS

### Browser Version

Chrome

### Firebase SDK Version

^9.22.2

### Firebase SDK Product:

Functions

### Describe your project's tooling

NextJS 13

### Describe the problem

In development (local), in the NextJS logs, a warning appears (on the server side):

```log
Module not found: Can't resolve 'encoding' in '/node_modules/node-fetch/lib'

Import trace for requested module:
./node_modules/node-fetch/lib/index.js
./node_modules/@firebase/functions/dist/esm-node/index.node.esm.js
./node_modules/firebase/functions/dist/index.mjs
./src/utils/firebase.js
./src/components/Mailing.js
./src/components/Footer.js
```

### Steps and code to reproduce issue

The warning appears whenever you import Firebase from any file.

**firebase.js**

```js
import { initializeApp, getApps } from 'firebase/app';
import { getFunctions, connectFunctionsEmulator } from 'firebase/functions';

const config = {
  apiKey: "xxxxx",
  authDomain: "xxxxx",
  ...
};

const app = !getApps().length ? initializeApp(config) : getApps()[0];

let functions = getFunctions(app);

if (process.env.NODE_ENV === 'development') connectFunctionsEmulator(functions, 'localhost', '5001');

export {
  functions
};
```

**Comment by hsubox76** [comment] 2023-06-16 17:22
This is a duplicate of https://github.com/firebase/firebase-js-sdk/issues/7280. I modified the title of that one so it's easier to find.

**Closed by hsubox76** 2023-06-16 17:22 UTC
Labels: question, api: functions, v9

**Comment by AlexBrasileiro** [comment] 2023-06-18 17:39
@hsubox76 thanks!
