### ISSUE TITLE
[Firestore] ownerId null - precondition-failed another tab

### ISSUE THREAD

**Issue by markspolakovs** [firebase/firebase-js-sdk#511] opened 2018-02-14 14:33 UTC
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10 Fall Creators
  * Firebase SDK version: 4.9.1
  * Firebase Product: Firestore
  * Browser: Chrome 64.0.3282.140

### [REQUIRED] Describe the problem

Firestore gives a `precondition-failed` error "`There is another tab open with offline persistence enabled. Only one such tab is allowed at a time. The other tab must be closed or persistence must be disabled.`", despite not having any other tabs open, even after clearing all storage, including IndexedDB in Chrome's devtools.

#### Steps to reproduce:

Cannot reliably reproduce. Here is my console output:

```
error.js:149 Uncaught Error: There is another tab open with offline persistence enabled. Only one such tab is allowed at a time. The other tab must be closed or persistence must be disabled.
    at new FirestoreError (error.js:149)
    at indexeddb_persistence.js:201
    at persistence_promise.js:112
    at PersistencePromise../node_modules/@firebase/firestore/dist/esm/src/local/persistence_promise.js.PersistencePromise.wrapUserFunction (persistence_promise.js:98)
    at PersistencePromise../node_modules/@firebase/firestore/dist/esm/src/local/persistence_promise.js.PersistencePromise.wrapSuccess (persistence_promise.js:112)
    at PersistencePromise._this.nextCallback (persistence_promise.js:82)
    at persistence_promise.js:52
    at persistence_promise.js:112
    at PersistencePromise../node_modules/@firebase/firestore/dist/esm/src/local/persistence_promise.js.PersistencePromise.wrapUserFunction (persistence_promise.js:98)
    at PersistencePromise../node_modules/@firebase/firestore/dist/esm/src/local/persistence_promise.js.PersistencePromise.wrapSuccess (persistence_promise.js:112)
    at PersistencePromise../node_modules/@firebase/firestore/dist/esm/src/local/persistence_promise.js.PersistencePromise.next (persistence_promise.js:73)
    at PersistencePromise._this.nextCallback (persistence_promise.js:82)
    at persistence_promise.js:52
    at IDBRequest.request.onsuccess (simple_db.js:376)
```

From peeking at devtools, it looks like `dbOwner.ownerId` is null - this happens even after I delete the database in DevTools. Also, oddly enough, my `enablePersistence()` promise handler has a `catch()`, which does not get called.

Here is my code (from a React app with TypeScript):

```js
async componentDidMount() {
  firebase
    .firestore()
    .enablePersistence()
    .then(() => {
    this.loadOrders();
    })
    .catch(err => {
    console.log(err);
    if (err.code == "failed-precondition") {
        this.setState({
        error:
            "You have this app open in multiple tabs. Please only open it in one tab, and refresh to continue."
        });
    } else if (err.code == "unimplemented") {
        this.setState({
        error:
            "Your browser does not support offline."
        });
    }
    this.loadOrders();
    });
}
```

**Comment by mikelehen** [comment] 2018-02-21 22:29
Thanks for the report.  To ensure only a single tab uses offline persistence, we have an "owner lease" stored in IndexedDB.  The "owner tab" acquires the lease when it opens and then "refreshes" it every 4 seconds, which prevents any newly-opened tab from acquiring the lease (new tabs won't take the lease as long as it's been refreshed within the last 5 seconds).

From your report (in particular that your catch handler isn't being called) it sounds like perhaps your tab is acquiring the lease but then later loses it because another tab has managed to "steal" it. In general this shouldn't happen, but it could potentially happen if your tab was in the background and got throttled to the point that it could no longer refresh the owner lease, or something along those lines.

Does that sound like a possibility?  Any additional data you can provide about how / when this occurs (e.g. confirming that it happens after the tab has been in the background for a while) would be helpful.  Thanks!

**Comment by markspolakovs** [comment] 2018-02-26 21:20
Hey, sorry for my slow reply.

That does sound like a possibility - having Tab A open but in the background, opening Tab B, closing it, and going back to Tab A. But it should reacquire the lease after a refresh, no? And the thing that was **super weird** is that even after clearing all data in DevTools for that origin, it still could not reacquire the lease.

Either way, this is a super rare issue that I can't reliably repro, so sorry I can't be more helpful 😬 and thanks for looking into it anyway!

**Comment by mikelehen** [comment] 2018-02-28 00:19
cc/ @schmidt-sebastian who is reworking how our lease works...  In the future, the client won't require the lease to work and should be more resilient to losing it.

Clearing data in DevTools should have definitely allowed the lease to be reacquired though!  That's very strange.

In any case, I'm going to close this, but feel free to reopen if you manage to find a way to reproduce this as we're interested in better understanding the scenarios in which the lease can be lost. But like I said, we have some work in progress that should improve the situation.  Thanks for the feedback!

**Closed by mikelehen** 2018-02-28 00:19 UTC
Labels: Component-Firestore
