### ISSUE TITLE
Firestore Timestamp (Date) is sometimes stored as a Map

### ISSUE THREAD

**Issue by basvandenheuvel** [firebase/firebase-js-sdk#2507] opened 2020-01-08 12:25 UTC
* Operating System version: Windows 10
  * Browser version: Chrome 79
  * Firebase SDK version: 6.6.2
  * Firebase Product: Firestore

**Problem:**

When storing a Date in Firestore, it should be stored as a Timestamp which is shown as a Date in the Firebase Console (with type Timestamp). Example:
![image](https://user-images.githubusercontent.com/3515248/71977327-c7264780-3218-11ea-8eb2-409fb163c2e5.png)

However, in our project roughly 1 out of every 10.000 updates we do, the Date is stored wrong, it is shown as a type Map with two fields. Example:
![image](https://user-images.githubusercontent.com/3515248/71977655-a4486300-3219-11ea-9b76-09df2db44cce.png)

**Data used:**

The update object we use to update the document in the database  `{ date: new Date() }`.

**Comment by wu-hui** [comment] 2020-01-08 17:23
Hi basvandenheuvel,

Thanks for reporting this issue! 

From what you described, it sounds like something is reading a timestamp, and somehow it is converted to a object (JSON object for example), and then the converted object is written back.

Are you using some framework like React or Angular or Vue? Have you audited all places this data could be written from, maybe from back-end jobs?

It'd be really helpful if you can provide steps to re-produce this problem.

Thanks

**Comment by wu-hui** [comment] 2020-01-08 17:28
After discussing with my coworkers, this looks similar to two of our previous reporting:

https://github.com/firebase/firebase-js-sdk/issues/921
https://github.com/firebase/firebase-js-sdk/issues/1084

Both are caused by the web frameworks wrapping around Firestore SDK. You might want to check if it is the same cause.

Thanks.

**Comment by hsubox76** [comment] 2020-01-08 20:01
Actually I think https://github.com/firebase/firebase-js-sdk/issues/1084 looks like it might be caused by some kind of prod build optimization (in the user's project) that converts the Timestamp object into an object literal.

If it's happening in 1 out of 10,000 updates is it possible a very small number of users are using some environment or JS engine (old IE or other unusual browser?) that goes down such a code path?

**Comment by wu-hui** [comment] 2020-01-08 20:28
That is certainly possible, it might help if user could log the environment(browser, framework, etc) when updating timestamp, to see if it's all from the same environment.

**Comment by basvandenheuvel** [comment] 2020-01-09 12:22
Hi all,

Thanks for your answers. The code exists within our Ionic (3) app using Angular (5.2). 
All our users are using "the same version" of the application, by that i mean they all have the same version of Ionic, Firebase and Angular.

What @wu-hui mentions about the date being converted somehow to an object and being stored again sounds like one of the most logical explanations so far.. We will look into this possible problem.

**Comment by wu-hui** [comment] 2020-01-13 15:01
Closing the issue for now. You can ask to re-open if it turns out it is a Firestore bug after all.

**Closed by wu-hui** 2020-01-13 15:01 UTC
Labels: api: firestore, needs-attention
