### ISSUE TITLE
Firebase Tizen Web app support

### ISSUE THREAD

**Issue by sureshsu** [firebase/firebase-js-sdk#6551] opened 2022-08-23 11:54 UTC
[Uploading sample-firebase-app.zip…]()

Tizen webapp with Firebase analytics - Events are not received in the console.

### [REQUIRED] Describe your environment

  * Operating System version: Tizen 6.0
  * Browser version: Tizen Web app running in Tizen 6.0
  * Firebase SDK version: 9.9.3
  * Firebase Product: Analytics

### [REQUIRED] Describe the problem

Environment: Samsung Smart TVs
Firebase JS SDK when bundled with our Web app, analytics works properly in Tizen browser and other browsers (Chrome, etc).
However when the same app is packaged as Tizen Web app and loaded in Samsung Smart TV, firebase analytics events are not received on the firebase console. 

#### Steps to reproduce:

Package firebase web app with analytics as Tizen web app
Install it in Tizen Smart TVs and run the app

#### Relevant Code:

```javascript
Attached sample web app. This needs to be packaged as sample Tizen web app.
```

**Comment by hsubox76** [comment] 2022-08-24 17:21
It may be difficult to reproduce your Tizen setup on our end so can I ask you to make a similar test app that does not use Firebase but makes direct `gtag()` calls to the same measurementId and see if they have the same issue? (You'll have to check the backend data by looking at the Google Analytics dashboard and not the Firebase Console because if you don't use Firebase, it won't attach the Firebase installations ID and it may not show up in the Firebase Console.) https://developers.google.com/analytics/devguides/collection/gtagjs#:~:text=The%20Google%20tag%20(gtag.,a%20site%20for%20Google%20Analytics.

I'm asking because Firebase Analytics for Web is pretty much just a wrapper around gtag.js, and if gtag by itself doesn't work, there's no code we can change in the Firebase SDK to make it do so (and you'd have to contact the gtag team for support). But if gtag by itself does work, that means the issue lies with us.

**Comment by sureshsu** [comment] 2022-12-15 10:38
Limitation of Google Analytics to support for Tizen web app:
https://issuetracker.google.com/issues/231344514?pli=1
https://issuetracker.google.com/issues/174954288?pli=1

**Comment by DellaBitta** [comment] 2023-05-28 17:15
Hi @sureshsu, 

It looks like the Google Analytics team is tracking this issue in the links that you've provided. If this is the case then I think more information is to be found in those links that in this ticket, and we'll probably close this one as a duplicate. If not then please let us know.

Thanks!

**Closed** 2023-06-08 01:05 UTC
Labels: type: question, needs-info, no-recent-activity, api: analytics
