### ISSUE TITLE
Missing Peer Dependencies for Firebase 9 Beta

### ISSUE THREAD

**Issue by lschmierer** [firebase/firebase-js-sdk#4799] opened 2021-04-16 09:33 UTC
### [REQUIRED] Describe your environment

  * Operating System version: Windows 10 Pro (Build 19042), Node 14, NPM 6
  * Browser version: n/a
  * Firebase SDK version: 9.0.0-beta.1
  * Firebase Product: all

#### Steps to reproduce:
`npm i firebase@9.0.0-beta.1`

```javascript
npm WARN @firebase/firestore-compat@0.0.900-exp.894b5da5a requires a peer of @firebase/app@0.x but none is installed. You must install peer dependencies yourself.
npm WARN @firebase/storage-compat@0.0.900-exp.894b5da5a requires a peer of @firebase/app@0.x but none is installed. You must install peer dependencies yourself.
npm WARN @firebase/database-compat@0.0.900-exp.894b5da5a requires a peer of @firebase/app@0.x but none is installed. You must install peer dependencies yourself.
npm WARN @firebase/storage-types@0.4.0 requires a peer of @firebase/util@1.x but none is installed. You must install peer dependencies yourself.
```

**Comment by looptheloop88** [comment] 2021-04-16 11:47
Hi @lschmierer, thanks for the report. I was able to replicate the issue using SDK version `9.0.0-beta.1`.

This issue has been raised and discussed with the team. I will keep this thread posted for any updates.

**Comment by akauppi** [comment] 2021-04-16 20:05
Isn’t this a duplicate of https://github.com/firebase/firebase-js-sdk/issues/4789 - only mentioning that it also affects 9 beta.

**Comment by lschmierer** [comment] 2021-04-16 22:05
@akauppi  #4789 has an incorrect dependency warning while this is about missing missing peer dependencies.
#4789 appears to happen on npm@7 while this is on npm@7.

Npm@7 automatically installs peer dependencies while npm@6 doesn’t.

**Comment by Feiyang1** [comment] 2021-05-14 00:54
The warnings should be gone in `9.0.0-beta.2`.

**Closed by Feiyang1** 2021-05-14 00:54 UTC
Labels: api: core, type: bug, v9
