### ISSUE TITLE
After relinking Firebase project to analytics, get "The measurement ID in the local Firebase config does not match the measurement ID fetched from the server"

### ISSUE THREAD

**Issue by arcticmatt** [firebase/firebase-js-sdk#4291] opened 2021-01-14 06:18 UTC
### Describe your environment
  * Operating System version: macOS 10.15.2
  * Browser version: Chrome Version 87.0.4280.141 (Official Build) (x86_64)
  * Firebase SDK version: 8.2.1
  * Firebase Product: Analytics

### Describe the problem
I unlinked and relinked Analytics from my project more than once following [these instructions](https://support.google.com/analytics/answer/9289234?authuser=0). Each time I relink, the Firebase console shows me a new `measurementId`. 

However, when I try to use the new `measurementId` in my Firebase config, I see this error in the console:
```
@firebase/analytics: The measurement ID in the local Firebase config (G-foobar) does not match the measurement ID fetched from the server (G-helloworld). To ensure analytics events are always sent to the correct Analytics property, update the measurement ID field in the local config or remove it from the local config.
```

The former ID is the ID I see in the Firebase console. The latter ID is the original `measurementId` before I unlinked and relinked. Based on this, it seems like the `measurementId` fetched automatically from the server is out-of-date and does not respect unlinking and relinking to analytics.

Note that I originally unlinked Analytics from Firebase because I wanted to configure enhanced measurements, but was unable to. https://stackoverflow.com/questions/63816141/how-can-i-configure-enhanced-measurements-for-a-google-analytics-app-web-prop describes the issue I was hitting. The fact that data is still going to the old `measurementId`, while a bug, also happens to solve this problem. That is, after unlinking, I can configure enhanced measurements (you can't do this when it's linked), and since data still goes to the old `measurementId`, those changes take effect.

#### Steps to reproduce:
Described above.

#### Relevant Code:

I'm basically doing something like this:
```
const firebaseConfig = {...};
firebase.initializeApp(firebaseConfig);
firebase.analytics();
```

Once default events like `page_view` start getting logged (which I see in the console since I'm using the [Google Analytics Debugger](https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna?hl=en) extension), I see the aforementioned error in the console.

**Comment by arcticmatt** [comment] 2021-01-14 06:34
Here's some more evidence that something screwy is going on with unlinking and relinking. Every time I unlink and relink, a new "property" is created under my Google Analytics account. I can see in the debug view for an old property that my data is still being logged there, since my code thinks it should be using an old `measurementId`. However, the logs don't show up in the Firebase debug view, because that view is for the new `measurementId`.

**Comment by hsubox76** [comment] 2021-01-14 17:48
Created an internal bug b/177555355 for the team that controls the dynamic config endpoint.

In the meantime, how long do you wait after relinking? I wonder if there's a delay for the dynamic config backend (that serves the fetched config) to update, after you relink.

**Comment by arcticmatt** [comment] 2021-01-14 18:07
@hsubox76 I was wondering if waiting would fix it, but it looks like it didn't. I tried again just now and am still seeing the same error. It's been 10+ hours since relinking. 

Also just to clarify, is the bug you filed for the issue where you can't edit the stream configuration?
![image](https://user-images.githubusercontent.com/4356178/104630865-3c103680-5650-11eb-9772-c26eefe7c154.png)

**Comment by hsubox76** [comment] 2021-01-14 18:53
I think that UI is intentional but it is out of scope of this repo.

The bug I filed is for the exact issue you brought up originally, which is that whatever populates the measurementId in the object fetched by the dynamic config fetch call is not updating when you unlink and relink a Google Analytics account. I referenced this issue.

**Comment by arcticmatt** [comment] 2021-01-14 19:39
Ah gotcha, thanks. Do you know where would be a good place to report a bug for the other issue (the one I screenshotted)? It prevents me from configuring enhanced measurements when Firebase is linked.

**Comment by arcticmatt** [comment] 2021-01-14 19:46
I just tried it again, and now it works! The behavior still seems buggy if you have to wait this long though. 

Unfortunately, this also means that my enhanced measurements are no longer working as I'd like them to, since they're going to the property whose stream configurations are locked down (see screenshot above). So... actually, it was kinda nice to have the buggy behavior, because I could look at the Debug View in Google Analytics instead of Firebase and was able to edit the stream configurations. Oh well.

**Comment by rromanchuk** [comment] 2021-04-05 19:50
should i just be using g4 web datastream?  I dont understand the firebase web data stream. It wants to redirect back to firebase, but where are all the configuration settings like  Enhanced measurement, Measurement Protocol API secrets, connected site tags, etc? I'm not using the `firebase` client to log events on web, so can i just kill `firebase.analytics();` and use a measurement id of g4 web data stream.

**Comment by csaicharan** [comment] 2021-04-15 10:44
The issue is not only with Google Analytics, The performance metrics and traces were also logged under the MesurementId fetched from the server instead of local.

**Comment by AadamZ5** [comment] 2021-09-13 21:21
I just ran into OP's issue as well. @arcticmatt, what were the steps you took to resolve this issue, or was it a random success? 

Seems frustrating that there is no way to update the `webConfig` object that gets passed to the front end. I can see in the network inspector that it is sending the old measurement ID, and I'm getting the same error in the console. Additionally, using the archaic [Google Analytics Debugger](https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna), I can see it posting events to the old measurement ID as well. However, Firebase console lists the new measurement ID in the configuration it generates for my app. 

What is the purpose of using a firebase config option if the `webConfig` enpoint ( at `https://firebase.googleapis.com/v1alpha/projects/-/apps/[your]:[app]:[id]:[here]/webConfig` ) is going to overwrite it? The returned web config overwrites everything I specified in my firebase config file except the `apiKey`. Head scratcher...

@hsubox76 Any update on the status of the internal bug?

**Comment by hsubox76** [comment] 2021-09-14 16:41
It sounds like in his case there was just a delay in updating.

Setting the measurement ID from the local config is only used as a backup if the dynamic config cannot be fetched. The dynamic config is intended to be the main source of truth. The reasoning behind this decision was that the Firebase project's measurement ID may change due to moving streams, or linking and unlinking them, and that someone doing so on the backend shouldn't require any changes in the front end code.

How long has it been since you unlinked/relinked and if you're able to get it working again, how long after was it? If there is a delay, and I can get an idea of how long it is, I can report it on the internal bug and try to get a response again.

**Comment by AadamZ5** [comment] 2021-09-14 17:46
@hsubox76 
> How long has it been since you unlinked/relinked and if you're able to get it working again, how long after was it? If there is a delay, and I can get an idea of how long it is, I can report it on the internal bug and try to get a response again.

The `webConfig` endpoint seems to be sending the updated measurement ID now, but I'm not sure of exactly when that changed. I obsessively checked until about an hour and a half after I changed it, so I guess we'd assume the update happened sometime within 1.5 to 20 hrs. after the relinking. I did unlink and relink multiple times, and it now has updated to the correct one even after the multiple relinks, so I think this is working correctly, albeit a bit slower than I expected. 

You mentioned documentation about this delay (if it isn't a bug), and I think that would be awesome. I think the best approach would be some sort of notification on the UI about a possible discrepancy, but I think that the UI is not in this particular issue's scope. 

Thanks for your speedy reply! Let me know if any other info would be useful.

**Comment by luisfelipesd** [comment] 2021-09-17 02:33
I have the same issue now. Its been 10 hours and i still get the error what am I supposed to do?

**Comment by hsubox76** [comment] 2021-09-17 16:54
It seemed to take about a day for the other two people that reported it, so let me know if it doesn't fix itself within a day. I'll try to talk to the team that handles dynamic config and see if I can get any clarity on if this is intended behavior. It'll be good if I can gather as much info as possible on roughly how long the delay seems to be.

**Comment by luisfelipesd** [comment] 2021-09-17 17:28
yeah it took a day. it is working now. thank you @hsubox76

**Comment by hsubox76** [comment] 2021-09-20 23:33
It looks like a 24 hour delay is standard. I'll try to find a way to add this to our documentation so no one else is taken by surprise.

**Comment by DustinJSilk** [comment] 2021-09-23 08:44
I've hit this same issue now, going on 17 hours now and still not working. 
Glad to see it'll come right in a few hours time.

**Comment by emmalearnscode** [comment] 2021-11-08 16:05
I added analytics to a firebase project about 8 hours ago and I'm getting a similar issue, except it's not had analytics before so there's no old measurement id stored.
<img width="361" alt="Screenshot 2021-11-08 161604" src="https://user-images.githubusercontent.com/57045550/140775954-0a007e65-5c08-4a5c-a5db-d0038edda1b6.png">

Would be nice if the documentation mentioned this problem as it's a whole day wasted trying to debug this.

**Comment by hsubox76** [comment] 2021-11-08 17:45
We're working on getting it added to documentation somewhere, thanks for alerting us to the additional case (no analytics, then linked it later).

**Comment by hsubox76** [comment] 2021-12-13 18:07
Added a note to the documentation here under "Link your Firebase project to Analytics": https://support.google.com/analytics/answer/9289234

**Comment by wilburt** [comment] 2021-12-25 16:55
> Added a note to the documentation here under "Link your Firebase project to Analytics": https://support.google.com/analytics/answer/9289234

@hsubox76 Please, can this also be added to the [setup guide on Firebase](https://firebase.google.com/docs/analytics/get-started?platform=web#before_you_begin)? Wasted a couple of hours head-scratching until I landed here. MIne was a first-time setup.

**Comment by hsubox76** [comment] 2022-03-25 18:20
For people having trouble with a delay on a "first-time setup", can you describe the steps you took? Did you enable analytics when creating the project and still see a delay, or did you not initially enable analytics on your project, and then enabled it after the project had already been created, and then you saw a delay? Did you use the automatically provided measurement ID or did you link another measurement ID?

Just want to be clear so the documentation changes will be accurate. Thanks.

**Comment by hsubox76** [comment] 2022-07-12 17:12
Closing this, if anyone is having problems with a delay on a "first-time setup", if you can answer the questions in the comment directly above, I will update the documentation as needed or reopen this to make any fixes if needed. Thanks.

**Closed by hsubox76** 2022-07-12 17:12 UTC
Labels: api: analytics
