### ISSUE TITLE
Nested arrays

### ISSUE THREAD

**Issue by notsonotso** [firebase/firebase-js-sdk#231] opened 2017-10-17 18:29 UTC
Porting a Realtime Database to firestore is proving difficult because it's not possible store nested arrays.

We consider this a serious flaw and a show stopper.

**Comment by mmlleevvyy** [comment] 2017-10-19 15:27
Duplicate of #193

**Comment by jshcrowthe** [comment] 2017-10-19 15:34
Thanks @mmlleevvyy :) closing in favor of the mentioned issue

**Closed by jshcrowthe** 2017-10-19 15:34 UTC
Labels: needs-triage
