### ISSUE TITLE
Performance Monitoring: SDK installation crashes in Edge InPrivate

### ISSUE THREAD

**Issue by polamjag** [firebase/firebase-js-sdk#1933] opened 2019-07-01 10:30 UTC
### Describe your environment

  * Operating System version: Windows 10 Pro (version 1809, build 17763.557)
  * Browser version:  Microsoft Edge 44.17763.1.0 (Microsoft EdgeHTML 18.17763)
  * Firebase SDK version: 6.2.4
  * Firebase Product: performance

#### Steps to reproduce:

1. Install Firebase Performance Monitoring SDK to web page
1. Open the web page with Microsoft Edge in InPrivate browsing
1. SDK Initialization will crash because IndexedDB's apis are `undefined` in Edge's InPrivate mode
    - It's known problem and confirmed by Edge team: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/9968399/
        - Microsoft is replacing EdgeHTML with Blink, however I'd like to avoid crashing because I think EdgeHTML-based browser may remain for a certain period

#### Relevant Code:

https://stackblitz.com/edit/firebase-issue-sandbox-dznogg 
https://firebase-issue-sandbox-dznogg.stackblitz.io

Screenshot on Edge: IDBIndex is referenced while it's not defined,  and JavaScript execution doesn't reaches to `console.log('foobar');`:

![20190701191001](https://user-images.githubusercontent.com/685936/60428739-8085de00-9c34-11e9-966d-a3a39e7d2566.png)

It just works as expected on Chrome: 

<img width="963" alt="scr 2019-07-01 at 19 09 02" src="https://user-images.githubusercontent.com/685936/60428522-f3db2000-9c33-11e9-85d2-fff3001d6003.png">

**Comment by mmermerkaya** [comment] 2019-07-01 11:55
Duplicate of #1774.

**Closed by mmermerkaya** 2019-07-01 11:55 UTC
Labels: needs-triage
