### ISSUE TITLE
FR: plans for auth MFA with TOTP or WebAuthn?

### ISSUE THREAD

**Issue by wvanderdeijl** [firebase/firebase-js-sdk#4301] opened 2021-01-15 18:45 UTC
### Describe your environment

  * Operating System version: any
  * Browser version: any
  * Firebase SDK version: 8.2.3
  * Firebase Product: auth (auth, database, storage, etc)

### Describe the problem

It is great that Multi factor auth is supported with SMS, but this is not considered to be the most secure way of MFA. We are embarking on a sensitive project and are wondering if time based one time passwords (TOTP) or WebAuthn with physical tokens are on the roadmap as MFA methods for Firebase Auth (and Google Cloud Indentity Platform)

**Comment by wvanderdeijl** [comment] 2021-01-15 20:40
Sorry. I tried searching for TOTP issues and couldn’t find any. After filing this issue I found #2123 requesting WebAuthn. 
when thinking about WebAuthn please also consider TOTP

**Comment by AminAtwi-ITXI** [comment] 2021-10-29 23:32
+1

**Comment by Ivstiv** [comment] 2021-11-22 15:23
+1

**Comment by theiliad** [comment] 2022-07-04 16:24
+100000000

**Comment by johnozbay** [comment] 2022-07-28 06:28
Some good news from 2 days ago: 
https://firebase.blog/posts/2022/07/new-firebase-auth-features

**Comment by akauppi** [comment] 2022-07-28 15:35
Duplicate of https://github.com/firebase/firebase-js-sdk/issues/2123 or the other way round?

**Comment by tianhuil** [comment] 2023-09-26 17:47
It looks like Firebase finally added this: https://firebase.google.com/docs/auth/web/totp-mfa

**Comment by Xiaoshouzi-gh** [comment] 2023-10-02 03:43
TOTP MFA support is released to public, resolving this issue.

**Closed by Xiaoshouzi-gh** 2023-10-02 03:43 UTC
Labels: api: auth, feature request
