### ISSUE TITLE
Firestore: Support for large offline collections

### ISSUE THREAD

**Issue by adammeyer** [firebase/firebase-js-sdk#2591] opened 2020-02-03 15:03 UTC
* Operating System version: Mac
  * Browser version:  Chromium 73
  * Firebase SDK version: 7.8.0
  * Firebase Product: Firestore

### [REQUIRED] Describe the problem

When using offline persistence, the browser locks up if many records were modified since last load.

#### Steps to reproduce:
- Launch web app
- Enable offline persistence
- Add 3,500 (or more) documents to Firestore
- Close app
- Delete those 3,500 documents from admin console (or another app, browser or computer)
- Relaunch web app (in original browser) and retrieve docs `collection().get()`
- Browser becomes unresponsive

Sometimes the browser become responsive again and all data will be correct, but that can take > 30 seconds sometimes.

**To fix** I simply delete the Firestore IndexedDB and reload the app, all is good until another large amount of docs are modified or deleted.  This isn't an issue with the amount of docs in a collection, it's an issue with how the offline persistence "syncs" a large amount of changes.

Please advise if anyone has a workaround or solution.

**Comment by schmidt-sebastian** [comment] 2020-02-03 17:25
@adammeyer Thanks for filing this issue! We are aware that there is room for improvement when it comes to our IndexedDB performance and are constantly looking at ways to continue to improve this situation. 

Unfortunately, there are no short term fixes: Most of the perceived slowness is coming from the fact that loading data from IndexedDB is very slow and that our main query processing logic currently loads all documents in a collection to guarantee cache-coherent results.

For now, I would suggest that your modify your usage of Firestore to better fit our query implementation:
- You should only load as much data as needed.
- You should use a larger number of small collections, rather than putting a lot of data into a single collection.
- You should re-use queries. Queries that are executed frequently perform much better as of v7.5.0.
- You can reduce the cache size via [cachesizebytes](https://firebase.google.com/docs/reference/js/firebase.firestore.Settings.html#cachesizebytes)

I hope that these suggestions solve some of your pain points.

**Comment by schmidt-sebastian** [comment] 2020-02-03 18:07
Follow up: My colleague pointed out that you may hit an additional code path that could slow you down. Every time a document is deleted remotely but still available locally, the SDK performs something that we call "limbo resolution". This is an explicit lookup that the SDK performs to bring cached data in sync with the server. In your case, after we processed 3500 items from the cached collection, this likely means that the SDK issues 3500 individual read requests to update its cache. We will discuss internally if there is a short term fix for at least this part of the problem.

**Comment by adammeyer** [comment] 2020-02-03 18:44
Thank you @schmidt-sebastian!

One thing I have noticed is that after docs have been deleted or modified and the app reloaded, the `onSnapshot` listener fires an "added" event, then a "removed"/"modified" event for every doc.  This may be causing unnecessary queries/lookups.

**Comment by schmidt-sebastian** [comment] 2020-02-03 19:10
The "added" event is fired because the first snapshot is served from cache. Once we have computed the first snapshot and received the response from the server, we know that our state is inconsistent with the backend. To resolve this, we issue individual listen requests. As this finish one by one, we will update the snapshot that we raised originally. So over time you will see a "remove" event for every document until our local cache is once again synced with the backend (`[SnaphshotMetadata.fromCache](https://firebase.google.com/docs/reference/js/firebase.firestore.SnapshotMetadata.html#fromcache)` will be `false`).

**Comment by adammeyer** [comment] 2020-02-03 19:21
Got it, thanks.

I don't mind if the "get" after large modification or deletions take a long time.  But is there any way to get a status or count  so I can build some type of progress bar?  And for the process to not lock up the browser?  Could I use set a limit and do things in batches?  Thank you.

**Comment by cmditch** [comment] 2020-04-28 06:12
Indeed @adammeyer a status or count would be nice, for either a progress bar or the "wipe indexedDB + reload" hack you mentioned.

**Comment by cmditch** [comment] 2020-04-28 06:16
@schmidt-sebastian here are some interesting discoveries we've made, in case your dev team is unaware of this behavior. 

We've noticed that the "browser hang" increases linearly with both the length of the document path and the number of documents in a given collection.

The latter is unsurprising based on the info you've provided above, but the doc path behavior is pretty interesting.

e.g. Updates made to `/this/is/three/collections/deep/{id}` freezes our application three times as long as `/shallowDocs/{id}`.

Hope you find this useful. Cheers.

**Comment by schmidt-sebastian** [comment] 2020-04-28 17:57
@cmditch That's very interesting. I will investigate.

**Comment by schmidt-sebastian** [comment] 2020-04-28 18:57
@cmditch I don't see any statically relevant difference in a quick test: https://gist.github.com/schmidt-sebastian/d2bc9e77becaf8b75359407d744fd0c7

Some questions for you:
- Do you have persistence enabled?
- What browser are you testing on?
- Are there documents at ` /this/is/three/collections/deep/{id}`? Does this reproduce if you invoke `clearPersistence()`?

**Comment by adammeyer** [comment] 2020-05-17 12:45
Happy to help here, what other information can I provide?

**Comment by schmidt-sebastian** [comment] 2020-05-18 18:02
@adammeyer Do you mind answering the questions in https://github.com/firebase/firebase-js-sdk/issues/2591#issuecomment-620794082? Thank you1

**Comment by burtonator** [comment] 2020-10-24 18:21
Can I advise the Firestore team to prioritize this please ? this is really killing us and has been sort of a major problem for a long time now.  

Most of our queries are for collection +id and these at *least* should come from the cache instantly since you can map to the exact document.

**Comment by burtonator** [comment] 2020-11-11 01:14
Would it be possible to get an ETA for this.  Or at least let us know if it's on the short term agenda?  

This is becoming a serious blocker for our app and I'm considering writing our own persistence layer with indexes to solve this problem.

Our indexes aren't super complicated so we should be able to build this out well and get better performance.

... but would love to be lazy and have you guys fix it!  We're also willing to be guinea pigs if you have something in the works.  

Our app (getpolarized.io) is trying to really leverage offline snapshots so the user can work offline or online (including on mobile) and the cache performance for larger datasets just falls over.   

I'm burton at getpolarized  if you'd like to reach out directly.

**Comment by schmidt-sebastian** [comment] 2020-11-11 20:12
While we are considering prioritizing "offline first" usage for 2021, no decision has been made and there is no ETA.

**Comment by burtonator** [comment] 2020-11-12 00:11
@schmidt-sebastian Thanks!  This helps a lot and helps us prioritize.

One thing I'd like to point out is that I think offline-first could be THE killer feature for firestore and might really help with growth.

When I first saw that you guys had offline snapshots I was super excited and was even ok with 'offline-tolerant' but finding out that no indexes were used and that performance was bad was really a big hit on our development plans.  

It's sort of hidden that the performance is bad and really only acceptable for smaller apps.  

The snapshot API for Firestore is really amazing to work with and offline cache WITH indexes would really really be amazing.  

I'll be holding my breath in the mean time so no pressure :)

**Comment by burtonator** [comment] 2021-01-13 16:10
@schmidt-sebastian any update on this?  This is by far the biggest bug/issue we have in firestore.

**Comment by schmidt-sebastian** [comment] 2021-01-13 17:00
This is an enormous undertaking. We don't have an ETA.

**Comment by burtonator** [comment] 2021-01-13 22:19
I think I have a basic/simple API for this and will try to publish the code. 

My idea is to create a wrapper for the snapshot APIs but use a key factory and save to the store directly.  

It's a limited API vs what you guys expose but might work well for some people.

I think in your situation the paths are sort of the main problem.  And the indexes.  We're just going to build our own simple indexes.

**Comment by burtonator** [comment] 2021-11-20 23:07
Nearly a year later.  Can we get an update on this?

This is critical for us and basically (by far) the biggest negative to using Firestore for us.

Performance is critical. 

I'll either have to completely rewrite our data to function from our *own* cache or I have to migrate to something like:

https://replicache.dev/

We've made some design tradeoff due to this which aren't super fun including storing blobs in GCS but they don't participate in transactions like in Firestore.  

This puts just an absolutely massive burden on us and it might just be easier to migrate away from Firestore rather than implement things from the ground up.

**Comment by schmidt-sebastian** [comment] 2021-11-22 16:21
We are wrapping up our Indexing implementation for the Android SDK and hope to be able to release an experimental version soon. We will then start porting this implementation to iOS and Web. Unfortunately, I am not able to predict a release date.

**Comment by samcorcos** [comment] 2022-11-13 22:53
Hey @schmidt-sebastian is there anything we can do to support to get this over the finish line? I'm happy to contribute dev resources / money :) This will be blocking for us in ~6 months. We're using the web version of Firebase.

**Comment by schmidt-sebastian** [comment] 2022-11-14 00:56
cc @ehsannas

**Comment by ehsannas** [comment] 2022-11-16 20:11
Hey @samcorcos . We've released the _early preview_ of Client-Side Indexing (https://firebase.google.com/docs/firestore/manage-data/enable-offline#configure_offline_query_indexes). Please give it a try and we'd love to hear your feedback.

**Comment by jbalidiong** [comment] 2023-02-02 08:52
Hi @samcorcos, looks like the main issue has been resolved. I'll be closing this issue now. If you encounter another issue, feel free to create a new one.

**Closed by jbalidiong** 2023-02-02 08:52 UTC
Labels: api: firestore, type: feature request
