### ISSUE TITLE
Object are not valid as a React child

### ISSUE THREAD

**Issue by miteshsavani** [firebase/firebase-js-sdk#908] opened 2018-06-06 15:47 UTC
Not able to use latest version 5.0.4. I am getting error while using it

![image](https://user-images.githubusercontent.com/19145166/41049626-fb6e38cc-69ce-11e8-9ee9-2ba3a1bde4a2.png)

**Comment by puf** [comment] 2018-06-07 03:08
Same error with code (but unfortunately no accepted answer yet): https://stackoverflow.com/questions/50730706/objects-are-not-valid-as-react-child-react-native

**Comment by MidorikawaShun** [comment] 2018-06-07 17:30
This happens to me too. Only way to get around it is installing 5.0.3

**Comment by adisai123** [comment] 2018-06-13 17:38
I am also getting the same error, but if I run it over debug mode, it works properly.

**Comment by willianlouzefonseca** [comment] 2018-06-13 21:15
I just install the version 4.6.2 of firebase, this works for me

**Comment by AilsonFreire** [comment] 2018-06-21 15:34
A got the same error here is a link that solved this problem. But I think this solution is ugly cause I like to put firebase config in a separate file. So I dowgrade to 5.0.3 and it´s works

https://stackoverflow.com/questions/50555275/react-native-objects-are-not-valid-as-a-react-child-found-object-with-keys

**Comment by jshcrowthe** [comment] 2018-06-29 18:02
Duplicate of #871

**Closed by jshcrowthe** 2018-06-29 18:02 UTC
Labels: needs-triage

**Comment by Daniyal-Najeeb** [comment] 2018-10-01 15:54
Try this, this work for me and I am using firebase version 5.5.2
import firebase from '@firebase/app'
import '@firebase/auth'

**Comment by brianandreasen1983** [comment] 2018-10-19 17:32
> Try this, this work for me and I am using firebase version 5.5.2
> import firebase from '@firebase/app'
> import '@firebase/auth'

This works like a charm thank you Daniyal-Najeeb. :)

**Comment by tuanluu-agilityio** [comment] 2018-11-06 14:52
> Try this, this work for me and I am using firebase version 5.5.2
> import firebase from '@firebase/app'
> import '@firebase/auth'

It works fine for me. Save my life 💯 🙇

**Comment by presencewebdesign** [comment] 2018-11-20 13:46
I changed this line 

import firebase from 'firebase'; 

to this 

import firebase from '@firebase/app'

**Comment by changx03** [comment] 2018-12-04 00:20
> Try this, this work for me and I am using firebase version 5.5.2
> import firebase from '@firebase/app'
> import '@firebase/auth'
Tested on firebase Version 5.6.0
Works fine 👍

I wonder why import '@firebase/auth'?

**Comment by 24HourDeveloper** [comment] 2018-12-05 16:42
Hi I'm running version 5.5.9 in my react-native app and I used this to get it to work.
import firebase from '@firebase/app';
I wonder why in some of my apps I didn't have to do this.

**Comment by bopaiah** [comment] 2019-01-22 17:14
import core-js  in index.js seem to fix the problem for me.

import 'core-js';
import {AppRegistry} from 'react-native';

**Comment by aldarisbm** [comment] 2019-01-22 22:10
> import core-js in index.js seem to fix the problem for me.

This didn't work for me, I installed 5.0.3

**Comment by rajeevrocker7** [comment] 2019-01-30 06:48
I solved it 👍 

1. cleaning builds
2. change in package.json-> "firebase": "^5.5.2",
3. npm install

Now, you'll need to import all the parts for Firebase that you're using.
I was using Auth, Storage and Database. 
So I had to add:

4.
change this--> // import firebase from 'firebase';
to this-->
import firebase from '@firebase/app';
import '@firebase/auth';
import "@firebase/database";

5. run on device (react-native run-android)

:) 💯

**Comment by nkorojoseph** [comment] 2019-03-03 14:50
> I solved it 👍
> 
> 1. cleaning builds
> 2. change in package.json-> "firebase": "^5.5.2",
> 3. npm install
> 
> Now, you'll need to import all the parts for Firebase that you're using.
> I was using Auth and Database. and Of course, firebase.initializeApp(config);
> So I had to add:
> 
> 
> change this--> // import firebase from 'firebase';
> to this-->
> import firebase from '@firebase/app';
> import '@firebase/auth';
> import "@firebase/database";
> 
> 1. run on device (react-native run-android)
> 
> :) 💯

without additional process,

i just used the 
`import '@firebase/database'` and it worked.

thanks

**Comment by MaximWuyts** [comment] 2019-03-07 08:27
Make sure you import React without {} 
![image](https://user-images.githubusercontent.com/32163906/53942440-0ba5fb80-40bb-11e9-8e84-b38224190ff6.png)

**Comment by Mahi-Uddin** [comment] 2019-03-08 03:56
> import core-js in index.js seem to fix the problem for me.
> 
> import 'core-js';
> import {AppRegistry} from 'react-native';

Thanks, it worked for me :)

**Comment by presencewebdesign** [comment] 2019-03-08 14:01
Again had the same error, I am now using version ^5.8.5

Remove any instance of the import if you're not using it in my case it was in the App.js 

import fire from '../config/firebase';
