### ISSUE TITLE
Can't connect to local Firestore emulator

### ISSUE THREAD

**Issue by nfarina** [firebase/firebase-js-sdk#1721] opened 2019-04-24 18:44 UTC
### Describe your environment

  * Operating System version: macOS 10.14.4
  * Browser version: Chrome 73.0.3683.103
  * Firebase SDK version: 5.10.0
  * Firebase Product: firestore

### Describe the problem

Sorry to open an issue for this, I really did try to solve it myself!

I'm attempting to test my web application components locally in [Storybook](https://storybook.js.org). My app uses Firestore on the backend.

I'd like my components to load data from the [Firestore Emulator](https://firebase.google.com/docs/firestore/security/test-rules-emulator) while running in Storybook.

I'm configuring Firestore and asking it to connect to localhost on port 8080 without SSL (see code below) but I'm getting this error in the browser:

```sh
[2019-04-24T18:31:48.971Z]  @firebase/firestore: Firestore (5.10.0): Could not reach Cloud Firestore backend. Backend didn't respond within 10 seconds. [snip]
```

Note that the same emulator works fantastically for my Node-based unit tests which read/write data to it.

#### Steps to reproduce:

  1. [Setup and start the local emulator](https://firebase.google.com/docs/firestore/security/test-rules-emulator)
  2. Write client code to connect to it (see below).

#### Relevant Code:

```typescript
    import firebase from 'firebase/app';
    import 'firebase/firestore';

    const projectId = "test-" + Date.now();

    const app = initializeApp({ projectId });

    app.firestore().settings({
      host: "http://localhost:8080",
      ssl: false,
    });

    // Try saving some data.
    app.firestore().doc("posts/post1").set({title: "First Post"});
```

**Comment by samtstern** [comment] 2019-04-24 19:03
@nfarina right now the Firebase Web SDK running in a browser cannot connect to the Firestore emulator because the emulator only speaks gRPC (used by Android, iOS, and others) but not WebChannel (something we only use in the Web SDK).

Are you running this test from a browser or from a `node` process?

**Comment by samtstern** [comment] 2019-04-24 19:04
Oh wait I see:
> but I'm getting this error in the browser:

In that case this is the intended behavior right now.  We do plan to add WebChannel support to the emulators one day (cc @ryanpbrewster) but it's probably a little ways off.

I am going to close this issue since there is nothing that will be done within the JS SDK to address this.  Thank you for your feedback!

**Closed by samtstern** 2019-04-24 19:04 UTC
Labels: api: firestore

**Comment by nfarina** [comment] 2019-04-24 19:57
OK understood. Thanks for the quick reply!

**Comment by impaler** [comment] 2019-05-23 06:19
FYI feature request was made here https://github.com/firebase/firebase-tools/issues/1001 using this for the web SDK is a big productivity boost

**Comment by samtstern** [comment] 2019-05-23 14:20
Thanks for the link @impaler, let's keep using that as the main place to discuss this.

**Comment by wilhuff** [comment] 2019-05-23 14:25
Note that you can use the Web SDK under Node.js, and when you do, it uses gRPC. In this configuration the Web SDK can talk to the emulator.

If you add a dependency on `indexeddbshim` you'll even be able to exercise offline persistence scenarios in Node.

This makes it possible to at least run tests against the emulator (even if you can't your run the main application there yet).

**Comment by mikelehen** [comment] 2019-05-23 15:46
Note that running the client with `indexeddbshim` only works if you set a USE_MOCK_PERSISTENCE=YES environment variable since this isn't generally a supported configuration (don't try to use it in production).

**Comment by yuchenshi** [comment] 2019-10-01 23:46
Late to the party but now it works (TM) on the web as well. [Here's how](https://firebase.google.com/docs/emulator-suite/connect_and_prototype#web).
