### ISSUE TITLE
Inconsistencies in signatures of `useFunctionsEmulator` and `useAuthEmulator` (web v9 beta)

### ISSUE THREAD

**Issue by mgreenbe** [firebase/firebase-js-sdk#4986] opened 2021-06-04 23:43 UTC
### [REQUIRED] Describe your environment

  * Operating System version: MACOS 11.5
  * Browser version: N/A
  * Firebase SDK version: 9.0.0-beta.2
  * Firebase Product: auth, functions

### [REQUIRED] Describe the problem

The function signatures of `useFunctionsEmulator` and `useAuthEmulator` are inconsistent:

- To use the functions emulator, the command I need to run has the form `useFunctionsEmulator(fns, "localhost", 5001)`. 
- To use the auth emulator, the command I need to run has the form `useAuthEmulator(fns, "http://localhost:9099")`.
- If I include the combine `localhost` and `5001` into `http://localhost:5001` in `useFunctionsEmulator`, I get an error.
- If I separate `http://localhost:9099` into `localhost` and `9099` in `useAuthEmulator`, I get an error.

```javascript
let { initializeApp } = require("firebase/app")
let { initializeAuth, useAuthEmulator } = require("firebase/auth")
let { getFunctions, useFunctionsEmulator, httpsCallable } = require("firebase/functions");

let config = {
// redacted!!
};

let app = initializeApp(config)
let fns = getFunctions(app)
let auth = initializeAuth(app)
// useFunctionsEmulator(fns, "http://localhost:5001") // this one errors
useFunctionsEmulator(fns, "localhost", 5001)
// useAuthEmulator(auth, "localhost", 9099) // this one errors
useAuthEmulator(auth, "http://localhost:9099")

let test = async () => {
    let helloWorld = httpsCallable(fns, "helloWorld")
    await helloWorld()
    //     console.log(result)
}

test().then(() => console.log("done"))
```

```javascript
// functions/index.js
let functions = require('firebase-functions');

exports.helloWorld = functions.https.onCall((data) => {
    return { payload: "Hello, world!" }
});
```

**Comment by looptheloop88** [comment] 2021-06-08 15:56
Hi @mgreenbe, thanks for the report. This is expected, since the method signature or the parameters of [useFunctionsEmulator](https://firebase.google.com/docs/reference/js/v9/functions.md#usefunctionsemulator) and [useAuthEmulator](https://firebase.google.com/docs/reference/js/v9/auth#useauthemulator) aren't similar.

To use Authentication emulator in v9 SDK:
```
import { getAuth, useAuthEmulator } from "firebase/auth";

const auth = getAuth();
useAuthEmulator(auth, "http://localhost:9099");
```

To use Functions emulator in v9 SDK:
```
import { getApp } from "firebase/app";
import { getFunctions, useFunctionsEmulator } from "firebase/functions";

const functions = getFunctions(getApp());
useFunctionsEmulator(functions, "localhost", 5001);
```

We are aware that many developers would like to normalize the method signature of the Firebase emulators. There's already an internal feature request for this, however we can't provide definite timelines or details for when it will be available. You may keep an eye out on our release notes or this thread to get updates in the future.

For reference, the internal feature request is b/185364099.

**Comment by mgreenbe** [comment] 2021-06-09 02:05
Ok. Thanks for the clarification. Since you're already tracking this internally, feel free to close the issue if you think it's appropriate.

**Comment by looptheloop88** [comment] 2021-06-09 08:56
I will close this issue and mark as a duplicate of #4781.

**Closed by looptheloop88** 2021-06-09 08:56 UTC
Labels: internal-bug-filed, testing-sdk, type: feature request, v9
