### ISSUE TITLE
warnings when installing with yarn

### ISSUE THREAD

**Issue by PutziSan** [firebase/firebase-js-sdk#1794] opened 2019-05-17 07:45 UTC
This is a duplicate of https://github.com/firebase/firebase-js-sdk/issues/1207, but there is no further reaction and the problem is definitely not fixed yet. The very first impression of firebase when you install it with yarn is a real WOW-experience (wall-of-warning-experience):

![image](https://user-images.githubusercontent.com/13392042/57910794-6495cb00-7886-11e9-884a-22017519cdf6.png)

And please, the solution is not "just use npm". If you want to leave it as peerDependency, okay, it's your package. But could you explain to us why you decide to do this? Maybe it's a very good point and we can learn something.

Please also see the comment at the corresponding yarn-issue: https://github.com/yarnpkg/yarn/issues/5347#issuecomment-463038189

### [REQUIRED] Describe your environment

  * Operating System version: win10, yarn-1.16.0
  * Firebase SDK version: firebase@6.0.2
  * Firebase Product: all

### [REQUIRED] Describe the problem

When installing with yarn, warnings appear.

#### Steps to reproduce:

```shell
mkdir firebase-warning
cd firebase-warning
yarn add firebase
```

**Comment by Feiyang1** [comment] 2019-05-21 00:17
Thank you for bringing this issue to our attention, again! 

This is definitely not a good user experience and we should fix it given the fact that yarn is really popular nowadays. I made a PR to address it - https://github.com/firebase/firebase-js-sdk/pull/1807

As to why we  keep `@firebase/app-type` as a peer dependency - it's because `@firebase/app` is a peer dependency and `@firebase/app-type` should be the same one that `@firebase/app` depends on.

It makes sense for `@firebase/{component}` to peer depend on `@firebase/app`, otherwise if you install `@firebase/{component}` individually and each of the component depends on a different version of `@firebase/app`, you will run into incompatible firebase instances and other weird issues caused by it.

**Comment by Feiyang1** [comment] 2019-05-24 18:16
Closing this as 6.0.4 is out with the fix.

**Closed by Feiyang1** 2019-05-24 18:16 UTC
Labels: api: core
