### ISSUE TITLE
Auth does not work in ionic apps on iphone devices or sims

### ISSUE THREAD

**Issue by donhmorris** [firebase/firebase-js-sdk#5552] opened 2021-09-27 18:32 UTC
### [REQUIRED] Describe your environment

  * Operating System version: _Mac 11.6
  * Browser version: Chrome 93
  * Firebase SDK version: 9
  * Firebase Product: auth
  * ionic 5.5.2

### [REQUIRED] Describe the problem
Using the v9 sdk, onAuthStateChanged does not fire when signing in on iphone simulator nor iphone device when using the ionic framework.

Reverting back to v8 works fine. Something was broken in v9 for use with ionic framework.

#### Steps to reproduce:
Create a sign in with email and password login. Will work in browser; will not work in iphone simulator or iphone device. It will just hang, waiting for a login result.

#### Relevant Code:
Steps to set up and reproduce

1. clone git clone https://donhmorris@bitbucket.org/donhmorris/testlogin2.git
2. run npm i
3. run ionic lab
4. login in browser with credentials: email = 'don@test.com'. pwd = 'password'
5. Message will be displayed in app that says "Signed in as don@test.com" and Logout button is displayed on success. A toast will appear in red if an error occurs.
6. stop ionic lab; run ionic cap run ios
7. select an iphone simulator model. Any version will do. Recommend iphone 13.
8. attempt to login using the previous credentials
9. nothing will happen. no errors, exceptions or anything. app just hangs

**Comment by sam-gc** [comment] 2021-09-28 17:44
It looks like you're using angularfire. Would you mind closing this and reopening it in https://github.com/angular/angularfire?

**Comment by donhmorris** [comment] 2021-09-28 17:56
The angular/fire guys already punted to Firebase. 
The same problem exists if you use the Firebase sdk v9 by itself. Would it help if I converted my demo app to use just the Firebase sdk?

**Comment by donhmorris** [comment] 2021-09-28 19:55
I created a new demo project that is identical except it uses just the firebase v9 sdk. I updated my original description to point to the new git repository.

**Comment by jayordway** [comment] 2021-09-28 20:01
I had the same problem as well. I used this method at app initialization and it works with Ionic and Capacitor:

```
init() {
    const app = initializeApp(environment.firebase);
    if (Capacitor.isNativePlatform) {
      initializeAuth(app, {
        persistence: indexedDBLocalPersistence
      });
    }
    this.firestore = getFirestore(app);
  }
```

`indexedDBLocalPersistence` was not exposed in angular/fire, but there may be a way to do it, I was having issues with angular fire, but this above worked fine using firebase 9 exclusively. There may be a way to do it with angular/fire - I will look into it later.

**Comment by donhmorris** [comment] 2021-09-28 20:36
I tried your suggestion and it worked.
I'm guessing the v8 sdk did this and it was dropped from v9. Still seems like a bug in the v9 sdk to me.

**Comment by sam-gc** [comment] 2021-09-28 21:31
I see, yeah this is definitely working as intended. The `getAuth()` function in the main package assumes a browser context. For more specific platforms/edge cases, the `initializeAuth()` function is what you should use. I'd also recommend trying the Cordova-specific imports, which include a `getAuth()` implementation that is meant to work in Cordova-type environments.

For example, switch **all** of your imports to `import {} from 'firebase/auth/cordova';` More information here: https://firebase.google.com/docs/auth/web/cordova (one note: there is an issue with this docs page, the `/cordova` is missing from the import path)

**Closed by sam-gc** 2021-09-28 21:31 UTC
Labels: api: auth, needs-attention, v9
