### ISSUE TITLE
@firebase/rules-unit-testing fails when loaded as es6 module with firebase-js-sdk >= 9.2.0

### ISSUE THREAD

**Issue by kenkunz** [firebase/firebase-js-sdk#5825] opened 2021-12-20 17:16 UTC
### [REQUIRED] Describe your environment

  * Operating System version: macOS Monterey 12.0.1
  * Browser version: n/a
  * Firebase SDK version: >= 9.2.0
  * Firebase Product: rules-unit-testing, firestore

### [REQUIRED] Describe the problem

With `@firebase/rules-unit-testing@2.0.1` and `firebase >=9.0.0 <=9.1.3`, the test utilities work
whether loaded as a cjs require or an es6 module. After upgrading to `firebase >=9.2.0`, the
utilities no longer work when loaded as es6 module, but still work when loaded with cjs require.

Since other firebase modules support es6 module loading, it seems surprising for rules-unit-testing
not to fully support this as well.

#### Current workaround

Using cjs require for my firestore rules tests.

#### Steps to reproduce:

1. install dependency: [Firebase Emulators](https://firebase.google.com/docs/emulator-suite/install_and_configure)
1. clone [kenkunz/firestore-testing-repro](https://github.com/kenkunz/firestore-testing-repro) and install npm modules
   ```bash
   git clone https://github.com/kenkunz/firestore-testing-repro.git
   cd firestore-testing-repro
   npm install
   ```
1. run the tests
   ```bash
   npm run test
   ```
   Note that both `test.js` and `test.cjs` complete successfully

1. upgrade to `firebase@9.2.0` (or greater)
   ```bash
   npm i -D firebase@9.2.0
   ```
1. run the tests again
   ```bash
   npm run test
   ```
   Note that `test.cjs` still passes but `test.js` fails (see error output below)

#### Error output:

```
FirebaseError: Expected first argument to collection() to be a CollectionReference, a DocumentReference or FirebaseFirestore
at doc (file:///Users/ken/Code/firestore-testing-repro/node_modules/@firebase/firestore/dist/index.node.mjs:19998:19)
at file:///Users/ken/Code/firestore-testing-repro/test.js:8:20
at RulesTestEnvironmentImpl.<anonymous> (node_modules/@firebase/rules-unit-testing/dist/index.cjs.js:310:46)
at step (node_modules/@firebase/rules-unit-testing/dist/index.cjs.js:74:23)
at Object.next (node_modules/@firebase/rules-unit-testing/dist/index.cjs.js:55:53)
at /Users/ken/Code/firestore-testing-repro/node_modules/@firebase/rules-unit-testing/dist/index.cjs.js:48:71
at new Promise (<anonymous>)
at __awaiter (node_modules/@firebase/rules-unit-testing/dist/index.cjs.js:44:12)
at RulesTestEnvironmentImpl.withSecurityRulesDisabled (node_modules/@firebase/rules-unit-testing/dist/index.cjs.js:300:16)
at Context.<anonymous> (file:///Users/ken/Code/firestore-testing-repro/test.js:7:19)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by jbalidiong** [comment] 2021-12-23 15:42
Hi @kenkunz, thanks for the report. I was able to reproduce the behavior now. Let me check what we can do for this issue or bring someone here that can provide more context about it. I’ll update this thread if I have any information to share.

**Comment by angrycat9000** [comment] 2021-12-28 13:53
Thanks for the work around @kenkunz.  I hit this bug when upgrading to the new 9.0 API

**Comment by ChromeQ** [comment] 2022-08-29 12:23
Noticed this is old but it is still an issue with firebase v9.9.3 and @firebase/rules-unit-testing v2.0.4 so it would be good to see an update or a fix here

**Comment by ghinda** [comment] 2024-11-07 10:08
Seems to be fixed with with the latest `firebase 11.0.1` and `@firebase/rules-unit-testing 4.0.0`.

**Comment by DellaBitta** [comment] 2024-11-07 21:25
@kenkunz,

Can you confirm that this was fixed in v11?

**Comment by kenkunz** [comment] 2024-11-08 15:26
> @kenkunz,
> 
> Can you confirm that this was fixed in v11?

Sorry, I haven't been actively using Firebase for a while, and don't have bandwidth to dust this off to test atm.

**Closed** 2024-11-21 02:03 UTC
Labels: question, needs-info, no-recent-activity, testing-sdk, v9
