### ISSUE TITLE
"Module" before "main" is default in Node Webpack builds, now generates an (obnoxious) warning

### ISSUE THREAD

**Issue by arpowers** [firebase/firebase-js-sdk#1612] opened 2019-03-18 14:21 UTC
In reference to this conversation: 
https://github.com/firebase/firebase-js-sdk/pull/1536#issuecomment-473408965

Issue at Hand: There is a problem with assuming the "module" field in package.json is for the browser. Webpack (and everyone else) is assuming 'module' is the go-to package for node! 

I would suggest making the Browserify (or similar) use-case the "special-case" because  remember: ANY SSR use of Firebase is going to get this warning!

Other packages definitely throw nasty errors in Node if "main" is processed before "module". I can tell you because I get 4 or 5 issues just on my setup here.  

Solutions: 

**Remember Transpilation is Really Easy**
You are trying to make something too easy. Transpilation from esm to cjs and so on is easy with transpilation. I do it all the time.  Why don't you just recommend this to people who need it? The solution you are providing is NOT easy to remedy because of the "rock in a hard place" nature of "broken if you do, broken if you don't."

**Thread**
I don't know if you've tried this: 
https://github.com/webpack/webpack/issues/4674

**A Flag to Disable the Warning?** 
The 'module' package runs fine in Node actually; its the massive warning thats the problem (in my case). 

**Use Case:** 
Vue JS - Server-Side Rendered App

  * Operating System version: Latest Mac OSX
  * Browser version: Latest Chrome
  * Firebase SDK version: Latest
  * Firebase Product:  Auth, Firestore, more...

@Feiyang1

**Comment by Feiyang1** [comment] 2019-03-20 20:44
Are you doing SSR or making a bundle targeting NodeJs? If you are doing SSR and you know you don't need to run any firebase code(e.g. firestore), can you just ignore it? We have seen people who want to target NodeJs, but included the browser build incorrectly wondering why it doesn't work. This message is very useful for them for debugging.

As to which field should be used for what build, I think it's bit of a mess for packages that provide different node and browser builds, and there is no consensus at the moment.

Can you please clarify who `everyone else` you are referring to? I'm not super up to date on it, but I know rollup (rollup-node-resolve) doesn't assume it. Also unpkg and polymer-cli all look at module field first for loading module files natively in browser.

BTW, I have looked at https://github.com/webpack/webpack/issues/4674#issuecomment-355853969,  but it only works for webpack( e.g. rollup doesn't understand this syntax).

**Comment by arpowers** [comment] 2019-03-21 15:03
@Feiyang1 

We are using 'vue-server-renderer' to create a bundle that is then used by the Node server to render the page. Calls to Firestore are made at runtime, to do prefetches and so on... 

I've created a video showing my current experience and the warnings i'm getting when taking your Webpack suggestion (vs the Firebase warning when I don't)

https://drive.google.com/drive/folders/1mdmtVoH9gdHs1k21WdOuN3o5G5MOl_WT?usp=sharing

<img width="911" alt="Screen Shot 2019-03-21 at 10 57 47 AM" src="https://user-images.githubusercontent.com/308134/54761701-f5269680-4bc8-11e9-9bcc-45077733efc7.png">


Also, off-topic, but I'm developing Firebase into an open-source serverless CMS and would appreciate a call with some engineers to work through some of the issues we're having. Not sure who to talk with...

**Comment by Feiyang1** [comment] 2019-03-21 18:55
@samtstern What support channel can @arpowers contact?

**Comment by samtstern** [comment] 2019-03-21 19:15
@arpowers that sounds cool!  However we are a small team and can't offer calls with individual developers, we'd be on the phone all day and get nothing done!

I'd suggest posting about your ideas on the firebase-talk mailing list once you have something to show:
https://groups.google.com/forum/#!forum/firebase-talk

You may also want to talk to the developers of one of these Firebase CMS services:
https://flamelink.io/
https://www.pushtable.com/

**Comment by arpowers** [comment] 2019-03-22 15:03
@samtstern this product could bring thousands of new Firebase customers (we have created Frameworks used by 100k+ sites already), but everytime i run into a problem i get dead ended. Support people don't seem to know anything about solutions to even moderately complicated problems.

**Comment by samtstern** [comment] 2019-03-22 15:05
@arpowers if you want to email me a list of questions about Firestore, I am happy to answer them or try and find answers.

My email address is on my GitHub profile.

**Comment by arpowers** [comment] 2019-04-18 14:23
@Feiyang1 any updates on this?

**Comment by Feiyang1** [comment] 2019-04-18 20:51
Are you facing any new issue with the CLI, or just the warning message? I'm asking because you mentioned SSR was the problem, just want to clarify the use case here. Thanks.

**Comment by mhofman** [comment] 2019-05-05 20:26
> BTW, I have looked at [webpack/webpack#4674 (comment)](https://github.com/webpack/webpack/issues/4674#issuecomment-355853969), but it only works for webpack( e.g. rollup doesn't understand this syntax).

My reading of https://github.com/rollup/rollup-plugin-node-resolve/pull/183 is that the syntax should work with rollup as well.

**Comment by evdama** [comment] 2020-01-16 08:33
Is there any new best-practice or otherwise progress on the SSR subject? Similiar to Angular, Vue SSR and React users I'm having import issues Sapper (a SSR toolkit for Svelte vs3). The issues are as mentioned here https://github.com/codediodeio/sveltefire/issues/4 and here https://github.com/firebase/firebase-js-sdk/issues/1797

**Comment by fkrauthan** [comment] 2022-10-08 03:27
Hey is there any news? I get the issue using `pnpm` with create react app (webpack). It looks like the issue is that it tries to pull in `index.esm2017.js` which contains a `const json = require(defaultsJsonPath);` line that triggers the warning in webpack: `Critical dependency: the request of a dependency is an expression`.

**Comment by ChromeQ** [comment] 2022-10-09 22:49
Same problem as @fkrauthan above. For me seems to be only happening with updating firebase from 9.10.0 to 9.11.0.

**Comment by hsubox76** [comment] 2022-10-10 17:19
That's a bug and will be fixed in the release this week. See https://github.com/firebase/firebase-js-sdk/issues/6660 I don't think it's related to this older issue.

**Comment by hsubox76** [comment] 2023-08-07 17:46
This warning message is no longer in the codebase at this time, closing the issue.

**Closed by hsubox76** 2023-08-07 17:46 UTC
Labels: api: core, feature request
