### ISSUE TITLE
if i stop remote debugging, i start to get view.getQuery error while using firebase in react native

### ISSUE THREAD

**Issue by ihsanktmr** [firebase/firebase-js-sdk#2388] opened 2019-11-28 16:53 UTC
I get this error; 'TypeError: undefined is not an object (evaluating 'view.getQuery)'

I am able to use `firebase.auth()`. After I login the app I get the error.

**Important Note**: There is no error when debugger is on.

This is where I call `firebase.database()` which causes the error.

```
componentDidMount(){
    firebase.database().ref(`/posts/`).on('value', snapshot => {
        const keys = Object.keys(snapshot.val());
        alert(keys)
    });
}
```

I tried to upgrade and downgrade to all the firebase versions, it didn't solve.
related library versions;

```
"firebase": "^6.3.3",
"react": "^16.6.3",
"react-native": "0.58.3",
```

```
Android API 28
Java version: 1.8.0
```

Thanks for your recommendations.

![oQT4W](https://user-images.githubusercontent.com/26416028/69822863-6ae30780-1218-11ea-9b3f-a78e9a16a5f4.png)

**Comment by rommelpe** [comment] 2019-11-28 18:40
Thanks for your report! Looking at the error logs itself, it seems that Firebase wasn't mention at all so I'm suspecting this can be an issue in the library/plugin used. I wasn't able to reproduce this on my end using firebase (6.3.3) or even the latest one (v7.5.0). Atm, it's difficult to pinpoint what might be the cause of the issue since we can't reproduce if could you provide the ff, we'd be happy to investigate further:

- [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) of your app that we can run locally
- Detailed steps taken that led to the error message encountered
- Additionally, I ran into this [post](https://stackoverflow.com/questions/57147432/typeerror-undefined-is-not-an-object-evaluating-view-getquery-after-login-for
) and it seems that it works fine in physical device: does it work for you?

**Comment by ihsanktmr** [comment] 2019-12-06 13:41
Sorry for late response. I simplified my code and still getting the error. here is my full code;

**App.js**
```
import React, { Component } from 'react';
import Main from './src/Main'
import firebase from 'firebase';

export default class App extends Component {
    componentWillMount(){
        var config = {
            apiKey: "",
            authDomain: "",
            databaseURL: "",
            projectId: "",
            storageBucket: "",
            messagingSenderId: "",
        };
        firebase.initializeApp(config);
    };
    render() {
        return <Main/>
    }
}

```


**Main.js**
```
import React, { Component } from 'react';
import firebase from "firebase";
import {Text} from "react-native";
export default class Main extends Component {
    componentDidMount(){
        firebase.database().ref(`/posts/`).on('value', snapshot => {
            const keys = Object.keys(snapshot.val());
            alert(keys)
        });
    }
    render() {
        return (
            <Text>Hello world</Text>
        );
    }
}
```

I can still generate same error with just these 2 classes this is very interesting.

**package.json**
```
{
  "name": "staffbasedeneme",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "base-64": "^0.1.0",
    "firebase": "^6.3.3",
    "jetifier": "^1.6.4",
    "lodash": "^4.17.11",
    "prop-types": "^15.6.2",
    "react": "^16.6.3",
    "react-native": "0.58.3",
    "react-native-actionsheet": "^2.4.2",
    "react-native-barcode-mask": "^1.1.0",
    "react-native-camera": "^3.11.1",
    "react-native-elements": "^1.1.0",
    "react-native-fetch-blob": "^0.10.8",
    "react-native-gesture-handler": "^1.2.1",
    "react-native-image-picker": "^0.28.0",
    "react-native-modal-datetime-picker": "^6.0.0",
    "react-native-modal-dropdown": "^0.6.2",
    "react-native-reanimated": "^1.0.1",
    "react-native-router-flux": "^4.0.6",
    "react-native-swiper": "^1.5.14",
    "react-native-tab-view": "^2.2.0",
    "react-native-vector-icons": "^6.2.0",
    "react-redux": "^6.0.0",
    "redux": "^4.0.1",
    "redux-thunk": "^2.3.0"
  },
  "devDependencies": {
    "babel-core": "7.0.0-bridge.0",
    "babel-jest": "24.0.0",
    "jest": "24.0.0",
    "metro-react-native-babel-preset": "0.51.1",
    "react-test-renderer": "16.6.3"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

Screenshot when debugger is open; 

![Screenshot_1575639430](https://user-images.githubusercontent.com/26416028/70326992-efe8a500-1846-11ea-96a6-8649a36c9f93.png)

Screenshot when debugger is closed;

![Screenshot_1575639573](https://user-images.githubusercontent.com/26416028/70327031-ff67ee00-1846-11ea-90c7-c54c809b6e49.png)



Thank you for your help. Regards.

**Comment by rommelpe** [comment] 2019-12-10 18:42
Init:
![image](https://user-images.githubusercontent.com/56452310/70557998-f36d8a80-1bbe-11ea-8cc6-ad8b9f7a308c.png)

![image](https://user-images.githubusercontent.com/56452310/70558148-48110580-1bbf-11ea-8040-f617a397f436.png)

**Comment by rommelpe** [comment] 2019-12-10 19:32
Thanks for working on the repro. I tried to reproduce, but wasn't able to replicate it. I got a warning message but doesn't seem related to the issue.

![image](https://user-images.githubusercontent.com/56452310/70559104-0ed99500-1bc1-11ea-9294-f1d0e3caad71.png)


What do you mean by when debugger is opened/closed? Is it the debugger in the Android studio itself? I tried that too and get the same result having just a warning message.

![image](https://user-images.githubusercontent.com/56452310/70558537-0a60ac80-1bc0-11ea-9b5b-a640f9417a67.png)

![image](https://user-images.githubusercontent.com/56452310/70558484-ef8e3800-1bbf-11ea-9ad9-644d1dd123ce.png)


Have you tried consider upgrading your react dependencies ``` "react": "16.9.0","react-native": "0.61.5",```  to the latest version (or even JS Firebase SDK [v.7.5.2](https://firebase.google.com/support/release-notes/js))? 

Also, it would be easier to isolate the issue if you'll omit some unnecessary dependencies.

**Comment by ihsanktmr** [comment] 2019-12-20 18:08
Sorry for late response. Error is just disappeared itself.  I still don't know what was that about thank you anyways. If it appears again I will put new codes here with the error.

**Comment by rommelpe** [comment] 2020-01-03 08:17
No worries, @ihsanktmr. While this isn't yet reproducible, I'll be closing this issue for better tracking.You can always reply on this thread to re-open the issue and so we can continue where we left off. Thanks!

**Closed by rommelpe** 2020-01-03 08:17 UTC
Labels: api: database, needs-attention
