### ISSUE TITLE
FR: Query by subcollection

### ISSUE THREAD

**Issue by sondresorbye0111** [firebase/firebase-js-sdk#1009] opened 2018-07-14 14:36 UTC
I want to get all teams where the user is a member of. Currently, I am querying by a object with uid as key. 

The teams can potentially have thousands of members and the user can be member of many teams. Therefore, this approach is not scalable. A better approach would be to query be a subcollection with all users. 

I also could make another collection to make a relationship between the users and teams (like SQL databases). The problem with this is that a have to make another request to Firestone.

Is it a scalable solution to this?

**Comment by codediodeio** [comment] 2018-07-14 17:14
In Cloud Datastore it's possible to get up to 1,000 entities with an array of keys. 

```
datastore.get( [...keys] )
```

Is something similar on the roadmap in Firestore? I think this could solve many of the relational challenges like the one referenced above.

**Comment by Thaina** [comment] 2018-07-26 06:56
> user can be member of many teams

Don't think subcollection query would satisfied this case

Instead I think you need

```json
//user doc
{
    memberOf : {
         teamID1 : true,
         teamID2 : true,
         teamID3 : true,
         teamID4 : true,
    }
}
```

```C#
var teamQuery = db.Collection("users").WhereEqualTo("memberOf.teamID{x}",true);
```

**Comment by sondresorbye0111** [comment] 2018-07-30 16:54
@Thaina, this is the solution I am currently using. However, this approach is not very scalable. A team couød potentially have thousands of members.

**Comment by mohshraim** [comment] 2018-07-30 17:29
i think same FR already exist
https://github.com/firebase/firebase-js-sdk/issues/572

**Comment by Thaina** [comment] 2018-07-31 01:28
@sondresorbye0111 Then you need the opposite, storing teamID in user doc. Given that the more possible side of relation would be the main to store the less one

And if you need true scalable of both side. Maybe you need another collection, a relationship collection. Which is storing very small document, only

```json
docid : "teamID:userID"
{
    "team" : teamID,
    "user" : userID,
}
```

And so you could query both way

**Comment by sondresorbye0111** [comment] 2018-07-31 07:07
@Thaina, this is a solution, but it requires two roundtrips to the database. Therefore, I think it would actually be slower than downloading some extra other users IDs.

**Comment by wilhuff** [comment] 2018-09-12 01:09
Thanks for your interest! This is a duplicate of #572.

As we said there, this is definitely on the road map. Right now we're working on stabilizing what we have for GA so this isn't imminent, but this is very high on our list of priorities, don't worry :-).

**Closed by wilhuff** 2018-09-12 01:09 UTC
Labels: Component-Firestore, feature-request
