### ISSUE TITLE
Firebase Analytics for Web not working in IE11 (without polyfills)

### ISSUE THREAD

**Issue by thorium369** [firebase/firebase-js-sdk#2538] opened 2020-01-14 13:42 UTC
### [REQUIRED] Describe your environment

  * Operating System version: Windows 8.1
  * Browser version: IE11 (11.0.9600.19507)
  * Firebase SDK version: 7.6.2
  * Firebase Product: Analytics

### [REQUIRED] Describe the problem
The Firebase Analytics JS plugin for Web gives below error in IE console:
```
SCRIPT438: Object doesn't support property or method 'values'
File: firebase-analytics.js, Line: 1, Column: 19887
```
Any events fired using _logEvent_ fail because of this.

#### Steps to reproduce:
- Create a sample html page
- Add Firebase SDK (core and Analytics) via CDN:
```
<!-- Firebase App (the core Firebase SDK) is always required and must be listed first -->
<script src="https://www.gstatic.com/firebasejs/7.6.2/firebase-app.js"></script>
<!-- If you enabled Analytics in your project, add the Firebase SDK for Analytics -->
<script src="https://www.gstatic.com/firebasejs/7.6.2/firebase-analytics.js"></script>
```
- Open page in IE11 with console(dev-tools) open

Note: I have not included any polyfills library in my webpage since as per docs 'Analytics' is supported fine on IE11. Link: https://firebase.google.com/support/guides/environments_js-sdk

**Comment by rommelpe** [comment] 2020-01-14 14:16
It looks like you still need to [include polyfills](https://firebase.google.com/support/guides/environments_js-sdk#supported_environments) in your application.

> You still need to include polyfills for environments that don't support the features required by Firebase.

If you’ve incorporated polyfills and still having issues, please share a [repro](https://stackoverflow.com/help/minimal-reproducible-example) so I can check it on my end.

**Comment by hsubox76** [comment] 2020-01-14 19:19
Just to clarify any confusion, "environments that don't support the features required by Firebase" refers to environments that don't support the **browser APIs/features** required by Firebase.  It doesn't mean polyfills are not required for Firebase **products** (such as analytics) supported in that environment.  Polyfills are required for Firebase to work in IE.

If you scroll down, ES Stable is listed in the Required Polyfills for IE 11.

**Comment by thorium369** [comment] 2020-01-15 08:53
@hsubox76 @rommelpe Thanks for clarifying!
I thought that line (which you both mentioned) meant that polyfills are required only for features not supported (like Cloud Messaging) which have a red flag in the table.
I added the ES Stable polyfill and I was able to log events and see them in the Analytics Dashboard.

**Comment by rommelpe** [comment] 2020-01-15 09:08
Glad to hear that, @thorium369. I'll be closing this issue now. Should you have any other Firebase-specific questions and want to continue the discussion, just leave a comment here and we are happy to re-open this.

**Closed by rommelpe** 2020-01-15 09:08 UTC
Labels: api: analytics, needs-attention
