### ISSUE TITLE
Are there anyway that we could used to check that the credential existed but not create new account?

### ISSUE THREAD

**Issue by Thaina** [firebase/firebase-js-sdk#1942] opened 2019-07-04 04:36 UTC
Since we could get and link credential with many sources. Google, Facebook, GooglePlay, GameCenter, github, etc. I need to have some way to verified that, is the credential already existed and linked with some ID or not

But I don't want to signed in with that credential immediately. Because I need to generate custom userID. If it linked I will let it signed in. But if it not I would like to have user pass the initial process first and the server will minting the token to let user signing in and link their credential with it after that

Is there any API to do that, especially in client?

If not I would like to request API Auth.getUserIDFromCredential(credential) or Auth.signInWithExistingCredential(credential) that will signed in only if the credential has already been linked with any account

**Comment by Feiyang1** [comment] 2019-07-08 21:31
Duplicate of https://github.com/firebase/firebase-js-sdk/issues/1945

**Closed by Feiyang1** 2019-07-08 21:31 UTC
Labels: api: auth, type: discussion

**Comment by Thaina** [comment] 2019-07-09 01:37
@Feiyang1 It's not. The #1945 was intended to request in node repo for server side functionality. This issue was just the same functionality but on client side

I expect that #1945 would be moved back to node repo so this issue should be kept opened please

**Comment by Thaina** [comment] 2019-07-15 17:17
@Feiyang1 Please reopen this issue and move another one back to the node sdk repo
