### ISSUE TITLE
Firebase cloud messaging push notification token encounter an UNREGISTERED (HTTP 404)

### ISSUE THREAD

**Issue by Parth-andhariya-maruti** [firebase/firebase-js-sdk#7271] opened 2023-04-28 07:53 UTC
**Describe your environment**

  * Operating System Version: Android 12
  * Browser version: Chrome 112.0.5615.135 
  * Firebase SDK version: ^9.19.1
  * Firebase Product: (auth, cloud massaging push notification)

**Describe the problem**
I am using a PWA for my application and I get a token using the method getToken and then attempt to send a notification to that token using the "https://fcm.googleapis.com/fcm/send" API, but I encounter an UNREGISTERED (HTTP 404) problem. Again when I try to fetch the token, it gets the same token. This means that the token I am using is a valid one. But while sending the notification using the same token, I get the message UNREGISTERED. Please review and provide guidance.

**Steps to reproduce**

**to send a notification**
curl --location --request POST 'https://fcm.googleapis.com/fcm/send' \
--header 'Content-Type: application/json' \
--header 'Authorization: key=<SERVER_KEY> \
--data-raw '{
    "registration_ids": [
        "<FIREBASE_USER_TOKEN>"
    ],
    "notification": {
        "title": "<,TITLE_OF_NOTIFICATION>"
        "body": "<BODY_MASSAGE_OF_NOTIFICATION>"
    }
}'

**to get a token from the firebase**

 const permission = await Notification.requestPermission();
                    if (permission === 'granted') {
                        const token = await getToken(messaging, {
                            vapidKey: process.env.VAPID_KEY,
                        });
                     }

**firebase-messaging-sw.js file for get a notification**

[sw.odf](https://github.com/firebase/firebase-js-sdk/files/11351209/sw.odf)

**Comment by jbalidiong** [comment] 2023-05-02 14:01
Hi @Parth-andhariya-maruti, thanks for the report. I tried replicating, but I wasn't able to reproduce the error. Usually, a [404 error](https://firebase.google.cn/docs/reference/fcm/rest/v1/ErrorCode#:~:text=HTTP%20error%20code%20%3D%20404) code occurs when an app instance is unregistered from FCM wherein the token used is invalid and a new token must be used.

We highly recommend following [best practices for FCM registration token management](https://firebase.google.com/docs/cloud-messaging/manage-tokens) to avoid having issues with invalid tokens as you move forward. Also, you can use [Google App Instance API](https://developers.google.com/instance-id/reference/server#get_information_about_app_instances) for you to check the values of your users' tokens in the Firebase server. I'll be closing this for now. If the issue persists, feel free to comment and reopen this issue.

**Closed by jbalidiong** 2023-05-02 14:01 UTC
Labels: api: messaging, v9

**Comment by riddhi-24** [comment] 2023-05-22 07:10
Hi @jbalidiong, I am facing the same issue, though it is not reproducible every time, and we are following all the best practices mentioned in the doc, still facing this, can you share what can be the reason or how can we fix it? as these errors frequency is very high, thanks in advance.
