### ISSUE TITLE
On iOS signInWithRedirect() launches Safari in private mode and can't redirect back to the app after signup

### ISSUE THREAD

**Issue by gspuzic** [firebase/firebase-js-sdk#1044] opened 2018-07-25 02:24 UTC
### [REQUIRED] Describe your environment

  * Operating System version: iOS 10.x
  * Browser version: Cordova web view engine CDVUIWebViewEngine
  * Firebase SDK version: 5.2.0
  * Firebase Product: auth

### [REQUIRED] Describe the problem

On iOS 10.x, if Safari is set to private mode, Firebase JS is unable to close Safari and re-direct back to the app with a "can't close the window since it was not opened by javascript" warning printed to the console.

#### Steps to reproduce:

Implement OAuth in a simple Cordova app using Ionic as described in the Firebase docs. Set Safari to private mode. Run the app on iOS 10.x. Try to sign up with Facebook.

#### Relevant Code:

NA

**Comment by wti806** [comment] 2018-07-26 17:59
@gsoltis  I'm using cordova ios 4.5.4 and tested on iOS 10.3 and I'm not able to replicate the issue. It works as expected.

**Comment by gsoltis** [comment] 2018-07-26 21:50
@wti806 did you mean to tag @gspuzic ?

**Comment by wti806** [comment] 2018-07-26 22:50
@gsoltis Oh Sorry about that.  Updated the comment.

**Comment by gspuzic** [comment] 2018-07-31 02:42
@wti806 Thanks for trying, I'm also unable to reproduce this now. We did have a user reporting this issue, and I found turning Safari private browsing off solved it for that particular case. The error message they were getting was during re-direction back to the app: "can't close the window since it was not opened by javascript".

The general problem here is this whole flow rely's on launching an external app and we have no way of controlling its settings (e.g. this breaks if the user has turned off javascript in safari settings). The error message back from the browser is also of no use "user has cancelled before finalising".

**Comment by wti806** [comment] 2018-07-31 17:45
@gspuzic  When you testing it, is the SafariViewController opened in private mode or not? Even I switched to private mode in safari, the SafariViewController opened was not in dark theme. So I'm not sure the window opened in firebase app is in private mode or not. In addition, we do rely on web storage for sign in with OAuth providers. It's a known issue #1040

**Comment by gspuzic** [comment] 2018-08-01 09:28
Yes, it is the dark theme. Here is the screenshot from the session (this is after logging in with Facebook when the window fails to close and re-direct back to the app)

![img_7051](https://user-images.githubusercontent.com/41413117/43513219-5951b70c-95bc-11e8-8507-9a4420fe5877.PNG)

**Comment by tiagodurante** [comment] 2018-08-06 15:32
I have a same problem. 😓

**Comment by arikanorh** [comment] 2018-08-07 05:28
I'm having the same problem. It happens only and always in  private mode

**Comment by newfivefour** [comment] 2018-08-25 09:27
This problems appears with both Firefox and Safari in iPhone iOS 11 when trying to redirect auth login with facebook in private browsing mode.

When you use private browsing mode, the redirect doesn't work, and you're sent to a blank blarblar.firebaseapp.com webpage. If you then use normal browsing mode in either browser it works fine.

But strangely, private browsing mode in chrome on iPhone iOS 11 does work fine.

**Comment by angelserranoperez** [comment] 2018-08-26 07:01
I have the same issue:
https://stackoverflow.com/questions/52010167/signinwithredirect-with-googleauthprovider-gets-white-screen-on-safari-when-i-se

The thing is that if you insist again then the account was stored and if you choose it then you can sign in.

**Comment by gspuzic** [comment] 2018-08-26 07:04
Can we escalate this issue for a fix?

**Comment by yuchenshi** [comment] 2020-05-11 16:26
This is a duplicate of #1040

**Closed by yuchenshi** 2020-05-11 16:26 UTC
Labels: api: auth
