### ISSUE TITLE
Incorrect type for `firebase.apps`

### ISSUE THREAD

**Issue by mayhewluke** [firebase/firebase-js-sdk#1189] opened 2018-09-01 22:37 UTC
### [REQUIRED] Describe your environment

  * Operating System version: N/A
  * Browser version: N/A
  * Firebase SDK version: 5.4.2
  * Firebase Product: app (auth, database, storage, etc)

### [REQUIRED] Describe the problem

`firebase.apps` is defined [in the root `index.d.ts`](https://github.com/firebase/firebase-js-sdk/blob/master/packages/firebase/index.d.ts#L108) as `(firebase.app.App | null)[]`. However, in `app-types` [it's defined](https://github.com/firebase/firebase-js-sdk/blob/master/packages/app-types/index.d.ts#L97) as `FirebaseApp[]`, which is the same as it's actual definition [in the source file](https://github.com/firebase/firebase-js-sdk/blob/master/packages/app/src/firebaseApp.ts#L344).

If I understand correctly, it seems like the root `index.d.ts` should be brought in sync with the other files.

**Comment by Feiyang1** [comment] 2018-09-26 18:17
Hi @mayhewluke, thanks for reporting this! The differences are by design. Types defined in app-types are internal typings we use for development, while typings defined in root index.d.ts are the public interface we expose to developers. That said, I do find a problem - null should not be a type of the member of the array. It is being addressed by https://github.com/firebase/firebase-js-sdk/pull/1252

**Closed by Feiyang1** 2018-09-26 18:17 UTC
Labels: Component-Core

**Comment by mayhewluke** [comment] 2018-09-28 14:27
Thanks for the fix, @Feiyang1! And for explaining - I'm glad to be able to understand the situation better now. Maybe now I'll know enough to be able to contribute a PR myself next time :smile:
