### ISSUE TITLE
feature request: ML Kit support

### ISSUE THREAD

**Issue by Ploppy3** [firebase/firebase-js-sdk#943] opened 2018-06-19 09:41 UTC
Hello,
I don't see anything related to Firebase's ML Kit, therefore I would like to ask if you plan to support it?

**Comment by jshcrowthe** [comment] 2018-06-29 18:09
Duplicate of #944 (I think you wanted the other one regardless)

**Closed by jshcrowthe** 2018-06-29 18:09 UTC
Labels: needs-triage

**Comment by Ploppy3** [comment] 2018-06-29 20:20
@jshcrowthe Thank you! Forgot to close this one! My bad :(
