### ISSUE TITLE
JS SDK Upgrade issue - 7.21.0 => 8.6.5

### ISSUE THREAD

**Issue by olivierkrener** [firebase/firebase-js-sdk#5017] opened 2021-06-11 13:57 UTC
### [REQUIRED] Describe your environment

  * Operating System version: _____ iOS 12.5.3
  * Browser version: _____ Safari 12.5.3
  * Firebase SDK version: _____ SDK JS 8.6.5
  * Firebase Product: _____ auth, firestore

### [REQUIRED] Describe the problem

My app was installed a long time ago on this client, at the time using the JS SDK version 7.21.0. Since then the app has evolved and I am now using version 8.6.5. Redeploying a new version seems to cause all kinds of Firestore issues, my guess is that it is some problem with the Firestore SDK upgrading its IndexedDB structure.
After clearing the cache (including IndexedDB) the app starts normally.

Attached are some logs I could get (note that they are not coming directly from the firebase SDK, but it is mostly copy-through). [This is using the "error" log level, setting the log level to "debug" did not produce any logs](https://firebase.google.com/docs/reference/js/firebase#loglevel)...

Now that my client has upgraded I cannot reproduce the problem anymore so this is more a heads up describing a potential issue.
[FB error.txt](https://github.com/firebase/firebase-js-sdk/files/6638862/FB.error.txt)

**Comment by Feiyang1** [comment] 2021-06-11 18:01
Thanks for the error log! I don't think we changed indexedDB schema from 7 to 8. Even if we did, we should take care of the upgrade gracefully.

@schmidt-sebastian Can you please take a look?

**Comment by var-const** [comment] 2021-06-19 02:08
We did introduce a schema upgrade (from version 10 to 11) in [`8.1.0`](https://github.com/firebase/firebase-js-sdk/commits/firebase%408.0.2)  (see #3594). However, trying out FriendlyEats, I could upgrade from `7.21.0` to `8.6.5` without any issues. @wu-hui Andy, do you have any ideas?

**Comment by wu-hui** [comment] 2021-06-21 14:12
It was across a major version bump, but if it is fixed by clearing all cache, then maybe it is related to the bundles change. Although, it only added stuff, not changing existing data. 

Do you have sourcemap for chunk-vendors.1f431f9a.js ?

**Comment by olivierkrener** [comment] 2021-06-22 13:54
Unfortunately I dont have more info than what I have already published

**Comment by looptheloop88** [comment] 2021-07-08 15:25
Hi @olivierkrener, just wanted to ask and see if you're still having the similar issue when using the latest JS SDK version?

**Closed** 2021-07-21 01:02 UTC
Labels: api: firestore, needs-info, no-recent-activity

**Comment by olivierkrener** [comment] 2021-07-21 08:57
> Hi @olivierkrener, just wanted to ask and see if you're still having the similar issue when using the latest JS SDK version?

As I mentioned, after clearing the cache, the install went fine - but now I cannot reproduce the state when the issue occurred.

**Comment by var-const** [comment] 2021-07-22 00:11
Thank you for the update. Unfortunately, we were unable to reproduce this issue by just doing an upgrade between these two versions, so there must have been some additional factor triggering it that would probably be impossible to determine now. Please let us know if you run into any more trouble.
