### ISSUE TITLE
Next JS deployed via Vercel started failing with release push for 8.6.4

### ISSUE THREAD

**Issue by joshketellapper** [firebase/firebase-js-sdk#4975] opened 2021-06-03 23:33 UTC
* Browser version: Npm Build
  * Firebase SDK version: 8.6.4
  * Firebase Product: Firebase

Our build started failing since we were using `"firebase": "^8.6.1",` in our project.json. 

Error:

```
17:27:04.330  	Failed to compile.
17:27:04.330  	./node_modules/@firebase/firestore/dist/esm5/prebuilt-db9cc925-eb007c37.js
17:27:04.330  	Attempted import error: 'FetchXmlHttpFactory' is not exported from '@firebase/webchannel-wrapper' (imported as 'v').
17:27:04.331  	> Build error occurred
17:27:04.331  	Error: > Build failed because of webpack errors
17:27:04.332  	    at /vercel/path0/node_modules/next/dist/build/index.js:17:924
17:27:04.332  	    at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/telemetry/trace/trace.js:6:584)
17:27:04.408  	error Command failed with exit code 1.
17:27:04.408  	info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
17:27:04.427  	Error: Command "yarn run build" exited with 1
```

fix:

Update package.json to `"firebase": "8.6.3",`. Guessed this was with the 8.6.4 release since it was pushed a few hours ago. 

Sorry, if this is a https://github.com/vercel issue.

**Comment by RAGOpoR** [comment] 2021-06-04 04:25
I have same issue
```
Failed to compile.

./node_modules/@firebase/firestore/dist/esm5/prebuilt-db9cc925-eb007c37.js
Attempted import error: 'FetchXmlHttpFactory' is not exported from '@firebase/webchannel-wrapper' (imported as 'v').


> Build error occurred
Error: > Build failed because of webpack errors
    at /opt/homebrew/lib/node_modules/next/dist/build/index.js:15:918
    at async Span.traceAsyncFn (/opt/homebrew/lib/node_modules/next/dist/telemetry/trace/trace.js:5:584)
```

**Comment by looptheloop88** [comment] 2021-06-04 09:24
Hi @joshketellapper, thanks for the report. I will mark this issue as duplicate of #4977.

**Closed by looptheloop88** 2021-06-04 09:24 UTC
Labels: api: core
