### ISSUE TITLE
Query is not returning results

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [firebase/firebase-js-sdk#7726] opened 2023-10-26 20:07 UTC
### Operating System

Windows 11

### Browser Version

Chrome 118

### Firebase SDK Version

10.5.0 ; angularFire 16.0.0; rxFire 6.0.5

### Firebase SDK Product:

Analytics, AppCheck, Auth, Database, Firestore, Functions, Performance, Storage

### Describe your project's tooling

angular cli 16.2

### Describe the problem

Upgrade of firebase 9.2.3 to 10.5.0
in our automated testing that runs on playwright, there are now queries/connections of angularFire that never (after 20 seconds) resolve. This is consistent.

### Steps and code to reproduce issue

I'm adding the code that actually calls angularFire to connect to Firestore.
I'm also adding the logging that has firestore logging set to debug
And the playwright trace file

**Comment by LanderBeeuwsaert** [comment] 2023-10-26 20:08
[Uploading organisation_crud_0_trace.zip…]()
![organisation_crud_testsuite_0](https://github.com/firebase/firebase-js-sdk/assets/1098243/e4693d8a-2681-48ac-8287-e44f2a2c0ff9)
[organisation_crud_testsuite_0.txt](https://github.com/firebase/firebase-js-sdk/files/13182365/organisation_crud_testsuite_0.txt)

**Comment by LanderBeeuwsaert** [comment] 2023-10-26 20:09
[organisation_crud_0_trace.zip](https://github.com/firebase/firebase-js-sdk/files/13182383/organisation_crud_0_trace.zip)

**Comment by LanderBeeuwsaert** [comment] 2023-10-26 20:10
<img width="1323" alt="image" src="https://github.com/firebase/firebase-js-sdk/assets/1098243/8be0ad75-0e17-48fb-a559-acf9e445dcb2">

**Comment by tom-andersen** [comment] 2023-10-27 16:44
We are tracking this issue, and will have a fix out soon. For now, you can use up to version 10.3.1.

**Comment by tom-andersen** [comment] 2023-10-27 16:53
This is a duplicate of: https://github.com/firebase/firebase-js-sdk/issues/7652

**Closed** 2023-10-27 16:53 UTC
Labels: bug, duplicate, api: firestore

**Comment by MarkDuckworth** [comment] 2023-10-27 22:26
@LanderBeeuwsaert, we released a fix for hanging queries so you can now use v10.5.2.
