### ISSUE TITLE
Firestore doesn't support JavaScript objects with custom prototypes

### ISSUE THREAD

**Issue by nomagick** [firebase/firebase-js-sdk#8337] opened 2024-06-26 08:17 UTC
### Firebase SDK Product:

Firestore

### Describe the problem

Firestore doesn't support JavaScript objects with custom prototypes.

"Doesn't support JavaScript objects with custom prototypes" means it would not work with custom classes.

This disability had caused mass regression in code quality.

Could you simply call `toJSON()` of any unknown object or pick its own properties like a normal person would do?

**Comment by tom-andersen** [comment] 2024-06-26 17:49
We explicitly decided to not support serialization of custom classes for the Web and Node.JS client as we won't be able to deserialize back into these types. I will happily bring any suggestions on how to improve this up for team discussion. I think allowing writes of custom classes will create unexpected results for some developers when trying to use data read back from Firestore.

I think the functionality you are looking for can be found in converters. See: [Custom objects](https://firebase.google.com/docs/firestore/manage-data/add-data?_gl=1*nkb4dq*_up*MQ..*_ga*MTU3MzE5MzcxNi4xNzE5NDIzMzE3*_ga_CW55HF8NVT*MTcxOTQyMzMxNy4xLjAuMTcxOTQyMzMxNy4wLjAuMA..#custom_objects)

**Comment by nomagick** [comment] 2024-06-27 04:02
As a library it needs to be neutral to developer expertise level.
It should not expect that the developer would not really know what they are doing and dictate a "safe" way.

More importantly, it needs to be upward compatible with the project, if someone tries to improve code quality and manage the code towards better maintenance and readability.

In the case of Javascript, the native `JSON.stringify` and `JSON.parse` already demonstrated the way of doing serialization and deserialization in Javascript world, also setting a base line of doing so. 
People would expect similar behavior when they see a `serialize` / `deserialize` feature.

The custom classes, are all subclasses of `Object`, you should treat them the same way as plain Objects, instead of refusing to process them. 

That is, only export the `enumerable` `ownProperties` of an object when serializing, and create simple object when deserializing.
You can also refer to MongoDB driver and see how they serialize and deserialize objects.

**Comment by tom-andersen** [comment] 2024-07-02 13:30
I'll take your suggestion up for discussion with the team.

**Comment by tom-andersen** [comment] 2024-07-02 18:20
Duplicate of: https://github.com/firebase/firebase-js-sdk/issues/476

**Comment by wu-hui** [comment] 2024-07-02 18:20
This has been discussed before:

https://github.com/firebase/firebase-js-sdk/issues/476
https://github.com/googleapis/nodejs-firestore/issues/143

Our reasoning remains, in particular what you proposed does not solve the concerns raised in https://github.com/firebase/firebase-js-sdk/issues/476. 

What works for other tools might not be a good fit for our product, and we will not support this feature unless we have good answers to the concerns we had. Also, you can do what you want to achieve with converters and customize however you want to serialize/deserialize custom prototypes, you are not limited AFAICT.

One more note: you are welcome to make feature request and propose designs to help us implement this feature. But please keep your comments respectful with your future communications. Please refer to our code of conduct: https://github.com/firebase/.github/blob/c189bc7785a73039b6002050777a2dbea624f38c/CODE_OF_CONDUCT.md

**Closed by wu-hui** 2024-07-02 18:20 UTC
Labels: api: firestore, feature request
