### ISSUE TITLE
V9 deleteUser RecaptchaVerifier Error (auth/argument-error)

### ISSUE THREAD

**Issue by RaheutRahwana** [firebase/firebase-js-sdk#5443] opened 2021-09-04 06:36 UTC
### [REQUIRED] Describe your environment

  * Operating System version: Fedora Linux 34
  * Browser version: Version 95.0.4621.4 (Official Build) dev (64-bit)
  * Firebase SDK version: 9.0.1
  * Firebase Product: auth

#### Steps to reproduce:
Import: deleteUser GoogleAuthProvider reauthenticateWithPopup RecaptchaVerifier and dependencies.
Now load RecaptchaVerifier and then run delet user.
**Deleting user was fine** but I get:
```
FirebaseError: Firebase: Error (auth/argument-error).
    at createErrorInternal (assert.ts:95)
    at _assert (assert.ts:126)
    at RecaptchaVerifier.validateStartingState (recaptcha_verifier.ts:206)
    at new RecaptchaVerifier (recaptcha_verifier.ts:120)
```
There is no error without loading/running RecaptchaVerifier.

#### Relevant Code:

RecaptchaVerifier
```javascript
const recaptchaVerifier = new RecaptchaVerifier("recaptcha", {}, auth);
let recaptchaWidgetId;
recaptchaVerifier.render().then((widgetId) => {
  recaptchaWidgetId = widgetId;
}).catch(console.error);
```
deleteUser
```javascript
button.onclick = () => {
  reauthenticateWithPopup(user, new GoogleAuthProvider()).then((result) => {
    return deleteUser(result.user);
  }).catch(console.error);
};
```

**Comment by sam-gc** [comment] 2021-09-07 15:45
Hi @RaheutRahwana, thanks for filing this. I tried reproducing this issue, but the code works for me. The assert that's failing in your case (thanks for the stack trace!) appears to be this one:
https://github.com/firebase/firebase-js-sdk/blob/10c7b49489a517164dd77de41e11f82776db2562/packages/auth/src/platform_browser/recaptcha/recaptcha_verifier.ts#L206-L210

There may be something else going on here. Your recaptcha setup is not invisible per the code snippet, so the only other part that's failing is that the recaptcha container must have other child nodes. Can you confirm if any other nodes exist in the DOM under the `<div id="recapctha">` element?

**Comment by RaheutRahwana** [comment] 2021-09-08 03:12
Hi @sam-gc, thanks for the reply.

>Can you confirm if any other nodes exist in the DOM under the `<div id="recapctha">` element?

I can confirm that there are no other nodes under that DOM.

After doing some re-investigation, I found that this happened because the `const recaptchaVerifier` variable was declared inside the `onAuthStateChanged()` function. After I moved it out, no more errors were thrown. Everything worked as expected.

This code is the embodiment of sdk version 8 to version 9. In version 8 this does not happen. Is this normal? Thanks again.

Before:
```javascript
onAuthStateChanged(auth, (user) => {
  if (user) {
    const recaptchaVerifier = new RecaptchaVerifier("recaptcha", {}, auth);
    let recaptchaWidgetId;
    recaptchaVerifier.render().then((widgetId) => {
      recaptchaWidgetId = widgetId;
    }).catch(console.error);

    button.onclick = () => {
      reauthenticateWithPopup(user, new GoogleAuthProvider()).then((result) => {
        return deleteUser(result.user);
      }).catch(console.error);
    };
  }
});
```
After:
```javascript
const recaptchaVerifier = new RecaptchaVerifier("recaptcha", {}, auth);
onAuthStateChanged(auth, (user) => {
  if (user) {
    the rest of the code...
  }
});
```

**Comment by sam-gc** [comment] 2021-09-09 16:13
Hmm, it should also fail in v9, though it's possible there is some small behavioral deviation. The fix makes sense: you're associating a single `div` with a single `RecaptchaVerifier`. I'm going to go ahead and close this out for now, but feel free to reopen if the issue reappears.

**Closed by sam-gc** 2021-09-09 16:13 UTC
Labels: api: auth, needs-attention, v9

**Comment by johnsutor** [comment] 2021-10-05 16:49
Something that worked for me (using Next JS and Firebase v9) is to use React Effects in the following manner:
```js
    useEffect(async () => {
        if (process.browser && !document.getElementById('recaptcha-container').hasChildNodes()) {
            const recaptchaVerifier = new RecaptchaVerifier('recaptcha-container', {
                'size': 'normal',
            }, auth);
            const recaptchaId = await recaptchaVerifier.render()
            const verified = await recaptchaVerifier.verify()
            if (verified.length) {
                setRecaptchaSolved(true)
            }
        }
    })
```
