### ISSUE TITLE
Unable to resolve module react-native-community/async-storage

### ISSUE THREAD

**Issue by paarasbhandari** [firebase/firebase-js-sdk#1899] opened 2019-06-21 04:22 UTC
![Simulator Screen Shot - iPhone X - 2019-06-21 at 00 20 38](https://user-images.githubusercontent.com/31348197/59897424-997fcb00-93ba-11e9-8e40-1e2caa82d5d3.png)

**Comment by hsubox76** [comment] 2019-06-21 18:40
This is caused by this recent change: https://github.com/firebase/firebase-js-sdk/pull/1879

I think that the problem is that it's only checking for the very specific error code 'MODULE_NOT_FOUND' and perhaps a different error code is being thrown in Expo.  Currently working on a fix that will try to require the React Native core bundled AsyncStorage after any error on the first require call.

In the meantime, the quickest fix would be to install `@react-native-community/async-storage` into your React Native project as it will be required in the future anyway (React Native is deprecating the version bundled with React Native core).

We're also working on getting documentation to reflect this.

**Comment by hsubox76** [comment] 2019-06-21 18:43
Duplicate of #1898

**Closed by hsubox76** 2019-06-21 18:43 UTC
Labels: api: core
