### ISSUE TITLE
5.0.4 Typescript definitions are broken

### ISSUE THREAD

**Issue by swftvsn** [firebase/firebase-js-sdk#882] opened 2018-05-30 07:04 UTC
### [REQUIRED] Describe your environment

  * Operating System version: High Sierra
  * Firebase SDK version: 5.0.0, 5.0.1, 5.0.2, 5.0.3, 5.0.4
  * Firebase Product: firestore, auth

### [REQUIRED] Describe the problem
Can't compile typescript project.
#### Steps to reproduce:
Update to any of the 5.x.x series and you can't compile anymore.. This problem has been discussed in #767 
#### Relevant Code:

```ts
import { SomeClass } from '@firebase/firestore-types'
```

results in 
```ts
ERROR in ./src/app/service/some/some.service.ts
Module not found: Error: Can't resolve '@firebase/firestore-types' in '/Users/someuser/git/someproject/src/app/service/some'
```

Repro here: 
https://github.com/pyoner/vue-firebase-plugin
run: npm run test
here travis job result https://travis-ci.org/pyoner/vue-firebase-plugin/jobs/382075803

**Comment by mikelehen** [comment] 2018-05-30 16:19
Josh, could you by chance take a look at this and #767 and provide guidance?

**Comment by jshcrowthe** [comment] 2018-05-30 19:02
I'm closing this as a duplicate of #767 response will be there. I think have an idea of what is going on.

**Closed by jshcrowthe** 2018-05-30 19:02 UTC
Labels: Component-Firestore
