### ISSUE TITLE
".info/serverTimeOffset" does not work anymore

### ISSUE THREAD

**Issue by l2aelba** [firebase/firebase-js-sdk#2043] opened 2019-08-01 08:22 UTC
### [REQUIRED] Describe your environment

  * Operating System version: Browsers
  * Browser version: All
  * Firebase SDK version: 6.3.3
  * Firebase Product: database

### [REQUIRED] Describe the problem

I am using ```.ref('.info/serverTimeOffset')``` for getting servertime's offset.
But seems like an update I upgrade from v5 to v6 it does not  work anymore

#### Steps to reproduce:

Try code below. It just still waitting...
#### Relevant Code:
```js
const getServerTimeOffset = await firebase.database().ref('.info/serverTimeOffset').once('value')
console.log(getServerTimeOffset)
```

**Comment by l2aelba** [comment] 2019-08-01 08:29
Oh I found this and its work after I downgraded to 6.2.3

![Screenshot 2019-08-01 at 10 28 18](https://user-images.githubusercontent.com/983458/62277778-1e90e200-b447-11e9-8ae6-1aa1bb221b05.png)
https://firebase.google.com/support/release-notes/js

**Comment by schmidt-sebastian** [comment] 2019-08-02 00:04
@l2aelba Sorry about the trouble. You should now be able to update your build to the latest version. 

Let us know if you still encounter this issue and we will re-open this.

**Comment by glauberramos** [comment] 2019-08-02 04:53
I believe this issue is still happening, just tested with 6.3.4 @schmidt-sebastian. I can't get any value for `firebase.database().ref('/.info/serverTimeOffset')`

**Comment by schmidt-sebastian** [comment] 2019-08-02 05:12
Just to double check - did you include the slash as in your comment? It should just be ".info/serverTimeOffset" as the issue description. Thanks!

**Comment by glauberramos** [comment] 2019-08-02 05:14
I just tried without the slash now and still can't get any value

**Comment by puf** [comment] 2019-08-02 08:25
I just tried this and indeed am unable to get the `.info/serverTimeOffset` on SDK version 6.* (including 6.3.3). See https://jsbin.com/voqivel/edit?html,js,console

**Comment by schmidt-sebastian** [comment] 2019-08-02 15:57
Playing with the snippet above, I was able to get the serverTimestampOffset the first couple of times. I am however now also not able to see its value. I will file an internal bug for us look into this.

**Comment by puf** [comment] 2019-08-02 23:33
I'm consistently unable to get the offset with 6.3.*. Before that it seems to work.

**Comment by glauberramos** [comment] 2019-08-06 18:19
Hello @schmidt-sebastian, any update on this? It would be nice to have an idea when this will be fixed because it's currently blocking me in using the latest version of Firebase with the encoding issue fixed (#2035). Thanks

**Comment by schmidt-sebastian** [comment] 2019-08-06 18:40
I'm currently a bit swamped and am planning on looking at this next week. Note that you should be able to go back a couple of releases, as the underlying issue for #2035 was a regression introduced in UglifyJS earlier this year.

**Comment by glauberramos** [comment] 2019-08-06 18:42
Thanks! I will try an older version.

**Comment by schmidt-sebastian** [comment] 2019-08-07 20:14
This will be fixed when https://github.com/firebase/firebase-js-sdk/pull/2061 is merged, likely in the next version.

**Closed** 2019-08-07 20:45 UTC
Labels: api: database
