### ISSUE TITLE
Lighthouse "DOM mutation events" fail audit

### ISSUE THREAD

**Issue by yaronyosef** [firebase/firebase-js-sdk#335] opened 2017-11-28 14:31 UTC
### [REQUIRED] Describe your environment

  * Operating System version: macOS High Sierra 10.13
  * Firebase SDK version: "0.1.3"
  * Firebase Product: database

### [REQUIRED] Describe the problem

Lighthouse Version: 2.6.0 fails at the "Best Practices" section:

"Uses Mutation Events in its own scripts
Audit error: Required EventListeners gatherer encountered an error: Protocol error (DOM.resolveNode): No node with given id found"

#### Steps to reproduce:

just run Lighthouse Version: 2.6.0 on firebase database 0.1.3 and you'll see that error.

#### Relevant Code:

```javascript
document.addEventListener('DOMContentLoaded', wrappedFn, false);
```
at "packages/database/src/core/util/util.ts" line 260

**Comment by jshcrowthe** [comment] 2017-11-28 17:55
Closing (dupe of #336)

**Closed by jshcrowthe** 2017-11-28 17:55 UTC
Labels: Component: Database
