### ISSUE TITLE
Inconsistent APIs to invoke auth emulator vs. firestore emulator in v9

### ISSUE THREAD

**Issue by etiennestuder** [firebase/firebase-js-sdk#5132] opened 2021-07-09 11:42 UTC
### [REQUIRED] Environment info

**firebase-tools:**

9.16.0

**Platform:**

macOS

### [REQUIRED] Test case

```
useAuthEmulator(auth, 'http://localhost:9099');
useFirestoreEmulator(db, 'localhost', 8080);
```

### [REQUIRED] Steps to reproduce

See `Test case` section for the currently inconsistent method parameters between the two APIs.

### [REQUIRED] Expected behavior

```
useAuthEmulator(auth, 'localhost', 9099);
useFirestoreEmulator(db, 'localhost', 8080);
```

Other APIs to use the different emulators might be affected, too.

### [REQUIRED] Actual behavior

See `Test case` section for the currently inconsistent method parameters between the two APIs.

**Comment by looptheloop88** [comment] 2021-07-09 12:59
I will close this issue and mark as a duplicate of #4781.

**Closed by looptheloop88** 2021-07-09 12:59 UTC
Labels: needs-triage

**Comment by etiennestuder** [comment] 2021-07-10 09:21
> Would you prefer:
> 
> 1. They stay inconsistent
> 2. They all move to `useEmulator('http://host:port')` form?

@samtstern I would have preferred #2 since consistent APIs require less mental overhead when working with them than inconsistent APIs, at least IMHO.

**Comment by samtstern** [comment] 2021-07-12 11:08
@etiennestuder thanks for the feedback!
