### ISSUE TITLE
memory leak in firestore().doc().set()

### ISSUE THREAD

**Issue by zeevl** [firebase/firebase-js-sdk#2372] opened 2019-11-19 22:20 UTC
### [REQUIRED] Describe your environment

  * Operating System version: macOS 10.15.1
  * Browser version: n/a (node 10.15 w/ jest 24)
  * Firebase SDK version: 7.4.0
  * Firebase Product: database

### [REQUIRED] Describe the problem
`jest --detect-leaks` reports memory leaks with `firestore().doc().set()`

#### Steps to reproduce:
```
git clone https://github.com/zeevl/firestore-set-memleak
cd firestore-set-memleak
vim test.test.js
# add firebase credentials to initalizeApp()
yarn install
npx jest --detect-leaks
```
Expected: success
Result: memory leaks detected

**Comment by rommelpe** [comment] 2019-11-20 15:16
Thank you for taking time filling this issue. This may have seem to be related to issue https://github.com/googleapis/nodejs-firestore/issues/768. I'll file a report and confirm this internally.

**Comment by mikelehen** [comment] 2019-11-26 00:07
Thanks for the report.  This isn't _too_ surprising.  Firebase uses various singleton instances, etc. to track state.  I can actually reproduce the leak reported by jest with just:
```
const firebase = require('firebase/app');
require('firebase/firestore');

describe('test', () => {
  it('doesnt leak memory', async () => {
  })
})
```

If you're running into a specific issue with unbounded memory usage we can look into it, but we don't provide any guarantees about cleaning up all traces of the SDK when it comes to memory usage.

Can I ask how important this is to you and what your overall goal is?  We would likely accept (noninvasive) PRs to clean up memory usage but beyond that I'm not sure if/when we'd be able to invest much time into this.  Thanks!

**Comment by MaximeHeckel** [comment] 2020-09-30 19:41
@mikelehen @zeevl my team actually is running into this issue

Started looking at why our Jest tests was running out of memory even for very easy test (I saw a high heap usage like 900MB for a simple hello world)

Are there or has there been any plans to address this? It's not blocking or anything but definitely worrisome as it's making some of our Jest test suite unstable

**Comment by melliu** [comment] 2020-10-19 15:49
we experience memory leaking on production when using firestore too,

       admin.initializeApp();
       admin.app().firestore().doc().set();
       admin.app().firestore().doc().update();

![image](https://user-images.githubusercontent.com/6526913/96474424-caffe500-1200-11eb-82df-c638d293ccfb.png)

**Comment by dconeybe** [comment] 2020-11-20 19:04
@melliu My sincere apologies for sitting on your issue report for so long. Based on the code snippet you provided, it looks like you are using the Admin SDK (not the Web SDK). If that is the case then the correct repository for this issue is https://github.com/googleapis/nodejs-firestore. I'd be happy to log this issue there on your behalf if you'd like. In order to do that it would be helpful (but not required) to get some additional information from you:

1. What OS are you running on (e.g. Windows, Mac, Linux)?
1. What Node.js version are you using?
1. What npm version are you using?
1. Can you provide a minimal app to reproduce (e.g. a GitHub repository)?
1. What tool did you use to produce that graph that you included?

Thank you for your time and sorry again for not responding sooner.

**Comment by dconeybe** [comment] 2020-11-20 19:11
@MaximeHeckel Please accept my sincere apologies for taking so long to reply to your comment. As mentioned in an earlier comment, we do not promise to clean up every single object when calling `app.dispose()`; however, unbounded memory growth or extreme memory consumption (900MB in your case) is concerning. Are you able to provide some more details about the memory issues that you are experiencing? A sample app and/or steps to reproduce, if available, would be helpful. Thank you.

**Comment by MaximeHeckel** [comment] 2020-11-23 21:10
hey @dconeybe , no worries, I went around the issue and decided to manually mock any firestore/firebase dependent call or functions. This reduced our memory leakage enough to make our unit tests running again

**Comment by dconeybe** [comment] 2020-11-25 19:13
Thanks for the response, @MaximeHeckel. From what I can tell, the only action remaining for the Firestore dev team is to potentially open up a similar ticket in the nodejs-firestore repository on behalf of @melliu. As a result, I've added the "needs-info" tag, which will automatically close this issue if there are no more responses.

**Closed** 2020-12-09 02:02 UTC
Labels: api: firestore, needs-info, no-recent-activity
