### ISSUE TITLE
[Firestore] Awaiting doc manipulation hangs until coming back online with persistence

### ISSUE THREAD

**Issue by Snugug** [firebase/firebase-js-sdk#6515] opened 2022-08-08 00:43 UTC
### [REQUIRED] Describe your environment

  * Operating System version: Mac OS 12.1
  * Browser version: Chrome 103.0.5060.134
  * Firebase SDK version: @firebase/firestore 3.4.12/
  * Firebase Product: Firestore (auth, database, storage, etc)

### [REQUIRED] Describe the problem

`await`ing a DB function (`addDoc`, `writeBatch`, `updateDoc`, `setDoc` tried, likely fails with `deleteDoc` too) when offline and persistence is enabled correctly writes to the IndexedDB database and triggers relevant `onSnapshot` listens, but doesn't resolve, leaving code hanging until the user comes back online. Because the promises won't resolve, anything more than simple updates are unusable offline and the same Firestore code fundamentally doesn't work the same when offline and online, even with persistence enabled.

#### Steps to reproduce:
* Initialize Firebase app with `{initializeApp} from 'firebase/app'` using standard Firebase config
* Create a Firestore DB using `{initializeFirestore} from 'firebase/firestore'` referencing previous app
* Enable IndexedDB persistence for that Firestore DB using `{enableIndexedDbPersistence} from 'firebase/firestore'`
* `await` the promise completion of `addDoc`, `writeBatch`, `updateDoc`, or `setDoc` from `'firebase/firestore'` and observe the results with `onSnapshot` and log a message when the `await` is complete.
  * Notice when online, this works as expected
  * **Problem** Notice when offline (Chrome Dev Tools->Offline), the change completes (`onSnapshot` observes the change) but the `await`ed function stalls and won't complete (move on to the `log` after the `await`) until _after_ you come back online.

#### Relevant Code:

```javascript
import { initializeApp } from 'firebase/app';
import {
  enableIndexedDbPersistence,
  CACHE_SIZE_UNLIMITED,
  initializeFirestore,
  addDoc,
  updateDoc,
  ref,
  doc,
  collection,
  query,
  where,
  onSnapshot
} from from 'firebase/firestore';

const firebaseConfig = { /* config here */ };
const firebase = initializeApp(firebaseConfig);
const db = initializeFirestore(firebase, {
  cacheSizeBytes: CACHE_SIZE_UNLIMITED,
});
enableIndexedDbPersistence(db);

const todos = query(collection(db, 'todos'), where('done', '==', false));
onSnapshot(todos, s => s.docs.map(d => console.log(d.data()))); // Will fire both online and offline as the persisted data does get written to/updated correctly


// Attached to a text input
async function change(e) {
  const id = e.target.dataset.id;
  const value = e.target.value;

  try {
    if (id) {
      const ref = doc(db, `todos/${id}`);
      await updateDoc(ref, { done: true });
      console.log('Done!');  // Won't fire when offline
    } else {
      const ref = collection(db, 'todos');
      await addDoc(db, {text: value, done: false});
      console.log('Added!'); // Won't fire when offline
  } catch (e) {
    console.error(e); // There's no error triggered when offline, it just hangs
  }
}
```

**EDIT: Added try/catch to show I'm not getting an error**

**Comment by jorroll** [comment] 2022-08-08 21:22
@Snugug I'm just a Firebase user like yourself (i.e. I'm not on the Firebase team), but this is working as intended and is also [stated in the docs](https://firebase.google.com/docs/reference/js/firestore_.md#adddoc).

For example, documentation for `addDoc()` (similar to `setDoc()` and the other CRUD functions).
> A Promise resolved with a DocumentReference pointing to the newly created document after it has been written to the backend (Note that it won't resolve while you're offline).

I'd say that they could do a better job highlighting this detail in the docs though. For example, it's not mentioned on the [`add data` section](https://firebase.google.com/docs/firestore/manage-data/add-data) of the documentation but should be.

> the same Firestore code fundamentally doesn't work the same when offline and online, even with persistence enabled.

I agree that the SDK's API could be improved here (e.g. it should be easier to know when a change has been integrated into the local cache), but I think it's reasonable for the promises to only resolve when the change has been committed on the server. Of course, if the Firestore SDK offered versions of the CRUD functions (i.e. `setDoc()`, etc) that returned observables that emitted an event when the change had been integrated into the local cache and completed when committed on the server, I'd probably take advantage of them.

**Comment by Snugug** [comment] 2022-08-09 10:17
Thanks, I def missed that as it appears to only be mentioned there in the auto-generated docs but neither in the CRUD nor the persistence docs. The reason I said "Firestore code fundamentally doesn't work the same when offline and online" is because the persistence docs say it should:

> To use offline persistence, you don't need to make any changes to the code that you use to access Cloud Firestore data. With offline persistence enabled, the Cloud Firestore client library automatically manages online and offline data access and synchronizes local data when the device is back online.

I still think this should be considered a bug. It breaks user expectations based on (most) available documentation, is very difficult to work around in user land (my initial thought is needing to set up an observable factory, combining your CRUD action with `onSnapshot` to listen for when those changes occur in cache and again for when the promises resolve), and effectively makes persistence mode a read-only and removing the ability to build offline-first apps with Firestore.

Another option for resolving this, if wanting to continue to provide Promises for their language-level control support, would be change the return from a `DocumentReference` to a Promise for one, with the promise for one resolving once it's bee successfully written to the DB. I guess the question there is (and this isn't something I've been able to test yet) will FS web "try again" with data in the cache after reload, or does it rely on keeping that promise unresolved to actually write back to the live DB?

**Comment by dconeybe** [comment] 2022-08-09 20:23
Hi @Snugug. Sorry for the confusion this has caused you. As @jorroll mentioned, this is indeed expected, and intended behavior. It's been this way for so long that it would be a massively breaking change if we ever changed this contract. So, we're stuck with it. We don't have any plans to change this behavior or provide an alternate API to wait for the write to local cache separately from the write to the backend. We do, however, provide `waitForPendingWrites()`, which returns a promise that resolves once _all_ local writes have been written to (or rejected by) the backend: https://firebase.google.com/docs/reference/js/firestore_#waitforpendingwrites.

**Comment by Snugug** [comment] 2022-08-09 22:05
@dconeybe is there an equivalent for cache? The problem isn't waiting for the backend, it's not blocking work after something's been written to the cache. Without something similar, this becomes very hard to solve in user-space and I'd ask it be re-opened, maybe as a feature request.

**Comment by dconeybe** [comment] 2022-08-10 19:18
Since @Snugug is a fellow Googler, we were able to talk and he told me about a solution he came up with which I'd like to share here for future readers of this thread.

There is no way to directly listen for the local cache being updated for a particular write. One workaround is to include a key/value pair in the document with a unique ID in the last write to the document. Then, add a snapshot listener and wait for a snapshot that includes that unique ID key/value pair. At that point you know that the write has been committed to local cache and future snapshot listeners will get a snapshot that includes those writes.

**Closed by dconeybe** 2022-08-10 19:18 UTC
Labels: api: firestore

**Comment by Snugug** [comment] 2022-08-11 00:06
Here's a working code sample for anyone looking to implement the above recommendation themselves:

```js
  function offlineAdd(ref, value) {
    // Hold the value
    let v = value;
    // Hold the reference
    let r = ref;
    // Hold the query
    let q;

    // // OPTIONAL: Let strings be passed in as queries
    // if (typeof ref === 'string') {
    //   // If it's an even number of path parts, it's a doc, otherwise it's a collection
    //   if (ref.split('/').length % 2 === 0) {
    //     r = doc(db, ref);
    //   } else {
    //     ref = collection(db, ref);
    //   }
    // }

    // Collections need a UID added to their value to listen for
    if (r.type === 'collection') {
      // Create a unique ID to listen for
      const uid = crypto.randomUUID();
      v = { ...value, _writeid: uid };
      q = query(r, where('_writeid', '==', uid));
    } else {
      q = query(r);
    }

    // Return a Promose to work with standard async/await flow
    return new Promise((res, rej) => {
      try {
        // Capture the document, which will be a promise when the document gets written to the backend
        const document = addDoc(r, v);

        // Capture the snapshot, which will fire when the document gets written to the cache
        const unsubscribe = onSnapshot(q, () => {
          // Unsubscribe from the snapshot so it doesn't continue to fire
          unsubscribe();
          // Resolve the promise with an object with the document (so `await`ing the promise won't also `await` the backend write)
          res({ document });
        });
      } catch (e) {
        // Reject if there's an error
        rej(e);
      }
    });
  }
```
