### ISSUE TITLE
XMLHttpRequest error when navigating away from a page 

### ISSUE THREAD

**Issue by LewPerren** [firebase/firebase-js-sdk#4527] opened 2021-02-25 16:06 UTC
**Describe your environment**

  * Operating System version: MacOS Mojave 10.14.6
  * Browser version: Safari 13.1.2 & Chrome 88.0.4324.192
  * Firebase SDK version: 8.2.9
  * Firebase Product: firestore 
 
We suspect this error will show in other environments.
 
**Describe the problem:**

The following error shows intermittently in the Javascript console when navigating away from pages:

"XMLHttpRequest cannot load https://firestore.googleapis.com/google.firestore.v1.Firestore/Listen/channel? .... due to access control checks."
xhrio.js:645

The error does not seem to cause any problems, but we would still like to understand why it is happening and hopefully remove the issue.

**Steps to reproduce:**

This error can be reproduce by following your tutorial at: https://firebase.google.com/docs/firestore/quickstart. We set up a test project to reproduce the error. The errors:

XMLHttpRequest cannot load https://firestore.googleapis.com/google.firestore.v1.Firestore/Listen/channel?database=projects%2Ftesterror-e354e%2Fdatabases%2F(default)&gsessionid=o4gxow0wGZPErAvAcIB3p2wTBSGisgSICPDiHTKf2P4&VER=8&RID=rpc&SID=J4L2I5PrjTyVMZGoeqR2Sg&CI=0&AID=6&TYPE=xmlhttp&zx=9kswfhsajhtz&t=2 due to access control checks. 

Please note the Chrome console does not default to log XMLHttpRequests so you have to select the option. It is also helpful to have preserve logs selected so errors do not disappear.

**Relevant Code:**

This is intentionally as minimal as we could provide to show the error and is based upon your tutorial.

```javascript
<html>

<head>
    <script src="https://www.gstatic.com/firebasejs/8.2.9/firebase-app.js"></script>
    <script src="https://www.gstatic.com/firebasejs/8.2.9/firebase-firestore.js"></script>
</head>

<body>

    <script>
       
        firebase.initializeApp({
            apiKey: XXXXXX,
            authDomain: XXXXXX,
            projectId: XXXXX
        });

        var db = firebase.firestore();

        db.collection("users").get().then((querySnapshot) => {
            querySnapshot.forEach((doc) => {
                console.log(`${doc.id} => ${doc.data()}`);
            });
        });

    </script>

</body>

</html>
```

Thanks,

_Lew_

**Comment by dconeybe** [comment] 2021-02-25 16:16
Hi @LewPerren. I'm confident that this error message can be safely ignored. I'll dig into it, though, and will reply back to confirm and provide additional information and if we will take any steps to avoid the error.

**Comment by LewPerren** [comment] 2021-02-25 16:19
Thanks @dconeybe

**Comment by LewPerren** [comment] 2021-02-25 18:33
Hi @dconeybe,

The firebase.app().delete() method closes the connection and releases resources. This appears to get rid of the error. I realize I should not call the constructor directly, but to stick with the tutorial example I have called directly in the code below. I also added an await on the db.collection, else there is a race condition and the connection is lost before the data is received. Do you see any issues with this solution, assuming I do not need listeners?

``

<html>

<head>
    <script src="https://www.gstatic.com/firebasejs/8.2.9/firebase-app.js"></script>
    <script src="https://www.gstatic.com/firebasejs/8.2.9/firebase-firestore.js"></script>
</head>

<body>

    <script>

     window.onload = loadController();

        async function loadController() {

        firebase.initializeApp({
            apiKey: XXXXXX,
            authDomain: XXXXXX,
            projectId: XXXXX
        });

        var db = firebase.firestore();

        // await added to stop race condition

        await db.collection("users").get().then((querySnapshot) => {
            querySnapshot.forEach((doc) => {
                console.log(`${doc.id} => ${doc.data()}`);
            });
        });
     
     // proposed solution to issue

      firebase.app().delete();

}

    </script>

</body>

</html>
``

**Comment by dconeybe** [comment] 2021-02-26 16:24
@LewPerren I have confirmed that the "XMLHttpRequest cannot load ... due to access control checks" error is nothing to worry about. Another user had actually asked about the same thing 6 months ago (https://github.com/firebase/firebase-js-sdk/issues/3708) and after discussing internally (b/167265358 for Googlers) it was decided to not fix it.

Your suggested workaround of calling `firebase.app().delete()` is perfectly reasonable. Note that `delete()` returns a `Promise` so you may want to `await` on that as well.

> I realize I should not call the constructor directly

Could you clarify what you mean by this? I don't see any constructors being called directly in your code.

**Comment by LewPerren** [comment] 2021-02-26 18:44
@dconeybe 

Thanks for your help. On calling the constructor directly, I just meant that I could have assigned the firebase.initializeApp() to an instance variable and then called the delete() method against that instance. I believe this is the approach you recommend.

Thanks again.

Lew

**Comment by dconeybe** [comment] 2021-02-26 19:19
Ahh I see what you mean about the constructor. It *would* be ideal/cleaner to re-use the instance returned from `initializeApp()` but it will certainly work as you've written it.

I'm going to close this issue since I don't think there are further actions to be taken by the Firestore SDK team. If you disagree or have further comments/questions feel free to re-open it. Thanks for taking the time to submit this issue report!

**Closed by dconeybe** 2021-02-26 19:19 UTC
Labels: api: firestore
