### ISSUE TITLE
Failed to execute 'subscribe' on 'PushManager': Subscription failed - no active Service Worker

### ISSUE THREAD

**Issue by sara-jegorova** [firebase/firebase-js-sdk#5797] opened 2021-12-06 11:23 UTC
### [REQUIRED] Describe your environment

  * Operating System version: MacOS 12.0.1
  * Browser version: Chrome Version 96.0.4664.55 (Official Build) (x86_64)
  * Firebase SDK version: 9.5.0
  * Firebase Product: messaging

### [REQUIRED] Describe the problem

Sometimes calling messaging getToken returns the error: `Failed to execute 'subscribe' on 'PushManager': Subscription failed - no active Service Worker`. It seems to only occur on the first page load, when the user refreshes the notifications work and there's no error anymore.

#### Steps to reproduce:
1. Add `firebase-messaging-sw.js` to root of domain
2. Call firebase initializeApp
3. Call firebase getMessaging
4. Ask and approve browser notification permission
5. Add firebase onMessage listener
6. Call firebase`await getToken(messaging, {  vapidKey: <VAPID_KEY>  })`

Error sometimes appears with `Failed to execute 'subscribe' on 'PushManager': Subscription failed - no active Service Worker`

#### Relevant Code:
`firebase-messaging-sw.js` is at the root of project and firebase gets initialised right away:

```
import { initializeApp } from 'firebase/app';
import { getMessaging,  isSupported, Messaging } from 'firebase/messaging';

isSupported()
  .then((supported) => {
    if (supported) {
      initializeApp(firebaseConfig);
      messaging = getMessaging();
    } else {
      console.error('Browser does not support notifications');
    }
  })

const registerToken = async (
  messaging: Messaging
): Promise<{ token?: string; error?: unknown }> => {
  try {
    const currentToken = await getToken(messaging, {
      vapidKey: <VAPID_KEY>,
    });

    // server call with token
    await api.registerToken(currentToken);
    return { token: currentToken };
  } catch (error) {
    // Failed to execute 'subscribe' on 'PushManager': Subscription failed - no active Service Worker
    return { error };
    }
};
```

Since firebase handles registering `firebase-messaging-sw.js` itself, I had a look at the codebase, and it seems the issue originates from:
https://github.com/firebase/firebase-js-sdk/blob/f5a17143b1930b7b7b45d431ad21f50b236e4f80/packages/messaging/src/internals/token-manager.ts#L39

https://github.com/firebase/firebase-js-sdk/blob/master/packages/messaging/src/internals/token-manager.ts#L164

**Comment by zwu52** [comment] 2021-12-10 19:31
@sara-jegorova Thanks for reporting. We stopped supporting `getToken` for sw because it has some compatibility issue with older browser ([v9 API doc](https://firebase.google.com/docs/reference/js/messaging_sw). Please call `getToken` in window. 
Cheers

**Comment by sara-jegorova** [comment] 2021-12-13 08:41
@zwu52 Hi, sorry there was a miscommunication on my part, the code sample I gave is at the root of my project (index.ts), not in the service worker.

**Comment by zwu52** [comment] 2021-12-13 17:55
hmm. I can't reproduce the error. 

The error seems to indicate that the sw is unregistered by the time of the subscription call. You mentioned this is happens "sometimes" which is a bit intriguing to me. Because in `registerDefaultSSw.ts` file, we await for the registration process. 

Do you mind making a minimum reproducible repo I can look deeper into?

**Comment by sara-jegorova** [comment] 2021-12-14 11:57
I tried re-creating the setup I have but I wasn't able to reproduce the issue in there either. It is a rather tricky issue, because it only occurs when the user loads the page for the first time, and not for every user either... I'm attaching the setup anyways:
[firebase-issue-5797.zip](https://github.com/firebase/firebase-js-sdk/files/7711383/firebase-issue-5797.zip)

**Comment by zwu52** [comment] 2021-12-14 18:03
Thanks for the repo. Unfortunately I couldn't reproduce even on a freshly installed app
![Screen Shot 2021-12-14 at 9 58 36 AM](https://user-images.githubusercontent.com/24631855/146053984-40be882e-9c37-4ae9-b82d-5009ecbd7261.png). 

By "freshly installed", I removed the app's notification permission and cleared the site's cache. 

My educated guess is that there might be some wired racing going with the React setup you have, I noticed many `useEffect` hooks were applied. I would suggest to clean up a bit so that you are calling `app = getApp()`, `messaging=getMessaging(app)` and `getToken(messaging` in this sequence.   

Closing this ticket. Feel free to attach any further discovery and we could chat on the thread  🍻

**Closed by zwu52** 2021-12-14 18:03 UTC
Labels: api: messaging, v9
