### ISSUE TITLE
React Native, iOS: "Can't find variable: Image"

### ISSUE THREAD

**Issue by enzomd** [firebase/firebase-js-sdk#1279] opened 2018-10-03 18:02 UTC
```
Unhandled JS Exception: Can't find variable: Image
```

I get this message when I run a transaction on the iOS Simulator **offline**:

```js
const ok = await db.runTransaction(async (t) => {
    t.set(docRef, data);
    return true;
});
```

It retries the transaction around 3-5 times over around 2 minutes, then throws the Exception.

I am using the Xcode "Network Link Conditioner" to disable the network.

**Related**
https://github.com/firebase/firebase-js-sdk/issues/183

### Environment
- iOS Simulator
- MacOS,
- RN: 0.55.3
- Firebase (from yarn.lock):
```
firebase@^5.5.2:
  resolved "https://registry.yarnpkg.com/firebase/-/firebase-5.5.2.tgz#05fa180c058941dcbfc248882e829f2945aa0568"
    "@firebase/app" "0.3.4"
    "@firebase/auth" "0.7.7"
    "@firebase/database" "0.3.6"
    "@firebase/firestore" "0.8.2"
    "@firebase/functions" "0.3.1"
    "@firebase/messaging" "0.3.6"
    "@firebase/polyfill" "0.3.3"
    "@firebase/storage" "0.2.3"
```

**Comment by mikelehen** [comment] 2018-10-04 18:55
Do you by chance get callstack with that error?  Offhand I'm having trouble tracking down where it's coming from.  Or if you can throw a project on github that reproduces the problem, that would help.

**Comment by enzomd** [comment] 2018-10-07 18:16
> It's worth noting that transactions do not work offline

That is the reason I am using `runTransaction` - I want to get a fail message in response.

Because **there are no timeouts or cancellations for Promises**, the normal `await docRef.set(data)` does not resolve when offline.

The `runTransaction` API gives a failed Promise after a certain amount of time.

**I also want to avoid using the local cache**, which the Firestore APIs seem to use unpredictably even when its turned off via settings.

It would be good to have a `{source: "server"}` option for writes and onSnapshot (it exists for reads).

The `react-native-firebase` library also has critical bugs.

Do you think Im better of just using the HTTP API directly?


I could not get a proper stack trace from React Native. This is from Chrome, Im not sure if there is a better way?

![image](https://user-images.githubusercontent.com/23221295/46585091-fbceb080-ca63-11e8-95f7-98d8d4d6a7a8.png)

**Comment by mikelehen** [comment] 2018-10-08 16:49
Hrm, yeah, if you don't want caching or offline support, then the REST API may be a better option for you.  Though I don't think it supports realtime listens (as onSnapshot() provides), so if you're using that, it may not be a perfect fit. :-/

**Comment by fredrivett** [comment] 2018-11-14 14:00
I'm getting a similar issue, first bug report came in on Oct 17th 2018.

I'm not trying to access any images in Firebase which is what's confusing me about this error. Using the Firebase npm package (https://www.npmjs.com/package/firebase) to access our Firestore DB.

Sentry error report:
<img width="1119" alt="screenshot_2018-11-14_at_13_53_44" src="https://user-images.githubusercontent.com/1713859/48487238-877eee00-e815-11e8-8ff3-b6a0a0682132.png">

**Comment by Danelund** [comment] 2018-12-04 17:21
@fredrivett did you resolve? I'm seeing the same thing

**Comment by fredrivett** [comment] 2018-12-04 17:33
@Danelund no that error still persists for me. We're now actually looking to move away from Firebase to AWS, so haven't investigated much further. Are you on the latest version of the firebase-js-sdk? That's the next port of call I'm going to check, upgrade that and check back in. If you end up upgrading I'd be interested to hear if that fixes the issue.

**Comment by Danelund** [comment] 2018-12-07 18:31
@fredrivett  just upgraded to 5.5.7, seems to be working so far, but will have sentry report in from users :)

**Comment by fredrivett** [comment] 2019-01-10 11:47
@Danelund thanks for looping back. Did this fix it for you? We haven't got round to upgrading yet (I know), but be intrigued if it cleared things up your end.

**Comment by fredrivett** [comment] 2019-01-14 09:03
Hmmph. Super strange issue this. Does seem to be coming from Firebase but clearly not affecting everyone using the SDK in React Native as otherwise this thread would be flooded.

**Comment by mikelehen** [comment] 2019-01-19 02:16
Sorry for the delays.  I poked at this, and I have a hunch that the issue we're hitting is this `new Image()` [call](https://github.com/google/closure-library/blob/e656c0807353188f42b67722d56724a5afc13228/closure/goog/labs/net/webchannel/netutils.js#L110) in webchannel (one of our dependencies).  I've reached out to a dev on the team to see if we can get this resolved.

**Comment by fredrivett** [comment] 2019-01-19 11:19
No worries @mikelehen. Appreciate you taking a look.

**Comment by mikelehen** [comment] 2019-01-22 21:10
Internal tracking issue: b/123242479

**Comment by Huzaifaak** [comment] 2019-01-28 14:48
I am getting this issue with  "firebase": "^5.7.3". Maybe you can track this issue with this screenshot:
![screenshot_20190128-193924](https://user-images.githubusercontent.com/9552894/51843824-9e71ae80-2335-11e9-8ee8-3f1eb94d3976.jpg)

**Comment by wilhuff** [comment] 2019-03-05 18:11
@mikelehen FYI, the required webchannel fix has made it out to [public webchannel](https://github.com/google/closure-library/blob/master/closure/goog/labs/net/webchannel/netutils.js#L110).

**Comment by mikelehen** [comment] 2019-03-12 02:53
@wilhuff Thanks. I just checked and we picked up this change in https://github.com/firebase/firebase-js-sdk/commit/4983420937f1d8d0217a44ffdf505758f570dada so the issue should actually be resolved in the latest release.

Please holler if anybody is still running into this.

**Closed by mikelehen** 2019-03-12 02:53 UTC
Labels: api: firestore

**Comment by cawfree** [comment] 2019-07-03 15:29
Simple workaround:

> console.error = console.log;
