### ISSUE TITLE
Rate Limiting - Abuse protection #647

### ISSUE THREAD

**Issue by MSchmack** [firebase/firebase-js-sdk#2871] opened 2020-04-05 13:39 UTC
This might be the wrong place to bring up this "problem" but the issue [#647](https://github.com/firebase/firebase-js-sdk/issues/647) started a discussion about Rate Limiting that was closed without any mention of what's to come or to expect. 

Is there any update on the plans to tackle this gap in the security rules? @asciimike 

In the current situation one seems to be sol when a malicious party spams reads on the realtime database as even when rejected a security rule often triggers a read. As far as I know there is not even a way to see which person is doing the malicious queries. The previous thread contained a few more reasons why it's a important feature.

**Comment by dconeybe** [comment] 2020-04-07 04:36
Hi @MSchmack.  Thank you for contacting us with your concerns.  I'm currently talking to the team and some other teams to try and get you an answer.  I'll hopefully have a response in the next day or two.

**Comment by asciimike** [comment] 2020-04-07 04:48
Howdy @MSchmack, I no longer work on Firebase, so some of the other folks are going to have better idea of what's going on. I would rely on solutions like http://jsfiddle.net/firebase/VBmA5/ instead of something built in.

**Comment by MSchmack** [comment] 2020-04-07 09:57
Thanks @dconeybe .

@asciimike sad to hear. Thanks for the workaround but that solution only works in very niche situations. It ignores most of the issues listed in #647 and for a malicious users that would be one of the security rules that can be abused to spam reads on the rule side.

**Comment by dconeybe** [comment] 2020-04-08 18:37
I can confirm that at the moment there are no plans to implement this feature.  That being said, it is definitely worthwhile for us to consider.  This GitHub repository is, however, for the client SDK and not the correct place to get traction on this request.  In order to increase the visibility of this request and to allow others to +1 and comment please open a ticket with Cloud Firestore support.  To do this, go to https://firebase.google.com -> Support -> Bugs and Features -> Feature Request.  Be sure to include the link of this GitHub issue for context and mention b/135617967, which is another Google-internal ticket related to this request.  Thank you again for taking the time to create this ticket.  Since there is no further action to be taken in the client SDKs, I will close this issue.

**Closed by dconeybe** 2020-04-08 18:37 UTC
Labels: api: firestore

**Comment by pouledodue** [comment] 2020-04-20 19:12
@MSchmack did  you open the ticket ^^

I need this too to even consider Firestore as viable

**Comment by MSchmack** [comment] 2020-04-20 20:09
@pouledodue I've created the Ticket and will write an update once I get a response. In my experience these sorts of tickets end in a backlog like the lost ark in indiana jones but we'll see.

**Comment by MSchmack** [comment] 2020-04-22 20:01
@pouledodue Ticket has been processed.

> Thanks for reaching out, my name is Mau and I'll take care of this case.
> 
> That sounds really good, there's an ongoing discussion about this, I used your case as a vote up so the engineers can see how much impact is causing not having this feature. Please note that filing a feature request doesn't guarantee its approval. For now, you can keep an eye out for updates on our official blog and release notes for newly added products, features, and SDKs.
> 
> If you have any questions or another feature request, please contact us through our support channel.
> ref:_00D1Ux0Jq._5003p2PHDWb:ref
