### ISSUE TITLE
Performance issue with Firebase JS SDK v9 beta 2

### ISSUE THREAD

**Issue by nikhilag** [firebase/firebase-js-sdk#5078] opened 2021-06-29 10:31 UTC
After moving to v9 beta 2 sdk in a gatsbyjs project, I started getting the following 'Enable text compression' and 'Reduce unused javascript' issues in pagespeed insights:-

![image](https://user-images.githubusercontent.com/54072321/123782504-0a83e280-d8f3-11eb-9cbe-e9cf876798b3.png)

![image](https://user-images.githubusercontent.com/54072321/123783272-d0671080-d8f3-11eb-9024-f025012970d0.png)

This seems to be a performance bug connected with firebase auth. Kindly look into it.

**Comment by looptheloop88** [comment] 2021-06-29 13:57
Hi @nikhilag, thanks for the report. This issue might be due to the iframe being used by Firebase Authentication and loaded on certain situations on mobile.

I will mark this issue as duplicate of #4946.

**Closed by looptheloop88** 2021-06-29 13:57 UTC
Labels: api: auth, v9
