### ISSUE TITLE
Update AsyncStorage import

### ISSUE THREAD

**Issue by patrinoua** [firebase/firebase-js-sdk#6930] opened 2023-01-06 01:29 UTC
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@firebase/app@0.6.13` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@firebase/app/dist/index.rn.cjs.js b/node_modules/@firebase/app/dist/index.rn.cjs.js
index 7256b57..0c8ac25 100644
--- a/node_modules/@firebase/app/dist/index.rn.cjs.js
+++ b/node_modules/@firebase/app/dist/index.rn.cjs.js
@@ -645,7 +645,7 @@ function registerCoreComponents(firebase, variant) {
  * here
  */
 // eslint-disable-next-line @typescript-eslint/no-require-imports
-var AsyncStorage = require('react-native').AsyncStorage;
+var AsyncStorage = require("@react-native-async-storage/async-storage").AsyncStorage;
 firebase.INTERNAL.extendNamespace({
     INTERNAL: {
         reactNative: {
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by hsubox76** [comment] 2023-01-09 17:51
You didn't mention what the error/warning was that you are trying to fix but if it's similar to this one: https://github.com/firebase/firebase-js-sdk/issues/6493 then you'll want to import `AsyncStorage` yourself from `@ract-native-async-storage/async-storage` and then pass it to `getReactNativePersistence()`, and then pass that to `initializeAuth()`, per Sam's comment there.

We are hoping to make the community AsyncStorage package the default in a future breaking version of the Firebase SDK but for now, if we do this, it will break backwards compatibility.

**Comment by patrinoua** [comment] 2023-01-10 16:17
The warning I'm getting is

"AsyncStorage has been extracted from react-native core and will be removed in a future release"

https://stackoverflow.com/questions/55311228/how-to-remove-warning-async-storage-has-been-extracted-from-react-native-core

**Comment by hsubox76** [comment] 2023-01-10 17:42
Thanks, it seems to be the same issue as linked above, and it should go away if you pass the correct `AsyncStorage` (from the community package) into `getReactNativePersistence()` as described above.

Duplicate of https://github.com/firebase/firebase-js-sdk/issues/6493

**Closed by hsubox76** 2023-01-10 17:42 UTC
Labels: api: core, needs-attention
