### ISSUE TITLE
react native firebase

### ISSUE THREAD

**Issue by tiskender2** [firebase/firebase-js-sdk#884] opened 2018-05-31 06:20 UTC
my tsconfig.json getting this error when  i was import firebase to my project  "the  specified  path does not exist c:/../../config/tsconfig.base.json"  and  i dont have a config folder 
 how can i solve this error

**Comment by chardmd** [comment] 2018-06-02 00:33
`{
  "extends": "../../config/tsconfig.base.json",
  "compilerOptions": {
    "outDir": "dist",
    "declaration": false,
    "allowSyntheticDefaultImports": true
  },
  "exclude": [
    "dist/**/*"
  ]
}
`
I am also getting this error.

**Comment by tiskender2** [comment] 2018-06-04 23:34
when i was import firebase in app.js i am getting below error how can i solve this do you have any think ?

![capture](https://user-images.githubusercontent.com/17899883/40946982-fb2bd35e-6868-11e8-9096-ec696fb8c2be.PNG)

**Comment by liyuchenf1** [comment] 2018-06-05 12:45
delete the latest version of firebase, and npm install 5.0.2

**Comment by tiskender2** [comment] 2018-06-05 15:51
Which firebase version should i install ?

**Comment by liyuchenf1** [comment] 2018-06-05 15:53
5.0.2 npm

**Comment by tiskender2** [comment] 2018-06-05 21:45
didn't work
error = npm 5.0.2 not found

**Comment by liyuchenf1** [comment] 2018-06-07 13:15
I am not sure whether the latest firebase is working or not. 
5.0.2 works for me.
I mean firstly you should delete the firebase folder in your node_modules folder.
Then use npm to install 5.0.2 version. Command should be like npm install --save-exact firebase@5.0.2
You should find "firebase": "5.0.2" in your package.json

**Comment by tiskender2** [comment] 2018-06-08 05:53
Thanks its worked

**Comment by jshcrowthe** [comment] 2018-06-11 23:03
Hey all, I have had a hard time reproducing this error but I'm going to ensure that all of the `tsconfig.json` files have been removed from our built packages. That should help alleviate this: https://github.com/firebase/firebase-js-sdk/pull/915

**Comment by jshcrowthe** [comment] 2018-06-29 18:02
Duplicate of #871 closing.

**Closed by jshcrowthe** 2018-06-29 18:02 UTC
Labels: needs-triage
