### ISSUE TITLE
Firebase not support on Chrome 69.0.3497.81

### ISSUE THREAD

**Issue by adeelibr** [firebase/firebase-js-sdk#1220] opened 2018-09-11 11:59 UTC
Stack trace error:
```
code: "messaging/unsupported-browser"
message: "Messaging: This browser doesn't support the API's required to use the firebase SDK. (messaging/unsupported-browser)."
stack: "FirebaseError: Messaging: This browser doesn't support the API's required to use the firebase SDK.
```

Browser: Google Chrome
Version: Version 69.0.3497.81 (Official Build) (64-bit)
OS: Windows
Firebase SDK Version 5.4.
Firebase Product: Cloud Messaging

Steps To Reproduce:
Run any firebase app in the latest browser version of chrome.

**Comment by adeelibr** [comment] 2018-09-11 12:09
If there is any more information required from my end, let me know @for-anyone-who-reviews-this-issue. :)

**Comment by The-Don-Himself** [comment] 2018-09-14 09:29
@adeelibr I'm not a maintainer but could it be that you are running it in Incognito mode? Chrome blocks many APIs while running in that mode, I think its unfortunate they do that, but it does explain the issue you are facing because for me, same environment as your Firebase works well in Chrome but not in Incognito.

**Comment by adeelibr** [comment] 2018-09-14 10:08
No, I am not running it in incognito mode. It still throws the error. I hope a maintainer can help me solve this issue.

**Comment by The-Don-Himself** [comment] 2018-09-14 10:39
Ok, maybe try update Chrome to see if this error goes away, latest version is now 69.0.3497.92. Other than that, I'm out of ideas and sad I can't help you.

**Comment by The-Don-Himself** [comment] 2018-09-14 10:45
Or look into disabling all Chrome extensions to see if one is affecting it. Or for advanced debugging, look into your Chrome internal flags or settings (which can mess things up further).
I have no doubt in my mind that this has to be an isolated case so getting help here might be very hard given that its most like not an issue with Firebase. (otherwise there would be hundreds of complaints/issues).
All the best.

**Comment by The-Don-Himself** [comment] 2018-09-21 13:42
@adeelibr Any news on this? Can you close it? The new GitHub layout always draws my attention to opened/commented issues so I'd love to close it :)

**Comment by The-Don-Himself** [comment] 2018-09-21 14:33
Very unfortunate. And this is on the domain localhost? Or live domain with SSL? I'd suggest you create a reproducible demo on jsfiddle or similar, so that people can share and take a look at it. Also try disabling all extensions. There is a Chrome flag for it. For example, when I'm not in the mood to deal with cors, I have a .bat file on Windows with this content.

start "" "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --unsafely-treat-insecure-origin-as-secure="http://127.0.0.1" --user-data-dir="c:/_chrome_dev" --disable-web-security 

When I run that file, a totally new Chrome instance is started with those flags enabled. If you are on Windows, you can try that and let us know what happens.

**Comment by mmermerkaya** [comment] 2018-09-26 13:06
The code that checks if the browser has the necessary APIs is [here](https://github.com/firebase/firebase-js-sdk/blob/0beb028de38c74198592f47618400f9905d605da/packages/messaging/index.ts#L86). Can you make sure that you have all of these enabled?

Also you can use `messaging.isSupported()` to check if Messaging is supported, you don't need to use `try/catch`. Documentation [here](https://firebase.google.com/docs/reference/js/firebase.messaging#.isSupported).

**Comment by Syed687** [comment] 2018-09-27 11:30
code: "messaging/unsupported-browser"
message: "Messaging: This browser doesn't support the API's required to use the firebase SDK. (messaging/unsupported-browser)."
stack: "FirebaseError: Messaging: This browser doesn't support the API's required to use the firebase SDK.
Browser: Google Chrome
Version: Version 69.0.3497.81 (Official Build) (64-bit)
OS: Windows
Firebase SDK Version 5.4.
Firebase Product: Cloud Messaging

Please help to resolve this isuue.

**Comment by Syed687** [comment] 2018-09-27 13:04
Got fix: The issue pops up only in Http, In Https no issues.

**Comment by mmermerkaya** [comment] 2018-09-27 13:17
@Syed687 That is because service workers are only available on HTTPS websites. There's nothing Firebase can do about that. This is also mentioned in [our guide](https://firebase.google.com/docs/cloud-messaging/js/client).

I'm closing this issue. If you face a similar problem in the future, feel free to reply here and I'll reopen the issue if needed.

**Closed by mmermerkaya** 2018-09-27 13:17 UTC
Labels: Component-Messaging, Status: Repro Needed

**Comment by tyagip966** [comment] 2018-12-20 14:17
Runtime Error
Uncaught (in promise): FirebaseError: Messaging: This browser doesn't support the API's required to use the firebase SDK.


I found this error when I build the ionic application and run it on my mobile the application is blank but when I debug the application then above message is come

**Comment by mmermerkaya** [comment] 2018-12-20 17:18
@tyagip966 Sounds like your issue is unrelated to this one. Please create a new issue.
