### ISSUE TITLE
Firestore not working when authenticated?

### ISSUE THREAD

**Issue by patrickdevivo** [firebase/firebase-js-sdk#398] opened 2017-12-25 05:18 UTC
### [REQUIRED] Describe your environment

  * Operating System version: macOS
  * Firebase SDK version: 4.8.1
  * Firebase Product: `firestore` (and `auth`)

### [REQUIRED] Describe the problem
Please see this StackOverflow question: https://stackoverflow.com/questions/47957391/firebase-firestore-web-sdk-cannot-seem-to-connect-when-user-is-logged-in

I'm wondering if the issue has something to do with this line: https://github.com/firebase/firebase-js-sdk/blob/master/packages/auth/src/auth.js#L309 not declaring `configurable: true`

Please let me know if this is a bug or if I am potentially misunderstanding/misusing something. My Firebase setup looks something like this:

```js
import firebase from 'firebase'
import 'firebase/firestore'

const config = {
    apiKey: ...,
    authDomain: ...,
    databaseURL: ...,
    projectId: ...,
    storageBucket: ...,
    messagingSenderId: ...
};

firebase.firestore.setLogLevel("debug")
if (!firebase.apps.length) firebase.initializeApp(config)
export default firebase
```

**Comment by samtstern** [comment] 2018-02-07 22:11
Looks like @mikelehen responded on StackOverflow and asked for a minimal reproduction and the conversation petered out after that.  I am going to close this issue since it's old and the SO conversation is (slightly) more alive.  If you are able to reproduce this issue in a simple environment please provide the reproduction in that thread.

**Closed by samtstern** 2018-02-07 22:11 UTC
Labels: Component-Auth, Component-Firestore
