### ISSUE TITLE
firebase.messaging().deleteToken(Token) Failed on Firebase WEB SDK 7.6.1

### ISSUE THREAD

**Issue by fhajarf** [firebase/firebase-js-sdk#3325] opened 2020-06-30 09:49 UTC
### [REQUIRED] Describe your environment

  * Operating System version: windows 10
  * Browser version: Version 83.0.4103.116 (Official Build) (64-bit) 
  * Firebase SDK version: 7.6.1
  * Firebase Product: Firebase Cloud Messaging 

### [REQUIRED] Describe the problem

<img width="493" alt="error" src="https://user-images.githubusercontent.com/59512761/86111860-edde8000-bacf-11ea-86cb-4ec73ca0b236.PNG">

#### Steps to reproduce:
The issue occurs when a use grants notification permissions, gets a FCM token, then updates the notification permissions in the browser back to Ask (default), reloads the page, grants notification permissions again in Chrome, and get an error when trying to getToken at this point. Note: subsequent calls to getToken don't face this issue.

#### Relevant Code:

if(messaging){
messaging.requestPermission()
.then(async () => {
const token = await messaging.getToken();
const user= JSON.parse(localStorage.getItem('userObj'));
var isMyObjectEmpty = !Object.keys(user).length;
const doc = await db.collection('tokens').doc('webTokens').get();
if(user && !isMyObjectEmpty){
db.collection('tokens').doc(user.uid).set({webPushToken: token}, {merge: true}).then(() => {
}).catch((error) => {
console.log(error.message,'here we are');
})
}
if(doc.exists){
db.collection('tokens').doc('webTokens').update({tokens: firebase.firestore.FieldValue.arrayUnion(token)}).then(() => {
}).catch((error) => { console.log(error.message,'hahaha'); })
}
else {
console.log("Doc dosen't exist ");
}
})
.catch((err) => {
console.log("Unable to get permission to notify.", err.code);
});
  navigator.serviceWorker.addEventListener("message", (message) => console.log(message));

**Comment by zwu52** [comment] 2020-08-04 18:36
Hi fhajarf, thanks for reporting. It looks like this might be a duplicate of #2364. If there is no objection, I'll close this issue and update on that. Cheers.

**Closed** 2020-08-14 16:31 UTC
Labels: api: messaging
