### ISSUE TITLE
Firestore: FirebaseError The service is temporarily unavailable. 

### ISSUE THREAD

**Issue by alexanderott** [firebase/firebase-js-sdk#1875] opened 2019-06-12 16:03 UTC
### [REQUIRED] Describe your environment

  * Operating System version: macOS 10.14.5
  * Browser version: Chrome 75
  * Firebase SDK version: 5.9.4
  * Firebase Product: Firestore

### [REQUIRED] Describe the problem
Some of our clients have been randomly encountering the following error in the last few days. The error is thrown within the onSnapshot listener. This means that the listener is being detached and the application stops working (mostly), because the UI doesn't receive any updates from the database.

Stacktrace
```
FirebaseError The service is temporarily unavailable. 
    node_modules/@firebase/firestore/dist/index.cjs.js.pre-build-optimizer.js:352:27 new t
    node_modules/@firebase/firestore/dist/index.cjs.js.pre-build-optimizer.js:5844:15 e.fromRpcStatus
    node_modules/@firebase/firestore/dist/index.cjs.js.pre-build-optimizer.js:6341:43 e.fromWatchChange
    node_modules/@firebase/firestore/dist/index.cjs.js.pre-build-optimizer.js:14914:42 t.onMessage
    node_modules/@firebase/firestore/dist/index.cjs.js.pre-build-optimizer.js:14843:29 
    node_modules/@firebase/firestore/dist/index.cjs.js.pre-build-optimizer.js:14883:27 
    node_modules/@firebase/firestore/dist/index.cjs.js.pre-build-optimizer.js:7636:19 
    node_modules/zone.js/dist/zone.js.pre-build-optimizer.js:388:25 e.invoke
    node_modules/@angular/core/fesm5/core.js.pre-build-optimizer.js:17299:32 Object.onInvoke
    node_modules/zone.js/dist/zone.js.pre-build-optimizer.js:387:31 e.invoke
```

#### Steps to reproduce:
We are unable to reproduce the problem willingly. We encountered it once in local development, but have no idea why this error is occuring. The error seems unrelated to the available internet connection. If the device actually goes offline, the SDK switches to offline mode perfectly.

#### Relevant Code:
This is the code that we are using to attach our snapshot listeners. As you can see, the observer fires an error event when the error callback of onSnapshot is called. This completely detaches the snapshot listener. The detachment is expected, but the error itself is not.

```javascript
return new Observable<any>((observer) => {
	return query.onSnapshot((snapshot) => {
		const data = successCallback(snapshot);
		observer.next(data);
	}, (error) => {
		console.error(error);
		console.error(query);
		observer.error(error);
	}, observer.complete);
});
```

What is the recommended approach when this error occurs? Can we just try to reattach the listener? (example below)
Or is this an error that should be handled differently?

```javascript
return new Observable<any>((observer) => {
	let runCount = 0;
	let currentTeardownLogicFunction = null;
	const runQuery = () => {
		runCount++;
		return query.onSnapshot((snapshot) => {
			const data = successCallback(snapshot);
			observer.next(data);
		}, (error) => {
			console.error(error);
			console.error(query);
			if (runCount <= 3) {
				currentTeardownLogicFunction = runQuery();
			} else {
				observer.error(error);
			}
		}, observer.complete);
	};

	currentTeardownLogicFunction = runQuery();
	return () => {
		if (currentTeardownLogicFunction) {
			currentTeardownLogicFunction();
		}
	};
})
```

**Comment by rsgowman** [comment] 2019-06-13 14:13
Hi Alexander,

If you're able to collect logs when this situation occurs, that would be extremely helpful. However, since you can't reproduce the issue, that seems unlikely. Still, if you do figure out a way to reliably reproduce the issue, if you could enable the logs and the send them to us, that'd be useful. (You can upload the logs here... but if you do so, ensure you've scrubbed anything sensitive from them first. Otherwise, you can email them to me. My address is below.)

Based on what you've reported, our current hypothesis is that you're getting an UNAVAILABLE response after sending an add_target request on the watch stream. But we talked to some folks that work on the Firestore backend, and they have some metrics that suggest that those kinds of errors are currently occurring at a vanishingly small rate. Still, it could be that you're getting exceptionally unlucky (or that something in your app is somehow just different enough to cause this to occur more frequently than normal.) If you can provide your project id, I believe they can confirm if this is occurring in your app. (I'd encourage emailing that rather than posting it here. I'll share it with the relevant people internally.)

My email address is rgowman@google.com.


Retrying the listener on this error does seem like a reasonable approach. Retrying with an exponential backoff would be even better... especially if your app has a very large number of users.

**Comment by remotejob** [comment] 2019-11-12 02:35
Something like what happen. Request from Google RUN service:

`2019-11-11 11:34:25.645 EET2019/11/11 09:34:25 rpc error: code = DeadlineExceeded desc = The datastore operation timed out, or the data was temporarily unavailable.
2019-11-11 11:34:25.645 EET2019/11/11 09:34:25 actdom from firebase 0
2019-11-11 11:34:25.647 EETGET201218 B60 sGo-http-client/2.0 https://activedomains-hj27vy3k3a-uc.a.run.app/
2019-11-11 13:17:02.670 EET2019/11/11 11:17:02 rpc error: code = Unavailable desc = The service is temporarily unavailable. Please retry with exponential backoff.
2019-11-11 13:17:02.670 EET2019/11/11 11:17:02 actdom from firebase 0
2019-11-11 13:17:02.672 EETGET201218 B13.3 sGo-http-client/2.0 https://activedomains-hj27vy3k3a-uc.a.run.app/
2019-11-11 13:17:04.627 EET2019/11/11 11:17:04 rpc error: code = Unavailable desc = The service is temporarily unavailable. Please retry with exponential backoff.`

**Comment by schmidt-sebastian** [comment] 2019-11-12 20:17
@remotejob Since your error indicates a communication problem with the backend, do you mind filing a Google Cloud Support request that includes both timestamps for your errors as well as your Project ID? Please follow the steps here: https://cloud.google.com/support/. We should then be able to look at backend logs.

I am closing this issue for now, and our team will follow up via the support request. Thank you for your time!

**Closed by schmidt-sebastian** 2019-11-12 20:17 UTC
Labels: Status: Pending Response, api: firestore
