### ISSUE TITLE
v5.8.3 firebase.firestore() is not a function some how

### ISSUE THREAD

**Issue by l2aelba** [firebase/firebase-js-sdk#1547] opened 2019-02-19 09:30 UTC
### [REQUIRED] Describe your environment

  * Operating System version: Node 8
  * Browser version: All
  * Firebase SDK version: 5.8.3
  * Firebase Product: Firestore

### [REQUIRED] Describe the problem
I am using Firebase / Nuxt / Firebase hosting / Firebase functions.
After upgraded from **5.8.2** to **5.8.3** then I get

```
firebase.firestore() is not a function
```

But I downgraded back to **5.8.2** so its ok.

#### Steps to reproduce:

I followed the code from: https://medium.com/@pascalluther/nuxt-js-v2-firestore-ssr-938d8fb7d2b0

#### Relevant Code:

```javascript
import firebase from 'firebase/app'
import 'firebase/firestore'
if (!firebase.apps.length) {
  const config = {
    // My config
  }
  firebase.initializeApp(config)
}
const db = firebase.firestore()
export { db }
```

**Comment by rsgowman** [comment] 2019-02-19 17:42
Hi @l2aelba,

I tried this out, but couldn't reproduce the issue. I worked through that medium post until step 4 (write to firestore) since that's the step that looks like it should trigger this.

If you're able to do so, could you post the contents of these files: nuxt.config.js, package.json, package-lock.json?

Also, how are you running your local webserver? `npm run dev`?

**Comment by l2aelba** [comment] 2019-02-20 08:29
@rsgowman, forgot to tell about **its work** in local `npm run serve` but **not work** then deployed to **Firebase hosting**

**Comment by webcarrot** [comment] 2019-02-20 14:29
@l2aelba 
I had the same problem on local. Clearing npm cache and removing node_modules solved the problem. It looks like npm malfunction.

**Comment by rsgowman** [comment] 2019-02-20 23:02
Oh, I see. It doesn't look like that particular tutorial discussing hosting... which is a little more involved. But it looks like you managed to get it to work, at least with version 5.8.2. Are you able to share your project (but not the api keys of course)? Or share the additional steps you took?

**Comment by l2aelba** [comment] 2019-02-21 08:42
@rsgowman, I think its something like @webcarrot said.

But if you still need to see my sources ? You can give email to me or something private.

**Comment by l2aelba** [comment] 2019-02-21 09:01
I sent to rgowman_at_google.com

**Comment by Feiyang1** [comment] 2019-02-21 17:37
Closing since the issue has been resolved.

**Closed by Feiyang1** 2019-02-21 17:37 UTC
Labels: Component-Core, needs-attention

**Comment by l2aelba** [comment] 2019-04-08 13:45
@Feiyang1 @rsgowman 

Its back again v5.9.3 :(
