### ISSUE TITLE
useAuthEmulator and useFirestoreEmulator have different parameter signatures

### ISSUE THREAD

**Issue by ebeloded** [firebase/firebase-js-sdk#5038] opened 2021-06-17 04:24 UTC
### [REQUIRED] Describe your environment
  * Firebase SDK version: 9-beta.2
  * Firebase Product: auth, firestore

### [REQUIRED] Describe the problem

`useAuthEmulator` and `useFirestoreEmulator` are not consistent in their parameter signatures. `useAuthEmulator` expects host:port as a single string, whereas `userFirestoreEmulator` expects host and port as separate arguments, port passed as a number.

**Comment by looptheloop88** [comment] 2021-06-17 07:51
Hi @ebeloded, thanks for the report. We are aware that many developers would like to normalize the method signature of the Firebase emulators. There's already an internal feature request for this, however we can't provide definite timelines or details for when it will be available. You may keep an eye out on our release notes or this thread to get updates in the future.

For reference, the internal feature request is b/185364099.

**Comment by looptheloop88** [comment] 2021-06-17 07:52
I will close this issue and mark as a duplicate of #4781.

**Closed by looptheloop88** 2021-06-17 07:52 UTC
Labels: testing-sdk, v9
