### ISSUE TITLE
TransactionInactiveError in IE11

### ISSUE THREAD

**Issue by ckybonist** [firebase/firebase-js-sdk#4088] opened 2020-11-18 03:37 UTC
### [REQUIRED] Describe your environment

  * Operating System version: `Windows 7 / Windows 10`
  * Browser version: `IE 11.0`
  * Devise: Windows Phone
  * Firebase SDK version: `8.0.2`
  * Firebase Product: `analytics` (according to [Sentry log](https://sentry.io/share/issue/fc0ecd79890f4bd3b8392944d34b4c6d/))

![image](https://user-images.githubusercontent.com/3832925/99478046-ad07da80-298e-11eb-95a9-e73c6036a562.png)

### [REQUIRED] Describe the problem
We receive **325K** TransactionInactiveError from `firebase/analytics` module... An interesting info for you to know is the errors mostly occur on Nokia Lumia series.

![image](https://user-images.githubusercontent.com/3832925/99480061-52707d80-2992-11eb-8f5d-e108e4ad7075.png)

#### Steps to reproduce:
Demo site: https://firebase-next-debug.vercel.app/

1. `import 'firebase/analytics'` and `firebase.initializeApp(...)`
2. Use `IE  > 11 Emulation` to simulate `IE 11, Windows Phone 8.1 update`
3. You should see the `TransactionInactiveError`

![image](https://user-images.githubusercontent.com/3832925/99480819-d414db00-2993-11eb-83a3-99b9a1cc7a19.png)

![image](https://user-images.githubusercontent.com/3832925/99480322-d1fe4c80-2992-11eb-8f2b-1315d7aac64f.png)

#### Relevant Code:

https://github.com/ckybonist/firebase-next-debug/blob/main/firebase/clientApp.js

**Comment by hsubox76** [comment] 2020-11-18 18:07
Seems to be IndexedDB related so likely to be an installations issue, but it's also possible it happens during the initial IndexedDB environment check in Analytics. This might be tricky to reproduce.

**Comment by asgvard** [comment] 2020-12-14 11:07
We can reproduce the same error when using firebase on Samsung Tizen 2015 and 2016 TV devices. They are based on WebKit browser.

**Comment by DellaBitta** [comment] 2023-06-07 14:52
Hi @ ckybonist and @asgvard,

It's been a while. I'm just checking in to see if this is still an issues for you with the latest Firebase SDKs.

**Comment by ckybonist** [comment] 2023-06-08 02:28
Hi, we've removed IE11 from our supported browsers list, so this is not an issue for us.

**Comment by dwyfrequency** [comment] 2023-06-26 18:03
@ckybonist correct IE is no longer supported by firebase https://firebase.google.com/docs/web/environments-js-sdk#browsers. I'll close this issue

**Closed by dwyfrequency** 2023-06-26 18:03 UTC
Labels: question, needs-attention, api: analytics, api: installations
