### ISSUE TITLE
Error in alpha during building in node environment: Directory import is not supported resolving ES modules

### ISSUE THREAD

**Issue by Evertt** [firebase/firebase-js-sdk#4725] opened 2021-04-04 20:25 UTC
* Operating System version: macOS Big Sur
  * Browser version: irrelevant
  * Firebase SDK version: 0.9.x
  * Firebase Product: all of them

### [REQUIRED] Describe the problem
[I encountered this issue while trying to build a SvelteKit project that uses firebase.](https://github.com/sveltejs/kit/issues/612)

During the build process I get the following error:

```
> Directory import '/Users/evert/Sites/svind/node_modules/firebase/app' is not supported resolving ES modules imported from /Users/evert/Sites/svind/.svelte/output/server/app.js
Did you mean to import firebase@0.900.20/node_modules/firebase/app/dist/index.cjs.js?
Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import '/Users/evert/Sites/svind/node_modules/firebase/app' is not supported resolving ES modules imported from /Users/evert/Sites/svind/.svelte/output/server/app.js
Did you mean to import firebase@0.900.20/node_modules/firebase/app/dist/index.cjs.js?
    at new NodeError (node:internal/errors:329:5)
    at finalizeResolution (node:internal/modules/esm/resolve:319:17)
    at moduleResolve (node:internal/modules/esm/resolve:758:10)
    at Loader.defaultResolve [as _resolve] (node:internal/modules/esm/resolve:869:11)
    at Loader.resolve (node:internal/modules/esm/loader:86:40)
    at Loader.getModuleJob (node:internal/modules/esm/loader:230:28)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:57:40)
    at link (node:internal/modules/esm/module_job:56:36)
```

#### Steps to reproduce:
I don't know any other way to reproduce it, other than just by creating a svelte-kit project, importing firebase and trying to build it.

### Solution

I already know the solution though. You see, RxJS had the same problem and they recently fixed it. It's quite easy. Just add the following lines to the root `package.json`:

```
  "exports": {
    "./app": {
      "node": "./app/dist/index.cjs.js",
      "default": "./app/dist/index.esm.js"
    },
    "./auth": {
      "node": "./auth/dist/index.cjs.js",
      "default": "./auth/dist/index.esm.js"
    },
    "./firestore": {
      "node": "./firestore/dist/index.cjs.js",
      "default": "./firestore/dist/index.esm.js"
    },
    "./functions": {
      "node": "./functions/dist/index.cjs.js",
      "default": "./functions/dist/index.esm.js"
    },
    "./messaging": {
      "node": "./messaging/dist/index.cjs.js",
      "default": "./messaging/dist/index.esm.js"
    },
    "./performance": {
      "node": "./performance/dist/index.cjs.js",
      "default": "./performance/dist/index.esm.js"
    },
    "./remote-config": {
      "node": "./remote-config/dist/index.cjs.js",
      "default": "./remote-config/dist/index.esm.js"
    },
    "./storage": {
      "node": "./storage/dist/index.cjs.js",
      "default": "./storage/dist/index.esm.js"
    },
    "./package.json": "./package.json"
  }
```

**Comment by looptheloop88** [comment] 2021-04-12 17:36
Hi @Evertt, please share a [complete, but minimal](https://stackoverflow.com/help/minimal-reproducible-example) sample project that I can run locally to replicate the issue. Thanks!

**Comment by Mkassabov** [comment] 2021-04-19 02:25
@Everett
your fix seems to be missing the config for firebase/analytics.
something like:
```
"./analytics": {
  "node": "./analytics/dist/index.cjs.js",
  "default": "./analytics/dist/index.esm.js"
},
```
would also need to be added to the exports property of the package.json

**Comment by hsubox76** [comment] 2021-04-27 17:40
We added the exports field in package.json in this PR: https://github.com/firebase/firebase-js-sdk/pull/4767 and it's in the current beta release, so this should be fixed.

**Closed by hsubox76** 2021-04-27 17:40 UTC
Labels: alpha, api: core, needs-info, no-recent-activity
