### ISSUE TITLE
UnknownError: Connection to Indexed Database server lost. Refresh the page to try again

### ISSUE THREAD

**Issue by kevinrenskers** [firebase/firebase-js-sdk#4948] opened 2021-05-27 18:11 UTC
### [REQUIRED] Describe your environment

  * Operating System version: macOS 10.15.6
  * Browser version: Safari 14.0.3 and 
  * Firebase SDK version: 9.0.0-beta.2
  * Firebase Product: auth, storage, functions, firestore

### [REQUIRED] Describe the problem

I don't know what's happening or how to reproduce it, but I am seeing a *lot* of errors in Sentry with this error: 
`UnknownError: Connection to Indexed Database server lost. Refresh the page to try again`.

It started on May 11, has affected 14 users, and has generated over 11.000 errors to date. I haven't deployed anything on or around May 11, I updated to Firebase v9 on April 15th.

The errors are triggered literally every second for affected users.

It's happening on macOS and iOS only, and only in Safari / Mobile Safari / Chrome for iOS (which runs Apple's webkit of course).

![Screen Shot 2021-05-27 at 20 08 58](https://user-images.githubusercontent.com/229384/119875982-aa7ed280-bf27-11eb-8425-76559a73d205.png)

**Comment by looptheloop88** [comment] 2021-06-02 09:10
Hi @kevinrenskers, thanks for the report and for patiently waiting. This issue seems to be related to an Apple bug, see [here](https://bugs.webkit.org/show_bug.cgi?id=197050#c14) for your reference.

Apple said the bug has been fixed in iOS 13, but people are still seeing it in iOS 14. Have you noticed any patterns like the iOS version or error logs in the browser console?

**Comment by kevinrenskers** [comment] 2021-06-02 09:14
I don't think this is the same problem, as I am seeing it mostly in macOS 10.15.6 with Safari 14.0.3 - so no backgrounding / foregrounding going on here. Plus the error is different?

No other logs or details, no. I have disabled `enableIndexedDbPersistence`, and that seems to have stopped the errors.

**Comment by Feiyang1** [comment] 2021-06-02 17:14
The error you are seeing was reported happening after trying to reopen indexeddb after hitting the bug, see [this comment](https://bugs.webkit.org/show_bug.cgi?id=197050#c5). It also explains why disabling `enableIndexedDbPersistence` solves the issue.

There are probably other conditions other than backgrounding/foregrounding that triggers the bug. If you could reliably reproduce the issue, we can add new information to the bug. At this point, I don't think it's something we can fix in the SDK itself, but if you don't need `enableIndexedDbPersistence`, disabling it is a good workaround.

**Comment by Feiyang1** [comment] 2021-06-02 17:27
I don't think it's related to the v9 upgrade because we didn't change indexeddb related implementations. I would've asked you to downgrade back to v8 to confirm without hesitance if it doesn't require you to rewrite any code, but it does... so If there is any possibility that you could revert to v8, it would be great to confirm definitively it's not a v9 issue, and it's totally fine if you couldn't do it.

**Comment by kevinrenskers** [comment] 2021-06-02 17:29
Well, I don't have the problem myself, and I don't know how to reproduce. I just know that 14 users have managed to log over 12.000 errors in a few days 🙈 
I can absolutely not downgrade and then hope that those same users do the same thing that would've triggered the error before, sorry.

**Comment by syucream** [comment] 2021-07-19 01:33
Any progress? I have a similar issue with `9.0.0-beta.6`. Once I downgraded it to `8.3.1`, it seemed to be fixed.

**Comment by DellaBitta** [comment] 2023-06-06 01:34
Hi @syucream,

It's been a while since the last response. Is this still an issue for you, and if so, do you have any more context as to why it might be happening? Thanks!

**Closed** 2023-06-20 01:03 UTC
Labels: api: auth, question, needs-info, no-recent-activity, v9
