### ISSUE TITLE
Unable to register library "@firebase/installations-exp" with version "0.0.900": library name "@firebase/installations-exp" contains illegal characters (whitespace or "/")

### ISSUE THREAD

**Issue by FezVrasta** [firebase/firebase-js-sdk#4437] opened 2021-02-09 14:43 UTC
### Describe your environment

  * Operating System version: macOS Big Sur
  * Browser version: Chrome 88
  * Firebase SDK version: exp 0.0.900
  * Firebase Product: all?

### Describe the problem

I'm trying the exp release but after I migrated all my code to the new API I get the below error:

```
logger.ts:115 [2021-02-09T14:40:24.753Z]  @firebase/app: Unable to register library "@firebase/installations-exp" with version "0.0.900": library name "@firebase/installations-exp" contains illegal characters (whitespace or "/")
```

![image](https://user-images.githubusercontent.com/5382443/107379729-8240a480-6aed-11eb-96d3-c1d94389bc6e.png)

#### Steps to reproduce:

It happens as soon I open the web page.

#### Relevant Code:

Not sure to be honest.

**Comment by hsubox76** [comment] 2021-02-09 18:39
I think I know what's causing the warnings (yellow) and I'm pretty sure they're unrelated to the error (auth/internal-error). Can you give more information about how you're importing and using auth?

Meanwhile I will work on fixing what's causing the warnings.

**Comment by FezVrasta** [comment] 2021-02-09 20:16
Thanks for the reply! I fixed the red error by initializing auth as first thing, I'm still not sure what to do with the warnings though, they seem related to the performance package

**Comment by hsubox76** [comment] 2021-02-09 21:11
Yes, I think I know what the problem is with the warnings and have made a PR (https://github.com/firebase/firebase-js-sdk/pull/4440), thanks for bringing it up!

Adding this link as a reference for the auth error, we are fixing it by adding a warning: https://github.com/firebase/firebase-js-sdk/issues/4425

I will close this when https://github.com/firebase/firebase-js-sdk/pull/4440 (PR for the warnings) is merged.

**Comment by hsubox76** [comment] 2021-02-11 16:56
Merged, the warnings should be fixed in the next exp release (we don't have a set schedule for those yet).

**Closed by hsubox76** 2021-02-11 16:56 UTC
Labels: alpha, api: auth
