### ISSUE TITLE
Firebase PWA won't authenticate offline users in mobile browsers (works fine on desktop)

### ISSUE THREAD

**Issue by an0malous** [firebase/firebase-js-sdk#5529] opened 2021-09-21 21:45 UTC
### [REQUIRED] Describe your environment

  * Operating System version: macOS Big Sur 11.5.2
  * Browser version: Chrome 93.0.4577.82, 
  * Firebase SDK version: 9.0.2
  * Firebase Product: Authentication

### [REQUIRED] Describe the problem

I'm working on a React PWA using Firebase services. By PWA I mean it uses service workers, has Firestore offline data persistence enabled, and is supposed to log the user in as long as the session data is stored in the browser.

The problem I'm having is after a user is authenticated, I want the user to be able to turn off wifi and mobile data, and be able to open the app again, and the app treat the user like the user is authenticated. This all works fine on Chrome and Firefox desktop browsers.

However, when I use the latest Chrome and Firefox mobile browsers, the service workers work well but after turning off wifi an mobile data, the app doesn't treat the user like they are logged in and a error message in the console appears that reads "inner auth error". It unfortunately doesn't give much more information than that.

#### Steps to reproduce:

1) Open up Chrome or Firefox in mobile browser (The same error that occurs on mobile browsers also occurs on the latest desktop version of Safari, so Safari Desktop will work too.)

2) Log into application with the credentials below.
email: user@test.com pw: testpassword123

https://ravenstaging--review-dev-brown-4wcbt6-7jxhpu9l.web.app/

3) Disconnect internet and refresh the page.

4) Check dev tools console and network tabs for errors.

In production I get an error in the console that reads: Firebase Error:  (auth/internal error).
in development mode I get a similar error but some more output (see picture below. Screen shot was taken in Safari).
<img width="1680" alt="Screen Shot 2021-09-21 at 20 58 33" src="https://user-images.githubusercontent.com/62530683/134252147-c7efacfd-a52f-476e-80c9-99ad920fc114.png">

In the Network tab in dev tools I've noticed there is a request to the google api in the mobile browsers and Safari Desktop that fails. I haven't noticed this google api request in browsers that have no problem.
<img width="1680" alt="Screen Shot 2021-09-21 at 21 07 31" src="https://user-images.githubusercontent.com/62530683/134252230-33ba28d6-3e30-448b-8b98-5c1a1b525e25.png">

#### Relevant Code:
I've reproduced the error by creating a standard create react app PWA template and then by calling the "getAuth" method from "Firebase/auth".
```javascript
// TODO(you): code here to reproduce the problem
``

**Comment by sam-gc** [comment] 2021-09-23 18:05
Hi, thanks for opening this issue--

I believe the root of the problem is this code:
https://github.com/firebase/firebase-js-sdk/blob/4e7aba48afbc5d96e7a294aa56d3c52f680e4d03/packages/auth/src/platform_browser/popup_redirect.ts#L166-L169

If you are using `getAuth()` or if you're defining [`initializeAuth`](https://firebase.google.com/docs/reference/js/auth.md#initializeauth) with the [`browserPopupRedirectResolver`](https://firebase.google.com/docs/reference/js/auth.md#browserpopupredirectresolver), you will run into this issue on mobile and in Safari when offline. The reason is that for those browsers, the Auth SDK proactively initializes the code that is necessary to perform [`signInWithPopup`](https://firebase.google.com/docs/reference/js/auth.md#signinwithpopup) and [`signInWithRedirect`](https://firebase.google.com/docs/reference/js/auth.md#signinwithredirect). That proactive initialization involves loading the apis.google.com file you noticed in the network interface.

**To get around this,**
1. Initialize Auth _without_ the popup redirect resolver set by default:  
```js
import {initializeAuth, indexedDBLocalPersistence, browserLocalPersistence} from 'firebase/auth';
initializeAuth(app, {
  persistence: [indexedDBLocalPersistence, browserLocalPersistence],
  // Notice, no popupRedirectResolver field here
});
  ```
2. If you use any of the popup/redirect methods in your app, pass them the `browserPopupRedirectResolver` dependency explicitly:  
```js
import {browserPopupRedirectResolver, signInWithPopup, GoogleAuthProvider} from 'firebase/auth';
const userCredential = await signInWithPopup(auth, new GoogleAuthProvider(), browserPopupRedirectResolver);
```

Please try these steps and update the issue with the results

**Comment by bestexec** [comment] 2021-09-23 19:02
Thanks Sam, Im using popup method and your suggested work around is working fine for me!

**Comment by sam-gc** [comment] 2021-09-23 19:37
Awesome, glad to hear :)

I'm going to go ahead and close this out since the SDK is working as expected. I will look into adding a note in the docs regarding early initialization and what that means for e.g. offline apps.

**Closed by sam-gc** 2021-09-23 19:37 UTC
Labels: api: auth, type: question, needs-info, v9

**Comment by an0malous** [comment] 2021-09-23 21:11
This solved my issue. Thank you!
