### ISSUE TITLE
Error: Service database is not available

### ISSUE THREAD

**Issue by HaoboZ** [firebase/firebase-js-sdk#6388] opened 2022-06-26 05:11 UTC
### [REQUIRED] Describe your environment

  * Operating System version: Windows
  * Browser version: Edge
  * Firebase SDK version: 9.8.4
  * Firebase Product: database

#### Steps to reproduce:

When using the database with `const db = getDatabase( app );` I get the error `Error: Service database is not available`.
Running using NextJS, happens on build if placed outside components, happens on client side if placed in useMemo. This works with 9.8.1 and stopped working when upgrading firebase package.

**Comment by maneesht** [comment] 2022-06-27 01:24
Hi @HaoboZ, I am unable to reproduce this. Do you have a minimal reproducible example? I tried running:
```typescript
const app = initializeApp(firebaseConfig);
const db = getDatabase(app);
const Home = () => <div>Home</div>;
```
and didn't have any problems.

**Comment by HaoboZ** [comment] 2022-06-29 04:21
Was trying to reproduce it, but after updating packages again it seems to work now? Downgrading to 9.8.3 seems to still have the problem, but the latest version seems to be fine now.

**Comment by HaoboZ** [comment] 2022-07-09 03:00
@maneesht I just got this again, here's a reproduction of it https://github.com/HaoboZ/firebase-db-test.
You need to copy env.template to env and fill out the info.

**Comment by maneesht** [comment] 2022-07-11 22:35
@HaoboZ I was able to reproduce this issue and it seems like database is the only product affected. We are looking into this.

**Comment by HaoboZ** [comment] 2022-07-11 22:56
Sounds good! Its such a weird bug since it failed when I just started using 9.8.4 as well, but afterwards, it worked, maybe because of a dependency?

**Comment by maneesht** [comment] 2022-07-12 17:46
The interesting thing here is that I tried removing pnpm as the package manager and just used yarn and everything worked fine, regardless of the version. However, I created a new nextjs repo with pnpm and couldn't reproduce the issue. Still looking into this.

**Comment by maneesht** [comment] 2022-07-12 19:44
@hsubox76 you're right. There are two resolved versions of `@firebase/app`. @HaoboZ please use `@firebase/app@0.7.28` instead of `@firebase/app@0.7.27`.
<img width="2336" alt="image" src="https://user-images.githubusercontent.com/5403202/178580722-46e3892f-c01d-4359-bbf7-0e127a5193bd.png">

**Comment by HaoboZ** [comment] 2022-07-13 00:52
I see, this seems like a problem of the packageExtensions for it to work with yarn PnP. Is there a way for this to resolve automatically? Without the packageExtensions, it will never build since it says auth and database needs app as dependencies, and with it, it won't update correctly.

**Comment by maneesht** [comment] 2022-07-13 05:19
I applied the changes mentioned in my previous comment and left your packageExtensions as-is and it worked. In addition, the default setup created by `create-next-app` works fine without any extra yarn configuration.

**Comment by HaoboZ** [comment] 2022-07-14 06:44
the default create-next-app uses yarn without PnP. If you use PnP, it throws an error when trying to run it that says module not found, where I found a solution here https://github.com/firebase/firebase-js-sdk/issues/3707.

**Comment by maneesht** [comment] 2022-07-14 17:38
`pnpm create next-app --ts` actually allows you to use pnpm as your package manager

**Comment by maneesht** [comment] 2022-07-19 23:22
I'm going to go ahead and close this, as it seems like the original issue has been resolved.

**Closed by maneesht** 2022-07-19 23:22 UTC
Labels: api: database, v9
