### ISSUE TITLE
FR: Allow emulators to connect over HTTPS

### ISSUE THREAD

**Issue by caspermaven** [firebase/firebase-js-sdk#5648] opened 2021-10-21 13:07 UTC
### [REQUIRED] Describe your environment

  * Operating System version: macOS
  * Browser version: Safari 15.0
  * Firebase SDK version: 9.1.3
  * Firebase Product: auth, functions

#### Steps to reproduce:

The product we're building is a plugin for a parent application. The parent application provides a browser instance for our app to reside, but it imposes several security restrictions. Mainly, any call using the Fetch API must hit an HTTPS endpoint. All others are rejected.

When attempting to use the Firebase SDK, we noticed that the `http://` portion of the endpoint is hardcoded into the function. Ideally, we would like to override this to accept https://, since it would allow us to use tunneling services such as ngrok to satisfy the security.

Workarounds:

- Calling `functionsInstance.emulatorOrigin = 'https://5151-myemulator.com:5001'` directly may work but seems hacky.

#### Relevant Code:

https://github.com/firebase/firebase-js-sdk/blob/master/packages/functions/src/service.ts#L141

```javascript
/**
 * Modify this instance to communicate with the Cloud Functions emulator.
 *
 * Note: this must be called before this instance has been used to do any operations.
 *
 * @param host The emulator host (ex: localhost)
 * @param port The emulator port (ex: 5001)
 * @public
 */
export function connectFunctionsEmulator(
  functionsInstance: FunctionsService,
  host: string,
  port: number
): void {
  functionsInstance.emulatorOrigin = `http://${host}:${port}`;
}
```

Possible improvements:

- The `connectFunctionsEmulator` (and other connect functions) could accept an additional parameter for HTTPS.
- The function could detect if the user prefixes `host` with "https" and override the relevant portion of the string.

I appreciate you!

**Comment by BobbieGoede** [comment] 2021-12-20 13:23
We used to be able to set the full host and thus be able to support https urls. This broke since changes made in #3906.

```diff
export function useFunctionsEmulator(
  functionsInstance: FunctionsService,
--  origin: string
  host: string,
  port: number
): void {
--  functionsInstance.emulatorOrigin = origin;
++  functionsInstance.emulatorOrigin = `http://${host}:${port}`;
}
```

**Comment by hsubox76** [comment] 2021-12-20 17:06
Duplicate of https://github.com/firebase/firebase-js-sdk/issues/4124 (see that issue for more information).

**Closed by hsubox76** 2021-12-20 17:06 UTC
Labels: testing-sdk, type: feature request, v9
