### ISSUE TITLE
Module not found: Default condition should be last one

### ISSUE THREAD

**Issue by jfbaraky** [firebase/firebase-js-sdk#7005] opened 2023-02-02 23:57 UTC
### Describe your environment

  * Operating System version: macOS Monterey 12.4
  * Browser version: Google Chrome 109.0.5414.119
  * Firebase SDK version: 9.17.0
  * Firebase Product: any

### Describe the problem

When installing the version `9.17.0`, I was getting this error on the import:
```
Module not found: Default condition should be last one
> 1 | import { initializeApp, getApps, getApp } from 'firebase/app';
  2 | import { getAnalytics, isSupported } from 'firebase/analytics';
  3 | import { getAuth } from 'firebase/auth';
```

Doesn't matter the order of the imports.

#### Steps to reproduce:

1. `yarn add firebase`
2. import any firebase lib

#### Relevant Code:

The error is happening on the import first firebase package, doesn't matter which one of them.
```javascript
import { initializeApp, getApps, getApp } from 'firebase/app';
import { getAnalytics, isSupported } from 'firebase/analytics';
import { getAuth } from 'firebase/auth';
```

**Comment by jfbaraky** [comment] 2023-02-02 23:59
Looks like the Next.JS is emitting this error when importing the Firebase.
https://nextjs.org/docs/messages/module-not-found

**Comment by aaronmgdr** [comment] 2023-02-03 00:12
also getting this. It only started about a hour ago and I even tried re building an old deploy commit. only difference it seems is firebase 9.17 just dropped

**Comment by joshdchang** [comment] 2023-02-03 00:24
This seems to be a result of #6981. I submitted a PR to fix this: #7006. See: [https://github.com/firebase/firebase-js-sdk/issues/7002#issuecomment-1414526580](https://github.com/firebase/firebase-js-sdk/issues/7002#issuecomment-1414526580)

**Comment by toan-superman** [comment] 2023-02-03 05:49
I got the same issue here, and it just happened this morning. How can I fix that ?
![image](https://user-images.githubusercontent.com/122863873/216522659-a59b9364-f9b0-4f3c-a5b6-27c2dc9687dd.png)

**Comment by This-is-Shyam-Mahanta** [comment] 2023-02-03 07:17
facing the same issue on my exisitng ReactAPP. before there was no problem

**Comment by D3OXY** [comment] 2023-02-03 07:49
**Same issue**
Firebase SDK version: 9.17.0
![image](https://user-images.githubusercontent.com/66240773/216542068-f4eea431-7dfb-46b7-b865-242f3a301351.png)

**Comment by Angryman18** [comment] 2023-02-03 07:55
here is the solution. change the version run `yarn install`

![Screenshot from 2023-02-03 13-24-19](https://user-images.githubusercontent.com/63530626/216543505-3abe803e-5a6f-43cd-b093-01400eaaca5a.png)

**Comment by Angryman18** [comment] 2023-02-03 07:56
from fixed to the version. remove `^` also

**Comment by VuHuyDot** [comment] 2023-02-03 08:02
After following @Angryman18 suggestion. It has been fixed. Thank you very much

**Comment by fvilers** [comment] 2023-02-03 08:10
We can revert to version 9.16.0 to avoid the issue

**Comment by Angryman18** [comment] 2023-02-03 08:24
> how do i change the firebase version angry man

In package.json file

**Comment by bradley-owens** [comment] 2023-02-03 08:35
this did not fix my issue

**Comment by gowthamtirri** [comment] 2023-02-03 09:52
1. npm un firebase
2. npm i firebase@9.16.0

Solved my issue "Module not found: Default condition should be last one "

**Comment by gowthamtirri** [comment] 2023-02-03 09:52
> this did not fix my issue

1. npm un firebase
2. npm i firebase@9.16.0

Solved my issue "Module not found: Default condition should be last one "

**Comment by Naman-Sogani** [comment] 2023-02-03 10:01
> 1. npm un firebase
> 2. npm i firebase@9.16.0
> 
> Solved my issue "Module not found: Default condition should be last one "

Its working for me bro thnx..

**Comment by Reeywhaar** [comment] 2023-02-03 10:10
Checked all package.json files with following script

<details>

```js
/**
 * Checks if all package.json has
 * "default" export in `exports` entry
 * to be the last one
 */

const exec = require('child_process').execSync

function main() {
  const packages = exec('find node_modules -type f -name package.json').toString().split('\n')

  for (const pkg of packages) {
    try {
      const data = require(`./${pkg}`)
      if (!data.exports) {
        continue
      }
      if (!checkIfDefaultIsLast(data.exports)) {
        // console.info(pkg, data.exports, checkIfDefaultIsLast(data.exports))
        console.warn('FAIL', pkg)
      } else {
        // console.info('OK  ', pkg)
      }
    } catch (e) {
      if (e instanceof Error) {
        if (e.message.endsWith('Unexpected end of JSON input')) continue
      }
      console.error(e.message)
    }
  }
}

function checkIfDefaultIsLast(item) {
  if (typeof item === 'string') return true
  const entries = Array.from(Object.entries(item))
  const keys = entries.map(([key]) => key)
  if (keys.includes('default') && keys.indexOf('default') !== keys.length - 1) {
    return false
  }
  for (const [, value] of Object.entries(item)) {
    if (!checkIfDefaultIsLast(value)) return false
  }
  return true
}

main()
```

</details>

And it seems only firebase packages have exports entry messed up

**Comment by AnthonyNahas** [comment] 2023-02-03 11:03
I am facing the same issue after up grading lib from `v9.16.0` to `v9.17.0`

![Bildschirm­foto 2023-02-03 um 12 03 01](https://user-images.githubusercontent.com/20149774/216587784-c54055b9-1ea6-46c2-846a-0ba876e96a5d.png)

**Comment by iamSuraZz** [comment] 2023-02-03 12:17
Downgraded to 9.16.0 but now throwing new error :

 Compiled with problems:X

ERROR in ./src/FireBase/Firebase.js 14:15-37

export 'default' (imported as 'firebase') was not found in 'firebase/app' (possible exports: FirebaseError, SDK_VERSION, _DEFAULT_ENTRY_NAME, _addComponent, _addOrOverwriteComponent, _apps, _clearComponents, _components, _getProvider, _registerComponent, _removeServiceInstance, deleteApp, getApp, getApps, initializeApp, onLog, registerVersion, setLogLevel)

**Comment by jfbaraky** [comment] 2023-02-03 12:23
@iamSuraZz your issue probably is related to your import. 
You need to do a named import instead of a default one:
```javascript
import { initializeApp, getApps, getApp } from 'firebase/app';
```
instead of 
```javascript
import firebase from 'firebase/app';
```

**Comment by jfbaraky** [comment] 2023-02-03 12:28
If you're having trouble to move to the `9.16.0`, check if you have a `^` on the firebase version inside the `package.json` file. This will allow the install to check for new minor version, and will install the `9.17.0`. 

You can also create a `.npmrc` file on the root of your project with `save-exact=true` inside to force any new added package to be exact (you still need to remove the already existing `^`).

After the removal, you will need to run another `npm i` (or `yarn`).

**Comment by iamSuraZz** [comment] 2023-02-03 12:29
Fixed the error was here : 
import firebase from "firebase/compat/app";
import "firebase/compat/auth";
import "firebase/compat/firestore";
import "firebase/compat/database";

**Comment by BossBele** [comment] 2023-02-03 13:19
Changing firebase version from "^9.9.0" to "9.9.0" worked for me.

In some cases, removing the "^" from the firebase version in package.json, suprisingly works.

**Comment by miramgh** [comment] 2023-02-03 14:54
Im having the same issue 
none of those solutions worked for me

**Comment by PaulvdDool** [comment] 2023-02-03 14:57
Version 9.16.0 strict (without ^) worked for me.

**Comment by lincolnthree** [comment] 2023-02-03 15:04
This just started for me when upgrading `"^9.16.0",` to `"^9.17.0". Was working fine before.

**Comment by jbalidiong** [comment] 2023-02-03 15:07
Hi everyone, thanks for bringing this issue to our attention. I was able to reproduce the behavior. Let me check what we can do for this issue or bring someone here that can provide more context about it. I’ll update this thread if I have any information to share.

**Comment by Angryman18** [comment] 2023-02-03 15:07
^ means you will have minimum that version but with all upcoming patch releases & upgrades and removing ^ meaning you sticky want to install that particular version without any patch releases and updates on that version

**Comment by Reeywhaar** [comment] 2023-02-03 15:08
@jbalidiong issue caused by this commit https://github.com/firebase/firebase-js-sdk/commit/0bab0b7a786d1563bf665904c7097d1fe06efce5

**Comment by SANDAY-JS** [comment] 2023-02-03 15:14
Changed the version from latest to `9.15.0`, and it worked for me.
Also, make sure to remove `^`.

**Comment by eugenevk** [comment] 2023-02-03 16:47
In combination with Quasar CLI 2.0.0 it's even worse. After upgrade Quasar CLI from 1.4.0 to 2.0.0, axios from 0.26.1 to 1.3.1 and then upgrading firebase from 9.6.6 to 9.17.0, got same error, then downgraded to 9.6.6 and it didn't even work any more. Had to undo all package upgrades and redo Quasar etc.

**Comment by hsubox76** [comment] 2023-02-03 17:42
I have the fix merged and am working on an emergency release ASAP, will update when it is out.

**Closed** 2023-02-03 17:41 UTC
Labels: type: bug, v9

**Comment by dariovargaos** [comment] 2023-02-03 18:41
@Angryman18 guys just follow steps from this guy. It solved the issue.

**Comment by ginagr** [comment] 2023-02-03 19:18
Angryman steps work for me after switching from yarn to npm if that helps anyone else (you may need to do npm install --force)

**Comment by hsubox76** [comment] 2023-02-03 20:29
Version 9.17.1 has just been published to NPM, please let me know if anyone's still having problems.

If you still have issues with 9.17.1, before reporting the issue here, make sure to delete your `node_modules` and `package-lock.json`/`yarn.lock` files and reinstall. If yarn or npm doesn't overwrite the old `node_modules/@firebase/**/package.json` files, which sometimes happens when you do an upgrade/downgrade without deleting everything, you'll continue to have the same problem.

**Comment by fvadouko** [comment] 2023-02-03 20:43
It works for firbase 9.16.0 because we have this issue with vercel.

**Comment by danielalejandroalanis** [comment] 2023-02-03 21:45
Solved with the new version (9.17.1), I had to delete package-lock and node_modules for a clean install.

**Comment by BecayeSoft** [comment] 2023-02-03 21:45
> rted as 'firebase') was not found in 'firebase/app' (possible exports: FirebaseError, SDK_VERSION, _DEFAULT_ENTRY_NAME, _addComponent, _addOrOverwriteCompon

Thanks, man! It worked like a charm...

**Comment by BecayeSoft** [comment] 2023-02-03 21:46
> > this did not fix my issue
> 
> 1. npm un firebase
> 2. npm i firebase@9.16.0
> 
> Solved my issue "Module not found: Default condition should be last one "

Thanks, man! It worked like a charm...

**Comment by BecayeSoft** [comment] 2023-02-03 22:56
> Version 9.17.1 has just been published to NPM, please let me know if anyone's still having problems.
> 
> If you still have issues with 9.17.1, before reporting the issue here, make sure to delete your `node_modules` and `package-lock.json`/`yarn.lock` files and reinstall. If yarn or npm doesn't overwrite the old `node_modules/@firebase/**/package.json` files, which sometimes happens when you do an upgrade/downgrade without deleting everything, you'll continue to have the same problem.

@hsubox76, I created a new project with firebase 9.17.1. But now I'm getting some errors like this one: 

Error: node_modules/@angular/fire/compat/firestore/interfaces.d.ts:13:18 - error TS2430: Interface 'DocumentSnapshotExists<T>' incorrectly extends interface 'DocumentSnapshot<DocumentData>'.
  The types returned by 'data(...)' are incompatible between these types.
    Type 'T' is not assignable to type 'DocumentData | undefined'.
      Type 'T' is not assignable to type 'DocumentData'.

Do you have any idea?

**Comment by eduhsoto** [comment] 2023-02-04 01:20
> > > this did not fix my issue
> > 
> > 
> > 
> > 1. npm un firebase
> > 2. npm i firebase@9.16.0
> > 
> > Solved my issue "Module not found: Default condition should be last one "
> 
> Thanks, man! It worked like a charm...

this solution worked for me ... it is bug only version 17?

**Comment by Mydulislam** [comment] 2023-02-04 02:55
npm un firebase
npm i firebase@9.16.0
Solved my issue "Module not found: Default condition should be last one "

**Comment by phidelis30** [comment] 2023-02-06 05:59
I have this error, i use firebase 9.15.0. After I install this firebase remove ^.
but this is error
Uncaught FirebaseError: Function where() called with invalid data. Unsupported field value: undefined

**Comment by singhrishabh93** [comment] 2023-02-09 09:12
> here is the solution. change the version run `yarn install`
> 
> ![Screenshot from 2023-02-03 13-24-19](https://user-images.githubusercontent.com/63530626/216543505-3abe803e-5a6f-43cd-b093-01400eaaca5a.png)

Thank You so much

**Comment by eugenevk** [comment] 2023-02-13 13:10
Deleting node_modules and then reinstalling everything with npm (firebase version 9.17.1) fixed it for me.
