### ISSUE TITLE
Firebase Firestore enablePersistence() throws error. Memory-only build of Firestore??

### ISSUE THREAD

**Issue by Kubaguette** [firebase/firebase-js-sdk#5448] opened 2021-09-05 12:44 UTC
Operating System version: "react-native": "~0.63.4"
Firebase SDK version: 8.2.3
Firebase Product: firestore

Problem occurs when I want to enable persistence for my firestore querries. I have a chat app and without persistence I will have an insane data consuming application so this is crucial. I cant find the same error somewhere else, thats why I post it here. The error message states: 

> FirebaseError: You are using the memory-only build of Firestore. Persistence support is only available via the @firebase/firestore bundle or the firebase-firestore.js build.

Steps to reproduce:
- create a new react-native app
- run "npm install firebase"
- after initialising the firebase project with **initializeApp** try to enable persistence as I did in the code example

#### Relevant Code:

import firebase from "firebase";
import ApiKeys from "./constants/ApiKeys";

firebase.initializeApp(ApiKeys);
firebase.firestore().settings({ experimentalForceLongPolling: true }); 
firebase.firestore().enablePersistence(); // <--- This line is the problem

**Comment by hsubox76** [comment] 2021-09-07 18:33
First, FYI, we are currently on version 9+ of Firebase so any future bug fixes will require an upgrade.

Secondly, even in your current version 8 app, you seem to be using the all-in-one bundle, which is not recommended for production use. Does it help if you import individual packages as recommended? For example, replace your import line with:

```
import firebase from 'firebase/app';
import 'firebase/firestore';
```

If not, the next step is to upgrade to v9 ([guide here](https://firebase.google.com/docs/web/modular-upgrade#window-compat)) and let us know if the problem still exists in v9.

**Comment by wu-hui** [comment] 2021-09-14 13:58
@Kubaguette Are you still seeing the issue?

**Comment by Kubaguette** [comment] 2021-09-14 14:21
Yes but I overcame this problem by using Async-Storage and coding my own persistence-system so I do not rely anymore on the firestore persistence. 

Still, the issue technicaly remains.

**Comment by wu-hui** [comment] 2021-09-16 13:51
OK, have you tried what @hsubox76 suggested though? Or that did not solve your problem?

**Comment by Kubaguette** [comment] 2021-09-16 14:07
Yes, I tried to do the imports one by one and maybe resolve the problem that way but it did not help.

Im also staying on SDK8 because my project is now over 5000+ codelines long and I do not have any patience to update everything and restructure the code. Took me some days but I wrote my own persistence now.

Incase this would help future people, I can provide my approach and tell you how Ive done it.

**Comment by wu-hui** [comment] 2021-09-16 15:16
Feel free to write your approach here. 

SDK8 requires you to specify @firebase/firestore or firebase-firestore.js, as the error message implied. It is OK to stay at that version for now, but just want to point out that our new features and bug fixes will be added to V9.

**Comment by wu-hui** [comment] 2021-09-28 14:21
I could not reproduce this myself..I am closing this since you are no longer bothered by this. Feel free to paste you approach here, or if you think we should continue investigation, please paste a mini repro repo so we can move forward.

**Closed by wu-hui** 2021-09-28 14:21 UTC
Labels: api: firestore, needs-attention
