### ISSUE TITLE
Bug in 5.0.4 version.

### ISSUE THREAD

**Issue by berpcor** [firebase/firebase-js-sdk#938] opened 2018-06-16 20:29 UTC
https://stackoverflow.com/questions/50891391/importing-firebase-in-non-root-file-of-react-native-causes-error-in-android-emul
Look at there please.
I've downgraded to 5.0.2 and it's helped.

**Comment by jshcrowthe** [comment] 2018-06-28 19:59
Hey there @berpcor, I don't think this is an issue with Firebase but rather a dupe of a react native issue. Can you try loading Firebase before everything else and see if that fixes the problem?

**Comment by jshcrowthe** [comment] 2018-06-29 18:01
Duplicate of #871

**Closed by jshcrowthe** 2018-06-29 18:01 UTC
Labels: needs-triage

**Comment by berpcor** [comment] 2018-07-03 18:45
Unfortunately yes, I've tried all possible orders: before, after, middle, different depth in hierarchy...
