### ISSUE TITLE
Reboot required: Could not reach Cloud Firestore backend.

### ISSUE THREAD

**Issue by peili** [firebase/firebase-js-sdk#5134] opened 2021-07-09 22:04 UTC
We're experiencing users who intermittently can't reach Cloud Firestore backend.
Switching Networks using a different browser doesn't resolve the issue.

But often **rebooting** the machine resolves that issue.
 
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36 
Firebase SDK version: 8.6.8
Firebase Product: Firestore

> [2021-07-09T16:14:28.895Z]  @firebase/firestore: Firestore (8.6.8): Could not reach Cloud Firestore backend. Backend didn't respond within 10 seconds.
> This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.
> 
> Uncaught (in promise) FirebaseError: Failed to get document because the client is offline.
>     at new t (chunk-vendors.04585bfe.js:1506)
>     at next (chunk-vendors.04585bfe.js:2389)
>     at chunk-vendors.04585bfe.js:2373
>     at i (chunk-vendors.04585bfe.js:2693)

**Comment by rafikhan** [comment] 2021-07-10 01:35
@peili can you take a look at https://github.com/firebase/firebase-js-sdk/issues/1674 follow the instructions at the top and let us know on that particular ticket if it helped you?

**Comment by peili** [comment] 2021-07-10 10:44
> @peili can you take a look at #1674, follow the instructions at the top and let us know if it works for you?

@rafikhan Yes, we tried it also with `experimentalForceLongPolling` enabled. Same issue. Only rebooting fixed that broken state.

**Comment by looptheloop88** [comment] 2021-07-12 16:00
Hi @peili, thanks for the report. Usually, this kind of issue can be resolved by either using [experimentalAutoDetectLongPolling](https://firebase.google.com/docs/reference/js/firebase.firestore.Settings#optional-experimentalautodetectlongpolling) or [experimentalForceLongPolling](https://firebase.google.com/docs/reference/js/firebase.firestore.Settings#optional-experimentalforcelongpolling) option. If you're not seeing any changes after implementing these settings, try enabling the Firestore [debug logging](https://firebase.google.com/docs/reference/js/firebase.firestore#setloglevel) and share the result. Also, it would help if you can identify the part of your application or operations that possibly caused the error.

**Comment by charlesfries** [comment] 2021-07-16 22:02
I am also encountering this issue intermittently, after updating `firebase` from 8.7.0 to 8.7.1

**Comment by schmidt-sebastian** [comment] 2021-07-16 22:26
@charlesfries Firestore did not change between 8.7.0 and 8.7.1. Have you ever seen this issue with 8.7.0?

**Comment by charlesfries** [comment] 2021-07-16 22:54
I downgraded back to 8.7.0 and have not yet encountered the issue. Will update this comment if it happens again.

It's tough because it happens very rarely, about every hour or so.

**Comment by baptisteArno** [comment] 2021-07-27 13:20
Some of my users are reporting this issue. This is a real pain!

I can't reproduce the bug... I tried enabling `experimentalAutoDetectLongPolling`. It still happens eventually.

I'm using v8.8.0

**Closed** 2021-08-10 01:02 UTC
Labels: api: firestore, needs-info, no-recent-activity
