### ISSUE TITLE
[firebase/remote-config] fetchAndActivate is not giving fetched value from firebase api

### ISSUE THREAD

**Issue by liveHarshit** [firebase/firebase-js-sdk#5244] opened 2021-08-04 10:48 UTC
### [REQUIRED] Describe your environment

  * Operating System version: Linux Mint 20.2 Cinnamon
  * Browser version: Google Chrome Version 92.0.4515.107
  * Firebase SDK version: 0.6.21
  * Firebase Product: 0.1.37 (remote-config)

Suddenly firebase.remoteConfig().fetchAndActivate() is started giving default values although I can clearly see in chrome dev tools network tab that latest values are getting fetched from firebase

#### Steps to reproduce:
- Install "@firebase/app": "0.6.21" and  "@firebase/remote-config": "0.1.37" using npm
- Initilize firebase app and set firebase.remoteConfig().default config
- call remoteconfig fetchAndActivate and print values
- Values are same as default config but from firebase values are coming difference (check API calls)
- It was working fine but breaking suddenly from yesterday 
#### Relevant Code:

```javascript
const firebase = Firebase.apps.length
            ? Firebase.app()
            : Firebase.initializeApp({
                  apiKey,
                  projectId,
                  appId
              });
        const remoteConfig = firebase.remoteConfig();
        remoteConfig.defaultConfig = {
            test: "string1"
        };
        remoteConfig.settings.minimumFetchIntervalMillis = 60000;
        await remoteConfig
            .fetchAndActivate()
            .then(() => {
                const value = Firebase.app()
                    .remoteConfig()
                    .getValue("test")
                    .asString();
               console.log(`Value: ${value}`);
            })
```

**Comment by pdronenko** [comment] 2021-08-04 11:37
I'm having the same problem today :(

**Comment by ValeraGin** [comment] 2021-08-04 11:37
I too

**Comment by diamanta** [comment] 2021-08-04 11:38
Encountered same problem today.

**Comment by goshman** [comment] 2021-08-04 11:49
Same problem =(

**Comment by supernovel** [comment] 2021-08-04 12:08
ETag header not coming in RemoteConfig fetch api

**Comment by supernovel** [comment] 2021-08-04 12:11
ETag header not coming in RemoteConfig fetch api

**Comment by josemgmz** [comment] 2021-08-04 12:41
We are having the same problem.

**Comment by jancama2** [comment] 2021-08-04 12:48
Looks like the return value from the firebase api changed. Before, the config was stored as object in field `value` in IndexedDB, now it is stored in `value` in field `config`

Before:
```
value: { ... config here }
```
Now:
```
value: { config: { ...config here } }
```

I use firebase `8.2.10` from npm and have this problem too.

**Comment by Barik85** [comment] 2021-08-04 13:22
Same problem!

**Comment by vctqs1** [comment] 2021-08-04 13:26
same problem!

**Comment by arthurseredaa** [comment] 2021-08-04 13:27
Same problem!

**Comment by andrey11111111111177** [comment] 2021-08-04 13:34
same issue(

**Comment by StanZhuravlev** [comment] 2021-08-04 13:38
Same problem.

**Comment by looptheloop88** [comment] 2021-08-04 13:41
Hi All, thanks for the reports. We are aware of this issue and it's currently being investigated internally. We can't provide definite timelines or details for when it will be fixed. You may keep an eye out on this issue thread, our [release notes](https://firebase.google.com/support/release-notes/js) or via [Firebase support](https://firebase.google.com/support) channel to get updates.

Here's the internal bug (b/195493347) for reference.

**Comment by aiprogs** [comment] 2021-08-04 13:48
Thanks, i have same problem too.
We are waiting...

**Comment by midnightfim** [comment] 2021-08-04 13:50
same problem
waiting for solution, thanks

**Comment by liveHarshit** [comment] 2021-08-04 14:27
@looptheloop88 any quick workaround?

**Comment by MartinSchwarzmaier** [comment] 2021-08-04 14:30
We have now resorted to copying the values from the network tab, checked them in as hard coded values and read them out in the app. Not happy about it but our app is severly affected.

**Comment by sidona** [comment] 2021-08-04 14:47
same problem 
i will waiting....

**Comment by miszo** [comment] 2021-08-04 15:30
We have the same problem. We're on version 8.3.1

**Comment by serrg** [comment] 2021-08-04 15:46
Yep, same problem here, `remoteConfig.getAll()` returns empty object (`remoteConfig: firebase.remoteConfig.RemoteConfig`)

**Comment by banrobert** [comment] 2021-08-04 16:58
Same problem with 8.2.0 and 8.8.1 as well!

**Comment by rob-corell-fivestars** [comment] 2021-08-04 17:14
Same problem.

**Comment by danasilver** [comment] 2021-08-04 17:52
Hi all, I'm on the Remote Config team. We believe we identified the issue and have it fixed now. Let us know if you're still seeing this bug. Thanks for all the reports - they're really helpful identifying and debugging!

**Comment by ivan-ha** [comment] 2021-08-04 18:18
Experienced this problem today too. And seems now it's fixed 🎉 

Probably caused by missing `etag` in the firebase API response header
![ 2021-08-04 下午2 48 36](https://user-images.githubusercontent.com/20895743/128233547-2a449514-0c1d-4ed4-844e-f045d9a938b5.png)

Which then causing the `activate` method always return `false` since `lastSuccessfulFetchResponse.eTag` was `undefined` (line 101)
https://github.com/firebase/firebase-js-sdk/blob/c52eb4805511c2cc4285e0f71e09d5357d20a2ff/packages/remote-config/src/remote_config.ts#L93-L113

And because the fetched config was never saved to the browser's storage, in the `getValue` the `defaultConfig` always used.

**Comment by goshman** [comment] 2021-08-04 18:31
> Hi all, I'm on the Remote Config team. We believe we identified the issue and have it fixed now. Let us know if you're still seeing this bug. Thanks for all the reports - they're really helpful identifying and debugging!

Have checked. Fix confirmed. Thank you!

**Comment by looptheloop88** [comment] 2021-08-04 18:41
The issue is now resolved. Please note that this seems to be a backend issue and we didn't release a new SDK version for the fix.

**Closed by looptheloop88** 2021-08-04 18:41 UTC
Labels: api: remoteconfig, internal-bug-filed, type: bug

**Comment by liveHarshit** [comment] 2021-08-05 03:52
Thanks @danasilver @looptheloop88
