### ISSUE TITLE
Can't install @firebase/logger@0.1.1

### ISSUE THREAD

**Issue by francoberton** [firebase/firebase-js-sdk#830] opened 2018-05-16 10:31 UTC
When I try to install @firebase/logger@0.1.1, I get this error:

silly fetchPackageMetaData error for @firebase/logger@0.1.1 Unexpected end of JSON input while parsing near '...d21U9VOet6aBfZx3jDd5G'
verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...d21U9VOet6aBfZx3jDd5G'
verbose stack     at JSON.parse (<anonymous>)
verbose stack     at parseJson (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/node_modules/json-parse-better-errors/index.js:7:17)
 verbose stack     at consumeBody.call.then.buffer (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/src/body.js:96:50)
 verbose stack     at <anonymous>
 verbose stack     at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by mmermerkaya** [comment] 2018-05-16 10:36
Duplicate of #768. Please try the suggested fix from that issue.

**Closed by mmermerkaya** 2018-05-16 10:36 UTC
Labels: needs-triage
