### ISSUE TITLE
Typescript Error: Type 'ReadableStream' is not generic

### ISSUE THREAD

**Issue by zarko-tg** [firebase/firebase-js-sdk#4204] opened 2020-12-14 10:47 UTC
firebase 8.2.0

typescript 2.8.4

![Screenshot 2020-12-14 at 11 45 50](https://user-images.githubusercontent.com/6142411/102072264-eef73580-3e01-11eb-9e54-f3f1ec07d19f.png)

**Comment by hsubox76** [comment] 2020-12-14 17:43
It seems to not like this line (your sourcemap seems to be off by a couple of lines):

https://github.com/firebase/firebase-js-sdk/blob/04f2e24858e6935433b0f926ae58a8b9ceb2ec58/packages/firebase/index.d.ts#L8304

Since that's how the type is declared in the actual source code, and it compiles fine, I think it's maybe due to a discrepancy with either your version of Typescript (ours is 4.0.5) or any other code or dependency you have that declares types, that might have a different declaration of ReadableStream. Is it possible to upgrade Typescript?

**Comment by zarko-tg** [comment] 2020-12-14 20:45
Thanks for the comment @hsubox76. I rebuilt package-lock.json just in case but it didn't make a difference. For practical reasons we're behind with Ionic/Angular, and we've probably reached the max when it comes to bumping just Typescript, so upgrading it again is likely not an option.
I suppose you can close this case soon especially if not many others face the same.

**Comment by wilhuff** [comment] 2020-12-15 21:45
Since this is working for us but not working for you (and we're not hearing about this widely) the next step would be to come up with a minimal reproduction of your issue. Putting this together will likely point toward whether this is a typescript version problem or a dependency that's providing a conflicting definition of `ReadableStream`.

**Comment by schmidt-sebastian** [comment] 2020-12-16 18:25
The change to add generic arguments to `ReadableStream` was merged over 2 years ago. Are you able to update your TypeScript dependency (and published in Typescript v3.2)?

See https://github.com/microsoft/TypeScript/commit/40bd7c89abbdf79493e2ea20dd80d9eb657dc82e

**Comment by schmidt-sebastian** [comment] 2020-12-17 21:12
I am closing this for now as this issue can likely be resolved by an update to the user's build configuration. We can re-open this issue should that not be the case.

**Closed by schmidt-sebastian** 2020-12-17 21:12 UTC
Labels: api: firestore, needs-info
