### ISSUE TITLE
FR: Module is huge, consider splitting it into many submodules (inside same repo) and lazy loading, bundle size

### ISSUE THREAD

**Issue by OZZlE** [firebase/firebase-js-sdk#4862] opened 2021-05-04 09:26 UTC
### [REQUIRED] Describe your environment

  * Operating System version: Not applicable.
  * Browser version: Not applicable.
  * Firebase SDK version: 8.4.3
  * Firebase Product: auth

#### Steps to reproduce:

    yarn add firebase || npm install firebase
    import 'firebase/auth' # 61.1 KB gzipped, 199.6 KB not gzipped!
    import firebase from 'firebase/app' # 7.6 KB gzipped, 23.5 KB not gzipped
    
    firebase.initializeApp(config)
    this.auth = firebase.auth()

This is by far the biggest third party module we use and it's not easily replaceable by own code. 

If it's because the module is very framework generic, perhaps making specific versions is better, like react-firebase, angular-firebase, vue-firebase etc.

**Comment by OZZlE** [comment] 2021-05-04 09:32
https://bundlephobia.com/result?p=firebase@8.4.3

**Comment by Feiyang1** [comment] 2021-05-04 20:25
Have you tried the v9 beta SDK, which is modular and tree shakable? See https://github.com/firebase/firebase-js-sdk/discussions/4791 for our announcement

**Comment by Feiyang1** [comment] 2021-05-04 20:27
duplicate of https://github.com/firebase/firebase-js-sdk/issues/332

**Closed** 2021-05-04 20:29 UTC
Labels: api: core

**Comment by OZZlE** [comment] 2021-05-10 12:57
Thanks, it decreased 56.6KB(!) but it's still 166.5 KB for handling login (in our case).. so better but not awesome

**Comment by OZZlE** [comment] 2021-05-11 13:41
import 'firebase/compat/auth' # 140.4KB (gzipped 40.4K)
    import firebase from 'firebase/compat/app' # 26.1 KB (gzipped 8.9K)
    
We use OAuth, magic email link and login with username/pw. We use webpack. 

Maybe not huge gzipped but still the biggest node module we have as far as I can see.

we use 

    "firebase": "9.0.0-beta.1",

**Comment by laurentpayot** [comment] 2021-05-15 11:02
From your `import` lines I can see you're using the compatibility library. From [the docs](https://firebase.google.com/docs/web/modular-upgrade#about_the_compat_libraries):

> Compat libraries have little to no size or performance advantages over their version 8 counterparts.

I think the small size reduction you're experiencing only comes from the complete Firebase rewrite. To get the benefits of tree shaking you have to use the ["real" modular V9 version](https://firebase.google.com/docs/web/modular-upgrade#refactor_to_the_modular_style).
